package edu.ku.cete.domain.student;

import java.util.ArrayList;
import java.util.Collection;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

import edu.ku.cete.util.Criterion;

public class StudentExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.student
     *
     * @mbggenerated Thu Apr 26 20:33:35 CDT 2012
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.student
     *
     * @mbggenerated Thu Apr 26 20:33:35 CDT 2012
     */
    protected boolean distinct;

    protected Integer limit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.student
     *
     * @mbggenerated Thu Apr 26 20:33:35 CDT 2012
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.student
     *
     * @mbggenerated Thu Apr 26 20:33:35 CDT 2012
     */
    public StudentExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.student
     *
     * @mbggenerated Thu Apr 26 20:33:35 CDT 2012
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.student
     *
     * @mbggenerated Thu Apr 26 20:33:35 CDT 2012
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.student
     *
     * @mbggenerated Thu Apr 26 20:33:35 CDT 2012
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    public void setLimit(Integer limit) {
        this.limit = limit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.student
     *
     * @mbggenerated Thu Apr 26 20:33:35 CDT 2012
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.student
     *
     * @mbggenerated Thu Apr 26 20:33:35 CDT 2012
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.student
     *
     * @mbggenerated Thu Apr 26 20:33:35 CDT 2012
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.student
     *
     * @mbggenerated Thu Apr 26 20:33:35 CDT 2012
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.student
     *
     * @mbggenerated Thu Apr 26 20:33:35 CDT 2012
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.student
     *
     * @mbggenerated Thu Apr 26 20:33:35 CDT 2012
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.student
     *
     * @mbggenerated Thu Apr 26 20:33:35 CDT 2012
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.student
     *
     * @mbggenerated Thu Apr 26 20:33:35 CDT 2012
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andIdIsNull() {
            addCriterion("st.id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("st.id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("st.id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("st.id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("st.id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("st.id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("st.id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("st.id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("st.id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("st.id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("st.id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("st.id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andStatestudentidentifierIsNull() {
            addCriterion("st.statestudentidentifier is null");
            return (Criteria) this;
        }

        public Criteria andStatestudentidentifierIsNotNull() {
            addCriterion("st.statestudentidentifier is not null");
            return (Criteria) this;
        }

        public Criteria andStatestudentidentifierEqualTo(String value) {
            addCriterion("st.statestudentidentifier =", value, "statestudentidentifier");
            return (Criteria) this;
        }

        public Criteria andStatestudentidentifierNotEqualTo(String value) {
            addCriterion("st.statestudentidentifier <>", value, "statestudentidentifier");
            return (Criteria) this;
        }

        public Criteria andStatestudentidentifierIn(List<String> values) {
            addCriterion("st.statestudentidentifier in", values, "statestudentidentifier");
            return (Criteria) this;
        }

        public Criteria andStatestudentidentifierNotIn(List<String> values) {
            addCriterion("st.statestudentidentifier not in", values, "statestudentidentifier");
            return (Criteria) this;
        }
        
        public Criteria andAttendanceSchoolIdIsNull() {
            addCriterion("en.attendanceschoolid is null");
            return (Criteria) this;
        }

        public Criteria andAttendanceSchoolIdIsNotNull() {
            addCriterion("en.attendanceschoolid is not null");
            return (Criteria) this;
        }

        public Criteria andAttendanceSchoolIdEqualTo(long value) {
            addCriterion("en.attendanceschoolid =", value, "attendanceschoolid");
            return (Criteria) this;
        }

        public Criteria andAttendanceSchoolIdNotEqualTo(long value) {
            addCriterion("en.attendanceschoolid <>", value, "attendanceschoolid");
            return (Criteria) this;
        }

        public Criteria andAttendanceSchoolIdGreaterThan(long value) {
            addCriterion("en.attendanceschoolid >", value, "attendanceschoolid");
            return (Criteria) this;
        }

        public Criteria andAttendanceSchoolIdGreaterThanOrEqualTo(long value) {
            addCriterion("en.attendanceschoolid >=", value, "attendanceschoolid");
            return (Criteria) this;
        }

        public Criteria andAttendanceSchoolIdLessThan(long value) {
            addCriterion("en.attendanceschoolid <", value, "attendanceschoolid");
            return (Criteria) this;
        }

        public Criteria andAttendanceSchoolIdLessThanOrEqualTo(long value) {
            addCriterion("en.attendanceschoolid <=", value, "attendanceschoolid");
            return (Criteria) this;
        }

        public Criteria andAttendanceSchoolIdLike(long value) {
            addCriterion("en.attendanceschoolid like", value, "attendanceschoolid");
            return (Criteria) this;
        }

        public Criteria andAttendanceSchoolIdNotLike(long value) {
            addCriterion("en.attendanceschoolid not like", value, "attendanceschoolid");
            return (Criteria) this;
        }

        public Criteria andAttendanceSchoolIdIn(List<Long> values) {
            addCriterion("en.attendanceschoolid in", values, "attendanceschoolid");
            return (Criteria) this;
        }
        public Criteria andAttendanceSchoolIdNotIn(List<Long> values) {
            addCriterion("en.attendanceschoolid not in", values, "attendanceschoolid");
            return (Criteria) this;
        }

        public Criteria andAttendanceSchoolIdBetween(long value1, long value2) {
            addCriterion("en.attendanceschoolid between", value1, value2, "attendanceschoolid");
            return (Criteria) this;
        }

        public Criteria andAttendanceSchoolIdNotBetween(long value1, long value2) {
            addCriterion("en.attendanceschoolid not between", value1, value2, "attendanceschoolid");
            return (Criteria) this;
        }        
        
        public Criteria andAssessmentProgramIdIsNull() {
            addCriterion("st.assessmentprogramid is null");
            return (Criteria) this;
        }

        public Criteria andAssessmentProgramIdIsNotNull() {
            addCriterion("st.assessmentprogramid is not null");
            return (Criteria) this;
        }

        public Criteria andAssessmentProgramIdEqualTo(long value) {
            addCriterion("st.assessmentprogramid =", value, "assessmentprogramid");
            return (Criteria) this;
        }

        public Criteria andAssessmentProgramIdNotEqualTo(long value) {
            addCriterion("st.assessmentprogramid <>", value, "assessmentprogramid");
            return (Criteria) this;
        }

        public Criteria andAssessmentProgramIdGreaterThan(long value) {
            addCriterion("st.assessmentprogramid >", value, "assessmentprogramid");
            return (Criteria) this;
        }

        public Criteria andAssessmentProgramIdGreaterThanOrEqualTo(long value) {
            addCriterion("st.assessmentprogramid >=", value, "assessmentprogramid");
            return (Criteria) this;
        }

        public Criteria andAssessmentProgramIdLessThan(long value) {
            addCriterion("st.assessmentprogramid <", value, "assessmentprogramid");
            return (Criteria) this;
        }

        public Criteria andAssessmentProgramIdLessThanOrEqualTo(long value) {
            addCriterion("st.assessmentprogramid <=", value, "assessmentprogramid");
            return (Criteria) this;
        }

        public Criteria andAssessmentProgramIdLike(long value) {
            addCriterion("st.assessmentprogramid like", value, "assessmentprogramid");
            return (Criteria) this;
        }

        public Criteria andAssessmentProgramIdNotLike(long value) {
            addCriterion("st.assessmentprogramid not like", value, "assessmentprogramid");
            return (Criteria) this;
        }

        public Criteria andAssessmentProgramIdIn(List<Long> values) {
            addCriterion("st.assessmentprogramid in", values, "assessmentprogramid");
            return (Criteria) this;
        }
        public Criteria andAssessmentProgramIdNotIn(List<Long> values) {
            addCriterion("st.assessmentprogramid not in", values, "assessmentprogramid");
            return (Criteria) this;
        }

        public Criteria andAssessmentProgramIdBetween(long value1, long value2) {
            addCriterion("st.assessmentprogramid between", value1, value2, "assessmentprogramid");
            return (Criteria) this;
        }

        public Criteria andAssessmentProgramIdNotBetween(long value1, long value2) {
            addCriterion("st.assessmentprogramid not between", value1, value2, "assessmentprogramid");
            return (Criteria) this;
        }        
        
        
        public Criteria andSyncedIsNull() {
            addCriterion("st.synced is null");
            return (Criteria) this;
        }

        public Criteria andSyncedIsNotNull() {
            addCriterion("st.synced is not null");
            return (Criteria) this;
        }

        public Criteria andSyncedEqualTo(boolean value) {
            addCriterion("st.synced =", value, "synced");
            return (Criteria) this;
        }

        public Criteria andSyncedNotEqualTo(boolean value) {
            addCriterion("st.synced <>", value, "synced");
            return (Criteria) this;
        }

        public Criteria andSyncedGreaterThan(boolean value) {
            addCriterion("st.synced >", value, "synced");
            return (Criteria) this;
        }

        public Criteria andSyncedGreaterThanOrEqualTo(boolean value) {
            addCriterion("st.synced >=", value, "synced");
            return (Criteria) this;
        }

        public Criteria andSyncedLessThan(boolean value) {
            addCriterion("st.synced <", value, "synced");
            return (Criteria) this;
        }

        public Criteria andSyncedLessThanOrEqualTo(boolean value) {
            addCriterion("st.synced <=", value, "synced");
            return (Criteria) this;
        }

        public Criteria andSyncedIn(List<Boolean> values) {
            addCriterion("st.synced in", values, "synced");
            return (Criteria) this;
        }

        public Criteria andSyncedNotIn(List<Boolean> values) {
            addCriterion("st.synced not in", values, "synced");
            return (Criteria) this;
        }

        public Criteria andSyncedBetween(boolean value1, boolean value2) {
            addCriterion("st.synced between", value1, value2, "synced");
            return (Criteria) this;
        }

        public Criteria andSyncedNotBetween(boolean value1, boolean value2) {
            addCriterion("st.synced not between", value1, value2, "synced");
            return (Criteria) this;
        }

        public Criteria andLegalfirstnameIsNull() {
            addCriterion("st.legalfirstname is null");
            return (Criteria) this;
        }

        public Criteria andLegalfirstnameIsNotNull() {
            addCriterion("st.legalfirstname is not null");
            return (Criteria) this;
        }

        public Criteria andLegalfirstnameEqualTo(String value) {
            addCriterion("st.legalfirstname =", value, "legalfirstname");
            return (Criteria) this;
        }

        public Criteria andLegalfirstnameNotEqualTo(String value) {
            addCriterion("st.legalfirstname <>", value, "legalfirstname");
            return (Criteria) this;
        }

        public Criteria andLegalfirstnameGreaterThan(String value) {
            addCriterion("st.legalfirstname >", value, "legalfirstname");
            return (Criteria) this;
        }

        public Criteria andLegalfirstnameGreaterThanOrEqualTo(String value) {
            addCriterion("st.legalfirstname >=", value, "legalfirstname");
            return (Criteria) this;
        }

        public Criteria andLegalfirstnameLessThan(String value) {
            addCriterion("st.legalfirstname <", value, "legalfirstname");
            return (Criteria) this;
        }

        public Criteria andLegalfirstnameLessThanOrEqualTo(String value) {
            addCriterion("st.legalfirstname <=", value, "legalfirstname");
            return (Criteria) this;
        }

        public Criteria andLegalfirstnameLike(String value) {
            addCriterion("st.legalfirstname like", value, "legalfirstname");
            return (Criteria) this;
        }

        public Criteria andLegalfirstnameNotLike(String value) {
            addCriterion("st.legalfirstname not like", value, "legalfirstname");
            return (Criteria) this;
        }

        public Criteria andLegalfirstnameIn(List<String> values) {
            addCriterion("st.legalfirstname in", values, "legalfirstname");
            return (Criteria) this;
        }

        public Criteria andLegalfirstnameNotIn(List<String> values) {
            addCriterion("st.legalfirstname not in", values, "legalfirstname");
            return (Criteria) this;
        }

        public Criteria andLegalfirstnameBetween(String value1, String value2) {
            addCriterion("st.legalfirstname between", value1, value2, "legalfirstname");
            return (Criteria) this;
        }

        public Criteria andLegalfirstnameNotBetween(String value1, String value2) {
            addCriterion("st.legalfirstname not between", value1, value2, "legalfirstname");
            return (Criteria) this;
        }

        public Criteria andLegalmiddlenameIsNull() {
            addCriterion("st.legalmiddlename is null");
            return (Criteria) this;
        }

        public Criteria andLegalmiddlenameIsNotNull() {
            addCriterion("st.legalmiddlename is not null");
            return (Criteria) this;
        }

        public Criteria andLegalmiddlenameEqualTo(String value) {
            addCriterion("st.legalmiddlename =", value, "legalmiddlename");
            return (Criteria) this;
        }

        public Criteria andLegalmiddlenameNotEqualTo(String value) {
            addCriterion("st.legalmiddlename <>", value, "legalmiddlename");
            return (Criteria) this;
        }

        public Criteria andLegalmiddlenameGreaterThan(String value) {
            addCriterion("st.legalmiddlename >", value, "legalmiddlename");
            return (Criteria) this;
        }

        public Criteria andLegalmiddlenameGreaterThanOrEqualTo(String value) {
            addCriterion("st.legalmiddlename >=", value, "legalmiddlename");
            return (Criteria) this;
        }

        public Criteria andLegalmiddlenameLessThan(String value) {
            addCriterion("st.legalmiddlename <", value, "legalmiddlename");
            return (Criteria) this;
        }

        public Criteria andLegalmiddlenameLessThanOrEqualTo(String value) {
            addCriterion("st.legalmiddlename <=", value, "legalmiddlename");
            return (Criteria) this;
        }

        public Criteria andLegalmiddlenameLike(String value) {
            addCriterion("st.legalmiddlename like", value, "legalmiddlename");
            return (Criteria) this;
        }

        public Criteria andLegalmiddlenameNotLike(String value) {
            addCriterion("st.legalmiddlename not like", value, "legalmiddlename");
            return (Criteria) this;
        }

        public Criteria andLegalmiddlenameIn(List<String> values) {
            addCriterion("st.legalmiddlename in", values, "legalmiddlename");
            return (Criteria) this;
        }

        public Criteria andLegalmiddlenameNotIn(List<String> values) {
            addCriterion("st.legalmiddlename not in", values, "legalmiddlename");
            return (Criteria) this;
        }

        public Criteria andLegalmiddlenameBetween(String value1, String value2) {
            addCriterion("st.legalmiddlename between", value1, value2, "legalmiddlename");
            return (Criteria) this;
        }

        public Criteria andLegalmiddlenameNotBetween(String value1, String value2) {
            addCriterion("st.legalmiddlename not between", value1, value2, "legalmiddlename");
            return (Criteria) this;
        }

        public Criteria andLegallastnameIsNull() {
            addCriterion("st.legallastname is null");
            return (Criteria) this;
        }

        public Criteria andLegallastnameIsNotNull() {
            addCriterion("st.legallastname is not null");
            return (Criteria) this;
        }

        public Criteria andLegallastnameEqualTo(String value) {
            addCriterion("st.legallastname =", value, "legallastname");
            return (Criteria) this;
        }

        public Criteria andLegallastnameNotEqualTo(String value) {
            addCriterion("st.legallastname <>", value, "legallastname");
            return (Criteria) this;
        }

        public Criteria andLegallastnameGreaterThan(String value) {
            addCriterion("st.legallastname >", value, "legallastname");
            return (Criteria) this;
        }

        public Criteria andLegallastnameGreaterThanOrEqualTo(String value) {
            addCriterion("st.legallastname >=", value, "legallastname");
            return (Criteria) this;
        }

        public Criteria andLegallastnameLessThan(String value) {
            addCriterion("st.legallastname <", value, "legallastname");
            return (Criteria) this;
        }

        public Criteria andLegallastnameLessThanOrEqualTo(String value) {
            addCriterion("st.legallastname <=", value, "legallastname");
            return (Criteria) this;
        }

        public Criteria andLegallastnameLike(String value) {
            addCriterion("st.legallastname like", value, "legallastname");
            return (Criteria) this;
        }

        public Criteria andLegallastnameNotLike(String value) {
            addCriterion("st.legallastname not like", value, "legallastname");
            return (Criteria) this;
        }

        public Criteria andLegallastnameIn(List<String> values) {
            addCriterion("st.legallastname in", values, "legallastname");
            return (Criteria) this;
        }

        public Criteria andLegallastnameNotIn(List<String> values) {
            addCriterion("st.legallastname not in", values, "legallastname");
            return (Criteria) this;
        }

        public Criteria andLegallastnameBetween(String value1, String value2) {
            addCriterion("st.legallastname between", value1, value2, "legallastname");
            return (Criteria) this;
        }

        public Criteria andLegallastnameNotBetween(String value1, String value2) {
            addCriterion("st.legallastname not between", value1, value2, "legallastname");
            return (Criteria) this;
        }

        public Criteria andGenerationcodeIsNull() {
            addCriterion("st.generationcode is null");
            return (Criteria) this;
        }

        public Criteria andGenerationcodeIsNotNull() {
            addCriterion("st.generationcode is not null");
            return (Criteria) this;
        }

        public Criteria andGenerationcodeEqualTo(String value) {
            addCriterion("st.generationcode =", value, "generationcode");
            return (Criteria) this;
        }

        public Criteria andGenerationcodeNotEqualTo(String value) {
            addCriterion("st.generationcode <>", value, "generationcode");
            return (Criteria) this;
        }

        public Criteria andGenerationcodeGreaterThan(String value) {
            addCriterion("st.generationcode >", value, "generationcode");
            return (Criteria) this;
        }

        public Criteria andGenerationcodeGreaterThanOrEqualTo(String value) {
            addCriterion("st.generationcode >=", value, "generationcode");
            return (Criteria) this;
        }

        public Criteria andGenerationcodeLessThan(String value) {
            addCriterion("st.generationcode <", value, "generationcode");
            return (Criteria) this;
        }

        public Criteria andGenerationcodeLessThanOrEqualTo(String value) {
            addCriterion("st.generationcode <=", value, "generationcode");
            return (Criteria) this;
        }

        public Criteria andGenerationcodeLike(String value) {
            addCriterion("st.generationcode like", value, "generationcode");
            return (Criteria) this;
        }

        public Criteria andGenerationcodeNotLike(String value) {
            addCriterion("st.generationcode not like", value, "generationcode");
            return (Criteria) this;
        }

        public Criteria andGenerationcodeIn(List<String> values) {
            addCriterion("st.generationcode in", values, "generationcode");
            return (Criteria) this;
        }

        public Criteria andGenerationcodeNotIn(List<String> values) {
            addCriterion("st.generationcode not in", values, "generationcode");
            return (Criteria) this;
        }

        public Criteria andGenerationcodeBetween(String value1, String value2) {
            addCriterion("st.generationcode between", value1, value2, "generationcode");
            return (Criteria) this;
        }

        public Criteria andGenerationcodeNotBetween(String value1, String value2) {
            addCriterion("st.generationcode not between", value1, value2, "generationcode");
            return (Criteria) this;
        }

        public Criteria andDateofbirthIsNull() {
            addCriterion("st.dateofbirth is null");
            return (Criteria) this;
        }

        public Criteria andDateofbirthIsNotNull() {
            addCriterion("st.dateofbirth is not null");
            return (Criteria) this;
        }

        public Criteria andDateofbirthEqualTo(Date value) {
            addCriterionForJDBCDate("dateofbirth =", value, "dateofbirth");
            return (Criteria) this;
        }

        public Criteria andDateofbirthNotEqualTo(Date value) {
            addCriterionForJDBCDate("dateofbirth <>", value, "dateofbirth");
            return (Criteria) this;
        }

        public Criteria andDateofbirthGreaterThan(Date value) {
            addCriterionForJDBCDate("dateofbirth >", value, "dateofbirth");
            return (Criteria) this;
        }

        public Criteria andDateofbirthGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("dateofbirth >=", value, "dateofbirth");
            return (Criteria) this;
        }

        public Criteria andDateofbirthLessThan(Date value) {
            addCriterionForJDBCDate("dateofbirth <", value, "dateofbirth");
            return (Criteria) this;
        }

        public Criteria andDateofbirthLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("dateofbirth <=", value, "dateofbirth");
            return (Criteria) this;
        }

        public Criteria andDateofbirthIn(List<Date> values) {
            addCriterionForJDBCDate("dateofbirth in", values, "dateofbirth");
            return (Criteria) this;
        }

        public Criteria andDateofbirthNotIn(List<Date> values) {
            addCriterionForJDBCDate("dateofbirth not in", values, "dateofbirth");
            return (Criteria) this;
        }

        public Criteria andDateofbirthBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("dateofbirth between", value1, value2, "dateofbirth");
            return (Criteria) this;
        }

        public Criteria andDateofbirthNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("dateofbirth not between", value1, value2, "dateofbirth");
            return (Criteria) this;
        }

        public Criteria andCreatedIsNull() {
            addCriterion("st.created is null");
            return (Criteria) this;
        }

        public Criteria andCreatedIsNotNull() {
            addCriterion("st.created is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedEqualTo(Date value) {
            addCriterion("st.created =", value, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedNotEqualTo(Date value) {
            addCriterion("st.created <>", value, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedGreaterThan(Date value) {
            addCriterion("st.created >", value, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedGreaterThanOrEqualTo(Date value) {
            addCriterion("st.created >=", value, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedLessThan(Date value) {
            addCriterion("st.created <", value, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedLessThanOrEqualTo(Date value) {
            addCriterion("st.created <=", value, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedIn(List<Date> values) {
            addCriterion("st.created in", values, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedNotIn(List<Date> values) {
            addCriterion("st.created not in", values, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedBetween(Date value1, Date value2) {
            addCriterion("st.created between", value1, value2, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedNotBetween(Date value1, Date value2) {
            addCriterion("st.created not between", value1, value2, "created");
            return (Criteria) this;
        }

        public Criteria andModifiedIsNull() {
            addCriterion("st.modified is null");
            return (Criteria) this;
        }

        public Criteria andModifiedIsNotNull() {
            addCriterion("st.modified is not null");
            return (Criteria) this;
        }

        public Criteria andModifiedEqualTo(Date value) {
            addCriterion("st.modified =", value, "modified");
            return (Criteria) this;
        }

        public Criteria andModifiedNotEqualTo(Date value) {
            addCriterion("st.modified <>", value, "modified");
            return (Criteria) this;
        }

        public Criteria andModifiedGreaterThan(Date value) {
            addCriterion("st.modified >", value, "modified");
            return (Criteria) this;
        }

        public Criteria andModifiedGreaterThanOrEqualTo(Date value) {
            addCriterion("st.modified >=", value, "modified");
            return (Criteria) this;
        }

        public Criteria andModifiedLessThan(Date value) {
            addCriterion("st.modified <", value, "modified");
            return (Criteria) this;
        }

        public Criteria andModifiedLessThanOrEqualTo(Date value) {
            addCriterion("st.modified <=", value, "modified");
            return (Criteria) this;
        }

        public Criteria andModifiedIn(List<Date> values) {
            addCriterion("st.modified in", values, "modified");
            return (Criteria) this;
        }

        public Criteria andModifiedNotIn(List<Date> values) {
            addCriterion("st.modified not in", values, "modified");
            return (Criteria) this;
        }

        public Criteria andModifiedBetween(Date value1, Date value2) {
            addCriterion("st.modified between", value1, value2, "modified");
            return (Criteria) this;
        }

        public Criteria andModifiedNotBetween(Date value1, Date value2) {
            addCriterion("st.modified not between", value1, value2, "modified");
            return (Criteria) this;
        }

        public Criteria andInvalidIsNull() {
            addCriterion("st.invalid is null");
            return (Criteria) this;
        }

        public Criteria andInvalidIsNotNull() {
            addCriterion("st.invalid is not null");
            return (Criteria) this;
        }

        public Criteria andInvalidEqualTo(Boolean value) {
            addCriterion("st.invalid =", value, "invalid");
            return (Criteria) this;
        }

        public Criteria andInvalidNotEqualTo(Boolean value) {
            addCriterion("st.invalid <>", value, "invalid");
            return (Criteria) this;
        }

        public Criteria andInvalidGreaterThan(Boolean value) {
            addCriterion("st.invalid >", value, "invalid");
            return (Criteria) this;
        }

        public Criteria andInvalidGreaterThanOrEqualTo(Boolean value) {
            addCriterion("st.invalid >=", value, "invalid");
            return (Criteria) this;
        }

        public Criteria andInvalidLessThan(Boolean value) {
            addCriterion("st.invalid <", value, "invalid");
            return (Criteria) this;
        }

        public Criteria andInvalidLessThanOrEqualTo(Boolean value) {
            addCriterion("st.invalid <=", value, "invalid");
            return (Criteria) this;
        }

        public Criteria andInvalidIn(List<Boolean> values) {
            addCriterion("st.invalid in", values, "invalid");
            return (Criteria) this;
        }

        public Criteria andInvalidNotIn(List<Boolean> values) {
            addCriterion("st.invalid not in", values, "invalid");
            return (Criteria) this;
        }

        public Criteria andInvalidBetween(Boolean value1, Boolean value2) {
            addCriterion("st.invalid between", value1, value2, "invalid");
            return (Criteria) this;
        }

        public Criteria andInvalidNotBetween(Boolean value1, Boolean value2) {
            addCriterion("st.invalid not between", value1, value2, "invalid");
            return (Criteria) this;
        }

        public Criteria andInvalidfieldsIsNull() {
            addCriterion("st.invalidfields is null");
            return (Criteria) this;
        }

        public Criteria andInvalidfieldsIsNotNull() {
            addCriterion("st.invalidfields is not null");
            return (Criteria) this;
        }

        public Criteria andInvalidfieldsEqualTo(String value) {
            addCriterion("st.invalidfields =", value, "invalidfields");
            return (Criteria) this;
        }

        public Criteria andInvalidfieldsNotEqualTo(String value) {
            addCriterion("st.invalidfields <>", value, "invalidfields");
            return (Criteria) this;
        }

        public Criteria andInvalidfieldsGreaterThan(String value) {
            addCriterion("st.invalidfields >", value, "invalidfields");
            return (Criteria) this;
        }

        public Criteria andInvalidfieldsGreaterThanOrEqualTo(String value) {
            addCriterion("st.invalidfields >=", value, "invalidfields");
            return (Criteria) this;
        }

        public Criteria andInvalidfieldsLessThan(String value) {
            addCriterion("st.invalidfields <", value, "invalidfields");
            return (Criteria) this;
        }

        public Criteria andInvalidfieldsLessThanOrEqualTo(String value) {
            addCriterion("st.invalidfields <=", value, "invalidfields");
            return (Criteria) this;
        }

        public Criteria andInvalidfieldsLike(String value) {
            addCriterion("st.invalidfields like", value, "invalidfields");
            return (Criteria) this;
        }

        public Criteria andInvalidfieldsNotLike(String value) {
            addCriterion("st.invalidfields not like", value, "invalidfields");
            return (Criteria) this;
        }

        public Criteria andInvalidfieldsIn(List<String> values) {
            addCriterion("st.invalidfields in", values, "invalidfields");
            return (Criteria) this;
        }

        public Criteria andInvalidfieldsNotIn(List<String> values) {
            addCriterion("st.invalidfields not in", values, "invalidfields");
            return (Criteria) this;
        }

        public Criteria andInvalidfieldsBetween(String value1, String value2) {
            addCriterion("st.invalidfields between", value1, value2, "invalidfields");
            return (Criteria) this;
        }

        public Criteria andInvalidfieldsNotBetween(String value1, String value2) {
            addCriterion("st.invalidfields not between", value1, value2, "invalidfields");
            return (Criteria) this;
        }

        public Criteria andGenderIsNull() {
            addCriterion("st.gender is null");
            return (Criteria) this;
        }

        public Criteria andGenderIsNotNull() {
            addCriterion("st.gender is not null");
            return (Criteria) this;
        }

        public Criteria andGenderEqualTo(Integer value) {
            addCriterion("st.gender =", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderNotEqualTo(Integer value) {
            addCriterion("st.gender <>", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderGreaterThan(Integer value) {
            addCriterion("st.gender >", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderGreaterThanOrEqualTo(Integer value) {
            addCriterion("st.gender >=", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderLessThan(Integer value) {
            addCriterion("st.gender <", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderLessThanOrEqualTo(Integer value) {
            addCriterion("st.gender <=", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderIn(List<Integer> values) {
            addCriterion("st.gender in", values, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderNotIn(List<Integer> values) {
            addCriterion("st.gender not in", values, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderBetween(Integer value1, Integer value2) {
            addCriterion("st.gender between", value1, value2, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderNotBetween(Integer value1, Integer value2) {
            addCriterion("st.gender not between", value1, value2, "gender");
            return (Criteria) this;
        }
        
        public Criteria andUsernameIsNull() {
            addCriterion("st.username is null");
            return (Criteria) this;
        }

        public Criteria andUsernameIsNotNull() {
            addCriterion("st.username is not null");
            return (Criteria) this;
        }

        public Criteria andUsernameEqualTo(String value) {
            addCriterion("st.username =", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotEqualTo(String value) {
            addCriterion("st.username <>", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameGreaterThan(String value) {
            addCriterion("st.username >", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameGreaterThanOrEqualTo(String value) {
            addCriterion("st.username >=", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameLessThan(String value) {
            addCriterion("st.username <", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameLessThanOrEqualTo(String value) {
            addCriterion("st.username <=", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameLike(String value) {
            addCriterion("st.username like", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotLike(String value) {
            addCriterion("st.username not like", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameIn(List<String> values) {
            addCriterion("st.username in", values, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotIn(List<String> values) {
            addCriterion("st.username not in", values, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameBetween(String value1, String value2) {
            addCriterion("st.username between", value1, value2, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotBetween(String value1, String value2) {
            addCriterion("st.username not between", value1, value2, "username");
            return (Criteria) this;
        }

        public Criteria andPasswordIsNull() {
            addCriterion("st.password is null");
            return (Criteria) this;
        }

        public Criteria andPasswordIsNotNull() {
            addCriterion("st.password is not null");
            return (Criteria) this;
        }

        public Criteria andPasswordEqualTo(String value) {
            addCriterion("st.password =", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotEqualTo(String value) {
            addCriterion("st.password <>", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordGreaterThan(String value) {
            addCriterion("st.password >", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordGreaterThanOrEqualTo(String value) {
            addCriterion("st.password >=", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLessThan(String value) {
            addCriterion("st.password <", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLessThanOrEqualTo(String value) {
            addCriterion("st.password <=", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLike(String value) {
            addCriterion("st.password like", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotLike(String value) {
            addCriterion("st.password not like", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordIn(List<String> values) {
            addCriterion("st.password in", values, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotIn(List<String> values) {
            addCriterion("st.password not in", values, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordBetween(String value1, String value2) {
            addCriterion("st.password between", value1, value2, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotBetween(String value1, String value2) {
            addCriterion("st.password not between", value1, value2, "password");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.student
     *
     * @mbggenerated do_not_delete_during_merge Thu Apr 26 20:33:35 CDT 2012
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}