package edu.ku.cete.domain.content;

import java.util.Date;

import edu.ku.cete.domain.audit.AuditableDomain;

/**
 *
 * @author neil.howerton
 *
 */
public class ContentArea extends AuditableDomain {
    /**
	 * 
	 */
	private static final long serialVersionUID = -6381073989886707208L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.contentarea.id
     *
     * @mbggenerated Wed Sep 12 13:52:41 CDT 2012
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.contentarea.externalid
     *
     * @mbggenerated Wed Sep 12 13:52:41 CDT 2012
     */
    private Long externalId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.contentarea.sortorder
     *
     * @mbggenerated Wed Sep 12 13:52:41 CDT 2012
     */
    private Long sortOrder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.contentarea.name
     *
     * @mbggenerated Wed Sep 12 13:52:41 CDT 2012
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.contentarea.abbreviatedname
     *
     * @mbggenerated Wed Sep 12 13:52:41 CDT 2012
     */
    private String abbreviatedName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.contentarea.createdate
     *
     * @mbggenerated Wed Sep 12 13:52:41 CDT 2012
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.contentarea.modifieddate
     *
     * @mbggenerated Wed Sep 12 13:52:41 CDT 2012
     */
    private Date modifiedDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.contentarea.originationcode
     *
     * @mbggenerated Wed Sep 12 13:52:41 CDT 2012
     */
    private String originationCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.contentarea.id
     *
     * @return the value of public.contentarea.id
     *
     * @mbggenerated Wed Sep 12 13:52:41 CDT 2012
     */
    
    private String assessmentProgramCode;
    
    private Long assessmentProgramId;
    
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.contentarea.id
     *
     * @param id the value for public.contentarea.id
     *
     * @mbggenerated Wed Sep 12 13:52:41 CDT 2012
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.contentarea.externalid
     *
     * @return the value of public.contentarea.externalid
     *
     * @mbggenerated Wed Sep 12 13:52:41 CDT 2012
     */
    public Long getExternalId() {
        return externalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.contentarea.externalid
     *
     * @param externalId the value for public.contentarea.externalid
     *
     * @mbggenerated Wed Sep 12 13:52:41 CDT 2012
     */
    public void setExternalId(Long externalId) {
        this.externalId = externalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.contentarea.sortorder
     *
     * @return the value of public.contentarea.sortorder
     *
     * @mbggenerated Wed Sep 12 13:52:41 CDT 2012
     */
    public Long getSortOrder() {
        return sortOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.contentarea.sortorder
     *
     * @param sortOrder the value for public.contentarea.sortorder
     *
     * @mbggenerated Wed Sep 12 13:52:41 CDT 2012
     */
    public void setSortOrder(Long sortOrder) {
        this.sortOrder = sortOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.contentarea.name
     *
     * @return the value of public.contentarea.name
     *
     * @mbggenerated Wed Sep 12 13:52:41 CDT 2012
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.contentarea.name
     *
     * @param name the value for public.contentarea.name
     *
     * @mbggenerated Wed Sep 12 13:52:41 CDT 2012
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.contentarea.abbreviatedname
     *
     * @return the value of public.contentarea.abbreviatedname
     *
     * @mbggenerated Wed Sep 12 13:52:41 CDT 2012
     */
    public String getAbbreviatedName() {
        return abbreviatedName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.contentarea.abbreviatedname
     *
     * @param abbreviatedName the value for public.contentarea.abbreviatedname
     *
     * @mbggenerated Wed Sep 12 13:52:41 CDT 2012
     */
    public void setAbbreviatedName(String abbreviatedName) {
        this.abbreviatedName = abbreviatedName == null ? null : abbreviatedName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.contentarea.createdate
     *
     * @return the value of public.contentarea.createdate
     *
     * @mbggenerated Wed Sep 12 13:52:41 CDT 2012
     */
    public Date getCreateDate() {
        return getCreatedDate();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.contentarea.createdate
     *
     * @param createDate the value for public.contentarea.createdate
     *
     * @mbggenerated Wed Sep 12 13:52:41 CDT 2012
     */
    public void setCreateDate(Date createDate) {
        setCreatedDate(createDate);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.contentarea.modifieddate
     *
     * @return the value of public.contentarea.modifieddate
     *
     * @mbggenerated Wed Sep 12 13:52:41 CDT 2012
     */
    public Date getModifiedDate() {
        return modifiedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.contentarea.modifieddate
     *
     * @param modifiedDate the value for public.contentarea.modifieddate
     *
     * @mbggenerated Wed Sep 12 13:52:41 CDT 2012
     */
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.contentarea.originationcode
     *
     * @return the value of public.contentarea.originationcode
     *
     * @mbggenerated Wed Sep 12 13:52:41 CDT 2012
     */
    public String getOriginationCode() {
        return originationCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.contentarea.originationcode
     *
     * @param originationCode the value for public.contentarea.originationcode
     *
     * @mbggenerated Wed Sep 12 13:52:41 CDT 2012
     */
    public void setOriginationCode(String originationCode) {
        this.originationCode = originationCode == null ? null : originationCode.trim();
    }

	public String getAssessmentProgramCode() {
		return assessmentProgramCode;
	}

	public void setAssessmentProgramCode(String assessmentProgramCode) {
		this.assessmentProgramCode = assessmentProgramCode;
	}

	public Long getAssessmentProgramId() {
		return assessmentProgramId;
	}

	public void setAssessmentProgramId(Long assessmentProgramId) {
		this.assessmentProgramId = assessmentProgramId;
	}
}