package edu.ku.cete.domain.content;

import java.util.Date;

import org.apache.commons.lang3.StringUtils;

import edu.ku.cete.domain.audit.AuditableDomain;

public class GradeCourse extends AuditableDomain implements Comparable<GradeCourse>{

	private static final long serialVersionUID = 7168469353880328378L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.gradecourse.id
     *
     * @mbggenerated Wed Sep 12 13:56:00 CDT 2012
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.gradecourse.externalid
     *
     * @mbggenerated Wed Sep 12 13:56:00 CDT 2012
     */
    private Long externalId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.gradecourse.name
     *
     * @mbggenerated Wed Sep 12 13:56:00 CDT 2012
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.gradecourse.abbreviatedname
     *
     * @mbggenerated Wed Sep 12 13:56:00 CDT 2012
     */
    private String abbreviatedName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.gradecourse.ordinality
     *
     * @mbggenerated Wed Sep 12 13:56:00 CDT 2012
     */
    private Long ordinality;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.gradecourse.gradelevel
     *
     * @mbggenerated Wed Sep 12 13:56:00 CDT 2012
     */
    private Integer gradeLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.gradecourse.shortdescription
     *
     * @mbggenerated Wed Sep 12 13:56:00 CDT 2012
     */
    private String shortDescription;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.gradecourse.longdescription
     *
     * @mbggenerated Wed Sep 12 13:56:00 CDT 2012
     */
    private String longDescription;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.gradecourse.createdate
     *
     * @mbggenerated Wed Sep 12 13:56:00 CDT 2012
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.gradecourse.modifieddate
     *
     * @mbggenerated Wed Sep 12 13:56:00 CDT 2012
     */
    private Date modifiedDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.gradecourse.originationcode
     *
     * @mbggenerated Wed Sep 12 13:56:00 CDT 2012
     */
    private String originationCode;
    /**
     * Mapping id to the new grade course table
     */
    private Long assessmentProgramGradesId;
    private Long contentAreaId;
    
    private Long gradeBandId;
    private String gradeBandName;
    private String gradeBandAbbrName;
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.gradecourse.id
     *
     * @return the value of public.gradecourse.id
     *
     * @mbggenerated Wed Sep 12 13:56:00 CDT 2012
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.gradecourse.id
     *
     * @param id the value for public.gradecourse.id
     *
     * @mbggenerated Wed Sep 12 13:56:00 CDT 2012
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.gradecourse.externalid
     *
     * @return the value of public.gradecourse.externalid
     *
     * @mbggenerated Wed Sep 12 13:56:00 CDT 2012
     */
    public Long getExternalId() {
        return externalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.gradecourse.externalid
     *
     * @param externalId the value for public.gradecourse.externalid
     *
     * @mbggenerated Wed Sep 12 13:56:00 CDT 2012
     */
    public void setExternalId(Long externalId) {
        this.externalId = externalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.gradecourse.name
     *
     * @return the value of public.gradecourse.name
     *
     * @mbggenerated Wed Sep 12 13:56:00 CDT 2012
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.gradecourse.name
     *
     * @param name the value for public.gradecourse.name
     *
     * @mbggenerated Wed Sep 12 13:56:00 CDT 2012
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.gradecourse.abbreviatedname
     *
     * @return the value of public.gradecourse.abbreviatedname
     *
     * @mbggenerated Wed Sep 12 13:56:00 CDT 2012
     */
    public String getAbbreviatedName() {
        return abbreviatedName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.gradecourse.abbreviatedname
     *
     * @param abbreviatedName the value for public.gradecourse.abbreviatedname
     *
     * @mbggenerated Wed Sep 12 13:56:00 CDT 2012
     */
    public void setAbbreviatedName(String abbreviatedName) {
        this.abbreviatedName = abbreviatedName == null ? null : abbreviatedName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.gradecourse.ordinality
     *
     * @return the value of public.gradecourse.ordinality
     *
     * @mbggenerated Wed Sep 12 13:56:00 CDT 2012
     */
    public Long getOrdinality() {
        return ordinality;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.gradecourse.ordinality
     *
     * @param ordinality the value for public.gradecourse.ordinality
     *
     * @mbggenerated Wed Sep 12 13:56:00 CDT 2012
     */
    public void setOrdinality(Long ordinality) {
        this.ordinality = ordinality;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.gradecourse.gradelevel
     *
     * @return the value of public.gradecourse.gradelevel
     *
     * @mbggenerated Wed Sep 12 13:56:00 CDT 2012
     */
    public Integer getGradeLevel() {
        return gradeLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.gradecourse.gradelevel
     *
     * @param gradeLevel the value for public.gradecourse.gradelevel
     *
     * @mbggenerated Wed Sep 12 13:56:00 CDT 2012
     */
    public void setGradeLevel(Integer gradeLevel) {
        this.gradeLevel = gradeLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.gradecourse.shortdescription
     *
     * @return the value of public.gradecourse.shortdescription
     *
     * @mbggenerated Wed Sep 12 13:56:00 CDT 2012
     */
    public String getShortDescription() {
        return shortDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.gradecourse.shortdescription
     *
     * @param shortDescription the value for public.gradecourse.shortdescription
     *
     * @mbggenerated Wed Sep 12 13:56:00 CDT 2012
     */
    public void setShortDescription(String shortDescription) {
        this.shortDescription = shortDescription == null ? null : shortDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.gradecourse.longdescription
     *
     * @return the value of public.gradecourse.longdescription
     *
     * @mbggenerated Wed Sep 12 13:56:00 CDT 2012
     */
    public String getLongDescription() {
        return longDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.gradecourse.longdescription
     *
     * @param longDescription the value for public.gradecourse.longdescription
     *
     * @mbggenerated Wed Sep 12 13:56:00 CDT 2012
     */
    public void setLongDescription(String longDescription) {
        this.longDescription = longDescription == null ? null : longDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.gradecourse.createdate
     *
     * @return the value of public.gradecourse.createdate
     *
     * @mbggenerated Wed Sep 12 13:56:00 CDT 2012
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.gradecourse.createdate
     *
     * @param createDate the value for public.gradecourse.createdate
     *
     * @mbggenerated Wed Sep 12 13:56:00 CDT 2012
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.gradecourse.modifieddate
     *
     * @return the value of public.gradecourse.modifieddate
     *
     * @mbggenerated Wed Sep 12 13:56:00 CDT 2012
     */
    public Date getModifiedDate() {
        return modifiedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.gradecourse.modifieddate
     *
     * @param modifiedDate the value for public.gradecourse.modifieddate
     *
     * @mbggenerated Wed Sep 12 13:56:00 CDT 2012
     */
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.gradecourse.originationcode
     *
     * @return the value of public.gradecourse.originationcode
     *
     * @mbggenerated Wed Sep 12 13:56:00 CDT 2012
     */
    public String getOriginationCode() {
        return originationCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.gradecourse.originationcode
     *
     * @param originationCode the value for public.gradecourse.originationcode
     *
     * @mbggenerated Wed Sep 12 13:56:00 CDT 2012
     */
    public void setOriginationCode(String originationCode) {
        this.originationCode = originationCode == null ? null : originationCode.trim();
    }

	public Long getAssessmentProgramGradesId() {
		return assessmentProgramGradesId;
	}

	public void setAssessmentProgramGradesId(Long assessmentProgramGradesId) {
		this.assessmentProgramGradesId = assessmentProgramGradesId;
	}

	public Long getContentAreaId() {
		return contentAreaId;
	}

	public void setContentAreaId(Long contentAreaId) {
		this.contentAreaId = contentAreaId;
	}

	public Long getGradeBandId() {
		return gradeBandId;
	}

	public void setGradeBandId(Long gradeBandId) {
		this.gradeBandId = gradeBandId;
	}

	public String getGradeBandName() {
		return gradeBandName;
	}

	public void setGradeBandName(String gradeBandName) {
		this.gradeBandName = gradeBandName;
	}

	public String getGradeBandAbbrName() {
		return gradeBandAbbrName;
	}

	public void setGradeBandAbbrName(String gradeBandAbbrName) {
		this.gradeBandAbbrName = gradeBandAbbrName;
	}

	@Override
	public int compareTo(GradeCourse otherGrade) {
		if(this.abbreviatedName !=null) {
			if(StringUtils.isNumeric(this.abbreviatedName) && StringUtils.isNumeric(otherGrade.abbreviatedName)) {
				return Integer.valueOf(this.abbreviatedName).compareTo(Integer.valueOf(otherGrade.abbreviatedName)); 
			}
		}
		if(this.name !=null) {
			return this.name.compareTo(otherGrade.name);
		}
		return this.id.compareTo(otherGrade.id);
	}
	
	
}