package edu.ku.cete.domain.content;

import java.util.ArrayList;
import java.util.Collection;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.apache.commons.collections.CollectionUtils;

import edu.ku.cete.domain.audit.AuditableDomain;
import edu.ku.cete.domain.lm.LmNode;
import edu.ku.cete.domain.lm.TaskVariantLearningMapNode;
import edu.ku.cete.domain.test.ContentFrameworkDetail;
import edu.ku.cete.domain.test.TaskVariantContentFrameworkDetail;

public class TaskVariant extends AuditableDomain {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.taskvariant.id
     *
     * @mbggenerated Thu Oct 18 08:24:46 CDT 2012
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.taskvariant.externalid
     *
     * @mbggenerated Thu Oct 18 08:24:46 CDT 2012
     */
    private Long externalId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.taskvariant.taskname
     *
     * @mbggenerated Thu Oct 18 08:24:46 CDT 2012
     */
    private String taskName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.taskvariant.variantname
     *
     * @mbggenerated Thu Oct 18 08:24:46 CDT 2012
     */
    private String variantName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.taskvariant.taskstem
     *
     * @mbggenerated Thu Oct 18 08:24:46 CDT 2012
     */
    private String taskStem;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.taskvariant.itemdescription
     *
     * @mbggenerated Thu Oct 18 08:24:46 CDT 2012
     */
    private String itemDescription;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.taskvariant.tasktypeid
     *
     * @mbggenerated Thu Oct 18 08:24:46 CDT 2012
     */
    private Long taskTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.taskvariant.tasklayoutid
     *
     * @mbggenerated Thu Oct 18 08:24:46 CDT 2012
     */
    private Long taskLayoutId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.taskvariant.tasklayoutformatid
     *
     * @mbggenerated Thu Oct 18 08:24:46 CDT 2012
     */
    private Long taskLayoutFormatId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.taskvariant.contentareaid
     *
     * @mbggenerated Thu Oct 18 08:24:46 CDT 2012
     */
    private Long contentAreaId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.taskvariant.gradecourseid
     *
     * @mbggenerated Thu Oct 18 08:24:46 CDT 2012
     */
    private Long gradeCourseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.taskvariant.testingprogramid
     *
     * @mbggenerated Thu Oct 18 08:24:46 CDT 2012
     */
    private Long testingProgramId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.taskvariant.frameworktypeid
     *
     * @mbggenerated Thu Oct 18 08:24:46 CDT 2012
     */
    private Long frameworkTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.taskvariant.taskdifficultyid
     *
     * @mbggenerated Thu Oct 18 08:24:46 CDT 2012
     */
    private Long taskDifficultyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.taskvariant.cognitivetaxonomyid
     *
     * @mbggenerated Thu Oct 18 08:24:46 CDT 2012
     */
    private Long cognitiveTaxonomyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.taskvariant.cognitivetaxonomydimensionid
     *
     * @mbggenerated Thu Oct 18 08:24:46 CDT 2012
     */
    private Long cognitiveTaxonomyDimensionId;
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.taskvariant.createdate
     *
     * @mbggenerated Thu Oct 18 08:24:46 CDT 2012
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.taskvariant.modifieddate
     *
     * @mbggenerated Thu Oct 18 08:24:46 CDT 2012
     */
    private Date modifiedDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.taskvariant.originationcode
     *
     * @mbggenerated Thu Oct 18 08:24:46 CDT 2012
     */
    private String originationCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.taskvariant.version
     *
     * @mbggenerated Thu Oct 18 08:24:46 CDT 2012
     */
    private Integer version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.taskvariant.testlet
     *
     * @mbggenerated Thu Oct 18 08:24:46 CDT 2012
     */
    private Boolean testlet;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.taskvariant.contextstimulusid
     *
     * @mbggenerated Thu Oct 18 08:24:46 CDT 2012
     */
    private Long contextStimulusId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.taskvariant.numberofresponses
     *
     * @mbggenerated Thu Oct 18 08:24:46 CDT 2012
     */
    private Integer numberOfResponses;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.taskvariant.shuffled
     *
     * @mbggenerated Thu Oct 18 08:24:46 CDT 2012
     */
    private Boolean shuffled;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.taskvariant.innovativeitempackagepath
     *
     * @mbggenerated Thu Oct 18 08:24:46 CDT 2012
     */
    private String innovativeItemPackagePath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.taskvariant.directions
     *
     * @mbggenerated Thu Oct 18 08:24:46 CDT 2012
     */
    private String directions;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.taskvariant.cue
     *
     * @mbggenerated Thu Oct 18 08:24:46 CDT 2012
     */
    private String cue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.taskvariant.completion
     *
     * @mbggenerated Thu Oct 18 08:24:46 CDT 2012
     */
    private String completion;
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.taskvariant.testlet
     *
     * @mbggenerated Thu Oct 18 08:24:46 CDT 2012
     */
    private Boolean rubricNeeded;
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.taskvariant.completion
     *
     * @mbggenerated Thu Oct 18 08:24:46 CDT 2012
     */
    private String taskType;
    
    private String taskSubType;
    
    private String contentCode;
    
    private Integer taskPosition;
   
	private Map<String,LmNode> lmNodeMap = new HashMap<String,LmNode>();
    /**
     * Holds the different foils attached to this Task Variant. Aides in scoring student responses.
     */
    private List<TaskVariantsFoils> taskVariantsFoils;

	private List<TaskVariantContentFrameworkDetail> taskVariantContentFrameworkDetails;
	
	private String scoringMethod;
	private Integer maxScore;
	private String essentialElement;
	private Long essentialElementId;
	
	private String studentResponse;
	
	private List<Foil> foilResponse;
	
	private Long responseOptionId;
	
	public Long getResponseOptionId() {
		return responseOptionId;
	}

	public void setResponseOptionId(Long responseOptionId) {
		this.responseOptionId = responseOptionId;
	}

	public String getTaskDefinition() {
		return taskDefinition;
	}

	public void setTaskDefinition(String taskDefinition) {
		this.taskDefinition = taskDefinition;
	}

	private String taskDefinition;

    /**
	 * @return the essentialElementId
	 */
	public Long getEssentialElementId() {
		return essentialElementId;
	}

	/**
	 * @param essentialElementId the essentialElementId to set
	 */
	public void setEssentialElementId(Long essentialElementId) {
		this.essentialElementId = essentialElementId;
	}

	/**
	 * @return the essentialElement
	 */
	public String getEssentialElement() {
		return essentialElement;
	}

	/**
	 * @param essentialElement the essentialElement to set
	 */
	public void setEssentialElement(String essentialElement) {
		this.essentialElement = essentialElement;
	}

	/**
	 * @return the maxScore
	 */
	public Integer getMaxScore() {
		return maxScore;
	}

	/**
	 * @param maxScore the maxScore to set
	 */
	public void setMaxScore(Integer maxScore) {
		this.maxScore = maxScore;
	}

	/**
	 * @return the scoringMethod
	 */
	public String getScoringMethod() {
		return scoringMethod;
	}

	/**
	 * @param scoringMethod the scoringMethod to set
	 */
	public void setScoringMethod(String scoringMethod) {
		this.scoringMethod = scoringMethod;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.taskvariant.id
     *
     * @return the value of public.taskvariant.id
     *
     * @mbggenerated Thu Oct 18 08:24:46 CDT 2012
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.taskvariant.id
     *
     * @param id the value for public.taskvariant.id
     *
     * @mbggenerated Thu Oct 18 08:24:46 CDT 2012
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.taskvariant.externalid
     *
     * @return the value of public.taskvariant.externalid
     *
     * @mbggenerated Thu Oct 18 08:24:46 CDT 2012
     */
    public Long getExternalId() {
        return externalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.taskvariant.externalid
     *
     * @param externalId the value for public.taskvariant.externalid
     *
     * @mbggenerated Thu Oct 18 08:24:46 CDT 2012
     */
    public void setExternalId(Long externalId) {
        this.externalId = externalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.taskvariant.taskname
     *
     * @return the value of public.taskvariant.taskname
     *
     * @mbggenerated Thu Oct 18 08:24:46 CDT 2012
     */
    public String getTaskName() {
        return taskName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.taskvariant.taskname
     *
     * @param taskName the value for public.taskvariant.taskname
     *
     * @mbggenerated Thu Oct 18 08:24:46 CDT 2012
     */
    public void setTaskName(String taskName) {
        this.taskName = taskName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.taskvariant.variantname
     *
     * @return the value of public.taskvariant.variantname
     *
     * @mbggenerated Thu Oct 18 08:24:46 CDT 2012
     */
    public String getVariantName() {
        return variantName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.taskvariant.variantname
     *
     * @param variantName the value for public.taskvariant.variantname
     *
     * @mbggenerated Thu Oct 18 08:24:46 CDT 2012
     */
    public void setVariantName(String variantName) {
        this.variantName = variantName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.taskvariant.taskstem
     *
     * @return the value of public.taskvariant.taskstem
     *
     * @mbggenerated Thu Oct 18 08:24:46 CDT 2012
     */
    public String getTaskStem() {
        return taskStem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.taskvariant.taskstem
     *
     * @param taskStem the value for public.taskvariant.taskstem
     *
     * @mbggenerated Thu Oct 18 08:24:46 CDT 2012
     */
    public void setTaskStem(String taskStem) {
        this.taskStem = taskStem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.taskvariant.itemdescription
     *
     * @return the value of public.taskvariant.itemdescription
     *
     * @mbggenerated Thu Oct 18 08:24:46 CDT 2012
     */
    public String getItemDescription() {
        return itemDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.taskvariant.itemdescription
     *
     * @param itemDescription the value for public.taskvariant.itemdescription
     *
     * @mbggenerated Thu Oct 18 08:24:46 CDT 2012
     */
    public void setItemDescription(String itemDescription) {
        this.itemDescription = itemDescription;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.taskvariant.tasktypeid
     *
     * @return the value of public.taskvariant.tasktypeid
     *
     * @mbggenerated Thu Oct 18 08:24:46 CDT 2012
     */
    public Long getTaskTypeId() {
        return taskTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.taskvariant.tasktypeid
     *
     * @param taskTypeId the value for public.taskvariant.tasktypeid
     *
     * @mbggenerated Thu Oct 18 08:24:46 CDT 2012
     */
    public void setTaskTypeId(Long taskTypeId) {
        this.taskTypeId = taskTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.taskvariant.tasklayoutid
     *
     * @return the value of public.taskvariant.tasklayoutid
     *
     * @mbggenerated Thu Oct 18 08:24:46 CDT 2012
     */
    public Long getTaskLayoutId() {
        return taskLayoutId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.taskvariant.tasklayoutid
     *
     * @param taskLayoutId the value for public.taskvariant.tasklayoutid
     *
     * @mbggenerated Thu Oct 18 08:24:46 CDT 2012
     */
    public void setTaskLayoutId(Long taskLayoutId) {
        this.taskLayoutId = taskLayoutId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.taskvariant.tasklayoutformatid
     *
     * @return the value of public.taskvariant.tasklayoutformatid
     *
     * @mbggenerated Thu Oct 18 08:24:46 CDT 2012
     */
    public Long getTaskLayoutFormatId() {
        return taskLayoutFormatId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.taskvariant.tasklayoutformatid
     *
     * @param taskLayoutFormatId the value for public.taskvariant.tasklayoutformatid
     *
     * @mbggenerated Thu Oct 18 08:24:46 CDT 2012
     */
    public void setTaskLayoutFormatId(Long taskLayoutFormatId) {
        this.taskLayoutFormatId = taskLayoutFormatId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.taskvariant.contentareaid
     *
     * @return the value of public.taskvariant.contentareaid
     *
     * @mbggenerated Thu Oct 18 08:24:46 CDT 2012
     */
    public Long getContentAreaId() {
        return contentAreaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.taskvariant.contentareaid
     *
     * @param contentAreaId the value for public.taskvariant.contentareaid
     *
     * @mbggenerated Thu Oct 18 08:24:46 CDT 2012
     */
    public void setContentAreaId(Long contentAreaId) {
        this.contentAreaId = contentAreaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.taskvariant.gradecourseid
     *
     * @return the value of public.taskvariant.gradecourseid
     *
     * @mbggenerated Thu Oct 18 08:24:46 CDT 2012
     */
    public Long getGradeCourseId() {
        return gradeCourseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.taskvariant.gradecourseid
     *
     * @param gradeCourseId the value for public.taskvariant.gradecourseid
     *
     * @mbggenerated Thu Oct 18 08:24:46 CDT 2012
     */
    public void setGradeCourseId(Long gradeCourseId) {
        this.gradeCourseId = gradeCourseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.taskvariant.testingprogramid
     *
     * @return the value of public.taskvariant.testingprogramid
     *
     * @mbggenerated Thu Oct 18 08:24:46 CDT 2012
     */
    public Long getTestingProgramId() {
        return testingProgramId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.taskvariant.testingprogramid
     *
     * @param testingProgramId the value for public.taskvariant.testingprogramid
     *
     * @mbggenerated Thu Oct 18 08:24:46 CDT 2012
     */
    public void setTestingProgramId(Long testingProgramId) {
        this.testingProgramId = testingProgramId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.taskvariant.frameworktypeid
     *
     * @return the value of public.taskvariant.frameworktypeid
     *
     * @mbggenerated Thu Oct 18 08:24:46 CDT 2012
     */
    public Long getFrameworkTypeId() {
        return frameworkTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.taskvariant.frameworktypeid
     *
     * @param frameworkTypeId the value for public.taskvariant.frameworktypeid
     *
     * @mbggenerated Thu Oct 18 08:24:46 CDT 2012
     */
    public void setFrameworkTypeId(Long frameworkTypeId) {
        this.frameworkTypeId = frameworkTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.taskvariant.taskdifficultyid
     *
     * @return the value of public.taskvariant.taskdifficultyid
     *
     * @mbggenerated Thu Oct 18 08:24:46 CDT 2012
     */
    public Long getTaskDifficultyId() {
        return taskDifficultyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.taskvariant.taskdifficultyid
     *
     * @param taskDifficultyId the value for public.taskvariant.taskdifficultyid
     *
     * @mbggenerated Thu Oct 18 08:24:46 CDT 2012
     */
    public void setTaskDifficultyId(Long taskDifficultyId) {
        this.taskDifficultyId = taskDifficultyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.taskvariant.cognitivetaxonomyid
     *
     * @return the value of public.taskvariant.cognitivetaxonomyid
     *
     * @mbggenerated Thu Oct 18 08:24:46 CDT 2012
     */
    public Long getCognitiveTaxonomyId() {
        return cognitiveTaxonomyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.taskvariant.cognitivetaxonomyid
     *
     * @param cognitiveTaxonomyId the value for public.taskvariant.cognitivetaxonomyid
     *
     * @mbggenerated Thu Oct 18 08:24:46 CDT 2012
     */
    public void setCognitiveTaxonomyId(Long cognitiveTaxonomyId) {
        this.cognitiveTaxonomyId = cognitiveTaxonomyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.taskvariant.cognitivetaxonomydimensionid
     *
     * @return the value of public.taskvariant.cognitivetaxonomydimensionid
     *
     * @mbggenerated Thu Oct 18 08:24:46 CDT 2012
     */
    public Long getCognitiveTaxonomyDimensionId() {
        return cognitiveTaxonomyDimensionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.taskvariant.cognitivetaxonomydimensionid
     *
     * @param cognitiveTaxonomyDimensionId the value for public.taskvariant.cognitivetaxonomydimensionid
     *
     * @mbggenerated Thu Oct 18 08:24:46 CDT 2012
     */
    public void setCognitiveTaxonomyDimensionId(Long cognitiveTaxonomyDimensionId) {
        this.cognitiveTaxonomyDimensionId = cognitiveTaxonomyDimensionId;
    }

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.taskvariant.createdate
     *
     * @return the value of public.taskvariant.createdate
     *
     * @mbggenerated Thu Oct 18 08:24:46 CDT 2012
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.taskvariant.createdate
     *
     * @param createDate the value for public.taskvariant.createdate
     *
     * @mbggenerated Thu Oct 18 08:24:46 CDT 2012
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.taskvariant.modifieddate
     *
     * @return the value of public.taskvariant.modifieddate
     *
     * @mbggenerated Thu Oct 18 08:24:46 CDT 2012
     */
    public Date getModifiedDate() {
        return modifiedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.taskvariant.modifieddate
     *
     * @param modifiedDate the value for public.taskvariant.modifieddate
     *
     * @mbggenerated Thu Oct 18 08:24:46 CDT 2012
     */
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.taskvariant.originationcode
     *
     * @return the value of public.taskvariant.originationcode
     *
     * @mbggenerated Thu Oct 18 08:24:46 CDT 2012
     */
    public String getOriginationCode() {
        return originationCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.taskvariant.originationcode
     *
     * @param originationCode the value for public.taskvariant.originationcode
     *
     * @mbggenerated Thu Oct 18 08:24:46 CDT 2012
     */
    public void setOriginationCode(String originationCode) {
        this.originationCode = originationCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.taskvariant.version
     *
     * @return the value of public.taskvariant.version
     *
     * @mbggenerated Thu Oct 18 08:24:46 CDT 2012
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.taskvariant.version
     *
     * @param version the value for public.taskvariant.version
     *
     * @mbggenerated Thu Oct 18 08:24:46 CDT 2012
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.taskvariant.testlet
     *
     * @return the value of public.taskvariant.testlet
     *
     * @mbggenerated Thu Oct 18 08:24:46 CDT 2012
     */
    public Boolean getTestlet() {
        return testlet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.taskvariant.testlet
     *
     * @param testlet the value for public.taskvariant.testlet
     *
     * @mbggenerated Thu Oct 18 08:24:46 CDT 2012
     */
    public void setTestlet(Boolean testlet) {
        this.testlet = testlet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.taskvariant.contextstimulusid
     *
     * @return the value of public.taskvariant.contextstimulusid
     *
     * @mbggenerated Thu Oct 18 08:24:46 CDT 2012
     */
    public Long getContextStimulusId() {
        return contextStimulusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.taskvariant.contextstimulusid
     *
     * @param contextStimulusId the value for public.taskvariant.contextstimulusid
     *
     * @mbggenerated Thu Oct 18 08:24:46 CDT 2012
     */
    public void setContextStimulusId(Long contextStimulusId) {
        this.contextStimulusId = contextStimulusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.taskvariant.numberofresponses
     *
     * @return the value of public.taskvariant.numberofresponses
     *
     * @mbggenerated Thu Oct 18 08:24:46 CDT 2012
     */
    public Integer getNumberOfResponses() {
        return numberOfResponses;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.taskvariant.numberofresponses
     *
     * @param numberOfResponses the value for public.taskvariant.numberofresponses
     *
     * @mbggenerated Thu Oct 18 08:24:46 CDT 2012
     */
    public void setNumberOfResponses(Integer numberOfResponses) {
        this.numberOfResponses = numberOfResponses;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.taskvariant.shuffled
     *
     * @return the value of public.taskvariant.shuffled
     *
     * @mbggenerated Thu Oct 18 08:24:46 CDT 2012
     */
    public Boolean getShuffled() {
        return shuffled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.taskvariant.shuffled
     *
     * @param shuffled the value for public.taskvariant.shuffled
     *
     * @mbggenerated Thu Oct 18 08:24:46 CDT 2012
     */
    public void setShuffled(Boolean shuffled) {
        this.shuffled = shuffled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.taskvariant.innovativeitempackagepath
     *
     * @return the value of public.taskvariant.innovativeitempackagepath
     *
     * @mbggenerated Thu Oct 18 08:24:46 CDT 2012
     */
    public String getInnovativeItemPackagePath() {
        return innovativeItemPackagePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.taskvariant.innovativeitempackagepath
     *
     * @param innovativeItemPackagePath the value for public.taskvariant.innovativeitempackagepath
     *
     * @mbggenerated Thu Oct 18 08:24:46 CDT 2012
     */
    public void setInnovativeItemPackagePath(String innovativeItemPackagePath) {
        this.innovativeItemPackagePath = innovativeItemPackagePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.taskvariant.directions
     *
     * @return the value of public.taskvariant.directions
     *
     * @mbggenerated Thu Oct 18 08:24:46 CDT 2012
     */
    public String getDirections() {
        return directions;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.taskvariant.directions
     *
     * @param directions the value for public.taskvariant.directions
     *
     * @mbggenerated Thu Oct 18 08:24:46 CDT 2012
     */
    public void setDirections(String directions) {
        this.directions = directions;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.taskvariant.cue
     *
     * @return the value of public.taskvariant.cue
     *
     * @mbggenerated Thu Oct 18 08:24:46 CDT 2012
     */
    public String getCue() {
        return cue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.taskvariant.cue
     *
     * @param cue the value for public.taskvariant.cue
     *
     * @mbggenerated Thu Oct 18 08:24:46 CDT 2012
     */
    public void setCue(String cue) {
        this.cue = cue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.taskvariant.completion
     *
     * @return the value of public.taskvariant.completion
     *
     * @mbggenerated Thu Oct 18 08:24:46 CDT 2012
     */
    public String getCompletion() {
        return completion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.taskvariant.completion
     *
     * @param completion the value for public.taskvariant.completion
     *
     * @mbggenerated Thu Oct 18 08:24:46 CDT 2012
     */
    public void setCompletion(String completion) {
        this.completion = completion;
    }

    /**
	 * @return the lmNode
	 */
	public Map<String,LmNode> getLmNodeMap() {
		return lmNodeMap;
	}

    /**
	 * @return the lmNode
	 */
	public Collection<LmNode> getLmNodes() {
		return lmNodeMap.values();
	}
	/**
	 * @param lmNode the lmNode to set
	 */
	public void setLmNodeMap(Map<String,LmNode> lmNodeMap) {
		this.lmNodeMap = lmNodeMap;
	}
	/**
	 * @param lmNode the lmNode to set
	 */
	public void addLmNode(LmNode lmNode) {
		if(lmNode != null && lmNode.getNodeKey() != null) {
			if(! getLmNodeMap().containsKey(lmNode.getNodeKey())) {
				getLmNodeMap().put(lmNode.getNodeKey(), lmNode);
			}
		}
	}
	/**
     * @return the taskVariantsFoils
     */
    public List<TaskVariantsFoils> getTaskVariantsFoils() {
        return taskVariantsFoils;
    }

    /**
	 * @return the taskVariantContentFrameworkDetails
	 */
	public List<TaskVariantContentFrameworkDetail> getTaskVariantContentFrameworkDetails() {
		return taskVariantContentFrameworkDetails;
	}

	/**
	 * @param taskVariantContentFrameworkDetails the taskVariantContentFrameworkDetails to set
	 */
	public void setTaskVariantContentFrameworkDetails(
			List<TaskVariantContentFrameworkDetail> taskVariantContentFrameworkDetails) {
		this.taskVariantContentFrameworkDetails = taskVariantContentFrameworkDetails;
	}

	/**
     * @param taskVariantsFoils the taskVariantsFoils to set
     */
    public void setTaskVariantsFoils(List<TaskVariantsFoils> taskVariantsFoils) {
        this.taskVariantsFoils = taskVariantsFoils;
    }

	/**
	 * @param taskVariantsFoilsList {@link List}
	 */
	public final void setApplicableTaskVariantsFoils(
			List<TaskVariantsFoils> taskVariantsFoilsList) {
    	if (taskVariantsFoilsList != null && CollectionUtils.isNotEmpty(taskVariantsFoilsList)) {
    		for (TaskVariantsFoils taskVariantFoil:taskVariantsFoilsList) {
    			addTaskVariantsFoils(taskVariantFoil);
    		}
    	}
	}

    /**
     * @param taskVariantFoil {@link TaskVariantsFoils}
     */
    public final void addTaskVariantsFoils(TaskVariantsFoils taskVariantFoil) {
    	if (getTaskVariantsFoils() == null) {
    		this.taskVariantsFoils = new ArrayList<TaskVariantsFoils>();
    	}
		if (taskVariantFoil != null
				&& taskVariantFoil.getTaskVariantId() != null
				&& getId() != null
				&& getId().longValue() == taskVariantFoil.getTaskVariantId().longValue()
				) {
			this.taskVariantsFoils.add(taskVariantFoil);
		}
	}

	/**
	 * @param taskVariantContentFrameworkDetailsList
	 */
	public void setPrimaryContentFrameworkDetail(
			List<TaskVariantContentFrameworkDetail> taskVariantContentFrameworkDetailsList) {
    	if (taskVariantContentFrameworkDetailsList != null && CollectionUtils.isNotEmpty(taskVariantContentFrameworkDetailsList)) {
    		for (TaskVariantContentFrameworkDetail taskVariantContentFrameworkDetail:taskVariantContentFrameworkDetailsList) {
    			addTaskVariantContentFrameworkDetail(taskVariantContentFrameworkDetail);
    		}
    	}		
	}
	
	/**
	 * @return {@link ContentFrameworkDetail}
	 */
	public final ContentFrameworkDetail getPrimaryContentFrameworkDetail() {
		ContentFrameworkDetail primaryContentFrameworkDetail = null;
		if (getTaskVariantContentFrameworkDetails() != null
				&& CollectionUtils.isNotEmpty(getTaskVariantContentFrameworkDetails())
				&&  getTaskVariantContentFrameworkDetails().get(0) != null
				&&  getTaskVariantContentFrameworkDetails().get(0).getContentFrameworkDetail() != null
				) {
			primaryContentFrameworkDetail = getTaskVariantContentFrameworkDetails().get(0).getContentFrameworkDetail();
		}
		return primaryContentFrameworkDetail;
	}
	

	/**
	 * @param taskVariantContentFrameworkDetail {@link TaskVariantContentFrameworkDetail}
	 */
	public void addTaskVariantContentFrameworkDetail(
			TaskVariantContentFrameworkDetail taskVariantContentFrameworkDetail) {
    	if (getTaskVariantContentFrameworkDetails() == null) {
    		this.setTaskVariantContentFrameworkDetails(new ArrayList<TaskVariantContentFrameworkDetail>());
    	}
		if (taskVariantContentFrameworkDetail != null
				&& taskVariantContentFrameworkDetail.getTaskVariantId() != null
				&& getId() != null
				&& getId().longValue() == taskVariantContentFrameworkDetail.getTaskVariantId().longValue()
				) {
			this.taskVariantContentFrameworkDetails.add(taskVariantContentFrameworkDetail);
		}
	}

	
	/**
	 * 1. checks after adding.
	 * 
	 * @param taskVariantLearningMapNodes
	 */
	public void setApplicableLearningMapNodes(
			List<TaskVariantLearningMapNode> taskVariantLearningMapNodes) {
		for(TaskVariantLearningMapNode
				taskVariantLearningMapNode: taskVariantLearningMapNodes) {
			addApplicableLearningMapNode(
					taskVariantLearningMapNode);
		}
	}

	/**
	 * 1. check task variant id.
	 * 2. if same as this, then add to the lm node map, by key.
	 * 
	 * @param taskVariantLearningMapNode
	 */
	public void addApplicableLearningMapNode(
			TaskVariantLearningMapNode taskVariantLearningMapNode) {
		if(taskVariantLearningMapNode != null
				&& taskVariantLearningMapNode.getTaskVariantId(
						).equals(getId())) {
			this.addLmNode(new LmNode(
					taskVariantLearningMapNode.getNodeCode()));
		}
	}
	
	/**
	 * Update the node information, if a node is found based off key.
	 * 
	 * @param inLmNode
	 */
	public void updateNodeInfo(LmNode inLmNode) {
		LmNode lmNode = getLmNodeMap().get(
				inLmNode.getNodeKey());
		if(inLmNode != null
				&& lmNode != null) {
			lmNode.setNodeId(inLmNode.getNodeId());
			lmNode.setNodeName(inLmNode.getNodeName());
			lmNode.setProfiles(inLmNode.getProfiles());
			lmNode.setAttributeAndValues(inLmNode.getAttributeAndValues());
		}
	}
	public void updateNodeInfo(Set<LmNode> inLmNodes) {
		for(LmNode lmNode:inLmNodes) {
			updateNodeInfo(lmNode);
		}
	}

	public Boolean getRubricNeeded() {
		return rubricNeeded;
	}

	public void setRubricNeeded(Boolean rubricNeeded) {
		this.rubricNeeded = rubricNeeded;
	}

	public String getTaskType() {
		return taskType;
	}

	public void setTaskType(String taskType) {
		this.taskType = taskType;
	}
	
	private Long reportTaskLayoutFormatId;
	private Boolean scoringNeeded;
	private String scoringData;
	
	public Long getReportTaskLayoutFormatId() {
		return reportTaskLayoutFormatId;
	}

	public void setReportTaskLayoutFormatId(Long reportTaskLayoutFormatId) {
		this.reportTaskLayoutFormatId = reportTaskLayoutFormatId;
	}

	public Boolean getScoringNeeded() {
		return scoringNeeded;
	}

	public void setScoringNeeded(Boolean scoringNeeded) {
		this.scoringNeeded = scoringNeeded;
	}

	public String getScoringData() {
		return scoringData;
	}

	public void setScoringData(String scoringData) {
		this.scoringData = scoringData;
	}
	 
    public String getTaskSubType() {
		return taskSubType;
	}

	public void setTaskSubType(String taskSubType) {
		this.taskSubType = taskSubType;
	}

	public String getContentCode() {
		return contentCode == null ? "" : contentCode;
	}

	public void setContentCode(String contentCode) {
		this.contentCode = contentCode;
	}

	public Integer getTaskPosition() {
		return taskPosition;
	}

	public void setTaskPosition(Integer taskPosition) {
		this.taskPosition = taskPosition;
	}

	public String getStudentResponse() {
		return studentResponse;
	}

	public void setStudentResponse(String studentResponse) {
		this.studentResponse = studentResponse;
	}

	public List<Foil> getFoilResponse() {
		return foilResponse;
	}

	public void setFoilResponse(List<Foil> foilResponse) {
		this.foilResponse = foilResponse;
	}
	

}