package edu.ku.cete.domain.content;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TestSectionExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.testsection
     *
     * @mbggenerated Wed Dec 12 21:51:26 CST 2012
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.testsection
     *
     * @mbggenerated Wed Dec 12 21:51:26 CST 2012
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.testsection
     *
     * @mbggenerated Wed Dec 12 21:51:26 CST 2012
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.testsection
     *
     * @mbggenerated Wed Dec 12 21:51:26 CST 2012
     */
    public TestSectionExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.testsection
     *
     * @mbggenerated Wed Dec 12 21:51:26 CST 2012
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.testsection
     *
     * @mbggenerated Wed Dec 12 21:51:26 CST 2012
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.testsection
     *
     * @mbggenerated Wed Dec 12 21:51:26 CST 2012
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.testsection
     *
     * @mbggenerated Wed Dec 12 21:51:26 CST 2012
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.testsection
     *
     * @mbggenerated Wed Dec 12 21:51:26 CST 2012
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.testsection
     *
     * @mbggenerated Wed Dec 12 21:51:26 CST 2012
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.testsection
     *
     * @mbggenerated Wed Dec 12 21:51:26 CST 2012
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.testsection
     *
     * @mbggenerated Wed Dec 12 21:51:26 CST 2012
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.testsection
     *
     * @mbggenerated Wed Dec 12 21:51:26 CST 2012
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.testsection
     *
     * @mbggenerated Wed Dec 12 21:51:26 CST 2012
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.testsection
     *
     * @mbggenerated Wed Dec 12 21:51:26 CST 2012
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andExternalIdIsNull() {
            addCriterion("externalid is null");
            return (Criteria) this;
        }

        public Criteria andExternalIdIsNotNull() {
            addCriterion("externalid is not null");
            return (Criteria) this;
        }

        public Criteria andExternalIdEqualTo(Long value) {
            addCriterion("externalid =", value, "externalId");
            return (Criteria) this;
        }

        public Criteria andExternalIdNotEqualTo(Long value) {
            addCriterion("externalid <>", value, "externalId");
            return (Criteria) this;
        }

        public Criteria andExternalIdGreaterThan(Long value) {
            addCriterion("externalid >", value, "externalId");
            return (Criteria) this;
        }

        public Criteria andExternalIdGreaterThanOrEqualTo(Long value) {
            addCriterion("externalid >=", value, "externalId");
            return (Criteria) this;
        }

        public Criteria andExternalIdLessThan(Long value) {
            addCriterion("externalid <", value, "externalId");
            return (Criteria) this;
        }

        public Criteria andExternalIdLessThanOrEqualTo(Long value) {
            addCriterion("externalid <=", value, "externalId");
            return (Criteria) this;
        }

        public Criteria andExternalIdIn(List<Long> values) {
            addCriterion("externalid in", values, "externalId");
            return (Criteria) this;
        }

        public Criteria andExternalIdNotIn(List<Long> values) {
            addCriterion("externalid not in", values, "externalId");
            return (Criteria) this;
        }

        public Criteria andExternalIdBetween(Long value1, Long value2) {
            addCriterion("externalid between", value1, value2, "externalId");
            return (Criteria) this;
        }

        public Criteria andExternalIdNotBetween(Long value1, Long value2) {
            addCriterion("externalid not between", value1, value2, "externalId");
            return (Criteria) this;
        }

        public Criteria andTestIdIsNull() {
            addCriterion("testid is null");
            return (Criteria) this;
        }

        public Criteria andTestIdIsNotNull() {
            addCriterion("testid is not null");
            return (Criteria) this;
        }

        public Criteria andTestIdEqualTo(Long value) {
            addCriterion("testid =", value, "testId");
            return (Criteria) this;
        }

        public Criteria andTestIdNotEqualTo(Long value) {
            addCriterion("testid <>", value, "testId");
            return (Criteria) this;
        }

        public Criteria andTestIdGreaterThan(Long value) {
            addCriterion("testid >", value, "testId");
            return (Criteria) this;
        }

        public Criteria andTestIdGreaterThanOrEqualTo(Long value) {
            addCriterion("testid >=", value, "testId");
            return (Criteria) this;
        }

        public Criteria andTestIdLessThan(Long value) {
            addCriterion("testid <", value, "testId");
            return (Criteria) this;
        }

        public Criteria andTestIdLessThanOrEqualTo(Long value) {
            addCriterion("testid <=", value, "testId");
            return (Criteria) this;
        }

        public Criteria andTestIdIn(List<Long> values) {
            addCriterion("testid in", values, "testId");
            return (Criteria) this;
        }

        public Criteria andTestIdNotIn(List<Long> values) {
            addCriterion("testid not in", values, "testId");
            return (Criteria) this;
        }

        public Criteria andTestIdBetween(Long value1, Long value2) {
            addCriterion("testid between", value1, value2, "testId");
            return (Criteria) this;
        }

        public Criteria andTestIdNotBetween(Long value1, Long value2) {
            addCriterion("testid not between", value1, value2, "testId");
            return (Criteria) this;
        }

        public Criteria andTestSectionNameIsNull() {
            addCriterion("testsectionname is null");
            return (Criteria) this;
        }

        public Criteria andTestSectionNameIsNotNull() {
            addCriterion("testsectionname is not null");
            return (Criteria) this;
        }

        public Criteria andTestSectionNameEqualTo(String value) {
            addCriterion("testsectionname =", value, "testSectionName");
            return (Criteria) this;
        }

        public Criteria andTestSectionNameNotEqualTo(String value) {
            addCriterion("testsectionname <>", value, "testSectionName");
            return (Criteria) this;
        }

        public Criteria andTestSectionNameGreaterThan(String value) {
            addCriterion("testsectionname >", value, "testSectionName");
            return (Criteria) this;
        }

        public Criteria andTestSectionNameGreaterThanOrEqualTo(String value) {
            addCriterion("testsectionname >=", value, "testSectionName");
            return (Criteria) this;
        }

        public Criteria andTestSectionNameLessThan(String value) {
            addCriterion("testsectionname <", value, "testSectionName");
            return (Criteria) this;
        }

        public Criteria andTestSectionNameLessThanOrEqualTo(String value) {
            addCriterion("testsectionname <=", value, "testSectionName");
            return (Criteria) this;
        }

        public Criteria andTestSectionNameLike(String value) {
            addCriterion("testsectionname like", value, "testSectionName");
            return (Criteria) this;
        }

        public Criteria andTestSectionNameNotLike(String value) {
            addCriterion("testsectionname not like", value, "testSectionName");
            return (Criteria) this;
        }

        public Criteria andTestSectionNameIn(List<String> values) {
            addCriterion("testsectionname in", values, "testSectionName");
            return (Criteria) this;
        }

        public Criteria andTestSectionNameNotIn(List<String> values) {
            addCriterion("testsectionname not in", values, "testSectionName");
            return (Criteria) this;
        }

        public Criteria andTestSectionNameBetween(String value1, String value2) {
            addCriterion("testsectionname between", value1, value2, "testSectionName");
            return (Criteria) this;
        }

        public Criteria andTestSectionNameNotBetween(String value1, String value2) {
            addCriterion("testsectionname not between", value1, value2, "testSectionName");
            return (Criteria) this;
        }

        public Criteria andNumberOfTestItemsIsNull() {
            addCriterion("numberoftestitems is null");
            return (Criteria) this;
        }

        public Criteria andNumberOfTestItemsIsNotNull() {
            addCriterion("numberoftestitems is not null");
            return (Criteria) this;
        }

        public Criteria andNumberOfTestItemsEqualTo(Integer value) {
            addCriterion("numberoftestitems =", value, "numberOfTestItems");
            return (Criteria) this;
        }

        public Criteria andNumberOfTestItemsNotEqualTo(Integer value) {
            addCriterion("numberoftestitems <>", value, "numberOfTestItems");
            return (Criteria) this;
        }

        public Criteria andNumberOfTestItemsGreaterThan(Integer value) {
            addCriterion("numberoftestitems >", value, "numberOfTestItems");
            return (Criteria) this;
        }

        public Criteria andNumberOfTestItemsGreaterThanOrEqualTo(Integer value) {
            addCriterion("numberoftestitems >=", value, "numberOfTestItems");
            return (Criteria) this;
        }

        public Criteria andNumberOfTestItemsLessThan(Integer value) {
            addCriterion("numberoftestitems <", value, "numberOfTestItems");
            return (Criteria) this;
        }

        public Criteria andNumberOfTestItemsLessThanOrEqualTo(Integer value) {
            addCriterion("numberoftestitems <=", value, "numberOfTestItems");
            return (Criteria) this;
        }

        public Criteria andNumberOfTestItemsIn(List<Integer> values) {
            addCriterion("numberoftestitems in", values, "numberOfTestItems");
            return (Criteria) this;
        }

        public Criteria andNumberOfTestItemsNotIn(List<Integer> values) {
            addCriterion("numberoftestitems not in", values, "numberOfTestItems");
            return (Criteria) this;
        }

        public Criteria andNumberOfTestItemsBetween(Integer value1, Integer value2) {
            addCriterion("numberoftestitems between", value1, value2, "numberOfTestItems");
            return (Criteria) this;
        }

        public Criteria andNumberOfTestItemsNotBetween(Integer value1, Integer value2) {
            addCriterion("numberoftestitems not between", value1, value2, "numberOfTestItems");
            return (Criteria) this;
        }

        public Criteria andHelpNotesIsNull() {
            addCriterion("helpnotes is null");
            return (Criteria) this;
        }

        public Criteria andHelpNotesIsNotNull() {
            addCriterion("helpnotes is not null");
            return (Criteria) this;
        }

        public Criteria andHelpNotesEqualTo(String value) {
            addCriterion("helpnotes =", value, "helpNotes");
            return (Criteria) this;
        }

        public Criteria andHelpNotesNotEqualTo(String value) {
            addCriterion("helpnotes <>", value, "helpNotes");
            return (Criteria) this;
        }

        public Criteria andHelpNotesGreaterThan(String value) {
            addCriterion("helpnotes >", value, "helpNotes");
            return (Criteria) this;
        }

        public Criteria andHelpNotesGreaterThanOrEqualTo(String value) {
            addCriterion("helpnotes >=", value, "helpNotes");
            return (Criteria) this;
        }

        public Criteria andHelpNotesLessThan(String value) {
            addCriterion("helpnotes <", value, "helpNotes");
            return (Criteria) this;
        }

        public Criteria andHelpNotesLessThanOrEqualTo(String value) {
            addCriterion("helpnotes <=", value, "helpNotes");
            return (Criteria) this;
        }

        public Criteria andHelpNotesLike(String value) {
            addCriterion("helpnotes like", value, "helpNotes");
            return (Criteria) this;
        }

        public Criteria andHelpNotesNotLike(String value) {
            addCriterion("helpnotes not like", value, "helpNotes");
            return (Criteria) this;
        }

        public Criteria andHelpNotesIn(List<String> values) {
            addCriterion("helpnotes in", values, "helpNotes");
            return (Criteria) this;
        }

        public Criteria andHelpNotesNotIn(List<String> values) {
            addCriterion("helpnotes not in", values, "helpNotes");
            return (Criteria) this;
        }

        public Criteria andHelpNotesBetween(String value1, String value2) {
            addCriterion("helpnotes between", value1, value2, "helpNotes");
            return (Criteria) this;
        }

        public Criteria andHelpNotesNotBetween(String value1, String value2) {
            addCriterion("helpnotes not between", value1, value2, "helpNotes");
            return (Criteria) this;
        }

        public Criteria andToolsUsageIdIsNull() {
            addCriterion("toolsusageid is null");
            return (Criteria) this;
        }

        public Criteria andToolsUsageIdIsNotNull() {
            addCriterion("toolsusageid is not null");
            return (Criteria) this;
        }

        public Criteria andToolsUsageIdEqualTo(Long value) {
            addCriterion("toolsusageid =", value, "toolsUsageId");
            return (Criteria) this;
        }

        public Criteria andToolsUsageIdNotEqualTo(Long value) {
            addCriterion("toolsusageid <>", value, "toolsUsageId");
            return (Criteria) this;
        }

        public Criteria andToolsUsageIdGreaterThan(Long value) {
            addCriterion("toolsusageid >", value, "toolsUsageId");
            return (Criteria) this;
        }

        public Criteria andToolsUsageIdGreaterThanOrEqualTo(Long value) {
            addCriterion("toolsusageid >=", value, "toolsUsageId");
            return (Criteria) this;
        }

        public Criteria andToolsUsageIdLessThan(Long value) {
            addCriterion("toolsusageid <", value, "toolsUsageId");
            return (Criteria) this;
        }

        public Criteria andToolsUsageIdLessThanOrEqualTo(Long value) {
            addCriterion("toolsusageid <=", value, "toolsUsageId");
            return (Criteria) this;
        }

        public Criteria andToolsUsageIdIn(List<Long> values) {
            addCriterion("toolsusageid in", values, "toolsUsageId");
            return (Criteria) this;
        }

        public Criteria andToolsUsageIdNotIn(List<Long> values) {
            addCriterion("toolsusageid not in", values, "toolsUsageId");
            return (Criteria) this;
        }

        public Criteria andToolsUsageIdBetween(Long value1, Long value2) {
            addCriterion("toolsusageid between", value1, value2, "toolsUsageId");
            return (Criteria) this;
        }

        public Criteria andToolsUsageIdNotBetween(Long value1, Long value2) {
            addCriterion("toolsusageid not between", value1, value2, "toolsUsageId");
            return (Criteria) this;
        }

        public Criteria andTaskDeliveryRuleIdIsNull() {
            addCriterion("taskdeliveryruleid is null");
            return (Criteria) this;
        }

        public Criteria andTaskDeliveryRuleIdIsNotNull() {
            addCriterion("taskdeliveryruleid is not null");
            return (Criteria) this;
        }

        public Criteria andTaskDeliveryRuleIdEqualTo(Long value) {
            addCriterion("taskdeliveryruleid =", value, "taskDeliveryRuleId");
            return (Criteria) this;
        }

        public Criteria andTaskDeliveryRuleIdNotEqualTo(Long value) {
            addCriterion("taskdeliveryruleid <>", value, "taskDeliveryRuleId");
            return (Criteria) this;
        }

        public Criteria andTaskDeliveryRuleIdGreaterThan(Long value) {
            addCriterion("taskdeliveryruleid >", value, "taskDeliveryRuleId");
            return (Criteria) this;
        }

        public Criteria andTaskDeliveryRuleIdGreaterThanOrEqualTo(Long value) {
            addCriterion("taskdeliveryruleid >=", value, "taskDeliveryRuleId");
            return (Criteria) this;
        }

        public Criteria andTaskDeliveryRuleIdLessThan(Long value) {
            addCriterion("taskdeliveryruleid <", value, "taskDeliveryRuleId");
            return (Criteria) this;
        }

        public Criteria andTaskDeliveryRuleIdLessThanOrEqualTo(Long value) {
            addCriterion("taskdeliveryruleid <=", value, "taskDeliveryRuleId");
            return (Criteria) this;
        }

        public Criteria andTaskDeliveryRuleIdIn(List<Long> values) {
            addCriterion("taskdeliveryruleid in", values, "taskDeliveryRuleId");
            return (Criteria) this;
        }

        public Criteria andTaskDeliveryRuleIdNotIn(List<Long> values) {
            addCriterion("taskdeliveryruleid not in", values, "taskDeliveryRuleId");
            return (Criteria) this;
        }

        public Criteria andTaskDeliveryRuleIdBetween(Long value1, Long value2) {
            addCriterion("taskdeliveryruleid between", value1, value2, "taskDeliveryRuleId");
            return (Criteria) this;
        }

        public Criteria andTaskDeliveryRuleIdNotBetween(Long value1, Long value2) {
            addCriterion("taskdeliveryruleid not between", value1, value2, "taskDeliveryRuleId");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNull() {
            addCriterion("createdate is null");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNotNull() {
            addCriterion("createdate is not null");
            return (Criteria) this;
        }

        public Criteria andCreateDateEqualTo(Date value) {
            addCriterion("createdate =", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotEqualTo(Date value) {
            addCriterion("createdate <>", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThan(Date value) {
            addCriterion("createdate >", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("createdate >=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThan(Date value) {
            addCriterion("createdate <", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThanOrEqualTo(Date value) {
            addCriterion("createdate <=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateIn(List<Date> values) {
            addCriterion("createdate in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotIn(List<Date> values) {
            addCriterion("createdate not in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateBetween(Date value1, Date value2) {
            addCriterion("createdate between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotBetween(Date value1, Date value2) {
            addCriterion("createdate not between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andModifiedDateIsNull() {
            addCriterion("modifieddate is null");
            return (Criteria) this;
        }

        public Criteria andModifiedDateIsNotNull() {
            addCriterion("modifieddate is not null");
            return (Criteria) this;
        }

        public Criteria andModifiedDateEqualTo(Date value) {
            addCriterion("modifieddate =", value, "modifiedDate");
            return (Criteria) this;
        }

        public Criteria andModifiedDateNotEqualTo(Date value) {
            addCriterion("modifieddate <>", value, "modifiedDate");
            return (Criteria) this;
        }

        public Criteria andModifiedDateGreaterThan(Date value) {
            addCriterion("modifieddate >", value, "modifiedDate");
            return (Criteria) this;
        }

        public Criteria andModifiedDateGreaterThanOrEqualTo(Date value) {
            addCriterion("modifieddate >=", value, "modifiedDate");
            return (Criteria) this;
        }

        public Criteria andModifiedDateLessThan(Date value) {
            addCriterion("modifieddate <", value, "modifiedDate");
            return (Criteria) this;
        }

        public Criteria andModifiedDateLessThanOrEqualTo(Date value) {
            addCriterion("modifieddate <=", value, "modifiedDate");
            return (Criteria) this;
        }

        public Criteria andModifiedDateIn(List<Date> values) {
            addCriterion("modifieddate in", values, "modifiedDate");
            return (Criteria) this;
        }

        public Criteria andModifiedDateNotIn(List<Date> values) {
            addCriterion("modifieddate not in", values, "modifiedDate");
            return (Criteria) this;
        }

        public Criteria andModifiedDateBetween(Date value1, Date value2) {
            addCriterion("modifieddate between", value1, value2, "modifiedDate");
            return (Criteria) this;
        }

        public Criteria andModifiedDateNotBetween(Date value1, Date value2) {
            addCriterion("modifieddate not between", value1, value2, "modifiedDate");
            return (Criteria) this;
        }

        public Criteria andOriginationCodeIsNull() {
            addCriterion("originationcode is null");
            return (Criteria) this;
        }

        public Criteria andOriginationCodeIsNotNull() {
            addCriterion("originationcode is not null");
            return (Criteria) this;
        }

        public Criteria andOriginationCodeEqualTo(String value) {
            addCriterion("originationcode =", value, "originationCode");
            return (Criteria) this;
        }

        public Criteria andOriginationCodeNotEqualTo(String value) {
            addCriterion("originationcode <>", value, "originationCode");
            return (Criteria) this;
        }

        public Criteria andOriginationCodeGreaterThan(String value) {
            addCriterion("originationcode >", value, "originationCode");
            return (Criteria) this;
        }

        public Criteria andOriginationCodeGreaterThanOrEqualTo(String value) {
            addCriterion("originationcode >=", value, "originationCode");
            return (Criteria) this;
        }

        public Criteria andOriginationCodeLessThan(String value) {
            addCriterion("originationcode <", value, "originationCode");
            return (Criteria) this;
        }

        public Criteria andOriginationCodeLessThanOrEqualTo(String value) {
            addCriterion("originationcode <=", value, "originationCode");
            return (Criteria) this;
        }

        public Criteria andOriginationCodeLike(String value) {
            addCriterion("originationcode like", value, "originationCode");
            return (Criteria) this;
        }

        public Criteria andOriginationCodeNotLike(String value) {
            addCriterion("originationcode not like", value, "originationCode");
            return (Criteria) this;
        }

        public Criteria andOriginationCodeIn(List<String> values) {
            addCriterion("originationcode in", values, "originationCode");
            return (Criteria) this;
        }

        public Criteria andOriginationCodeNotIn(List<String> values) {
            addCriterion("originationcode not in", values, "originationCode");
            return (Criteria) this;
        }

        public Criteria andOriginationCodeBetween(String value1, String value2) {
            addCriterion("originationcode between", value1, value2, "originationCode");
            return (Criteria) this;
        }

        public Criteria andOriginationCodeNotBetween(String value1, String value2) {
            addCriterion("originationcode not between", value1, value2, "originationCode");
            return (Criteria) this;
        }

        public Criteria andBeginInstructionsIsNull() {
            addCriterion("begininstructions is null");
            return (Criteria) this;
        }

        public Criteria andBeginInstructionsIsNotNull() {
            addCriterion("begininstructions is not null");
            return (Criteria) this;
        }

        public Criteria andBeginInstructionsEqualTo(String value) {
            addCriterion("begininstructions =", value, "beginInstructions");
            return (Criteria) this;
        }

        public Criteria andBeginInstructionsNotEqualTo(String value) {
            addCriterion("begininstructions <>", value, "beginInstructions");
            return (Criteria) this;
        }

        public Criteria andBeginInstructionsGreaterThan(String value) {
            addCriterion("begininstructions >", value, "beginInstructions");
            return (Criteria) this;
        }

        public Criteria andBeginInstructionsGreaterThanOrEqualTo(String value) {
            addCriterion("begininstructions >=", value, "beginInstructions");
            return (Criteria) this;
        }

        public Criteria andBeginInstructionsLessThan(String value) {
            addCriterion("begininstructions <", value, "beginInstructions");
            return (Criteria) this;
        }

        public Criteria andBeginInstructionsLessThanOrEqualTo(String value) {
            addCriterion("begininstructions <=", value, "beginInstructions");
            return (Criteria) this;
        }

        public Criteria andBeginInstructionsLike(String value) {
            addCriterion("begininstructions like", value, "beginInstructions");
            return (Criteria) this;
        }

        public Criteria andBeginInstructionsNotLike(String value) {
            addCriterion("begininstructions not like", value, "beginInstructions");
            return (Criteria) this;
        }

        public Criteria andBeginInstructionsIn(List<String> values) {
            addCriterion("begininstructions in", values, "beginInstructions");
            return (Criteria) this;
        }

        public Criteria andBeginInstructionsNotIn(List<String> values) {
            addCriterion("begininstructions not in", values, "beginInstructions");
            return (Criteria) this;
        }

        public Criteria andBeginInstructionsBetween(String value1, String value2) {
            addCriterion("begininstructions between", value1, value2, "beginInstructions");
            return (Criteria) this;
        }

        public Criteria andBeginInstructionsNotBetween(String value1, String value2) {
            addCriterion("begininstructions not between", value1, value2, "beginInstructions");
            return (Criteria) this;
        }

        public Criteria andEndInstructionsIsNull() {
            addCriterion("endinstructions is null");
            return (Criteria) this;
        }

        public Criteria andEndInstructionsIsNotNull() {
            addCriterion("endinstructions is not null");
            return (Criteria) this;
        }

        public Criteria andEndInstructionsEqualTo(String value) {
            addCriterion("endinstructions =", value, "endInstructions");
            return (Criteria) this;
        }

        public Criteria andEndInstructionsNotEqualTo(String value) {
            addCriterion("endinstructions <>", value, "endInstructions");
            return (Criteria) this;
        }

        public Criteria andEndInstructionsGreaterThan(String value) {
            addCriterion("endinstructions >", value, "endInstructions");
            return (Criteria) this;
        }

        public Criteria andEndInstructionsGreaterThanOrEqualTo(String value) {
            addCriterion("endinstructions >=", value, "endInstructions");
            return (Criteria) this;
        }

        public Criteria andEndInstructionsLessThan(String value) {
            addCriterion("endinstructions <", value, "endInstructions");
            return (Criteria) this;
        }

        public Criteria andEndInstructionsLessThanOrEqualTo(String value) {
            addCriterion("endinstructions <=", value, "endInstructions");
            return (Criteria) this;
        }

        public Criteria andEndInstructionsLike(String value) {
            addCriterion("endinstructions like", value, "endInstructions");
            return (Criteria) this;
        }

        public Criteria andEndInstructionsNotLike(String value) {
            addCriterion("endinstructions not like", value, "endInstructions");
            return (Criteria) this;
        }

        public Criteria andEndInstructionsIn(List<String> values) {
            addCriterion("endinstructions in", values, "endInstructions");
            return (Criteria) this;
        }

        public Criteria andEndInstructionsNotIn(List<String> values) {
            addCriterion("endinstructions not in", values, "endInstructions");
            return (Criteria) this;
        }

        public Criteria andEndInstructionsBetween(String value1, String value2) {
            addCriterion("endinstructions between", value1, value2, "endInstructions");
            return (Criteria) this;
        }

        public Criteria andEndInstructionsNotBetween(String value1, String value2) {
            addCriterion("endinstructions not between", value1, value2, "endInstructions");
            return (Criteria) this;
        }

        public Criteria andContextStimulusIdIsNull() {
            addCriterion("contextstimulusid is null");
            return (Criteria) this;
        }

        public Criteria andContextStimulusIdIsNotNull() {
            addCriterion("contextstimulusid is not null");
            return (Criteria) this;
        }

        public Criteria andContextStimulusIdEqualTo(Long value) {
            addCriterion("contextstimulusid =", value, "contextStimulusId");
            return (Criteria) this;
        }

        public Criteria andContextStimulusIdNotEqualTo(Long value) {
            addCriterion("contextstimulusid <>", value, "contextStimulusId");
            return (Criteria) this;
        }

        public Criteria andContextStimulusIdGreaterThan(Long value) {
            addCriterion("contextstimulusid >", value, "contextStimulusId");
            return (Criteria) this;
        }

        public Criteria andContextStimulusIdGreaterThanOrEqualTo(Long value) {
            addCriterion("contextstimulusid >=", value, "contextStimulusId");
            return (Criteria) this;
        }

        public Criteria andContextStimulusIdLessThan(Long value) {
            addCriterion("contextstimulusid <", value, "contextStimulusId");
            return (Criteria) this;
        }

        public Criteria andContextStimulusIdLessThanOrEqualTo(Long value) {
            addCriterion("contextstimulusid <=", value, "contextStimulusId");
            return (Criteria) this;
        }

        public Criteria andContextStimulusIdIn(List<Long> values) {
            addCriterion("contextstimulusid in", values, "contextStimulusId");
            return (Criteria) this;
        }

        public Criteria andContextStimulusIdNotIn(List<Long> values) {
            addCriterion("contextstimulusid not in", values, "contextStimulusId");
            return (Criteria) this;
        }

        public Criteria andContextStimulusIdBetween(Long value1, Long value2) {
            addCriterion("contextstimulusid between", value1, value2, "contextStimulusId");
            return (Criteria) this;
        }

        public Criteria andContextStimulusIdNotBetween(Long value1, Long value2) {
            addCriterion("contextstimulusid not between", value1, value2, "contextStimulusId");
            return (Criteria) this;
        }

        public Criteria andTicketedIsNull() {
            addCriterion("ticketed is null");
            return (Criteria) this;
        }

        public Criteria andTicketedIsNotNull() {
            addCriterion("ticketed is not null");
            return (Criteria) this;
        }

        public Criteria andTicketedEqualTo(Boolean value) {
            addCriterion("ticketed =", value, "ticketed");
            return (Criteria) this;
        }

        public Criteria andTicketedNotEqualTo(Boolean value) {
            addCriterion("ticketed <>", value, "ticketed");
            return (Criteria) this;
        }

        public Criteria andTicketedGreaterThan(Boolean value) {
            addCriterion("ticketed >", value, "ticketed");
            return (Criteria) this;
        }

        public Criteria andTicketedGreaterThanOrEqualTo(Boolean value) {
            addCriterion("ticketed >=", value, "ticketed");
            return (Criteria) this;
        }

        public Criteria andTicketedLessThan(Boolean value) {
            addCriterion("ticketed <", value, "ticketed");
            return (Criteria) this;
        }

        public Criteria andTicketedLessThanOrEqualTo(Boolean value) {
            addCriterion("ticketed <=", value, "ticketed");
            return (Criteria) this;
        }

        public Criteria andTicketedIn(List<Boolean> values) {
            addCriterion("ticketed in", values, "ticketed");
            return (Criteria) this;
        }

        public Criteria andTicketedNotIn(List<Boolean> values) {
            addCriterion("ticketed not in", values, "ticketed");
            return (Criteria) this;
        }

        public Criteria andTicketedBetween(Boolean value1, Boolean value2) {
            addCriterion("ticketed between", value1, value2, "ticketed");
            return (Criteria) this;
        }

        public Criteria andTicketedNotBetween(Boolean value1, Boolean value2) {
            addCriterion("ticketed not between", value1, value2, "ticketed");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.testsection
     *
     * @mbggenerated do_not_delete_during_merge Wed Dec 12 21:51:26 CST 2012
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }

        public Criteria andTestSectionNameLikeInsensitive(String value) {
            addCriterion("upper(testsectionname) like", value.toUpperCase(), "testSectionName");
            return this;
        }

        public Criteria andHelpNotesLikeInsensitive(String value) {
            addCriterion("upper(helpnotes) like", value.toUpperCase(), "helpNotes");
            return this;
        }

        public Criteria andOriginationCodeLikeInsensitive(String value) {
            addCriterion("upper(originationcode) like", value.toUpperCase(), "originationCode");
            return this;
        }

        public Criteria andBeginInstructionsLikeInsensitive(String value) {
            addCriterion("upper(begininstructions) like", value.toUpperCase(), "beginInstructions");
            return this;
        }

        public Criteria andEndInstructionsLikeInsensitive(String value) {
            addCriterion("upper(endinstructions) like", value.toUpperCase(), "endInstructions");
            return this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.testsection
     *
     * @mbggenerated Wed Dec 12 21:51:26 CST 2012
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}