package edu.ku.cete.model.security;

import edu.ku.cete.domain.security.RestrictionsOrganizations;
import edu.ku.cete.domain.security.RestrictionsOrganizationsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RestrictionsOrganizationsDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.restrictions_organizations
     *
     * @mbggenerated Tue Sep 04 20:59:29 CDT 2012
     */
    int countByExample(RestrictionsOrganizationsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.restrictions_organizations
     *
     * @mbggenerated Tue Sep 04 20:59:29 CDT 2012
     */
    int deleteByExample(RestrictionsOrganizationsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.restrictions_organizations
     *
     * @mbggenerated Tue Sep 04 20:59:29 CDT 2012
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.restrictions_organizations
     *
     * @mbggenerated Tue Sep 04 20:59:29 CDT 2012
     */
    int insert(RestrictionsOrganizations record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.restrictions_organizations
     *
     * @mbggenerated Tue Sep 04 20:59:29 CDT 2012
     */
    int insertSelective(RestrictionsOrganizations record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.restrictions_organizations
     *
     * @mbggenerated Tue Sep 04 20:59:29 CDT 2012
     */
    List<RestrictionsOrganizations> selectByExample(RestrictionsOrganizationsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.restrictions_organizations
     *
     * @mbggenerated Tue Sep 04 20:59:29 CDT 2012
     */
    RestrictionsOrganizations selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.restrictions_organizations
     *
     * @mbggenerated Tue Sep 04 20:59:29 CDT 2012
     */
    int updateByExampleSelective(@Param("record") RestrictionsOrganizations record, @Param("example") RestrictionsOrganizationsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.restrictions_organizations
     *
     * @mbggenerated Tue Sep 04 20:59:29 CDT 2012
     */
    int updateByExample(@Param("record") RestrictionsOrganizations record, @Param("example") RestrictionsOrganizationsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.restrictions_organizations
     *
     * @mbggenerated Tue Sep 04 20:59:29 CDT 2012
     */
    int updateByPrimaryKeySelective(RestrictionsOrganizations record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.restrictions_organizations
     *
     * @mbggenerated Tue Sep 04 20:59:29 CDT 2012
     */
    int updateByPrimaryKey(RestrictionsOrganizations record);
}