package edu.ku.cete.model.student.survey;

import edu.ku.cete.domain.student.survey.SurveySection;
import edu.ku.cete.domain.student.survey.SurveySectionComposite;
import edu.ku.cete.domain.student.survey.SurveySectionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SurveySectionDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.survey_section
     *
     * @mbggenerated Fri May 31 14:41:26 CDT 2013
     */
    int countByExample(SurveySectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.survey_section
     *
     * @mbggenerated Fri May 31 14:41:26 CDT 2013
     */
    int deleteByExample(SurveySectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.survey_section
     *
     * @mbggenerated Fri May 31 14:41:26 CDT 2013
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.survey_section
     *
     * @mbggenerated Fri May 31 14:41:26 CDT 2013
     */
    int insert(SurveySection record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.survey_section
     *
     * @mbggenerated Fri May 31 14:41:26 CDT 2013
     */
    int insertSelective(SurveySection record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.survey_section
     *
     * @mbggenerated Fri May 31 14:41:26 CDT 2013
     */
    List<SurveySection> selectByExample(SurveySectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.survey_section
     *
     * @mbggenerated Fri May 31 14:41:26 CDT 2013
     */
    SurveySection selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.survey_section
     *
     * @mbggenerated Fri May 31 14:41:26 CDT 2013
     */
    int updateByExampleSelective(@Param("record") SurveySection record, @Param("example") SurveySectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.survey_section
     *
     * @mbggenerated Fri May 31 14:41:26 CDT 2013
     */
    int updateByExample(@Param("record") SurveySection record, @Param("example") SurveySectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.survey_section
     *
     * @mbggenerated Fri May 31 14:41:26 CDT 2013
     */
    int updateByPrimaryKeySelective(SurveySection record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.survey_section
     *
     * @mbggenerated Fri May 31 14:41:26 CDT 2013
     */
    int updateByPrimaryKey(SurveySection record);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.survey_section
     *
     * @mbggenerated Fri May 31 14:41:26 CDT 2013
     */
    List<SurveySectionComposite> selectCompositeByExample(SurveySectionExample example);

	List<SurveySection> getSurveyRootSections();

	List<SurveySection> getSurveySubSections();

	List<Integer> getActiveRootSections(Long surveyId);

	int getFirstContactActivePageCount();
}