insert into operationaltestwindowstudent (studentid, contentareaid, courseid, exclude, activeflag, operationaltestwindowid, createddate) values ((select id from student where statestudentidentifier = '55507071'), (select id from contentarea where abbreviatedname ='M'), (select id from gradecourse where contentareaid = (select id from contentarea where abbreviatedname ='M') and abbreviatedname = ''),FALSE,true,10136,now());

insert into operationaltestwindowstudent (studentid, contentareaid, courseid, exclude, activeflag, operationaltestwindowid, createddate) values ((select id from student where statestudentidentifier = '55507071'), (select id from contentarea where abbreviatedname ='Sci'), (select id from gradecourse where contentareaid = (select id from contentarea where abbreviatedname ='Sci') and abbreviatedname = ''),FALSE,true,10136,now());

insert into operationaltestwindowstudent (studentid, contentareaid, courseid, exclude, activeflag, operationaltestwindowid, createddate) values ((select id from student where statestudentidentifier = '55507029'), (select id from contentarea where abbreviatedname ='Sci'), (select id from gradecourse where contentareaid = (select id from contentarea where abbreviatedname ='Sci') and abbreviatedname = ''),FALSE,true,10140,now());


-- Include

insert into operationaltestwindowstudent (studentid, contentareaid, courseid, exclude, activeflag, operationaltestwindowid, createddate) values ((select id from student where statestudentidentifier = '55507151'), (select id from contentarea where abbreviatedname ='Sci'), (select id from gradecourse where contentareaid = (select id from contentarea where abbreviatedname ='Sci') and abbreviatedname = 'BIO'),FALSE,true,10141,now());
insert into operationaltestwindowstudent (studentid, contentareaid, courseid, exclude, activeflag, operationaltestwindowid, createddate) values ((select id from student where statestudentidentifier = '55507152'), (select id from contentarea where abbreviatedname ='Sci'), (select id from gradecourse where contentareaid = (select id from contentarea where abbreviatedname ='Sci') and abbreviatedname = 'BIO'),FALSE,true,10141,now());
insert into operationaltestwindowstudent (studentid, contentareaid, courseid, exclude, activeflag, operationaltestwindowid, createddate) values ((select id from student where statestudentidentifier = '55507153'), (select id from contentarea where abbreviatedname ='Sci'), (select id from gradecourse where contentareaid = (select id from contentarea where abbreviatedname ='Sci') and abbreviatedname = 'BIO'),FALSE,true,10141,now());
insert into operationaltestwindowstudent (studentid, contentareaid, courseid, exclude, activeflag, operationaltestwindowid, createddate) values ((select id from student where statestudentidentifier = '55507154'), (select id from contentarea where abbreviatedname ='Sci'), (select id from gradecourse where contentareaid = (select id from contentarea where abbreviatedname ='Sci') and abbreviatedname = 'BIO'),FALSE,true,10141,now());
insert into operationaltestwindowstudent (studentid, contentareaid, courseid, exclude, activeflag, operationaltestwindowid, createddate) values ((select id from student where statestudentidentifier = '55507155'), (select id from contentarea where abbreviatedname ='Sci'), (select id from gradecourse where contentareaid = (select id from contentarea where abbreviatedname ='Sci') and abbreviatedname = 'BIO'),FALSE,true,10141,now());
insert into operationaltestwindowstudent (studentid, contentareaid, courseid, exclude, activeflag, operationaltestwindowid, createddate) values ((select id from student where statestudentidentifier = '55507157'), (select id from contentarea where abbreviatedname ='Sci'), (select id from gradecourse where contentareaid = (select id from contentarea where abbreviatedname ='Sci') and abbreviatedname = 'BIO'),FALSE,true,10141,now());
insert into operationaltestwindowstudent (studentid, contentareaid, courseid, exclude, activeflag, operationaltestwindowid, createddate) values ((select id from student where statestudentidentifier = '55507158'), (select id from contentarea where abbreviatedname ='Sci'), (select id from gradecourse where contentareaid = (select id from contentarea where abbreviatedname ='Sci') and abbreviatedname = 'BIO'),FALSE,true,10141,now());
insert into operationaltestwindowstudent (studentid, contentareaid, courseid, exclude, activeflag, operationaltestwindowid, createddate) values ((select id from student where statestudentidentifier = '55507159'), (select id from contentarea where abbreviatedname ='Sci'), (select id from gradecourse where contentareaid = (select id from contentarea where abbreviatedname ='Sci') and abbreviatedname = 'BIO'),FALSE,true,10141,now());
insert into operationaltestwindowstudent (studentid, contentareaid, courseid, exclude, activeflag, operationaltestwindowid, createddate) values ((select id from student where statestudentidentifier = '55507160'), (select id from contentarea where abbreviatedname ='Sci'), (select id from gradecourse where contentareaid = (select id from contentarea where abbreviatedname ='Sci') and abbreviatedname = 'BIO'),FALSE,true,10141,now());
insert into operationaltestwindowstudent (studentid, contentareaid, courseid, exclude, activeflag, operationaltestwindowid, createddate) values ((select id from student where statestudentidentifier = '55507161'), (select id from contentarea where abbreviatedname ='Sci'), (select id from gradecourse where contentareaid = (select id from contentarea where abbreviatedname ='Sci') and abbreviatedname = 'BIO'),FALSE,true,10141,now());
insert into operationaltestwindowstudent (studentid, contentareaid, courseid, exclude, activeflag, operationaltestwindowid, createddate) values ((select id from student where statestudentidentifier = '55507163'), (select id from contentarea where abbreviatedname ='Sci'), (select id from gradecourse where contentareaid = (select id from contentarea where abbreviatedname ='Sci') and abbreviatedname = 'BIO'),FALSE,true,10141,now());
insert into operationaltestwindowstudent (studentid, contentareaid, courseid, exclude, activeflag, operationaltestwindowid, createddate) values ((select id from student where statestudentidentifier = '55507164'), (select id from contentarea where abbreviatedname ='Sci'), (select id from gradecourse where contentareaid = (select id from contentarea where abbreviatedname ='Sci') and abbreviatedname = 'BIO'),FALSE,true,10141,now());
