--US17713 : PROD - Request to have student enrollments corrected that cannot be corrected with KSDE uploads

update enrollment set activeflag = true, exitwithdrawaldate = null, exitwithdrawaltype = null, modifieddate = now(), modifieduser = (select id from aartuser where username = 'cetesysadmin'), notes = 'Activated enrollment as per US17713' where id = ( select e.id   from enrollment e inner join student s on e.studentid = s.id inner join organization o on e.attendanceschoolid = o.id where o.id in (select id from organization_children((select id from organization where displayidentifier = 'KS')))  and s.stateid = (select id from organization where displayidentifier = 'KS') and o.displayidentifier = '1833' and s.statestudentidentifier = '4781643191' ) and activeflag is false; 

update enrollment set activeflag = true, exitwithdrawaldate = null, exitwithdrawaltype = null, modifieddate = now(), modifieduser = (select id from aartuser where username = 'cetesysadmin'), notes = 'Activated enrollment as per US17713' where id = ( select e.id   from enrollment e inner join student s on e.studentid = s.id inner join organization o on e.attendanceschoolid = o.id where o.id in (select id from organization_children((select id from organization where displayidentifier = 'KS')))  and s.stateid = (select id from organization where displayidentifier = 'KS') and o.displayidentifier = '6518' and s.statestudentidentifier = '8539765365' ) and activeflag is false; 

update enrollment set activeflag = true, exitwithdrawaldate = null, exitwithdrawaltype = null, modifieddate = now(), modifieduser = (select id from aartuser where username = 'cetesysadmin'), notes = 'Activated enrollment as per US17713' where id = ( select e.id   from enrollment e inner join student s on e.studentid = s.id inner join organization o on e.attendanceschoolid = o.id where o.id in (select id from organization_children((select id from organization where displayidentifier = 'KS')))  and s.stateid = (select id from organization where displayidentifier = 'KS') and o.displayidentifier = '1756' and s.statestudentidentifier = '7091179544' ) and activeflag is false; 

update enrollment set activeflag = true, exitwithdrawaldate = null, exitwithdrawaltype = null, modifieddate = now(), modifieduser = (select id from aartuser where username = 'cetesysadmin'), notes = 'Activated enrollment as per US17713' where id = ( select e.id   from enrollment e inner join student s on e.studentid = s.id inner join organization o on e.attendanceschoolid = o.id where o.id in (select id from organization_children((select id from organization where displayidentifier = 'KS')))  and s.stateid = (select id from organization where displayidentifier = 'KS') and o.displayidentifier = '6527' and s.statestudentidentifier = '7679902631' ) and activeflag is false; 

update enrollment set activeflag = true, exitwithdrawaldate = null, exitwithdrawaltype = null, modifieddate = now(), modifieduser = (select id from aartuser where username = 'cetesysadmin'), notes = 'Activated enrollment as per US17713' where id = ( select e.id   from enrollment e inner join student s on e.studentid = s.id inner join organization o on e.attendanceschoolid = o.id where o.id in (select id from organization_children((select id from organization where displayidentifier = 'KS')))  and s.stateid = (select id from organization where displayidentifier = 'KS') and o.displayidentifier = '6532' and s.statestudentidentifier = '3328796916' ) and activeflag is false; 

update enrollment set activeflag = true, exitwithdrawaldate = null, exitwithdrawaltype = null, modifieddate = now(), modifieduser = (select id from aartuser where username = 'cetesysadmin'), notes = 'Activated enrollment as per US17713' where id = ( select e.id   from enrollment e inner join student s on e.studentid = s.id inner join organization o on e.attendanceschoolid = o.id where o.id in (select id from organization_children((select id from organization where displayidentifier = 'KS')))  and s.stateid = (select id from organization where displayidentifier = 'KS') and o.displayidentifier = '6532' and s.statestudentidentifier = '7505920235' ) and activeflag is false; 

update enrollment set activeflag = true, exitwithdrawaldate = null, exitwithdrawaltype = null, modifieddate = now(), modifieduser = (select id from aartuser where username = 'cetesysadmin'), notes = 'Activated enrollment as per US17713' where id = ( select e.id   from enrollment e inner join student s on e.studentid = s.id inner join organization o on e.attendanceschoolid = o.id where o.id in (select id from organization_children((select id from organization where displayidentifier = 'KS')))  and s.stateid = (select id from organization where displayidentifier = 'KS') and o.displayidentifier = '6532' and s.statestudentidentifier = '9490083852' ) and activeflag is false; 

update enrollment set activeflag = true, exitwithdrawaldate = null, exitwithdrawaltype = null, modifieddate = now(), modifieduser = (select id from aartuser where username = 'cetesysadmin'), notes = 'Activated enrollment as per US17713' where id = ( select e.id   from enrollment e inner join student s on e.studentid = s.id inner join organization o on e.attendanceschoolid = o.id where o.id in (select id from organization_children((select id from organization where displayidentifier = 'KS')))  and s.stateid = (select id from organization where displayidentifier = 'KS') and o.displayidentifier = '6532' and s.statestudentidentifier = '3265611639' ) and activeflag is false;
 
update enrollment set activeflag = true, exitwithdrawaldate = null, exitwithdrawaltype = null, modifieddate = now(), modifieduser = (select id from aartuser where username = 'cetesysadmin'), notes = 'Activated enrollment as per US17713' where id = ( select e.id   from enrollment e inner join student s on e.studentid = s.id inner join organization o on e.attendanceschoolid = o.id where o.id in (select id from organization_children((select id from organization where displayidentifier = 'KS')))  and s.stateid = (select id from organization where displayidentifier = 'KS') and o.displayidentifier = '5636' and s.statestudentidentifier = '2728586012' ) and activeflag is false; 

update enrollment set activeflag = true, exitwithdrawaldate = null, exitwithdrawaltype = null, modifieddate = now(), modifieduser = (select id from aartuser where username = 'cetesysadmin'), notes = 'Activated enrollment as per US17713' where id = ( select e.id   from enrollment e inner join student s on e.studentid = s.id inner join organization o on e.attendanceschoolid = o.id where o.id in (select id from organization_children((select id from organization where displayidentifier = 'KS')))  and s.stateid = (select id from organization where displayidentifier = 'KS') and o.displayidentifier = '1198' and s.statestudentidentifier = '1570912904' ) and activeflag is false;

update enrollment set activeflag = true, exitwithdrawaldate = null, exitwithdrawaltype = null, modifieddate = now(), modifieduser = (select id from aartuser where username = 'cetesysadmin'), notes = 'Activated enrollment as per US17713' where id = ( select e.id   from enrollment e inner join student s on e.studentid = s.id inner join organization o on e.attendanceschoolid = o.id where o.id in (select id from organization_children((select id from organization where displayidentifier = 'KS')))  and s.stateid = (select id from organization where displayidentifier = 'KS') and o.displayidentifier = '2262' and s.statestudentidentifier = '8517699475' ) and activeflag is false; 

update enrollment set activeflag = true, exitwithdrawaldate = null, exitwithdrawaltype = null, modifieddate = now(), modifieduser = (select id from aartuser where username = 'cetesysadmin'), notes = 'Activated enrollment as per US17713' where id = ( select e.id   from enrollment e inner join student s on e.studentid = s.id inner join organization o on e.attendanceschoolid = o.id where o.id in (select id from organization_children((select id from organization where displayidentifier = 'KS')))  and s.stateid = (select id from organization where displayidentifier = 'KS') and o.displayidentifier = '3025' and s.statestudentidentifier = '1467268186' ) and activeflag is false; 

update enrollment set activeflag = true, exitwithdrawaldate = null, exitwithdrawaltype = null, modifieddate = now(), modifieduser = (select id from aartuser where username = 'cetesysadmin'), notes = 'Activated enrollment as per US17713' where id = ( select e.id   from enrollment e inner join student s on e.studentid = s.id inner join organization o on e.attendanceschoolid = o.id where o.id in (select id from organization_children((select id from organization where displayidentifier = 'KS')))  and s.stateid = (select id from organization where displayidentifier = 'KS') and o.displayidentifier = '3018' and s.statestudentidentifier = '3590583738' ) and activeflag is false; 

update enrollment set activeflag = true, exitwithdrawaldate = null, exitwithdrawaltype = null, modifieddate = now(), modifieduser = (select id from aartuser where username = 'cetesysadmin'), notes = 'Activated enrollment as per US17713' where id = ( select e.id   from enrollment e inner join student s on e.studentid = s.id inner join organization o on e.attendanceschoolid = o.id where o.id in (select id from organization_children((select id from organization where displayidentifier = 'KS')))  and s.stateid = (select id from organization where displayidentifier = 'KS') and o.displayidentifier = '3022' and s.statestudentidentifier = '9208702804' ) and activeflag is false; 

update enrollment set activeflag = true, exitwithdrawaldate = null, exitwithdrawaltype = null, modifieddate = now(), modifieduser = (select id from aartuser where username = 'cetesysadmin'), notes = 'Activated enrollment as per US17713' where id = ( select e.id   from enrollment e inner join student s on e.studentid = s.id inner join organization o on e.attendanceschoolid = o.id where o.id in (select id from organization_children((select id from organization where displayidentifier = 'KS')))  and s.stateid = (select id from organization where displayidentifier = 'KS') and o.displayidentifier = '3222' and s.statestudentidentifier = '1004366302' ) and activeflag is false; 

update enrollment set activeflag = true, exitwithdrawaldate = null, exitwithdrawaltype = null, modifieddate = now(), modifieduser = (select id from aartuser where username = 'cetesysadmin'), notes = 'Activated enrollment as per US17713' where id = ( select e.id   from enrollment e inner join student s on e.studentid = s.id inner join organization o on e.attendanceschoolid = o.id where o.id in (select id from organization_children((select id from organization where displayidentifier = 'KS')))  and s.stateid = (select id from organization where displayidentifier = 'KS') and o.displayidentifier = '7143' and s.statestudentidentifier = '2729489231' ) and activeflag is false; 

update enrollment set activeflag = true, exitwithdrawaldate = null, exitwithdrawaltype = null, modifieddate = now(), modifieduser = (select id from aartuser where username = 'cetesysadmin'), notes = 'Activated enrollment as per US17713' where id = ( select e.id   from enrollment e inner join student s on e.studentid = s.id inner join organization o on e.attendanceschoolid = o.id where o.id in (select id from organization_children((select id from organization where displayidentifier = 'KS')))  and s.stateid = (select id from organization where displayidentifier = 'KS') and o.displayidentifier = '3022' and s.statestudentidentifier = '9098665292' ) and activeflag is false; 

update enrollment set activeflag = true, exitwithdrawaldate = null, exitwithdrawaltype = null, modifieddate = now(), modifieduser = (select id from aartuser where username = 'cetesysadmin'), notes = 'Activated enrollment as per US17713' where id = ( select e.id   from enrollment e inner join student s on e.studentid = s.id inner join organization o on e.attendanceschoolid = o.id where o.id in (select id from organization_children((select id from organization where displayidentifier = 'KS')))  and s.stateid = (select id from organization where displayidentifier = 'KS') and o.displayidentifier = '3022' and s.statestudentidentifier = '2474147535' ) and activeflag is false; 

update enrollment set activeflag = true, exitwithdrawaldate = null, exitwithdrawaltype = null, modifieddate = now(), modifieduser = (select id from aartuser where username = 'cetesysadmin'), notes = 'Activated enrollment as per US17713' where id = ( select e.id   from enrollment e inner join student s on e.studentid = s.id inner join organization o on e.attendanceschoolid = o.id where o.id in (select id from organization_children((select id from organization where displayidentifier = 'KS')))  and s.stateid = (select id from organization where displayidentifier = 'KS') and o.displayidentifier = '3022' and s.statestudentidentifier = '4598547006' ) and activeflag is false; 

update enrollment set activeflag = true, exitwithdrawaldate = null, exitwithdrawaltype = null, modifieddate = now(), modifieduser = (select id from aartuser where username = 'cetesysadmin'), notes = 'Activated enrollment as per US17713' where id = ( select e.id   from enrollment e inner join student s on e.studentid = s.id inner join organization o on e.attendanceschoolid = o.id where o.id in (select id from organization_children((select id from organization where displayidentifier = 'KS')))  and s.stateid = (select id from organization where displayidentifier = 'KS') and o.displayidentifier = '7773' and s.statestudentidentifier = '8553664228' ) and activeflag is false; 

update enrollment set activeflag = true, exitwithdrawaldate = null, exitwithdrawaltype = null, modifieddate = now(), modifieduser = (select id from aartuser where username = 'cetesysadmin'), notes = 'Activated enrollment as per US17713' where id = ( select e.id   from enrollment e inner join student s on e.studentid = s.id inner join organization o on e.attendanceschoolid = o.id where o.id in (select id from organization_children((select id from organization where displayidentifier = 'KS')))  and s.stateid = (select id from organization where displayidentifier = 'KS') and o.displayidentifier = '7774' and s.statestudentidentifier = '6328334745' ) and activeflag is false; 

update enrollment set activeflag = true, exitwithdrawaldate = null, exitwithdrawaltype = null, modifieddate = now(), modifieduser = (select id from aartuser where username = 'cetesysadmin'), notes = 'Activated enrollment as per US17713' where id = ( select e.id   from enrollment e inner join student s on e.studentid = s.id inner join organization o on e.attendanceschoolid = o.id where o.id in (select id from organization_children((select id from organization where displayidentifier = 'KS')))  and s.stateid = (select id from organization where displayidentifier = 'KS') and o.displayidentifier = '7774' and s.statestudentidentifier = '9199254611' ) and activeflag is false; 

update enrollment set activeflag = true, exitwithdrawaldate = null, exitwithdrawaltype = null, modifieddate = now(), modifieduser = (select id from aartuser where username = 'cetesysadmin'), notes = 'Activated enrollment as per US17713' where id = ( select e.id   from enrollment e inner join student s on e.studentid = s.id inner join organization o on e.attendanceschoolid = o.id where o.id in (select id from organization_children((select id from organization where displayidentifier = 'KS')))  and s.stateid = (select id from organization where displayidentifier = 'KS') and o.displayidentifier = '7789' and s.statestudentidentifier = '9859271038' ) and activeflag is false; 
