--US17702 : PROD - Request to have student enrollments corrected that cannot be corrected with KSDE uploads


update enrollment set activeflag = true, exitwithdrawaldate = null, exitwithdrawaltype = null, modifieddate = now(), modifieduser = (select id from aartuser where username = 'cetesysadmin'), notes = 'Activated enrollment as per US17702' where id = ( select e.id   from enrollment e inner join student s on e.studentid = s.id inner join organization o on e.attendanceschoolid = o.id where o.id in (select id from organization_children((select id from organization where displayidentifier = 'KS')))  and s.stateid = (select id from organization where displayidentifier = 'KS') and o.displayidentifier = '0770' and s.statestudentidentifier = '4417110581' ); 

update enrollment set activeflag = true, exitwithdrawaldate = null, exitwithdrawaltype = null, modifieddate = now(), modifieduser = (select id from aartuser where username = 'cetesysadmin'), notes = 'Activated enrollment as per US17702' where id = ( select e.id   from enrollment e inner join student s on e.studentid = s.id inner join organization o on e.attendanceschoolid = o.id where o.id in (select id from organization_children((select id from organization where displayidentifier = 'KS')))  and s.stateid = (select id from organization where displayidentifier = 'KS') and o.displayidentifier = '0779' and s.statestudentidentifier = '5656779467' ); 

update enrollment set activeflag = true, exitwithdrawaldate = null, exitwithdrawaltype = null, modifieddate = now(), modifieduser = (select id from aartuser where username = 'cetesysadmin'), notes = 'Activated enrollment as per US17702' where id = ( select e.id   from enrollment e inner join student s on e.studentid = s.id inner join organization o on e.attendanceschoolid = o.id where o.id in (select id from organization_children((select id from organization where displayidentifier = 'KS')))  and s.stateid = (select id from organization where displayidentifier = 'KS') and o.displayidentifier = '0167' and s.statestudentidentifier = '9396955477' ); 

update enrollment set activeflag = true, exitwithdrawaldate = null, exitwithdrawaltype = null, modifieddate = now(), modifieduser = (select id from aartuser where username = 'cetesysadmin'), notes = 'Activated enrollment as per US17702' where id = ( select e.id   from enrollment e inner join student s on e.studentid = s.id inner join organization o on e.attendanceschoolid = o.id where o.id in (select id from organization_children((select id from organization where displayidentifier = 'KS')))  and s.stateid = (select id from organization where displayidentifier = 'KS') and o.displayidentifier = '4821' and s.statestudentidentifier = '2662150793' ); 

update enrollment set activeflag = true, exitwithdrawaldate = null, exitwithdrawaltype = null, modifieddate = now(), modifieduser = (select id from aartuser where username = 'cetesysadmin'), notes = 'Activated enrollment as per US17702' where id = ( select e.id   from enrollment e inner join student s on e.studentid = s.id inner join organization o on e.attendanceschoolid = o.id where o.id in (select id from organization_children((select id from organization where displayidentifier = 'KS')))  and s.stateid = (select id from organization where displayidentifier = 'KS') and o.displayidentifier = '7128' and s.statestudentidentifier = '1524908088' ); 

update enrollment set activeflag = true, exitwithdrawaldate = null, exitwithdrawaltype = null, modifieddate = now(), modifieduser = (select id from aartuser where username = 'cetesysadmin'), notes = 'Activated enrollment as per US17702' where id = ( select e.id   from enrollment e inner join student s on e.studentid = s.id inner join organization o on e.attendanceschoolid = o.id where o.id in (select id from organization_children((select id from organization where displayidentifier = 'KS')))  and s.stateid = (select id from organization where displayidentifier = 'KS') and o.displayidentifier = '4094' and s.statestudentidentifier = '2031898256' ); 

update enrollment set activeflag = true, exitwithdrawaldate = null, exitwithdrawaltype = null, modifieddate = now(), modifieduser = (select id from aartuser where username = 'cetesysadmin'), notes = 'Activated enrollment as per US17702' where id = ( select e.id   from enrollment e inner join student s on e.studentid = s.id inner join organization o on e.attendanceschoolid = o.id where o.id in (select id from organization_children((select id from organization where displayidentifier = 'KS')))  and s.stateid = (select id from organization where displayidentifier = 'KS') and o.displayidentifier = '4029' and s.statestudentidentifier = '5822121225' ); 

update enrollment set activeflag = true, exitwithdrawaldate = null, exitwithdrawaltype = null, modifieddate = now(), modifieduser = (select id from aartuser where username = 'cetesysadmin'), notes = 'Activated enrollment as per US17702' where id = ( select e.id   from enrollment e inner join student s on e.studentid = s.id inner join organization o on e.attendanceschoolid = o.id where o.id in (select id from organization_children((select id from organization where displayidentifier = 'KS')))  and s.stateid = (select id from organization where displayidentifier = 'KS') and o.displayidentifier = '1977' and s.statestudentidentifier = '7541372064' );
 
update enrollment set activeflag = true, exitwithdrawaldate = null, exitwithdrawaltype = null, modifieddate = now(), modifieduser = (select id from aartuser where username = 'cetesysadmin'), notes = 'Activated enrollment as per US17702' where id = ( select e.id   from enrollment e inner join student s on e.studentid = s.id inner join organization o on e.attendanceschoolid = o.id where o.id in (select id from organization_children((select id from organization where displayidentifier = 'KS')))  and s.stateid = (select id from organization where displayidentifier = 'KS') and o.displayidentifier = '6475' and s.statestudentidentifier = '6250781226' ); 

update enrollment set activeflag = true, exitwithdrawaldate = null, exitwithdrawaltype = null, modifieddate = now(), modifieduser = (select id from aartuser where username = 'cetesysadmin'), notes = 'Activated enrollment as per US17702' where id = ( select e.id   from enrollment e inner join student s on e.studentid = s.id inner join organization o on e.attendanceschoolid = o.id where o.id in (select id from organization_children((select id from organization where displayidentifier = 'KS')))  and s.stateid = (select id from organization where displayidentifier = 'KS') and o.displayidentifier = '5032' and s.statestudentidentifier = '7094427492' ); 