--US17678 : PROD - Request to have student enrollments corrected that cannot be corrected with KSDE uploads


update enrollment set activeflag = true, exitwithdrawaldate = null, exitwithdrawaltype = null, modifieddate = now(), modifieduser = (select id from aartuser where username = 'cetesysadmin'), notes = 'Activated enrollment as per US17678' where id = ( select e.id   from enrollment e inner join student s on e.studentid = s.id inner join organization o on e.attendanceschoolid = o.id where o.id in (select id from organization_children((select id from organization where displayidentifier = 'KS')))  and s.stateid = (select id from organization where displayidentifier = 'KS') and o.displayidentifier = '0155' and s.statestudentidentifier = '7303168915' ); 

update enrollment set activeflag = true, exitwithdrawaldate = null, exitwithdrawaltype = null, modifieddate = now(), modifieduser = (select id from aartuser where username = 'cetesysadmin'), notes = 'Activated enrollment as per US17678' where id = ( select e.id   from enrollment e inner join student s on e.studentid = s.id inner join organization o on e.attendanceschoolid = o.id where o.id in (select id from organization_children((select id from organization where displayidentifier = 'KS')))  and s.stateid = (select id from organization where displayidentifier = 'KS') and o.displayidentifier = '0157' and s.statestudentidentifier = '2076451641' ); 

update enrollment set activeflag = true, exitwithdrawaldate = null, exitwithdrawaltype = null, modifieddate = now(), modifieduser = (select id from aartuser where username = 'cetesysadmin'), notes = 'Activated enrollment as per US17678' where id = ( select e.id   from enrollment e inner join student s on e.studentid = s.id inner join organization o on e.attendanceschoolid = o.id where o.id in (select id from organization_children((select id from organization where displayidentifier = 'KS')))  and s.stateid = (select id from organization where displayidentifier = 'KS') and o.displayidentifier = '0167' and s.statestudentidentifier = '9396955477' ); 

update enrollment set activeflag = true, exitwithdrawaldate = null, exitwithdrawaltype = null, modifieddate = now(), modifieduser = (select id from aartuser where username = 'cetesysadmin'), notes = 'Activated enrollment as per US17678' where id = ( select e.id   from enrollment e inner join student s on e.studentid = s.id inner join organization o on e.attendanceschoolid = o.id where o.id in (select id from organization_children((select id from organization where displayidentifier = 'KS')))  and s.stateid = (select id from organization where displayidentifier = 'KS') and o.displayidentifier = '0112' and s.statestudentidentifier = '6128076491' ); 

update enrollment set activeflag = true, exitwithdrawaldate = null, exitwithdrawaltype = null, modifieddate = now(), modifieduser = (select id from aartuser where username = 'cetesysadmin'), notes = 'Activated enrollment as per US17678' where id = ( select e.id   from enrollment e inner join student s on e.studentid = s.id inner join organization o on e.attendanceschoolid = o.id where o.id in (select id from organization_children((select id from organization where displayidentifier = 'KS')))  and s.stateid = (select id from organization where displayidentifier = 'KS') and o.displayidentifier = '0112' and s.statestudentidentifier = '6972748305' ); 

update enrollment set activeflag = true, exitwithdrawaldate = null, exitwithdrawaltype = null, modifieddate = now(), modifieduser = (select id from aartuser where username = 'cetesysadmin'), notes = 'Activated enrollment as per US17678' where id = ( select e.id   from enrollment e inner join student s on e.studentid = s.id inner join organization o on e.attendanceschoolid = o.id where o.id in (select id from organization_children((select id from organization where displayidentifier = 'KS')))  and s.stateid = (select id from organization where displayidentifier = 'KS') and o.displayidentifier = '0113' and s.statestudentidentifier = '6946928733' ); 

update enrollment set activeflag = true, exitwithdrawaldate = null, exitwithdrawaltype = null, modifieddate = now(), modifieduser = (select id from aartuser where username = 'cetesysadmin'), notes = 'Activated enrollment as per US17678' where id = ( select e.id   from enrollment e inner join student s on e.studentid = s.id inner join organization o on e.attendanceschoolid = o.id where o.id in (select id from organization_children((select id from organization where displayidentifier = 'KS')))  and s.stateid = (select id from organization where displayidentifier = 'KS') and o.displayidentifier = '0113' and s.statestudentidentifier = '8210608967' ); 

update enrollment set activeflag = true, exitwithdrawaldate = null, exitwithdrawaltype = null, modifieddate = now(), modifieduser = (select id from aartuser where username = 'cetesysadmin'), notes = 'Activated enrollment as per US17678' where id = ( select e.id   from enrollment e inner join student s on e.studentid = s.id inner join organization o on e.attendanceschoolid = o.id where o.id in (select id from organization_children((select id from organization where displayidentifier = 'KS')))  and s.stateid = (select id from organization where displayidentifier = 'KS') and o.displayidentifier = '9013' and s.statestudentidentifier = '6191084013' ); 

update enrollment set activeflag = true, exitwithdrawaldate = null, exitwithdrawaltype = null, modifieddate = now(), modifieduser = (select id from aartuser where username = 'cetesysadmin'), notes = 'Activated enrollment as per US17678' where id = ( select e.id   from enrollment e inner join student s on e.studentid = s.id inner join organization o on e.attendanceschoolid = o.id where o.id in (select id from organization_children((select id from organization where displayidentifier = 'KS')))  and s.stateid = (select id from organization where displayidentifier = 'KS') and o.displayidentifier = '2050' and s.statestudentidentifier = '5182376766' ); 

update enrollment set activeflag = true, exitwithdrawaldate = null, exitwithdrawaltype = null, modifieddate = now(), modifieduser = (select id from aartuser where username = 'cetesysadmin'), notes = 'Activated enrollment as per US17678' where id = ( select e.id   from enrollment e inner join student s on e.studentid = s.id inner join organization o on e.attendanceschoolid = o.id where o.id in (select id from organization_children((select id from organization where displayidentifier = 'KS')))  and s.stateid = (select id from organization where displayidentifier = 'KS') and o.displayidentifier = '7620' and s.statestudentidentifier = '4696414817' ); 

update enrollment set activeflag = true, exitwithdrawaldate = null, exitwithdrawaltype = null, modifieddate = now(), modifieduser = (select id from aartuser where username = 'cetesysadmin'), notes = 'Activated enrollment as per US17678' where id = ( select e.id   from enrollment e inner join student s on e.studentid = s.id inner join organization o on e.attendanceschoolid = o.id where o.id in (select id from organization_children((select id from organization where displayidentifier = 'KS')))  and s.stateid = (select id from organization where displayidentifier = 'KS') and o.displayidentifier = '2276' and s.statestudentidentifier = '2412784981' ); 
