package edu.ku.cete.domain;

public class EssentialElementLinkageTranslationValues {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column essentialelementlinkagetranslationvalues.id
     *
     * @mbggenerated Tue Dec 10 11:23:56 CST 2013
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column essentialelementlinkagetranslationvalues.categoryid
     *
     * @mbggenerated Tue Dec 10 11:23:56 CST 2013
     */
    private Long categoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column essentialelementlinkagetranslationvalues.translationvalue
     *
     * @mbggenerated Tue Dec 10 11:23:56 CST 2013
     */
    private Float translationValue;
    
    private String categoryName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column essentialelementlinkagetranslationvalues.id
     *
     * @return the value of essentialelementlinkagetranslationvalues.id
     *
     * @mbggenerated Tue Dec 10 11:23:56 CST 2013
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column essentialelementlinkagetranslationvalues.id
     *
     * @param id the value for essentialelementlinkagetranslationvalues.id
     *
     * @mbggenerated Tue Dec 10 11:23:56 CST 2013
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column essentialelementlinkagetranslationvalues.categoryid
     *
     * @return the value of essentialelementlinkagetranslationvalues.categoryid
     *
     * @mbggenerated Tue Dec 10 11:23:56 CST 2013
     */
    public Long getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column essentialelementlinkagetranslationvalues.categoryid
     *
     * @param categoryId the value for essentialelementlinkagetranslationvalues.categoryid
     *
     * @mbggenerated Tue Dec 10 11:23:56 CST 2013
     */
    public void setCategoryId(Long categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column essentialelementlinkagetranslationvalues.translationvalue
     *
     * @return the value of essentialelementlinkagetranslationvalues.translationvalue
     *
     * @mbggenerated Tue Dec 10 11:23:56 CST 2013
     */
    public Float getTranslationValue() {
        return translationValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column essentialelementlinkagetranslationvalues.translationvalue
     *
     * @param translationValue the value for essentialelementlinkagetranslationvalues.translationvalue
     *
     * @mbggenerated Tue Dec 10 11:23:56 CST 2013
     */
    public void setTranslationValue(Float translationValue) {
        this.translationValue = translationValue;
    }

	/**
	 * @return the categoryName
	 */
	public String getCategoryName() {
		return categoryName;
	}

	/**
	 * @param categoryName the categoryName to set
	 */
	public void setCategoryName(String categoryName) {
		this.categoryName = categoryName;
	}
}