package edu.ku.cete.domain;

import java.util.Date;
import java.util.List;

public class BluePrint {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column blueprint.id
	 * @mbggenerated  Wed Mar 25 10:28:09 CDT 2015
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column blueprint.contentareaid
	 * @mbggenerated  Wed Mar 25 10:28:09 CDT 2015
	 */
	private Long contentAreaId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column blueprint.gradecourseid
	 * @mbggenerated  Wed Mar 25 10:28:09 CDT 2015
	 */
	private Long gradeCourseId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column blueprint.gradebandid
	 * @mbggenerated  Wed Mar 25 10:28:09 CDT 2015
	 */
	private Long gradeBandId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column blueprint.criteria
	 * @mbggenerated  Wed Mar 25 10:28:09 CDT 2015
	 */
	private Long criteria;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column blueprint.groupnumber
	 * @mbggenerated  Wed Mar 25 10:28:09 CDT 2015
	 */
	private Long groupNumber;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column blueprint.numberrequired
	 * @mbggenerated  Wed Mar 25 10:28:09 CDT 2015
	 */
	private Long numberRequired;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column blueprint.createduser
	 * @mbggenerated  Wed Mar 25 10:28:09 CDT 2015
	 */
	private Integer createdUser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column blueprint.createddate
	 * @mbggenerated  Wed Mar 25 10:28:09 CDT 2015
	 */
	private Date createdDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column blueprint.modifieduser
	 * @mbggenerated  Wed Mar 25 10:28:09 CDT 2015
	 */
	private Integer modifiedUser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column blueprint.modifieddate
	 * @mbggenerated  Wed Mar 25 10:28:09 CDT 2015
	 */
	private Date modifiedDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column blueprint.activeflag
	 * @mbggenerated  Wed Mar 25 10:28:09 CDT 2015
	 */
	private Boolean activeFlag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column blueprint.writingtestlet
	 * @mbggenerated  Wed Mar 25 10:28:09 CDT 2015
	 */
	private Boolean writingTestlet;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column blueprint.id
	 * @return  the value of blueprint.id
	 * @mbggenerated  Wed Mar 25 10:28:09 CDT 2015
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column blueprint.id
	 * @param id  the value for blueprint.id
	 * @mbggenerated  Wed Mar 25 10:28:09 CDT 2015
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column blueprint.contentareaid
	 * @return  the value of blueprint.contentareaid
	 * @mbggenerated  Wed Mar 25 10:28:09 CDT 2015
	 */
	public Long getContentAreaId() {
		return contentAreaId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column blueprint.contentareaid
	 * @param contentAreaId  the value for blueprint.contentareaid
	 * @mbggenerated  Wed Mar 25 10:28:09 CDT 2015
	 */
	public void setContentAreaId(Long contentAreaId) {
		this.contentAreaId = contentAreaId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column blueprint.gradecourseid
	 * @return  the value of blueprint.gradecourseid
	 * @mbggenerated  Wed Mar 25 10:28:09 CDT 2015
	 */
	public Long getGradeCourseId() {
		return gradeCourseId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column blueprint.gradecourseid
	 * @param gradeCourseId  the value for blueprint.gradecourseid
	 * @mbggenerated  Wed Mar 25 10:28:09 CDT 2015
	 */
	public void setGradeCourseId(Long gradeCourseId) {
		this.gradeCourseId = gradeCourseId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column blueprint.gradebandid
	 * @return  the value of blueprint.gradebandid
	 * @mbggenerated  Wed Mar 25 10:28:09 CDT 2015
	 */
	public Long getGradeBandId() {
		return gradeBandId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column blueprint.gradebandid
	 * @param gradeBandId  the value for blueprint.gradebandid
	 * @mbggenerated  Wed Mar 25 10:28:09 CDT 2015
	 */
	public void setGradeBandId(Long gradeBandId) {
		this.gradeBandId = gradeBandId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column blueprint.criteria
	 * @return  the value of blueprint.criteria
	 * @mbggenerated  Wed Mar 25 10:28:09 CDT 2015
	 */
	public Long getCriteria() {
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column blueprint.criteria
	 * @param criteria  the value for blueprint.criteria
	 * @mbggenerated  Wed Mar 25 10:28:09 CDT 2015
	 */
	public void setCriteria(Long criteria) {
		this.criteria = criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column blueprint.groupnumber
	 * @return  the value of blueprint.groupnumber
	 * @mbggenerated  Wed Mar 25 10:28:09 CDT 2015
	 */
	public Long getGroupNumber() {
		return groupNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column blueprint.groupnumber
	 * @param groupNumber  the value for blueprint.groupnumber
	 * @mbggenerated  Wed Mar 25 10:28:09 CDT 2015
	 */
	public void setGroupNumber(Long groupNumber) {
		this.groupNumber = groupNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column blueprint.numberrequired
	 * @return  the value of blueprint.numberrequired
	 * @mbggenerated  Wed Mar 25 10:28:09 CDT 2015
	 */
	public Long getNumberRequired() {
		return numberRequired;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column blueprint.numberrequired
	 * @param numberRequired  the value for blueprint.numberrequired
	 * @mbggenerated  Wed Mar 25 10:28:09 CDT 2015
	 */
	public void setNumberRequired(Long numberRequired) {
		this.numberRequired = numberRequired;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column blueprint.createduser
	 * @return  the value of blueprint.createduser
	 * @mbggenerated  Wed Mar 25 10:28:09 CDT 2015
	 */
	public Integer getCreatedUser() {
		return createdUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column blueprint.createduser
	 * @param createdUser  the value for blueprint.createduser
	 * @mbggenerated  Wed Mar 25 10:28:09 CDT 2015
	 */
	public void setCreatedUser(Integer createdUser) {
		this.createdUser = createdUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column blueprint.createddate
	 * @return  the value of blueprint.createddate
	 * @mbggenerated  Wed Mar 25 10:28:09 CDT 2015
	 */
	public Date getCreatedDate() {
		return createdDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column blueprint.createddate
	 * @param createdDate  the value for blueprint.createddate
	 * @mbggenerated  Wed Mar 25 10:28:09 CDT 2015
	 */
	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column blueprint.modifieduser
	 * @return  the value of blueprint.modifieduser
	 * @mbggenerated  Wed Mar 25 10:28:09 CDT 2015
	 */
	public Integer getModifiedUser() {
		return modifiedUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column blueprint.modifieduser
	 * @param modifiedUser  the value for blueprint.modifieduser
	 * @mbggenerated  Wed Mar 25 10:28:09 CDT 2015
	 */
	public void setModifiedUser(Integer modifiedUser) {
		this.modifiedUser = modifiedUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column blueprint.modifieddate
	 * @return  the value of blueprint.modifieddate
	 * @mbggenerated  Wed Mar 25 10:28:09 CDT 2015
	 */
	public Date getModifiedDate() {
		return modifiedDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column blueprint.modifieddate
	 * @param modifiedDate  the value for blueprint.modifieddate
	 * @mbggenerated  Wed Mar 25 10:28:09 CDT 2015
	 */
	public void setModifiedDate(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column blueprint.activeflag
	 * @return  the value of blueprint.activeflag
	 * @mbggenerated  Wed Mar 25 10:28:09 CDT 2015
	 */
	public Boolean getActiveFlag() {
		return activeFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column blueprint.activeflag
	 * @param activeFlag  the value for blueprint.activeflag
	 * @mbggenerated  Wed Mar 25 10:28:09 CDT 2015
	 */
	public void setActiveFlag(Boolean activeFlag) {
		this.activeFlag = activeFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column blueprint.writingtestlet
	 * @return  the value of blueprint.writingtestlet
	 * @mbggenerated  Wed Mar 25 10:28:09 CDT 2015
	 */
	public Boolean getWritingTestlet() {
		return writingTestlet;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column blueprint.writingtestlet
	 * @param writingTestlet  the value for blueprint.writingtestlet
	 * @mbggenerated  Wed Mar 25 10:28:09 CDT 2015
	 */
	public void setWritingTestlet(Boolean writingTestlet) {
		this.writingTestlet = writingTestlet;
	}

	private List<BluePrintEssentialElements> bluePrintEssentialElements;

	public List<BluePrintEssentialElements> getBluePrintEssentialElements() {
		return bluePrintEssentialElements;
	}

	public void setBluePrintEssentialElements(
			List<BluePrintEssentialElements> bluePrintEssentialElements) {
		this.bluePrintEssentialElements = bluePrintEssentialElements;
	}
}