package edu.ku.cete.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import edu.ku.cete.util.ParsingConstants;

public class DailyAccessCode {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dailyaccesscode.id
	 * @mbggenerated  Tue Jan 05 22:17:27 CST 2016
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dailyaccesscode.contentareaid
	 * @mbggenerated  Tue Jan 05 22:17:27 CST 2016
	 */
	private Long contentAreaId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dailyaccesscode.gradecourseid
	 * @mbggenerated  Tue Jan 05 22:17:27 CST 2016
	 */
	private Long gradeCourseId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dailyaccesscode.stageid
	 * @mbggenerated  Tue Jan 05 22:17:27 CST 2016
	 */
	private Long stageId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dailyaccesscode.partnumber
	 * @mbggenerated  Tue Jan 05 22:17:27 CST 2016
	 */
	private Integer partNumber;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dailyaccesscode.createduser
	 * @mbggenerated  Tue Jan 05 22:17:27 CST 2016
	 */
	private Long createdUser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dailyaccesscode.createddate
	 * @mbggenerated  Tue Jan 05 22:17:27 CST 2016
	 */
	private Date createdDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dailyaccesscode.modifieduser
	 * @mbggenerated  Tue Jan 05 22:17:27 CST 2016
	 */
	private Long modifiedUser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dailyaccesscode.modifieddate
	 * @mbggenerated  Tue Jan 05 22:17:27 CST 2016
	 */
	private Date modifiedDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dailyaccesscode.effectivedate
	 * @mbggenerated  Tue Jan 05 22:17:27 CST 2016
	 */
	private Date effectiveDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dailyaccesscode.accesscode
	 * @mbggenerated  Tue Jan 05 22:17:27 CST 2016
	 */
	private String accessCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dailyaccesscode.operationaltestwindowid
	 * @mbggenerated  Tue Jan 05 22:17:27 CST 2016
	 */
	private Long operationalTestwindowId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dailyaccesscode.id
	 * @return  the value of dailyaccesscode.id
	 * @mbggenerated  Tue Jan 05 22:17:27 CST 2016
	 */
	private Long gradeBandId;
	
	private boolean isPLTW;
	
	private String assessmentProgramCode;
	
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dailyaccesscode.id
	 * @param id  the value for dailyaccesscode.id
	 * @mbggenerated  Tue Jan 05 22:17:27 CST 2016
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dailyaccesscode.contentareaid
	 * @return  the value of dailyaccesscode.contentareaid
	 * @mbggenerated  Tue Jan 05 22:17:27 CST 2016
	 */
	public Long getContentAreaId() {
		return contentAreaId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dailyaccesscode.contentareaid
	 * @param contentAreaId  the value for dailyaccesscode.contentareaid
	 * @mbggenerated  Tue Jan 05 22:17:27 CST 2016
	 */
	public void setContentAreaId(Long contentAreaId) {
		this.contentAreaId = contentAreaId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dailyaccesscode.gradecourseid
	 * @return  the value of dailyaccesscode.gradecourseid
	 * @mbggenerated  Tue Jan 05 22:17:27 CST 2016
	 */
	public Long getGradeCourseId() {
		return gradeCourseId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dailyaccesscode.gradecourseid
	 * @param gradeCourseId  the value for dailyaccesscode.gradecourseid
	 * @mbggenerated  Tue Jan 05 22:17:27 CST 2016
	 */
	public void setGradeCourseId(Long gradeCourseId) {
		this.gradeCourseId = gradeCourseId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dailyaccesscode.stageid
	 * @return  the value of dailyaccesscode.stageid
	 * @mbggenerated  Tue Jan 05 22:17:27 CST 2016
	 */
	public Long getStageId() {
		return stageId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dailyaccesscode.stageid
	 * @param stageId  the value for dailyaccesscode.stageid
	 * @mbggenerated  Tue Jan 05 22:17:27 CST 2016
	 */
	public void setStageId(Long stageId) {
		this.stageId = stageId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dailyaccesscode.partnumber
	 * @return  the value of dailyaccesscode.partnumber
	 * @mbggenerated  Tue Jan 05 22:17:27 CST 2016
	 */
	public Integer getPartNumber() {
		return partNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dailyaccesscode.partnumber
	 * @param partNumber  the value for dailyaccesscode.partnumber
	 * @mbggenerated  Tue Jan 05 22:17:27 CST 2016
	 */
	public void setPartNumber(Integer partNumber) {
		this.partNumber = partNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dailyaccesscode.createduser
	 * @return  the value of dailyaccesscode.createduser
	 * @mbggenerated  Tue Jan 05 22:17:27 CST 2016
	 */
	public Long getCreatedUser() {
		return createdUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dailyaccesscode.createduser
	 * @param createdUser  the value for dailyaccesscode.createduser
	 * @mbggenerated  Tue Jan 05 22:17:27 CST 2016
	 */
	public void setCreatedUser(Long createdUser) {
		this.createdUser = createdUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dailyaccesscode.createddate
	 * @return  the value of dailyaccesscode.createddate
	 * @mbggenerated  Tue Jan 05 22:17:27 CST 2016
	 */
	public Date getCreatedDate() {
		return createdDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dailyaccesscode.createddate
	 * @param createdDate  the value for dailyaccesscode.createddate
	 * @mbggenerated  Tue Jan 05 22:17:27 CST 2016
	 */
	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dailyaccesscode.modifieduser
	 * @return  the value of dailyaccesscode.modifieduser
	 * @mbggenerated  Tue Jan 05 22:17:27 CST 2016
	 */
	public Long getModifiedUser() {
		return modifiedUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dailyaccesscode.modifieduser
	 * @param modifiedUser  the value for dailyaccesscode.modifieduser
	 * @mbggenerated  Tue Jan 05 22:17:27 CST 2016
	 */
	public void setModifiedUser(Long modifiedUser) {
		this.modifiedUser = modifiedUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dailyaccesscode.modifieddate
	 * @return  the value of dailyaccesscode.modifieddate
	 * @mbggenerated  Tue Jan 05 22:17:27 CST 2016
	 */
	public Date getModifiedDate() {
		return modifiedDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dailyaccesscode.modifieddate
	 * @param modifiedDate  the value for dailyaccesscode.modifieddate
	 * @mbggenerated  Tue Jan 05 22:17:27 CST 2016
	 */
	public void setModifiedDate(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dailyaccesscode.effectivedate
	 * @return  the value of dailyaccesscode.effectivedate
	 * @mbggenerated  Tue Jan 05 22:17:27 CST 2016
	 */
	public Date getEffectiveDate() {
		return effectiveDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dailyaccesscode.effectivedate
	 * @param effectiveDate  the value for dailyaccesscode.effectivedate
	 * @mbggenerated  Tue Jan 05 22:17:27 CST 2016
	 */
	public void setEffectiveDate(Date effectiveDate) {
		this.effectiveDate = effectiveDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dailyaccesscode.accesscode
	 * @return  the value of dailyaccesscode.accesscode
	 * @mbggenerated  Tue Jan 05 22:17:27 CST 2016
	 */
	public String getAccessCode() {
		return accessCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dailyaccesscode.accesscode
	 * @param accessCode  the value for dailyaccesscode.accesscode
	 * @mbggenerated  Tue Jan 05 22:17:27 CST 2016
	 */
	public void setAccessCode(String accessCode) {
		this.accessCode = accessCode == null ? null : accessCode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dailyaccesscode.operationaltestwindowid
	 * @return  the value of dailyaccesscode.operationaltestwindowid
	 * @mbggenerated  Tue Jan 05 22:17:27 CST 2016
	 */
	public Long getOperationalTestwindowId() {
		return operationalTestwindowId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dailyaccesscode.operationaltestwindowid
	 * @param operationalTestwindowId  the value for dailyaccesscode.operationaltestwindowid
	 * @mbggenerated  Tue Jan 05 22:17:27 CST 2016
	 */
	public void setOperationalTestwindowId(Long operationalTestwindowId) {
		this.operationalTestwindowId = operationalTestwindowId;
	}

	private Date beginDate;
	private Date endDate;

	private String contentAreaName;
	private String gradeCode;
	private String stageName;
	private String stageCode;
	private String gradeCourseName;
	private String gradeBandName;
	private String gradeBandCode;
	
	public Date getBeginDate() {
		return beginDate;
	}

	public void setBeginDate(Date beginDate) {
		this.beginDate = beginDate;
	}

	public Date getEndDate() {
		return endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	public String getContentAreaName() {
		return contentAreaName;
	}

	public void setContentAreaName(String contentAreaName) {
		this.contentAreaName = contentAreaName;
	}

	public String getGradeCode() {
		return gradeCode;
	}

	public void setGradeCode(String gradeCode) {
		this.gradeCode = gradeCode;
	}

	public String getStageName() {
		return stageName;
	}

	public void setStageName(String stageName) {
		this.stageName = stageName;
	}

	public String getStageCode() {
		return stageCode;
	}

	public void setStageCode(String stageCode) {
		this.stageCode = stageCode;
	}
	
	public String getGradeCourseName() {
		return gradeCourseName;
	}

	public void setGradeCourseName(String gradeCourseName) {
		this.gradeCourseName = gradeCourseName;
	}

	public List<String> buildJSONRow() {
		List<String> cells = new ArrayList<String>();

		if(getContentAreaId() != null) {
			cells.add(ParsingConstants.BLANK + getContentAreaId());
		} else {
			cells.add("");
		}
		
		if(getGradeCourseId() != null) {
			cells.add(ParsingConstants.BLANK + getGradeCourseId());
		} else {
			cells.add("");
		}
		
		if(getGradeBandId() != null) {
			cells.add(ParsingConstants.BLANK + getGradeBandId());
		} else {
			cells.add("");
		}		
		
		if(getContentAreaName() != null) {
			cells.add(ParsingConstants.BLANK + getContentAreaName());
		} else {
			cells.add("");
		}
        
		if(getGradeCourseName() != null) {
			cells.add(ParsingConstants.BLANK + getGradeCourseName());
		} else {
			cells.add("");
		}
		
		if(getGradeBandName() != null) {
			cells.add(ParsingConstants.BLANK + getGradeBandName());
		} else {
			cells.add("");
		}
		
		//pdf, csv
		cells.add("");
        
		
        
		return cells;
	}
	
	public Long getGradeBandId() {
		return gradeBandId;
	}

	public void setGradeBandId(Long gradeBandId) {
		this.gradeBandId = gradeBandId;
	}

	public String getGradeBandName() {
		return gradeBandName;
	}

	public void setGradeBandName(String gradeBandName) {
		this.gradeBandName = gradeBandName;
	}

	public boolean isPLTW() {
		return isPLTW;
	}

	public void setPLTW(boolean isPLTW) {
		this.isPLTW = isPLTW;
	}

	public String getAssessmentProgramCode() {
		return assessmentProgramCode;
	}

	public void setAssessmentProgramCode(String assessmentProgramCode) {
		this.assessmentProgramCode = assessmentProgramCode;
	}

	public String getGradeBandCode() {
		return gradeBandCode;
	}

	public void setGradeBandCode(String gradeBandCode) {
		this.gradeBandCode = gradeBandCode;
	}
	
}