package edu.ku.cete.domain;

import java.util.Date;

public class InterfaceRequestHistory {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column interfacerequesthistory.id
     *
     * @mbggenerated Tue Jun 09 07:16:29 CDT 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column interfacerequesthistory.interfacename
     *
     * @mbggenerated Tue Jun 09 07:16:29 CDT 2015
     */
    private String interfaceName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column interfacerequesthistory.requesteduserid
     *
     * @mbggenerated Tue Jun 09 07:16:29 CDT 2015
     */
    private String requestedUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column interfacerequesthistory.requestedipaddress
     *
     * @mbggenerated Tue Jun 09 07:16:29 CDT 2015
     */
    private String requestedIPAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column interfacerequesthistory.requesteddate
     *
     * @mbggenerated Tue Jun 09 07:16:29 CDT 2015
     */
    private Date requestedDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column interfacerequesthistory.modulereportid
     *
     * @mbggenerated Tue Jun 09 07:16:29 CDT 2015
     */
    private Long moduleReportId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column interfacerequesthistory.message
     *
     * @mbggenerated Tue Jun 09 07:16:29 CDT 2015
     */
    private String message;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column interfacerequesthistory.id
     *
     * @return the value of interfacerequesthistory.id
     *
     * @mbggenerated Tue Jun 09 07:16:29 CDT 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column interfacerequesthistory.id
     *
     * @param id the value for interfacerequesthistory.id
     *
     * @mbggenerated Tue Jun 09 07:16:29 CDT 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column interfacerequesthistory.interfacename
     *
     * @return the value of interfacerequesthistory.interfacename
     *
     * @mbggenerated Tue Jun 09 07:16:29 CDT 2015
     */
    public String getInterfaceName() {
        return interfaceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column interfacerequesthistory.interfacename
     *
     * @param interfaceName the value for interfacerequesthistory.interfacename
     *
     * @mbggenerated Tue Jun 09 07:16:29 CDT 2015
     */
    public void setInterfaceName(String interfaceName) {
        this.interfaceName = interfaceName == null ? null : interfaceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column interfacerequesthistory.requesteduserid
     *
     * @return the value of interfacerequesthistory.requesteduserid
     *
     * @mbggenerated Tue Jun 09 07:16:29 CDT 2015
     */
    public String getRequestedUserId() {
        return requestedUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column interfacerequesthistory.requesteduserid
     *
     * @param requestedUserId the value for interfacerequesthistory.requesteduserid
     *
     * @mbggenerated Tue Jun 09 07:16:29 CDT 2015
     */
    public void setRequestedUserId(String requestedUserId) {
        this.requestedUserId = requestedUserId == null ? null : requestedUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column interfacerequesthistory.requestedipaddress
     *
     * @return the value of interfacerequesthistory.requestedipaddress
     *
     * @mbggenerated Tue Jun 09 07:16:29 CDT 2015
     */
    public String getRequestedIPAddress() {
        return requestedIPAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column interfacerequesthistory.requestedipaddress
     *
     * @param requestedIPAddress the value for interfacerequesthistory.requestedipaddress
     *
     * @mbggenerated Tue Jun 09 07:16:29 CDT 2015
     */
    public void setRequestedIPAddress(String requestedIPAddress) {
        this.requestedIPAddress = requestedIPAddress == null ? null : requestedIPAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column interfacerequesthistory.requesteddate
     *
     * @return the value of interfacerequesthistory.requesteddate
     *
     * @mbggenerated Tue Jun 09 07:16:29 CDT 2015
     */
    public Date getRequestedDate() {
        return requestedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column interfacerequesthistory.requesteddate
     *
     * @param requestedDate the value for interfacerequesthistory.requesteddate
     *
     * @mbggenerated Tue Jun 09 07:16:29 CDT 2015
     */
    public void setRequestedDate(Date requestedDate) {
        this.requestedDate = requestedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column interfacerequesthistory.modulereportid
     *
     * @return the value of interfacerequesthistory.modulereportid
     *
     * @mbggenerated Tue Jun 09 07:16:29 CDT 2015
     */
    public Long getModuleReportId() {
        return moduleReportId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column interfacerequesthistory.modulereportid
     *
     * @param moduleReportId the value for interfacerequesthistory.modulereportid
     *
     * @mbggenerated Tue Jun 09 07:16:29 CDT 2015
     */
    public void setModuleReportId(Long moduleReportId) {
        this.moduleReportId = moduleReportId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column interfacerequesthistory.message
     *
     * @return the value of interfacerequesthistory.message
     *
     * @mbggenerated Tue Jun 09 07:16:29 CDT 2015
     */
    public String getMessage() {
        return message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column interfacerequesthistory.message
     *
     * @param message the value for interfacerequesthistory.message
     *
     * @mbggenerated Tue Jun 09 07:16:29 CDT 2015
     */
    public void setMessage(String message) {
        this.message = message == null ? null : message.trim();
    }
}