package edu.ku.cete.domain;

import java.util.ArrayList;
import java.util.List;
import java.util.Date;

public class SpecialCircumstanceExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table specialcircumstance
	 * @mbggenerated  Thu Jan 29 14:54:52 CST 2015
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table specialcircumstance
	 * @mbggenerated  Thu Jan 29 14:54:52 CST 2015
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table specialcircumstance
	 * @mbggenerated  Thu Jan 29 14:54:52 CST 2015
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table specialcircumstance
	 * @mbggenerated  Thu Jan 29 14:54:52 CST 2015
	 */
	public SpecialCircumstanceExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table specialcircumstance
	 * @mbggenerated  Thu Jan 29 14:54:52 CST 2015
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table specialcircumstance
	 * @mbggenerated  Thu Jan 29 14:54:52 CST 2015
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table specialcircumstance
	 * @mbggenerated  Thu Jan 29 14:54:52 CST 2015
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table specialcircumstance
	 * @mbggenerated  Thu Jan 29 14:54:52 CST 2015
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table specialcircumstance
	 * @mbggenerated  Thu Jan 29 14:54:52 CST 2015
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table specialcircumstance
	 * @mbggenerated  Thu Jan 29 14:54:52 CST 2015
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table specialcircumstance
	 * @mbggenerated  Thu Jan 29 14:54:52 CST 2015
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table specialcircumstance
	 * @mbggenerated  Thu Jan 29 14:54:52 CST 2015
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table specialcircumstance
	 * @mbggenerated  Thu Jan 29 14:54:52 CST 2015
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table specialcircumstance
	 * @mbggenerated  Thu Jan 29 14:54:52 CST 2015
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table specialcircumstance
	 * @mbggenerated  Thu Jan 29 14:54:52 CST 2015
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Long value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Long value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Long value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Long value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Long value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Long value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Long> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Long> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Long value1, Long value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Long value1, Long value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andSpecialCircumstanceTypeIsNull() {
			addCriterion("specialcircumstancetype is null");
			return (Criteria) this;
		}

		public Criteria andSpecialCircumstanceTypeIsNotNull() {
			addCriterion("specialcircumstancetype is not null");
			return (Criteria) this;
		}

		public Criteria andSpecialCircumstanceTypeEqualTo(String value) {
			addCriterion("specialcircumstancetype =", value,
					"specialCircumstanceType");
			return (Criteria) this;
		}

		public Criteria andSpecialCircumstanceTypeNotEqualTo(String value) {
			addCriterion("specialcircumstancetype <>", value,
					"specialCircumstanceType");
			return (Criteria) this;
		}

		public Criteria andSpecialCircumstanceTypeGreaterThan(String value) {
			addCriterion("specialcircumstancetype >", value,
					"specialCircumstanceType");
			return (Criteria) this;
		}

		public Criteria andSpecialCircumstanceTypeGreaterThanOrEqualTo(
				String value) {
			addCriterion("specialcircumstancetype >=", value,
					"specialCircumstanceType");
			return (Criteria) this;
		}

		public Criteria andSpecialCircumstanceTypeLessThan(String value) {
			addCriterion("specialcircumstancetype <", value,
					"specialCircumstanceType");
			return (Criteria) this;
		}

		public Criteria andSpecialCircumstanceTypeLessThanOrEqualTo(String value) {
			addCriterion("specialcircumstancetype <=", value,
					"specialCircumstanceType");
			return (Criteria) this;
		}

		public Criteria andSpecialCircumstanceTypeLike(String value) {
			addCriterion("specialcircumstancetype like", value,
					"specialCircumstanceType");
			return (Criteria) this;
		}

		public Criteria andSpecialCircumstanceTypeNotLike(String value) {
			addCriterion("specialcircumstancetype not like", value,
					"specialCircumstanceType");
			return (Criteria) this;
		}

		public Criteria andSpecialCircumstanceTypeIn(List<String> values) {
			addCriterion("specialcircumstancetype in", values,
					"specialCircumstanceType");
			return (Criteria) this;
		}

		public Criteria andSpecialCircumstanceTypeNotIn(List<String> values) {
			addCriterion("specialcircumstancetype not in", values,
					"specialCircumstanceType");
			return (Criteria) this;
		}

		public Criteria andSpecialCircumstanceTypeBetween(String value1,
				String value2) {
			addCriterion("specialcircumstancetype between", value1, value2,
					"specialCircumstanceType");
			return (Criteria) this;
		}

		public Criteria andSpecialCircumstanceTypeNotBetween(String value1,
				String value2) {
			addCriterion("specialcircumstancetype not between", value1, value2,
					"specialCircumstanceType");
			return (Criteria) this;
		}

		public Criteria andCedsCodeIsNull() {
			addCriterion("cedscode is null");
			return (Criteria) this;
		}

		public Criteria andCedsCodeIsNotNull() {
			addCriterion("cedscode is not null");
			return (Criteria) this;
		}

		public Criteria andCedsCodeEqualTo(Long value) {
			addCriterion("cedscode =", value, "cedsCode");
			return (Criteria) this;
		}

		public Criteria andCedsCodeNotEqualTo(Long value) {
			addCriterion("cedscode <>", value, "cedsCode");
			return (Criteria) this;
		}

		public Criteria andCedsCodeGreaterThan(Long value) {
			addCriterion("cedscode >", value, "cedsCode");
			return (Criteria) this;
		}

		public Criteria andCedsCodeGreaterThanOrEqualTo(Long value) {
			addCriterion("cedscode >=", value, "cedsCode");
			return (Criteria) this;
		}

		public Criteria andCedsCodeLessThan(Long value) {
			addCriterion("cedscode <", value, "cedsCode");
			return (Criteria) this;
		}

		public Criteria andCedsCodeLessThanOrEqualTo(Long value) {
			addCriterion("cedscode <=", value, "cedsCode");
			return (Criteria) this;
		}

		public Criteria andCedsCodeIn(List<Long> values) {
			addCriterion("cedscode in", values, "cedsCode");
			return (Criteria) this;
		}

		public Criteria andCedsCodeNotIn(List<Long> values) {
			addCriterion("cedscode not in", values, "cedsCode");
			return (Criteria) this;
		}

		public Criteria andCedsCodeBetween(Long value1, Long value2) {
			addCriterion("cedscode between", value1, value2, "cedsCode");
			return (Criteria) this;
		}

		public Criteria andCedsCodeNotBetween(Long value1, Long value2) {
			addCriterion("cedscode not between", value1, value2, "cedsCode");
			return (Criteria) this;
		}

		public Criteria andKsdeCodeIsNull() {
			addCriterion("ksdecode is null");
			return (Criteria) this;
		}

		public Criteria andKsdeCodeIsNotNull() {
			addCriterion("ksdecode is not null");
			return (Criteria) this;
		}

		public Criteria andKsdeCodeEqualTo(String value) {
			addCriterion("ksdecode =", value, "ksdeCode");
			return (Criteria) this;
		}

		public Criteria andKsdeCodeNotEqualTo(String value) {
			addCriterion("ksdecode <>", value, "ksdeCode");
			return (Criteria) this;
		}

		public Criteria andKsdeCodeGreaterThan(String value) {
			addCriterion("ksdecode >", value, "ksdeCode");
			return (Criteria) this;
		}

		public Criteria andKsdeCodeGreaterThanOrEqualTo(String value) {
			addCriterion("ksdecode >=", value, "ksdeCode");
			return (Criteria) this;
		}

		public Criteria andKsdeCodeLessThan(String value) {
			addCriterion("ksdecode <", value, "ksdeCode");
			return (Criteria) this;
		}

		public Criteria andKsdeCodeLessThanOrEqualTo(String value) {
			addCriterion("ksdecode <=", value, "ksdeCode");
			return (Criteria) this;
		}

		public Criteria andKsdeCodeLike(String value) {
			addCriterion("ksdecode like", value, "ksdeCode");
			return (Criteria) this;
		}

		public Criteria andKsdeCodeNotLike(String value) {
			addCriterion("ksdecode not like", value, "ksdeCode");
			return (Criteria) this;
		}

		public Criteria andKsdeCodeIn(List<String> values) {
			addCriterion("ksdecode in", values, "ksdeCode");
			return (Criteria) this;
		}

		public Criteria andKsdeCodeNotIn(List<String> values) {
			addCriterion("ksdecode not in", values, "ksdeCode");
			return (Criteria) this;
		}

		public Criteria andKsdeCodeBetween(String value1, String value2) {
			addCriterion("ksdecode between", value1, value2, "ksdeCode");
			return (Criteria) this;
		}

		public Criteria andKsdeCodeNotBetween(String value1, String value2) {
			addCriterion("ksdecode not between", value1, value2, "ksdeCode");
			return (Criteria) this;
		}

		public Criteria andAssessmentProgramIdIsNull() {
			addCriterion("assessmentprogramid is null");
			return (Criteria) this;
		}

		public Criteria andAssessmentProgramIdIsNotNull() {
			addCriterion("assessmentprogramid is not null");
			return (Criteria) this;
		}

		public Criteria andAssessmentProgramIdEqualTo(Long value) {
			addCriterion("assessmentprogramid =", value, "assessmentProgramId");
			return (Criteria) this;
		}

		public Criteria andAssessmentProgramIdNotEqualTo(Long value) {
			addCriterion("assessmentprogramid <>", value, "assessmentProgramId");
			return (Criteria) this;
		}

		public Criteria andAssessmentProgramIdGreaterThan(Long value) {
			addCriterion("assessmentprogramid >", value, "assessmentProgramId");
			return (Criteria) this;
		}

		public Criteria andAssessmentProgramIdGreaterThanOrEqualTo(Long value) {
			addCriterion("assessmentprogramid >=", value, "assessmentProgramId");
			return (Criteria) this;
		}

		public Criteria andAssessmentProgramIdLessThan(Long value) {
			addCriterion("assessmentprogramid <", value, "assessmentProgramId");
			return (Criteria) this;
		}

		public Criteria andAssessmentProgramIdLessThanOrEqualTo(Long value) {
			addCriterion("assessmentprogramid <=", value, "assessmentProgramId");
			return (Criteria) this;
		}

		public Criteria andAssessmentProgramIdIn(List<Long> values) {
			addCriterion("assessmentprogramid in", values,
					"assessmentProgramId");
			return (Criteria) this;
		}

		public Criteria andAssessmentProgramIdNotIn(List<Long> values) {
			addCriterion("assessmentprogramid not in", values,
					"assessmentProgramId");
			return (Criteria) this;
		}

		public Criteria andAssessmentProgramIdBetween(Long value1, Long value2) {
			addCriterion("assessmentprogramid between", value1, value2,
					"assessmentProgramId");
			return (Criteria) this;
		}

		public Criteria andAssessmentProgramIdNotBetween(Long value1,
				Long value2) {
			addCriterion("assessmentprogramid not between", value1, value2,
					"assessmentProgramId");
			return (Criteria) this;
		}

		public Criteria andActiveFlagIsNull() {
			addCriterion("activeflag is null");
			return (Criteria) this;
		}

		public Criteria andActiveFlagIsNotNull() {
			addCriterion("activeflag is not null");
			return (Criteria) this;
		}

		public Criteria andActiveFlagEqualTo(Boolean value) {
			addCriterion("activeflag =", value, "activeFlag");
			return (Criteria) this;
		}

		public Criteria andActiveFlagNotEqualTo(Boolean value) {
			addCriterion("activeflag <>", value, "activeFlag");
			return (Criteria) this;
		}

		public Criteria andActiveFlagGreaterThan(Boolean value) {
			addCriterion("activeflag >", value, "activeFlag");
			return (Criteria) this;
		}

		public Criteria andActiveFlagGreaterThanOrEqualTo(Boolean value) {
			addCriterion("activeflag >=", value, "activeFlag");
			return (Criteria) this;
		}

		public Criteria andActiveFlagLessThan(Boolean value) {
			addCriterion("activeflag <", value, "activeFlag");
			return (Criteria) this;
		}

		public Criteria andActiveFlagLessThanOrEqualTo(Boolean value) {
			addCriterion("activeflag <=", value, "activeFlag");
			return (Criteria) this;
		}

		public Criteria andActiveFlagIn(List<Boolean> values) {
			addCriterion("activeflag in", values, "activeFlag");
			return (Criteria) this;
		}

		public Criteria andActiveFlagNotIn(List<Boolean> values) {
			addCriterion("activeflag not in", values, "activeFlag");
			return (Criteria) this;
		}

		public Criteria andActiveFlagBetween(Boolean value1, Boolean value2) {
			addCriterion("activeflag between", value1, value2, "activeFlag");
			return (Criteria) this;
		}

		public Criteria andActiveFlagNotBetween(Boolean value1, Boolean value2) {
			addCriterion("activeflag not between", value1, value2, "activeFlag");
			return (Criteria) this;
		}

		public Criteria andCreateDateIsNull() {
			addCriterion("createdate is null");
			return (Criteria) this;
		}

		public Criteria andCreateDateIsNotNull() {
			addCriterion("createdate is not null");
			return (Criteria) this;
		}

		public Criteria andCreateDateEqualTo(Date value) {
			addCriterion("createdate =", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateNotEqualTo(Date value) {
			addCriterion("createdate <>", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateGreaterThan(Date value) {
			addCriterion("createdate >", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateGreaterThanOrEqualTo(Date value) {
			addCriterion("createdate >=", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateLessThan(Date value) {
			addCriterion("createdate <", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateLessThanOrEqualTo(Date value) {
			addCriterion("createdate <=", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateIn(List<Date> values) {
			addCriterion("createdate in", values, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateNotIn(List<Date> values) {
			addCriterion("createdate not in", values, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateBetween(Date value1, Date value2) {
			addCriterion("createdate between", value1, value2, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateNotBetween(Date value1, Date value2) {
			addCriterion("createdate not between", value1, value2, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreatedUserIsNull() {
			addCriterion("createduser is null");
			return (Criteria) this;
		}

		public Criteria andCreatedUserIsNotNull() {
			addCriterion("createduser is not null");
			return (Criteria) this;
		}

		public Criteria andCreatedUserEqualTo(Integer value) {
			addCriterion("createduser =", value, "createdUser");
			return (Criteria) this;
		}

		public Criteria andCreatedUserNotEqualTo(Integer value) {
			addCriterion("createduser <>", value, "createdUser");
			return (Criteria) this;
		}

		public Criteria andCreatedUserGreaterThan(Integer value) {
			addCriterion("createduser >", value, "createdUser");
			return (Criteria) this;
		}

		public Criteria andCreatedUserGreaterThanOrEqualTo(Integer value) {
			addCriterion("createduser >=", value, "createdUser");
			return (Criteria) this;
		}

		public Criteria andCreatedUserLessThan(Integer value) {
			addCriterion("createduser <", value, "createdUser");
			return (Criteria) this;
		}

		public Criteria andCreatedUserLessThanOrEqualTo(Integer value) {
			addCriterion("createduser <=", value, "createdUser");
			return (Criteria) this;
		}

		public Criteria andCreatedUserIn(List<Integer> values) {
			addCriterion("createduser in", values, "createdUser");
			return (Criteria) this;
		}

		public Criteria andCreatedUserNotIn(List<Integer> values) {
			addCriterion("createduser not in", values, "createdUser");
			return (Criteria) this;
		}

		public Criteria andCreatedUserBetween(Integer value1, Integer value2) {
			addCriterion("createduser between", value1, value2, "createdUser");
			return (Criteria) this;
		}

		public Criteria andCreatedUserNotBetween(Integer value1, Integer value2) {
			addCriterion("createduser not between", value1, value2,
					"createdUser");
			return (Criteria) this;
		}

		public Criteria andModifiedDateIsNull() {
			addCriterion("modifieddate is null");
			return (Criteria) this;
		}

		public Criteria andModifiedDateIsNotNull() {
			addCriterion("modifieddate is not null");
			return (Criteria) this;
		}

		public Criteria andModifiedDateEqualTo(Date value) {
			addCriterion("modifieddate =", value, "modifiedDate");
			return (Criteria) this;
		}

		public Criteria andModifiedDateNotEqualTo(Date value) {
			addCriterion("modifieddate <>", value, "modifiedDate");
			return (Criteria) this;
		}

		public Criteria andModifiedDateGreaterThan(Date value) {
			addCriterion("modifieddate >", value, "modifiedDate");
			return (Criteria) this;
		}

		public Criteria andModifiedDateGreaterThanOrEqualTo(Date value) {
			addCriterion("modifieddate >=", value, "modifiedDate");
			return (Criteria) this;
		}

		public Criteria andModifiedDateLessThan(Date value) {
			addCriterion("modifieddate <", value, "modifiedDate");
			return (Criteria) this;
		}

		public Criteria andModifiedDateLessThanOrEqualTo(Date value) {
			addCriterion("modifieddate <=", value, "modifiedDate");
			return (Criteria) this;
		}

		public Criteria andModifiedDateIn(List<Date> values) {
			addCriterion("modifieddate in", values, "modifiedDate");
			return (Criteria) this;
		}

		public Criteria andModifiedDateNotIn(List<Date> values) {
			addCriterion("modifieddate not in", values, "modifiedDate");
			return (Criteria) this;
		}

		public Criteria andModifiedDateBetween(Date value1, Date value2) {
			addCriterion("modifieddate between", value1, value2, "modifiedDate");
			return (Criteria) this;
		}

		public Criteria andModifiedDateNotBetween(Date value1, Date value2) {
			addCriterion("modifieddate not between", value1, value2,
					"modifiedDate");
			return (Criteria) this;
		}

		public Criteria andModifiedUserIsNull() {
			addCriterion("modifieduser is null");
			return (Criteria) this;
		}

		public Criteria andModifiedUserIsNotNull() {
			addCriterion("modifieduser is not null");
			return (Criteria) this;
		}

		public Criteria andModifiedUserEqualTo(Integer value) {
			addCriterion("modifieduser =", value, "modifiedUser");
			return (Criteria) this;
		}

		public Criteria andModifiedUserNotEqualTo(Integer value) {
			addCriterion("modifieduser <>", value, "modifiedUser");
			return (Criteria) this;
		}

		public Criteria andModifiedUserGreaterThan(Integer value) {
			addCriterion("modifieduser >", value, "modifiedUser");
			return (Criteria) this;
		}

		public Criteria andModifiedUserGreaterThanOrEqualTo(Integer value) {
			addCriterion("modifieduser >=", value, "modifiedUser");
			return (Criteria) this;
		}

		public Criteria andModifiedUserLessThan(Integer value) {
			addCriterion("modifieduser <", value, "modifiedUser");
			return (Criteria) this;
		}

		public Criteria andModifiedUserLessThanOrEqualTo(Integer value) {
			addCriterion("modifieduser <=", value, "modifiedUser");
			return (Criteria) this;
		}

		public Criteria andModifiedUserIn(List<Integer> values) {
			addCriterion("modifieduser in", values, "modifiedUser");
			return (Criteria) this;
		}

		public Criteria andModifiedUserNotIn(List<Integer> values) {
			addCriterion("modifieduser not in", values, "modifiedUser");
			return (Criteria) this;
		}

		public Criteria andModifiedUserBetween(Integer value1, Integer value2) {
			addCriterion("modifieduser between", value1, value2, "modifiedUser");
			return (Criteria) this;
		}

		public Criteria andModifiedUserNotBetween(Integer value1, Integer value2) {
			addCriterion("modifieduser not between", value1, value2,
					"modifiedUser");
			return (Criteria) this;
		}

		public Criteria andRequireConfirmationIsNull() {
			addCriterion("requireconfirmation is null");
			return (Criteria) this;
		}

		public Criteria andRequireConfirmationIsNotNull() {
			addCriterion("requireconfirmation is not null");
			return (Criteria) this;
		}

		public Criteria andRequireConfirmationEqualTo(Boolean value) {
			addCriterion("requireconfirmation =", value, "requireConfirmation");
			return (Criteria) this;
		}

		public Criteria andRequireConfirmationNotEqualTo(Boolean value) {
			addCriterion("requireconfirmation <>", value, "requireConfirmation");
			return (Criteria) this;
		}

		public Criteria andRequireConfirmationGreaterThan(Boolean value) {
			addCriterion("requireconfirmation >", value, "requireConfirmation");
			return (Criteria) this;
		}

		public Criteria andRequireConfirmationGreaterThanOrEqualTo(Boolean value) {
			addCriterion("requireconfirmation >=", value, "requireConfirmation");
			return (Criteria) this;
		}

		public Criteria andRequireConfirmationLessThan(Boolean value) {
			addCriterion("requireconfirmation <", value, "requireConfirmation");
			return (Criteria) this;
		}

		public Criteria andRequireConfirmationLessThanOrEqualTo(Boolean value) {
			addCriterion("requireconfirmation <=", value, "requireConfirmation");
			return (Criteria) this;
		}

		public Criteria andRequireConfirmationIn(List<Boolean> values) {
			addCriterion("requireconfirmation in", values,
					"requireConfirmation");
			return (Criteria) this;
		}

		public Criteria andRequireConfirmationNotIn(List<Boolean> values) {
			addCriterion("requireconfirmation not in", values,
					"requireConfirmation");
			return (Criteria) this;
		}

		public Criteria andRequireConfirmationBetween(Boolean value1,
				Boolean value2) {
			addCriterion("requireconfirmation between", value1, value2,
					"requireConfirmation");
			return (Criteria) this;
		}

		public Criteria andRequireConfirmationNotBetween(Boolean value1,
				Boolean value2) {
			addCriterion("requireconfirmation not between", value1, value2,
					"requireConfirmation");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table specialcircumstance
	 * @mbggenerated  Thu Jan 29 14:54:52 CST 2015
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table specialcircumstance
     *
     * @mbggenerated do_not_delete_during_merge Thu Jan 02 14:11:30 CST 2014
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}