package edu.ku.cete.domain;

import java.io.Serializable;

import edu.ku.cete.domain.audit.AuditableDomain;
import edu.ku.cete.domain.common.Category;
import edu.ku.cete.domain.content.TestSection;

public class StudentsTestSections extends AuditableDomain implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.studentstestsections.id
     *
     * @mbggenerated Wed Dec 12 15:45:42 CST 2012
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.studentstestsections.studentstestid
     *
     * @mbggenerated Wed Dec 12 15:45:42 CST 2012
     */
    private Long studentsTestId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.studentstestsections.testsectionid
     *
     * @mbggenerated Wed Dec 12 15:45:42 CST 2012
     */
    private Long testSectionId;
    
    /**
     * statusId.
     */
    private Long statusId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.studentstestsections.ticketno
     *
     * @mbggenerated Wed Dec 12 15:45:42 CST 2012
     */
    private String ticketNo;
    
    /**
     * studentsTests.
     */
    private StudentsTests studentsTests;

    private TestSection testSection;

	private Category status;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.studentstestsections
     *
     * @mbggenerated Wed Dec 12 15:45:42 CST 2012
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.studentstestsections.id
     *
     * @return the value of public.studentstestsections.id
     *
     * @mbggenerated Wed Dec 12 15:45:42 CST 2012
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.studentstestsections.id
     *
     * @param id the value for public.studentstestsections.id
     *
     * @mbggenerated Wed Dec 12 15:45:42 CST 2012
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.studentstestsections.studentstestid
     *
     * @return the value of public.studentstestsections.studentstestid
     *
     * @mbggenerated Wed Dec 12 15:45:42 CST 2012
     */
    public Long getStudentsTestId() {
        return studentsTestId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.studentstestsections.studentstestid
     *
     * @param studentsTestId the value for public.studentstestsections.studentstestid
     *
     * @mbggenerated Wed Dec 12 15:45:42 CST 2012
     */
    public void setStudentsTestId(Long studentsTestId) {
        this.studentsTestId = studentsTestId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.studentstestsections.testsectionid
     *
     * @return the value of public.studentstestsections.testsectionid
     *
     * @mbggenerated Wed Dec 12 15:45:42 CST 2012
     */
    public Long getTestSectionId() {
        return testSectionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.studentstestsections.testsectionid
     *
     * @param testSectionId the value for public.studentstestsections.testsectionid
     *
     * @mbggenerated Wed Dec 12 15:45:42 CST 2012
     */
    public void setTestSectionId(Long testSectionId) {
        this.testSectionId = testSectionId;
    }

    /**
	 * @return the statusId
	 */
	public Long getStatusId() {
		return statusId;
	}

	/**
	 * @param statusId the statusId to set
	 */
	public void setStatusId(Long statusId) {
		this.statusId = statusId;
	}

	/**
	 * @return the testSection
	 */
	public TestSection getTestSection() {
		return testSection;
	}

	/**
	 * @param testSection the testSection to set
	 */
	public void setTestSection(TestSection testSection) {
		this.testSection = testSection;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.studentstestsections.ticketno
     *
     * @return the value of public.studentstestsections.ticketno
     *
     * @mbggenerated Wed Dec 12 15:45:42 CST 2012
     */
    public String getTicketNo() {
        return ticketNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.studentstestsections.ticketno
     *
     * @param ticketNo the value for public.studentstestsections.ticketno
     *
     * @mbggenerated Wed Dec 12 15:45:42 CST 2012
     */
    public void setTicketNo(String ticketNo) {
        this.ticketNo = ticketNo == null ? null : ticketNo.trim();
    }

    
    /**
	 * @return the studentsTests
	 */
	public StudentsTests getStudentsTests() {
		return studentsTests;
	}

	/**
	 * @param studentsTests the studentsTests to set
	 */
	public void setStudentsTests(StudentsTests studentsTests) {
		this.studentsTests = studentsTests;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.studentstestsections
     *
     * @mbggenerated Wed Dec 12 15:45:42 CST 2012
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        StudentsTestSections other = (StudentsTestSections) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getStudentsTestId() == null ? other.getStudentsTestId() == null : this.getStudentsTestId().equals(other.getStudentsTestId()))
            && (this.getTestSectionId() == null ? other.getTestSectionId() == null : this.getTestSectionId().equals(other.getTestSectionId()))
            && (this.getTicketNo() == null ? other.getTicketNo() == null : this.getTicketNo().equals(other.getTicketNo()))
            && (this.getCreatedDate() == null ? other.getCreatedDate() == null : this.getCreatedDate().equals(other.getCreatedDate()))
            && (this.getCreatedUser() == null ? other.getCreatedUser() == null : this.getCreatedUser().equals(other.getCreatedUser()))
            && (this.getActiveFlag() == null ? other.getActiveFlag() == null : this.getActiveFlag().equals(other.getActiveFlag()))
            && (this.getModifiedUser() == null ? other.getModifiedUser() == null : this.getModifiedUser().equals(other.getModifiedUser()))
            && (this.getModifiedDate() == null ? other.getModifiedDate() == null : this.getModifiedDate().equals(other.getModifiedDate()));
    }
    /**
	 * @return the status
	 */
	public Category getStatus() {
		return status;
	}

	public void setStatus(Category status) {
		this.status = status;
	}
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.studentstestsections
     *
     * @mbggenerated Wed Dec 12 15:45:42 CST 2012
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getStudentsTestId() == null) ? 0 : getStudentsTestId().hashCode());
        result = prime * result + ((getTestSectionId() == null) ? 0 : getTestSectionId().hashCode());
        result = prime * result + ((getTicketNo() == null) ? 0 : getTicketNo().hashCode());
        result = prime * result + ((getCreatedDate() == null) ? 0 : getCreatedDate().hashCode());
        result = prime * result + ((getCreatedUser() == null) ? 0 : getCreatedUser().hashCode());
        result = prime * result + ((getActiveFlag() == null) ? 0 : getActiveFlag().hashCode());
        result = prime * result + ((getModifiedUser() == null) ? 0 : getModifiedUser().hashCode());
        result = prime * result + ((getModifiedDate() == null) ? 0 : getModifiedDate().hashCode());
        return result;
    }

	/* 
	 * toString is added because this object is used for communication with
	 * TDE services.
	 * (non-Javadoc)
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("StudentsTestSections [");
		if (id != null) {
			builder.append("id=");
			builder.append(id);
			builder.append(", ");
		}
		if (studentsTestId != null) {
			builder.append("studentsTestId=");
			builder.append(studentsTestId);
			builder.append(", ");
		}
		if (testSectionId != null) {
			builder.append("testSectionId=");
			builder.append(testSectionId);
			builder.append(", ");
		}
		if (statusId != null) {
			builder.append("statusId=");
			builder.append(statusId);
			builder.append(", ");
		}
		if (ticketNo != null) {
			builder.append("ticketNo=");
			builder.append(ticketNo);
			builder.append(", ");
		}
		if (studentsTests != null) {
			builder.append("studentsTests=");
			builder.append(studentsTests);
			builder.append(", ");
		}
		if (testSection != null) {
			builder.append("testSection=");
			builder.append(testSection);
			builder.append(", ");
		}
		if (status != null) {
			builder.append("status=");
			builder.append(status);
		}
		builder.append("]");
		return builder.toString();
	}

}