package edu.ku.cete.domain;

import java.util.Date;

import edu.ku.cete.domain.audit.AuditableDomain;

public class StudentTrackerBand extends AuditableDomain {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column studenttrackerband.id
	 * @mbggenerated  Thu Nov 19 12:00:48 CST 2015
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column studenttrackerband.studenttrackerid
	 * @mbggenerated  Thu Nov 19 12:00:48 CST 2015
	 */
	private Long studentTrackerId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column studenttrackerband.complexitybandid
	 * @mbggenerated  Thu Nov 19 12:00:48 CST 2015
	 */
	private Long complexityBandId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column studenttrackerband.testsessionid
	 * @mbggenerated  Thu Nov 19 12:00:48 CST 2015
	 */
	private Long testSessionId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column studenttrackerband.source
	 * @mbggenerated  Thu Nov 19 12:00:48 CST 2015
	 */
	private String source;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column studenttrackerband.activeflag
	 * @mbggenerated  Thu Nov 19 12:00:48 CST 2015
	 */
	private Boolean activeFlag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column studenttrackerband.createddate
	 * @mbggenerated  Thu Nov 19 12:00:48 CST 2015
	 */
	private Date createdDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column studenttrackerband.createduser
	 * @mbggenerated  Thu Nov 19 12:00:48 CST 2015
	 */
	private Long createdUser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column studenttrackerband.modifieddate
	 * @mbggenerated  Thu Nov 19 12:00:48 CST 2015
	 */
	private Date modifiedDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column studenttrackerband.modifieduser
	 * @mbggenerated  Thu Nov 19 12:00:48 CST 2015
	 */
	private Long modifiedUser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column studenttrackerband.essentialelementid
	 * @mbggenerated  Thu Nov 19 12:00:48 CST 2015
	 */
	private Long essentialElementId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column studenttrackerband.operationalwindowid
	 * @mbggenerated  Thu Nov 19 12:00:48 CST 2015
	 */
	private Long operationalWindowId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column studenttrackerband.id
	 * @return  the value of studenttrackerband.id
	 * @mbggenerated  Thu Nov 19 12:00:48 CST 2015
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column studenttrackerband.id
	 * @param id  the value for studenttrackerband.id
	 * @mbggenerated  Thu Nov 19 12:00:48 CST 2015
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column studenttrackerband.studenttrackerid
	 * @return  the value of studenttrackerband.studenttrackerid
	 * @mbggenerated  Thu Nov 19 12:00:48 CST 2015
	 */
	public Long getStudentTrackerId() {
		return studentTrackerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column studenttrackerband.studenttrackerid
	 * @param studentTrackerId  the value for studenttrackerband.studenttrackerid
	 * @mbggenerated  Thu Nov 19 12:00:48 CST 2015
	 */
	public void setStudentTrackerId(Long studentTrackerId) {
		this.studentTrackerId = studentTrackerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column studenttrackerband.complexitybandid
	 * @return  the value of studenttrackerband.complexitybandid
	 * @mbggenerated  Thu Nov 19 12:00:48 CST 2015
	 */
	public Long getComplexityBandId() {
		return complexityBandId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column studenttrackerband.complexitybandid
	 * @param complexityBandId  the value for studenttrackerband.complexitybandid
	 * @mbggenerated  Thu Nov 19 12:00:48 CST 2015
	 */
	public void setComplexityBandId(Long complexityBandId) {
		this.complexityBandId = complexityBandId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column studenttrackerband.testsessionid
	 * @return  the value of studenttrackerband.testsessionid
	 * @mbggenerated  Thu Nov 19 12:00:48 CST 2015
	 */
	public Long getTestSessionId() {
		return testSessionId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column studenttrackerband.testsessionid
	 * @param testSessionId  the value for studenttrackerband.testsessionid
	 * @mbggenerated  Thu Nov 19 12:00:48 CST 2015
	 */
	public void setTestSessionId(Long testSessionId) {
		this.testSessionId = testSessionId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column studenttrackerband.source
	 * @return  the value of studenttrackerband.source
	 * @mbggenerated  Thu Nov 19 12:00:48 CST 2015
	 */
	public String getSource() {
		return source;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column studenttrackerband.source
	 * @param source  the value for studenttrackerband.source
	 * @mbggenerated  Thu Nov 19 12:00:48 CST 2015
	 */
	public void setSource(String source) {
		this.source = source == null ? null : source.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column studenttrackerband.activeflag
	 * @return  the value of studenttrackerband.activeflag
	 * @mbggenerated  Thu Nov 19 12:00:48 CST 2015
	 */
	public Boolean getActiveFlag() {
		return activeFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column studenttrackerband.activeflag
	 * @param activeFlag  the value for studenttrackerband.activeflag
	 * @mbggenerated  Thu Nov 19 12:00:48 CST 2015
	 */
	public void setActiveFlag(Boolean activeFlag) {
		this.activeFlag = activeFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column studenttrackerband.createddate
	 * @return  the value of studenttrackerband.createddate
	 * @mbggenerated  Thu Nov 19 12:00:48 CST 2015
	 */
	public Date getCreatedDate() {
		return createdDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column studenttrackerband.createddate
	 * @param createdDate  the value for studenttrackerband.createddate
	 * @mbggenerated  Thu Nov 19 12:00:48 CST 2015
	 */
	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column studenttrackerband.createduser
	 * @return  the value of studenttrackerband.createduser
	 * @mbggenerated  Thu Nov 19 12:00:48 CST 2015
	 */
	public Long getCreatedUser() {
		return createdUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column studenttrackerband.createduser
	 * @param createdUser  the value for studenttrackerband.createduser
	 * @mbggenerated  Thu Nov 19 12:00:48 CST 2015
	 */
	public void setCreatedUser(Long createdUser) {
		this.createdUser = createdUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column studenttrackerband.modifieddate
	 * @return  the value of studenttrackerband.modifieddate
	 * @mbggenerated  Thu Nov 19 12:00:48 CST 2015
	 */
	public Date getModifiedDate() {
		return modifiedDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column studenttrackerband.modifieddate
	 * @param modifiedDate  the value for studenttrackerband.modifieddate
	 * @mbggenerated  Thu Nov 19 12:00:48 CST 2015
	 */
	public void setModifiedDate(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column studenttrackerband.modifieduser
	 * @return  the value of studenttrackerband.modifieduser
	 * @mbggenerated  Thu Nov 19 12:00:48 CST 2015
	 */
	public Long getModifiedUser() {
		return modifiedUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column studenttrackerband.modifieduser
	 * @param modifiedUser  the value for studenttrackerband.modifieduser
	 * @mbggenerated  Thu Nov 19 12:00:48 CST 2015
	 */
	public void setModifiedUser(Long modifiedUser) {
		this.modifiedUser = modifiedUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column studenttrackerband.essentialelementid
	 * @return  the value of studenttrackerband.essentialelementid
	 * @mbggenerated  Thu Nov 19 12:00:48 CST 2015
	 */
	public Long getEssentialElementId() {
		return essentialElementId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column studenttrackerband.essentialelementid
	 * @param essentialElementId  the value for studenttrackerband.essentialelementid
	 * @mbggenerated  Thu Nov 19 12:00:48 CST 2015
	 */
	public void setEssentialElementId(Long essentialElementId) {
		this.essentialElementId = essentialElementId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column studenttrackerband.operationalwindowid
	 * @return  the value of studenttrackerband.operationalwindowid
	 * @mbggenerated  Thu Nov 19 12:00:48 CST 2015
	 */
	public Long getOperationalWindowId() {
		return operationalWindowId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column studenttrackerband.operationalwindowid
	 * @param operationalWindowId  the value for studenttrackerband.operationalwindowid
	 * @mbggenerated  Thu Nov 19 12:00:48 CST 2015
	 */
	public void setOperationalWindowId(Long operationalWindowId) {
		this.operationalWindowId = operationalWindowId;
	}

	/**
	 * 
	 */
	private static final long serialVersionUID = -8622152916403151448L;
	private String essentialElementCode;
	private String testStatus;
	private Long studentTestId;
	private String contentAreaCode;

	public String getEssentialElementCode() {
		return essentialElementCode;
	}

	public void setEssentialElementCode(String essentialElementCode) {
		this.essentialElementCode = essentialElementCode;
	}

	public String getTestStatus() {
		return testStatus;
	}

	public void setTestStatus(String testStatus) {
		this.testStatus = testStatus;
	}

	public Long getStudentTestId() {
		return studentTestId;
	}

	public void setStudentTestId(Long studentTestId) {
		this.studentTestId = studentTestId;
	}

	public String getContentAreaCode() {
		return contentAreaCode;
	}

	public void setContentAreaCode(String contentAreaCode) {
		this.contentAreaCode = contentAreaCode;
	}
	
	private Long criteriaNumber;

	public Long getCriteriaNumber() {
		return criteriaNumber;
	}

	public void setCriteriaNumber(Long criteriaNumber) {
		this.criteriaNumber = criteriaNumber;
	}	

}