package edu.ku.cete.domain;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import edu.ku.cete.domain.professionaldevelopment.Module;
import edu.ku.cete.domain.user.User;
import edu.ku.cete.util.ParsingConstants;

public class UserModule {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usermodule.id
     *
     * @mbggenerated Sat Oct 19 18:56:34 CDT 2013
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usermodule.userid
     *
     * @mbggenerated Sat Oct 19 18:56:34 CDT 2013
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usermodule.moduleid
     *
     * @mbggenerated Sat Oct 19 18:56:34 CDT 2013
     */
    private Long moduleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usermodule.enrollmentstatusid
     *
     * @mbggenerated Sat Oct 19 18:56:34 CDT 2013
     */
    private Long enrollmentstatusid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usermodule.createddate
     *
     * @mbggenerated Sat Oct 19 18:56:34 CDT 2013
     */
    private Date createdDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usermodule.modifieddate
     *
     * @mbggenerated Sat Oct 19 18:56:34 CDT 2013
     */
    private Date modifiedDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usermodule.createduser
     *
     * @mbggenerated Sat Oct 19 18:56:34 CDT 2013
     */
    private Long createdUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usermodule.modifieduser
     *
     * @mbggenerated Sat Oct 19 18:56:34 CDT 2013
     */
    private Long modifiedUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usermodule.activeflag
     *
     * @mbggenerated Sat Oct 19 18:56:34 CDT 2013
     */
    private Boolean activeFlag;

    private Long stateId;
    
    private BigDecimal testFinalScore;
    
    private Boolean testResult;
    
    private Integer earnedCEU;
    
    private Date testCompletionDate;
    
    private Module module;
    
    private User user;
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usermodule.id
     *
     * @return the value of usermodule.id
     *
     * @mbggenerated Sat Oct 19 18:56:34 CDT 2013
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usermodule.id
     *
     * @param id the value for usermodule.id
     *
     * @mbggenerated Sat Oct 19 18:56:34 CDT 2013
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usermodule.userid
     *
     * @return the value of usermodule.userid
     *
     * @mbggenerated Sat Oct 19 18:56:34 CDT 2013
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usermodule.userid
     *
     * @param userId the value for usermodule.userid
     *
     * @mbggenerated Sat Oct 19 18:56:34 CDT 2013
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usermodule.moduleid
     *
     * @return the value of usermodule.moduleid
     *
     * @mbggenerated Sat Oct 19 18:56:34 CDT 2013
     */
    public Long getModuleId() {
        return moduleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usermodule.moduleid
     *
     * @param moduleId the value for usermodule.moduleid
     *
     * @mbggenerated Sat Oct 19 18:56:34 CDT 2013
     */
    public void setModuleId(Long moduleId) {
        this.moduleId = moduleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usermodule.enrollmentstatusid
     *
     * @return the value of usermodule.enrollmentstatusid
     *
     * @mbggenerated Sat Oct 19 18:56:34 CDT 2013
     */
    public Long getEnrollmentstatusid() {
        return enrollmentstatusid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usermodule.enrollmentstatusid
     *
     * @param enrollmentstatusid the value for usermodule.enrollmentstatusid
     *
     * @mbggenerated Sat Oct 19 18:56:34 CDT 2013
     */
    public void setEnrollmentstatusid(Long enrollmentstatusid) {
        this.enrollmentstatusid = enrollmentstatusid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usermodule.createddate
     *
     * @return the value of usermodule.createddate
     *
     * @mbggenerated Sat Oct 19 18:56:34 CDT 2013
     */
    public Date getCreatedDate() {
        return createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usermodule.createddate
     *
     * @param createdDate the value for usermodule.createddate
     *
     * @mbggenerated Sat Oct 19 18:56:34 CDT 2013
     */
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usermodule.modifieddate
     *
     * @return the value of usermodule.modifieddate
     *
     * @mbggenerated Sat Oct 19 18:56:34 CDT 2013
     */
    public Date getModifiedDate() {
        return modifiedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usermodule.modifieddate
     *
     * @param modifiedDate the value for usermodule.modifieddate
     *
     * @mbggenerated Sat Oct 19 18:56:34 CDT 2013
     */
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usermodule.createduser
     *
     * @return the value of usermodule.createduser
     *
     * @mbggenerated Sat Oct 19 18:56:34 CDT 2013
     */
    public Long getCreatedUser() {
        return createdUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usermodule.createduser
     *
     * @param createdUser the value for usermodule.createduser
     *
     * @mbggenerated Sat Oct 19 18:56:34 CDT 2013
     */
    public void setCreatedUser(Long createdUser) {
        this.createdUser = createdUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usermodule.modifieduser
     *
     * @return the value of usermodule.modifieduser
     *
     * @mbggenerated Sat Oct 19 18:56:34 CDT 2013
     */
    public Long getModifiedUser() {
        return modifiedUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usermodule.modifieduser
     *
     * @param modifiedUser the value for usermodule.modifieduser
     *
     * @mbggenerated Sat Oct 19 18:56:34 CDT 2013
     */
    public void setModifiedUser(Long modifiedUser) {
        this.modifiedUser = modifiedUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usermodule.activeflag
     *
     * @return the value of usermodule.activeflag
     *
     * @mbggenerated Sat Oct 19 18:56:34 CDT 2013
     */
    public Boolean getActiveFlag() {
        return activeFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usermodule.activeflag
     *
     * @param activeFlag the value for usermodule.activeflag
     *
     * @mbggenerated Sat Oct 19 18:56:34 CDT 2013
     */
    public void setActiveFlag(Boolean activeFlag) {
        this.activeFlag = activeFlag;
    }

	public Long getStateId() {
		return stateId;
	}

	public void setStateId(Long stateId) {
		this.stateId = stateId;
	}

	public Boolean getTestResult() {
		return testResult;
	}

	public void setTestResult(Boolean testResult) {
		this.testResult = testResult;
	}

	public Integer getEarnedCEU() {
		return earnedCEU;
	}

	public void setEarnedCEU(Integer earnedCEU) {
		this.earnedCEU = earnedCEU;
	}

	public Date getTestCompletionDate() {
		return testCompletionDate;
	}

	public void setTestCompletionDate(Date testCompletionDate) {
		this.testCompletionDate = testCompletionDate;
	}

	public BigDecimal getTestFinalScore() {
		return testFinalScore;
	}

	public void setTestFinalScore(BigDecimal testFinalScore) {
		this.testFinalScore = testFinalScore;
	}

	public Module getModule() {
		return module;
	}

	public void setModule(Module module) {
		this.module = module;
	}
		
	public User getUser() {
		return user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public List<String> buildTranscriptsJSONRow() {
		List<String> cells = new ArrayList<String>();
		
		//Setting  Actions(status) value		
		if(this.getModule().getId() != null) {
			cells.add(this.getModule().getId().toString());
		} else {
			cells.add(ParsingConstants.NOT_AVAILABLE);
		}
				
		//Setting Name value
		if(this.getModule().getName() !=  null) {
			cells.add(this.getModule().getName());
		} else {
			cells.add(ParsingConstants.NOT_AVAILABLE);
		}				

		if(this.getEarnedCEU() != null) {
			cells.add(this.getEarnedCEU().toString());
		} else {
			cells.add(ParsingConstants.NOT_AVAILABLE);
		}
		
		if(this.getTestCompletionDate() != null) {
			cells.add(this.getTestCompletionDate().toString());
		} else {
			cells.add(ParsingConstants.NOT_AVAILABLE);
		}
		
		if(this.getTestResult() != null) {
			if(this.getTestResult()){
				cells.add(ParsingConstants.BLANK + "Passed");
			} else {
				cells.add(ParsingConstants.BLANK + "Attempted");
			}
		} else {
			cells.add(ParsingConstants.NOT_AVAILABLE);
		}
		
		if(this.getModule().getRequiredflag() != null && this.getModule().getRequiredflag()) {
			cells.add(ParsingConstants.BLANK + "Yes");
		} else {
			cells.add(ParsingConstants.BLANK + "No");
		}	
		
		if(this.getUser() != null 
				&& this.getUser().getFirstName() != null) {
			cells.add(this.getUser().getFirstName() + " " + this.getUser().getSurName());
		} else {
			cells.add(ParsingConstants.NOT_AVAILABLE);
		}
		
		if(this.getUser() != null 
				&& this.getUser().getOrgName() != null) {
			cells.add(this.getUser().getOrgName());
		} else {
			cells.add(ParsingConstants.NOT_AVAILABLE);
		}		
		
		//Setting assessmentProgramName value
		if(this.getModule().getAssessmentProgramName() != null) {
			cells.add(this.getModule().getAssessmentProgramName());
		} else {
			cells.add(ParsingConstants.NOT_AVAILABLE);
		}
		
		return cells;
	}	
}