package edu.ku.cete.domain.enrollment;

import java.io.IOException;
import java.util.List;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.node.ArrayNode;
import com.fasterxml.jackson.databind.node.ObjectNode;

import edu.ku.cete.domain.content.ContentArea;
import edu.ku.cete.domain.content.GradeCourse;
import edu.ku.cete.domain.property.TraceableEntity;
import edu.ku.cete.domain.security.Restriction;
import edu.ku.cete.domain.user.User;

public class Roster extends TraceableEntity{
    /**
	 * 
	 */
	private static final long serialVersionUID = -3865795788747646697L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.roster.id
     *
     * @mbggenerated Mon May 07 11:35:01 CDT 2012
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.roster.course_section_name
     *
     * @mbggenerated Mon May 07 11:35:01 CDT 2012
     */
    private String courseSectionName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.roster.course_section_description
     *
     * @mbggenerated Mon May 07 11:35:01 CDT 2012
     */
    private String courseSectionDescription;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.roster.teacher_id
     *
     * @mbggenerated Mon May 07 11:35:01 CDT 2012
     */
    private Long teacherId;
    
    /**
     * attendanceSchoolId of the roster.
     */
    private Long attendanceSchoolId;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.roster.state_subject_area_id
     *
     * @mbggenerated Mon May 07 11:35:01 CDT 2012
     */
    private Long stateSubjectAreaId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.roster.course_enrollment_status_id
     *
     * @mbggenerated Mon May 07 11:35:01 CDT 2012
     */
    private Long courseEnrollmentStatusId;
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.roster.state_course_id
     *
     * @mbggenerated 
     */
    private String stateCourseCode;

    /**
     * restrictionId.
     */
    private Long restrictionId;

    /**
     * 
     */
    private List<Enrollment> enrollments;

    /**
     * 
     */
    private User teacher;

    /**
     * 
     */
    //private Category subject;
    private ContentArea subject;

	private Restriction restriction;
	
	/**
	 * stateSubjectCourseIdentifier
	 */
	private String stateSubjectCourseIdentifier;
	
	/**
	 * localCourseId
	 */
	private String localCourseId;
	
	/**
	 * educatorschooldisplayidentifier
	 */
	private String educatorschooldisplayidentifier;

	
	/**
	 * currentSchoolYear
	 */
	private int currentSchoolYear;
	
	private Long stateCoursesId;
	
	private GradeCourse course;
	
	private String schoolName;
	/**
	 * During Changed US16275
	 */
	private Long schoolId;
	
    private Integer totalRecords;
    
    private String educatorName;
	private String educatorId;
	private String subjectName;
	
	private Long classroomId;
	
	//private boolean activeflag;
    
    /**
	 *  rosterJsonString
	 */
    private String rosterJsonStr;
    /**
	 *  Source
	 */
    private Long source;

	/**
	 * @return the schoolId
	 */	
	public Long getSchoolId() {
		return schoolId;
	}
	
	/**
	 * @param schoolId the schoolId to set
	 */
	public void setSchoolId(Long schoolId) {
		this.schoolId = schoolId;
	}

	/**
	 * aypSchoolId
	 */
	private Long aypSchoolId;
	
	/**
	 * @return the aypSchoolId
	 */
	public Long getAypSchoolId() {
		return aypSchoolId;
	}
	/**
	 * @param aypSchoolId the aypSchoolId to set
	 */
	public void setAypSchoolId(Long aypSchoolId) {
		this.aypSchoolId = aypSchoolId;
	}
	/**
	 * @return the schoolName
	 */
	public String getSchoolName() {
		return schoolName;
	}
	/**
	 * @param schoolName the schoolName to set
	 */
	public void setSchoolName(String schoolName) {
		this.schoolName = schoolName;
	}
	/**
	 * @return the course
	 */
	public GradeCourse getCourse() {
		return course;
	}
	/**
	 * @param course the course to set
	 */
	public void setCourse(GradeCourse course) {
		this.course = course;
	}

	/**
	 * @return the stateCoursesId
	 */
	public Long getStateCoursesId() {
		return stateCoursesId;
	}
	/**
	 * @return the currentSchoolYear
	 */
	public int getCurrentSchoolYear() {
		return currentSchoolYear;
	}

	/**
	 * @param currentSchoolYear the currentSchoolYear to set
	 */
	public void setCurrentSchoolYear(int currentSchoolYear) {
		this.currentSchoolYear = currentSchoolYear;
	}


	/**
	/**
	 * @param stateCoursesId the stateCoursesId to set
	 */
	public void setStateCoursesId(Long stateCoursesId) {
		this.stateCoursesId = stateCoursesId;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.roster.id
     *
     * @return the value of public.roster.id
     *
     * @mbggenerated Mon May 07 11:35:01 CDT 2012
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.roster.id
     *
     * @param id the value for public.roster.id
     *
     * @mbggenerated Mon May 07 11:35:01 CDT 2012
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.roster.course_section_name
     *
     * @return the value of public.roster.course_section_name
     *
     * @mbggenerated Mon May 07 11:35:01 CDT 2012
     */
    public String getCourseSectionName() {
        return courseSectionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.roster.course_section_name
     *
     * @param courseSectionName the value for public.roster.course_section_name
     *
     * @mbggenerated Mon May 07 11:35:01 CDT 2012
     */
    public void setCourseSectionName(String courseSectionName) {
        this.courseSectionName = courseSectionName == null ? null : courseSectionName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.roster.course_section_description
     *
     * @return the value of public.roster.course_section_description
     *
     * @mbggenerated Mon May 07 11:35:01 CDT 2012
     */
    public String getCourseSectionDescription() {
        return courseSectionDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.roster.course_section_description
     *
     * @param courseSectionDescription the value for public.roster.course_section_description
     *
     * @mbggenerated Mon May 07 11:35:01 CDT 2012
     */
    public void setCourseSectionDescription(String courseSectionDescription) {
        this.courseSectionDescription = courseSectionDescription == null ? null : courseSectionDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.roster.teacher_id
     *
     * @return the value of public.roster.teacher_id
     *
     * @mbggenerated Mon May 07 11:35:01 CDT 2012
     */
    public Long getTeacherId() {
        return teacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.roster.teacher_id
     *
     * @param teacherId the value for public.roster.teacher_id
     *
     * @mbggenerated Mon May 07 11:35:01 CDT 2012
     */
    public void setTeacherId(Long teacherId) {
        this.teacherId = teacherId;
    }

    /**
	 * @return the restrictionId
	 */
	public Long getRestrictionId() {
		return restrictionId;
	}

	/**
	 * @param restrictionId the restrictionId to set
	 */
	public void setRestrictionId(Long restrictionId) {
		this.restrictionId = restrictionId;
	}
    /**
	 * @return the restriction {@link Restriction}
	 */
	public Restriction getRestriction() {
		return restriction;
	}

	/**
	 * @param restrict the restriction to set
	 */
	public void setRestriction(Restriction restrict) {
		this.restriction = restrict;
	}
	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.roster.state_subject_area_id
     *
     * @return the value of public.roster.state_subject_area_id
     *
     * @mbggenerated Mon May 07 11:35:01 CDT 2012
     */
    public Long getStateSubjectAreaId() {
        return stateSubjectAreaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.roster.state_subject_area_id
     *
     * @param stateSubjectAreaId the value for public.roster.state_subject_area_id
     *
     * @mbggenerated Mon May 07 11:35:01 CDT 2012
     */
    public void setStateSubjectAreaId(Long stateSubjectAreaId) {
        this.stateSubjectAreaId = stateSubjectAreaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.roster.course_enrollment_status_id
     *
     * @return the value of public.roster.course_enrollment_status_id
     *
     * @mbggenerated Mon May 07 11:35:01 CDT 2012
     */
    public Long getCourseEnrollmentStatusId() {
        return courseEnrollmentStatusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.roster.course_enrollment_status_id
     *
     * @param courseEnrollmentStatusId the value for public.roster.course_enrollment_status_id
     *
     * @mbggenerated Mon May 07 11:35:01 CDT 2012
     */
    public void setCourseEnrollmentStatusId(Long courseEnrollmentStatusId) {
        this.courseEnrollmentStatusId = courseEnrollmentStatusId;
    }


    /**
     * @return the students
     */
    public List<Enrollment> getEnrollments() {
        return enrollments;
    }

    /**
     * @param students the students to set
     */
    public void setStudents(List<Enrollment> enrollments) {
        this.enrollments = enrollments;
    }

    /**
     * @return the teacher
     */
    public User getTeacher() {
        return teacher;
    }

    /**
     * @param teacher the teacher to set
     */
    public void setTeacher(User teacher) {
        this.teacher = teacher;
    }

    /**
	 * @return the attendanceSchoolId
	 */
	public Long getAttendanceSchoolId() {
		return attendanceSchoolId;
	}

	/**
	 * @param attendanceSchoolId the attendanceSchoolId to set
	 */
	public void setAttendanceSchoolId(Long attendanceSchoolId) {
		this.attendanceSchoolId = attendanceSchoolId;
	}

	/**
     * @return the subject
     */
    public ContentArea getSubject() {
        return subject;
    }

    /**
     * @param subject the subject to set
     */
    public void setSubject(ContentArea subject) {
        this.subject = subject;
    }

	@Override
	public String getIdentifier() {
		// TODO Auto-generated method stub
		return null;
	}

	/**
	 * @return stateSubjectCourseIdentifier
	 */
	public String getStateSubjectCourseIdentifier() {
		return stateSubjectCourseIdentifier;
	}

	/**
	 * @param statesubjectcourseidentifier
	 */
	public void setStateSubjectCourseIdentifier(String stateSubjectCourseIdentifier) {
		this.stateSubjectCourseIdentifier = stateSubjectCourseIdentifier;
	}
	
	/**
	 * @return
	 */
	public String getLocalCourseId() {
		return localCourseId;
	}

	/**
	 * @param localCourseId
	 */
	public void setLocalCourseId(String localCourseId) {
		this.localCourseId = localCourseId;
	}
	
	/**
	 * @return
	 */
	public String getEducatorschooldisplayidentifier() {
		return educatorschooldisplayidentifier;
	}

	/**
	 * @param educatorschooldisplayidentifier
	 */
	public void setEducatorschooldisplayidentifier(String educatorschooldisplayidentifier) {
		this.educatorschooldisplayidentifier = educatorschooldisplayidentifier;
	}

	public String getStateCourseCode() {
		return stateCourseCode;
	}

	public void setStateCourseCode(String stateCourseCode) {
		this.stateCourseCode = stateCourseCode;
	}

	public Integer getTotalRecords() {
		return totalRecords;
	}

	public void setTotalRecords(Integer totalRecords) {
		this.totalRecords = totalRecords;
	}
	
	

	/**
	 * @return the educatorName
	 */
	public String getEducatorName() {
		return educatorName;
	}

	/**
	 * @param educatorName the educatorName to set
	 */
	public void setEducatorName(String educatorName) {
		this.educatorName = educatorName;
	}

	/**
	 * @return the educatorId
	 */
	public String getEducatorId() {
		return educatorId;
	}

	/**
	 * @param educatorId the educatorId to set
	 */
	public void setEducatorId(String educatorId) {
		this.educatorId = educatorId;
	}

	/**
	 * @return the subjectName
	 */
	public String getSubjectName() {
		return subjectName;
	}

	/**
	 * @param subjectName the subjectName to set
	 */
	public void setSubjectName(String subjectName) {
		this.subjectName = subjectName;
	}

	/*
	 * Udaya Kiran Jagana :Created for US18182 - For  Roster Json creation
	 * */
	public String buildJsonString(){
		try {
			
			ObjectMapper mapper = new ObjectMapper();
			//Create Object tree for roster object
			JsonNode root = mapper.createObjectNode();
			((ObjectNode)root).put( "rosterId",getId());
			((ObjectNode)root).put( "RosterName",getCourseSectionName()== null?  "" :getCourseSectionName());
			((ObjectNode)root).put( "Subject",getSubject() == null?  "  " :getSubject().getName());
			((ObjectNode)root).put( "Course",getCourse() == null?  "  " :getCourse().getName());
			((ObjectNode)root).put( "EducatorFirstName",getTeacher().getFirstName());
			((ObjectNode)root).put( "EducatorLastName",getTeacher().getSurName());			
			((ObjectNode)root).put( "EducatorID",getTeacher().getId());			
			ArrayNode enrollmentArrayNode = mapper.createArrayNode();			
			for (Enrollment enrollment: getEnrollments()) {
					//Creating new json object for each Student
					ObjectNode StudentNode = mapper.createObjectNode();
					StudentNode.put("StudentFirstName",enrollment.getStudent().getLegalFirstName());
					StudentNode.put("StudentLastName",enrollment.getStudent().getLegalLastName());
					StudentNode.put("StudentStateID",enrollment.getStudent().getStateStudentIdentifier());					
					//Add created roles object to Student array 	
					enrollmentArrayNode.add(StudentNode);						
			}
			((ObjectNode)root).set("Students", enrollmentArrayNode);
			((ObjectNode)root).put( "Source",getSourceType());
			((ObjectNode)root).put( "CreatedDate",getCreatedDate() == null?  "  " :getCreatedDate().toString());
			((ObjectNode)root).put( "Createduser",getCreatedUser());			
			((ObjectNode)root).put( "ModifiedDate",getModifiedDate() == null?  "  " :getModifiedDate().toString());
			((ObjectNode)root).put( "ModifiedUser",getModifiedUser());			
			rosterJsonStr = mapper.writeValueAsString(root);	
		
	}catch (JsonProcessingException e) {
		e.printStackTrace();
	} catch (IOException e) {
		e.printStackTrace();
	}	
		return rosterJsonStr;
}

	public String getRosterJsonStr() {
		return rosterJsonStr;
	}

	public void setRosterJsonStr(String rosterJsonStr) {
		this.rosterJsonStr = rosterJsonStr;
	}

	public Long getSource() {
		return source;
	}

	public void setSource(Long source) {
		this.source = source;
	}

	public Long getClassroomId() {
		return classroomId;
	}

	public void setClassroomId(Long classroomId) {
		this.classroomId = classroomId;
	}
		}
