package edu.ku.cete.domain.professionaldevelopment;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import edu.ku.cete.util.ParsingConstants;
import edu.ku.cete.util.DataReportTypeEnum;

public class ModuleReport implements Comparable<ModuleReport>{

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column modulereport.id
	 * @mbggenerated  Wed Nov 26 16:52:40 CST 2014
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column modulereport.groupid
	 * @mbggenerated  Wed Nov 26 16:52:40 CST 2014
	 */
	private Long groupId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column modulereport.reporttype
	 * @mbggenerated  Wed Nov 26 16:52:40 CST 2014
	 */
	private String reportType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column modulereport.description
	 * @mbggenerated  Wed Nov 26 16:52:40 CST 2014
	 */
	private String description;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column modulereport.stateid
	 * @mbggenerated  Wed Nov 26 16:52:40 CST 2014
	 */
	private Long stateId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column modulereport.statusid
	 * @mbggenerated  Wed Nov 26 16:52:40 CST 2014
	 */
	private Long statusId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column modulereport.filename
	 * @mbggenerated  Wed Nov 26 16:52:40 CST 2014
	 */
	private String fileName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column modulereport.activeflag
	 * @mbggenerated  Wed Nov 26 16:52:40 CST 2014
	 */
	private Boolean activeFlag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column modulereport.createduser
	 * @mbggenerated  Wed Nov 26 16:52:40 CST 2014
	 */
	private Integer createdUser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column modulereport.createddate
	 * @mbggenerated  Wed Nov 26 16:52:40 CST 2014
	 */
	private Date createdDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column modulereport.modifieduser
	 * @mbggenerated  Wed Nov 26 16:52:40 CST 2014
	 */
	private Integer modifiedUser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column modulereport.modifieddate
	 * @mbggenerated  Wed Nov 26 16:52:40 CST 2014
	 */
	private Date modifiedDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column modulereport.reporttypeid
	 * @mbggenerated  Wed Nov 26 16:52:40 CST 2014
	 */
	private Short reportTypeId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column modulereport.organizationid
	 * @mbggenerated  Wed Nov 26 16:52:40 CST 2014
	 */
	private Long organizationId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column modulereport.organizationtypeid
	 * @mbggenerated  Wed Nov 26 16:52:40 CST 2014
	 */
	private Long organizationTypeId;

	private String jsonData;

	private Date startTime;
	
	
    
	   private Long extractTypeId;
	    private String dataDetailFileName;
	    private String dataDetailFileLocation;
	    private String specialDataDetailFileLocation;
	    private String specialDataDetailFileName;
	    private boolean dataDetailActiveFlag;
	    private boolean specialDataDetailActiveFlag;
	    private String pdfFileName;
	
	
		

		

	/**
		 * @return the extractTypeId
		 */
		public Long getExtractTypeId() {
			return extractTypeId;
		}

		/**
		 * @param extractTypeId the extractTypeId to set
		 */
		public void setExtractTypeId(Long extractTypeId) {
			this.extractTypeId = extractTypeId;
		}

		/**
		 * @return the dataDetailFileName
		 */
		public String getDataDetailFileName() {
			return dataDetailFileName;
		}

		/**
		 * @param dataDetailFileName the dataDetailFileName to set
		 */
		public void setDataDetailFileName(String dataDetailFileName) {
			this.dataDetailFileName = dataDetailFileName;
		}

		/**
		 * @return the dataDetailFileLocation
		 */
		public String getDataDetailFileLocation() {
			return dataDetailFileLocation;
		}

		/**
		 * @param dataDetailFileLocation the dataDetailFileLocation to set
		 */
		public void setDataDetailFileLocation(String dataDetailFileLocation) {
			this.dataDetailFileLocation = dataDetailFileLocation;
		}

		/**
		 * @return the specialDataDetailFileLocation
		 */
		public String getSpecialDataDetailFileLocation() {
			return specialDataDetailFileLocation;
		}

		/**
		 * @param specialDataDetailFileLocation the specialDataDetailFileLocation to set
		 */
		public void setSpecialDataDetailFileLocation(
				String specialDataDetailFileLocation) {
			this.specialDataDetailFileLocation = specialDataDetailFileLocation;
		}

		/**
		 * @return the specialDataDetailFileName
		 */
		public String getSpecialDataDetailFileName() {
			return specialDataDetailFileName;
		}

		/**
		 * @param specialDataDetailFileName the specialDataDetailFileName to set
		 */
		public void setSpecialDataDetailFileName(String specialDataDetailFileName) {
			this.specialDataDetailFileName = specialDataDetailFileName;
		}

		

	/**
		 * @return the dataDetailActiveFlag
		 */
		public boolean isDataDetailActiveFlag() {
			return dataDetailActiveFlag;
		}

		/**
		 * @param dataDetailActiveFlag the dataDetailActiveFlag to set
		 */
		public void setDataDetailActiveFlag(boolean dataDetailActiveFlag) {
			this.dataDetailActiveFlag = dataDetailActiveFlag;
		}

		/**
		 * @return the specialDataDetailActiveFlag
		 */
		public boolean isSpecialDataDetailActiveFlag() {
			return specialDataDetailActiveFlag;
		}

		/**
		 * @param specialDataDetailActiveFlag the specialDataDetailActiveFlag to set
		 */
		public void setSpecialDataDetailActiveFlag(boolean specialDataDetailActiveFlag) {
			this.specialDataDetailActiveFlag = specialDataDetailActiveFlag;
		}

	public String getJsonData() {
		return jsonData;
	}

	public void setJsonData(String jsonData) {
		this.jsonData = jsonData == null ? null : jsonData.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column modulereport.id
	 * @return  the value of modulereport.id
	 * @mbggenerated  Wed Nov 26 16:52:40 CST 2014
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column modulereport.id
	 * @param id  the value for modulereport.id
	 * @mbggenerated  Wed Nov 26 16:52:40 CST 2014
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column modulereport.groupid
	 * @return  the value of modulereport.groupid
	 * @mbggenerated  Wed Nov 26 16:52:40 CST 2014
	 */
	public Long getGroupId() {
		return groupId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column modulereport.groupid
	 * @param groupId  the value for modulereport.groupid
	 * @mbggenerated  Wed Nov 26 16:52:40 CST 2014
	 */
	public void setGroupId(Long groupId) {
		this.groupId = groupId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column modulereport.reporttype
	 * @return  the value of modulereport.reporttype
	 * @mbggenerated  Wed Nov 26 16:52:40 CST 2014
	 */
	public String getReportType() {
		return reportType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column modulereport.reporttype
	 * @param reportType  the value for modulereport.reporttype
	 * @mbggenerated  Wed Nov 26 16:52:40 CST 2014
	 */
	public void setReportType(String reportType) {
		this.reportType = reportType == null ? null : reportType.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column modulereport.description
	 * @return  the value of modulereport.description
	 * @mbggenerated  Wed Nov 26 16:52:40 CST 2014
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column modulereport.description
	 * @param description  the value for modulereport.description
	 * @mbggenerated  Wed Nov 26 16:52:40 CST 2014
	 */
	public void setDescription(String description) {
		this.description = description == null ? null : description.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column modulereport.stateid
	 * @return  the value of modulereport.stateid
	 * @mbggenerated  Wed Nov 26 16:52:40 CST 2014
	 */
	public Long getStateId() {
		return stateId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column modulereport.stateid
	 * @param stateId  the value for modulereport.stateid
	 * @mbggenerated  Wed Nov 26 16:52:40 CST 2014
	 */
	public void setStateId(Long stateId) {
		this.stateId = stateId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column modulereport.statusid
	 * @return  the value of modulereport.statusid
	 * @mbggenerated  Wed Nov 26 16:52:40 CST 2014
	 */
	public Long getStatusId() {
		return statusId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column modulereport.statusid
	 * @param statusId  the value for modulereport.statusid
	 * @mbggenerated  Wed Nov 26 16:52:40 CST 2014
	 */
	public void setStatusId(Long statusId) {
		this.statusId = statusId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column modulereport.filename
	 * @return  the value of modulereport.filename
	 * @mbggenerated  Wed Nov 26 16:52:40 CST 2014
	 */
	public String getFileName() {
		return fileName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column modulereport.filename
	 * @param fileName  the value for modulereport.filename
	 * @mbggenerated  Wed Nov 26 16:52:40 CST 2014
	 */
	public void setFileName(String fileName) {
		this.fileName = fileName == null ? null : fileName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column modulereport.activeflag
	 * @return  the value of modulereport.activeflag
	 * @mbggenerated  Wed Nov 26 16:52:40 CST 2014
	 */
	public Boolean getActiveFlag() {
		return activeFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column modulereport.activeflag
	 * @param activeFlag  the value for modulereport.activeflag
	 * @mbggenerated  Wed Nov 26 16:52:40 CST 2014
	 */
	public void setActiveFlag(Boolean activeFlag) {
		this.activeFlag = activeFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column modulereport.createduser
	 * @return  the value of modulereport.createduser
	 * @mbggenerated  Wed Nov 26 16:52:40 CST 2014
	 */
	public Integer getCreatedUser() {
		return createdUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column modulereport.createduser
	 * @param createdUser  the value for modulereport.createduser
	 * @mbggenerated  Wed Nov 26 16:52:40 CST 2014
	 */
	public void setCreatedUser(Integer createdUser) {
		this.createdUser = createdUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column modulereport.createddate
	 * @return  the value of modulereport.createddate
	 * @mbggenerated  Wed Nov 26 16:52:40 CST 2014
	 */
	public Date getCreatedDate() {
		return createdDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column modulereport.createddate
	 * @param createdDate  the value for modulereport.createddate
	 * @mbggenerated  Wed Nov 26 16:52:40 CST 2014
	 */
	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column modulereport.modifieduser
	 * @return  the value of modulereport.modifieduser
	 * @mbggenerated  Wed Nov 26 16:52:40 CST 2014
	 */
	public Integer getModifiedUser() {
		return modifiedUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column modulereport.modifieduser
	 * @param modifiedUser  the value for modulereport.modifieduser
	 * @mbggenerated  Wed Nov 26 16:52:40 CST 2014
	 */
	public void setModifiedUser(Integer modifiedUser) {
		this.modifiedUser = modifiedUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column modulereport.modifieddate
	 * @return  the value of modulereport.modifieddate
	 * @mbggenerated  Wed Nov 26 16:52:40 CST 2014
	 */
	public Date getModifiedDate() {
		return modifiedDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column modulereport.modifieddate
	 * @param modifiedDate  the value for modulereport.modifieddate
	 * @mbggenerated  Wed Nov 26 16:52:40 CST 2014
	 */
	public void setModifiedDate(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column modulereport.reporttypeid
	 * @return  the value of modulereport.reporttypeid
	 * @mbggenerated  Wed Nov 26 16:52:40 CST 2014
	 */
	public Short getReportTypeId() {
		return reportTypeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column modulereport.reporttypeid
	 * @param reportTypeId  the value for modulereport.reporttypeid
	 * @mbggenerated  Wed Nov 26 16:52:40 CST 2014
	 */
	public void setReportTypeId(Short reportTypeId) {
		this.reportTypeId = reportTypeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column modulereport.organizationid
	 * @return  the value of modulereport.organizationid
	 * @mbggenerated  Wed Nov 26 16:52:40 CST 2014
	 */
	public Long getOrganizationId() {
		return organizationId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column modulereport.organizationid
	 * @param organizationId  the value for modulereport.organizationid
	 * @mbggenerated  Wed Nov 26 16:52:40 CST 2014
	 */
	public void setOrganizationId(Long organizationId) {
		this.organizationId = organizationId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column modulereport.organizationtypeid
	 * @return  the value of modulereport.organizationtypeid
	 * @mbggenerated  Wed Nov 26 16:52:40 CST 2014
	 */
	public Long getOrganizationTypeId() {
		return organizationTypeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column modulereport.organizationtypeid
	 * @param organizationTypeId  the value for modulereport.organizationtypeid
	 * @mbggenerated  Wed Nov 26 16:52:40 CST 2014
	 */
	public void setOrganizationTypeId(Long organizationTypeId) {
		this.organizationTypeId = organizationTypeId;
	}

	public Date getStartTime() {
		return startTime;
	}

	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}



	private String statusName;
	
	private boolean queued;
	
	
	
	public boolean isQueued() {
		return queued;
	}

	public void setQueued(boolean queued) {
		this.queued = queued;
	}

	public String getStatusName() {
		return statusName;
	}

	public void setStatusName(String statusName) {
		this.statusName = statusName;
	}

	public String getPdfFileName() {
		return pdfFileName;
	}

	public void setPdfFileName(String pdfFileName) {
		this.pdfFileName = pdfFileName;
	}
	public List<String> buildAdminReportsJSONRow() {
		List<String> cells = new ArrayList<String>();
		
		//Setting  id hidden column value		
		if(this.getId() != null) {
			cells.add(this.getId().toString());
		} else {
			cells.add(ParsingConstants.NOT_AVAILABLE);
		}
				
		//Setting Name value
		if(this.getReportType() !=  null) {
			cells.add(this.getReportType());
		} else {
			cells.add(ParsingConstants.NOT_AVAILABLE);
		}				

		if(this.getDescription() != null) {
			cells.add(this.getDescription().toString());
		} else {
			cells.add(ParsingConstants.NOT_AVAILABLE);
		}
		
		if(this.getCreatedDate() != null) {
			cells.add(this.getCreatedDate().toString());
		} else {
			cells.add(ParsingConstants.NOT_AVAILABLE);
		}
		
		if(this.getFileName() != null) {
			cells.add(this.getFileName());
		} else {
			cells.add(ParsingConstants.NOT_AVAILABLE);
		}
		
		if(this.getStatusName() != null) {
			cells.add(this.getStatusName());
		} else {
			cells.add(ParsingConstants.NOT_AVAILABLE);
		}	
		
		cells.add(ParsingConstants.NOT_AVAILABLE);
		
		return cells;
	}	
	
	public List<String> buildEmptyAdminReportsJSONRow() {
		List<String> cells = new ArrayList<String>();
		
		//Setting  id hidden column value		
		cells.add("-1");
		cells.add("Training Status");
		cells.add("Training status by user for required and optional modules");
		cells.add(ParsingConstants.BLANK);
		cells.add(ParsingConstants.BLANK);
		cells.add(ParsingConstants.BLANK);
		cells.add(ParsingConstants.NOT_AVAILABLE);
		
		
		return cells;
	}
	
	public List<String> buildEmptyAdminReportDetailsJSONRow() {
		List<String> cells = new ArrayList<String>();
		
		//Setting  id hidden column value		
		cells.add("-1");
		cells.add("Training Details");
		cells.add("Details by user and module. Facilitated training responses are provided by required modules.");
		cells.add(ParsingConstants.BLANK);
		cells.add(ParsingConstants.BLANK);
		cells.add(ParsingConstants.BLANK);
		cells.add(ParsingConstants.NOT_AVAILABLE);
		
		
		return cells;
	}
	
	
	public List<String> buildEmptyAdminReportStatusJSONRow() {
		List<String> cells = new ArrayList<String>();
		
		//Setting  id hidden column value		
		cells.add("-1");
		cells.add("Training Status");
		cells.add("Training status by user for required and optional modules");
		cells.add(ParsingConstants.BLANK);
		cells.add(ParsingConstants.BLANK);
		cells.add(ParsingConstants.BLANK);
		cells.add(ParsingConstants.NOT_AVAILABLE);
		
		
		return cells;
	}
	public List<String> buildEmptyExportDLMUsersJSONRow() {
		List<String> cells = new ArrayList<String>();
		
		//Setting  id hidden column value		
		cells.add("-1");
		cells.add("DLM PD Training List");
		cells.add("List of all DLM users eligible for PD training");
		cells.add(ParsingConstants.BLANK);
		cells.add(ParsingConstants.BLANK);
		cells.add(ParsingConstants.BLANK);
		cells.add(ParsingConstants.NOT_AVAILABLE);
		
		
		return cells;
	}
	
	public static List<String> buildEmptyJSONRow(DataReportTypeEnum type) {
		List<String> cells = new ArrayList<String>();
		
		cells.add("-1");
		cells.add(""+type.getId());
		cells.add(type.getName());
		cells.add(type.getDescription());
		cells.add(ParsingConstants.BLANK);
		cells.add(ParsingConstants.BLANK);
		cells.add(ParsingConstants.BLANK);
		cells.add(ParsingConstants.NOT_AVAILABLE);
		cells.add(type.getDataDetailFileLocation());
		cells.add(type.getDataDetailFileName());
		cells.add(type.getSpecialDataDetailFileLocation());
		cells.add(type.getSpecialDataDetailFileName());	
		cells.add(""+type.isDataDetailActiveFlag());
		cells.add(""+type.isSpecialDataDetailActiveFlag());
		cells.add(type.getQueued());
		cells.add(ParsingConstants.BLANK);
		
		return cells;
	}

	public List<String> buildDataReportsJSONRow() {
		List<String> cells = new ArrayList<String>();
		DataReportTypeEnum type = DataReportTypeEnum.getById(this.getReportTypeId());
		
		cells.add(this.getId().toString());
		cells.add(type.getId().toString());
		cells.add(type.getName());
		cells.add(type.getDescription());
		
		if(this.getCreatedDate() != null) {
			cells.add(Long.valueOf(this.getCreatedDate().getTime()).toString());
		} else {
			cells.add(ParsingConstants.NOT_AVAILABLE);
		}
		
		if(this.getFileName() != null) {
			cells.add(this.getFileName());
		} else {
			cells.add(ParsingConstants.NOT_AVAILABLE);
		}
		
		if(this.getStatusName() != null) {
			cells.add(this.getStatusName());
		} else {
			cells.add(ParsingConstants.NOT_AVAILABLE);
		}	
		
		cells.add(ParsingConstants.NOT_AVAILABLE);
		
		if(this.getDataDetailFileLocation() !=null){
			cells.add(this.getDataDetailFileLocation());
		}else{
			cells.add(ParsingConstants.NOT_AVAILABLE);
		}
		if(this.getDataDetailFileName() !=null){
			cells.add(this.getDataDetailFileName());
		}else{
			cells.add(ParsingConstants.NOT_AVAILABLE);
		}
		if(this.getSpecialDataDetailFileLocation() !=null){
			cells.add(this.getSpecialDataDetailFileLocation());
		}else{
			cells.add(ParsingConstants.NOT_AVAILABLE);
		}
		if(this.getSpecialDataDetailFileName() !=null){
			cells.add(this.getSpecialDataDetailFileName());
		}else{
			cells.add(ParsingConstants.NOT_AVAILABLE);
		}
		cells.add(""+this.isDataDetailActiveFlag());
		cells.add(""+this.isSpecialDataDetailActiveFlag());
		cells.add(type.getQueued());
		if(this.getPdfFileName() != null) {
			cells.add(this.getPdfFileName());
		} else {
			cells.add(ParsingConstants.NOT_AVAILABLE);
		}
		return cells;
	}

	@Override
	public int compareTo(ModuleReport o) {
		return this.getCreatedDate().compareTo(o.getCreatedDate());
	}

}