package edu.ku.cete.domain.professionaldevelopment;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class ProportionMetricsExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table proportionmetrics
     *
     * @mbggenerated Thu Nov 20 01:30:46 CST 2014
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table proportionmetrics
     *
     * @mbggenerated Thu Nov 20 01:30:46 CST 2014
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table proportionmetrics
     *
     * @mbggenerated Thu Nov 20 01:30:46 CST 2014
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proportionmetrics
     *
     * @mbggenerated Thu Nov 20 01:30:46 CST 2014
     */
    public ProportionMetricsExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proportionmetrics
     *
     * @mbggenerated Thu Nov 20 01:30:46 CST 2014
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proportionmetrics
     *
     * @mbggenerated Thu Nov 20 01:30:46 CST 2014
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proportionmetrics
     *
     * @mbggenerated Thu Nov 20 01:30:46 CST 2014
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proportionmetrics
     *
     * @mbggenerated Thu Nov 20 01:30:46 CST 2014
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proportionmetrics
     *
     * @mbggenerated Thu Nov 20 01:30:46 CST 2014
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proportionmetrics
     *
     * @mbggenerated Thu Nov 20 01:30:46 CST 2014
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proportionmetrics
     *
     * @mbggenerated Thu Nov 20 01:30:46 CST 2014
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proportionmetrics
     *
     * @mbggenerated Thu Nov 20 01:30:46 CST 2014
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proportionmetrics
     *
     * @mbggenerated Thu Nov 20 01:30:46 CST 2014
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proportionmetrics
     *
     * @mbggenerated Thu Nov 20 01:30:46 CST 2014
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table proportionmetrics
     *
     * @mbggenerated Thu Nov 20 01:30:46 CST 2014
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andGradeIdIsNull() {
            addCriterion("gradeid is null");
            return (Criteria) this;
        }

        public Criteria andGradeIdIsNotNull() {
            addCriterion("gradeid is not null");
            return (Criteria) this;
        }

        public Criteria andGradeIdEqualTo(Long value) {
            addCriterion("gradeid =", value, "gradeId");
            return (Criteria) this;
        }

        public Criteria andGradeIdNotEqualTo(Long value) {
            addCriterion("gradeid <>", value, "gradeId");
            return (Criteria) this;
        }

        public Criteria andGradeIdGreaterThan(Long value) {
            addCriterion("gradeid >", value, "gradeId");
            return (Criteria) this;
        }

        public Criteria andGradeIdGreaterThanOrEqualTo(Long value) {
            addCriterion("gradeid >=", value, "gradeId");
            return (Criteria) this;
        }

        public Criteria andGradeIdLessThan(Long value) {
            addCriterion("gradeid <", value, "gradeId");
            return (Criteria) this;
        }

        public Criteria andGradeIdLessThanOrEqualTo(Long value) {
            addCriterion("gradeid <=", value, "gradeId");
            return (Criteria) this;
        }

        public Criteria andGradeIdIn(List<Long> values) {
            addCriterion("gradeid in", values, "gradeId");
            return (Criteria) this;
        }

        public Criteria andGradeIdNotIn(List<Long> values) {
            addCriterion("gradeid not in", values, "gradeId");
            return (Criteria) this;
        }

        public Criteria andGradeIdBetween(Long value1, Long value2) {
            addCriterion("gradeid between", value1, value2, "gradeId");
            return (Criteria) this;
        }

        public Criteria andGradeIdNotBetween(Long value1, Long value2) {
            addCriterion("gradeid not between", value1, value2, "gradeId");
            return (Criteria) this;
        }

        public Criteria andConceptualAreaIdIsNull() {
            addCriterion("conceptualareaid is null");
            return (Criteria) this;
        }

        public Criteria andConceptualAreaIdIsNotNull() {
            addCriterion("conceptualareaid is not null");
            return (Criteria) this;
        }

        public Criteria andConceptualAreaIdEqualTo(Long value) {
            addCriterion("conceptualareaid =", value, "conceptualAreaId");
            return (Criteria) this;
        }

        public Criteria andConceptualAreaIdNotEqualTo(Long value) {
            addCriterion("conceptualareaid <>", value, "conceptualAreaId");
            return (Criteria) this;
        }

        public Criteria andConceptualAreaIdGreaterThan(Long value) {
            addCriterion("conceptualareaid >", value, "conceptualAreaId");
            return (Criteria) this;
        }

        public Criteria andConceptualAreaIdGreaterThanOrEqualTo(Long value) {
            addCriterion("conceptualareaid >=", value, "conceptualAreaId");
            return (Criteria) this;
        }

        public Criteria andConceptualAreaIdLessThan(Long value) {
            addCriterion("conceptualareaid <", value, "conceptualAreaId");
            return (Criteria) this;
        }

        public Criteria andConceptualAreaIdLessThanOrEqualTo(Long value) {
            addCriterion("conceptualareaid <=", value, "conceptualAreaId");
            return (Criteria) this;
        }

        public Criteria andConceptualAreaIdIn(List<Long> values) {
            addCriterion("conceptualareaid in", values, "conceptualAreaId");
            return (Criteria) this;
        }

        public Criteria andConceptualAreaIdNotIn(List<Long> values) {
            addCriterion("conceptualareaid not in", values, "conceptualAreaId");
            return (Criteria) this;
        }

        public Criteria andConceptualAreaIdBetween(Long value1, Long value2) {
            addCriterion("conceptualareaid between", value1, value2, "conceptualAreaId");
            return (Criteria) this;
        }

        public Criteria andConceptualAreaIdNotBetween(Long value1, Long value2) {
            addCriterion("conceptualareaid not between", value1, value2, "conceptualAreaId");
            return (Criteria) this;
        }

        public Criteria andEssentialElementIdIsNull() {
            addCriterion("essentialelementid is null");
            return (Criteria) this;
        }

        public Criteria andEssentialElementIdIsNotNull() {
            addCriterion("essentialelementid is not null");
            return (Criteria) this;
        }

        public Criteria andEssentialElementIdEqualTo(Long value) {
            addCriterion("essentialelementid =", value, "essentialElementId");
            return (Criteria) this;
        }

        public Criteria andEssentialElementIdNotEqualTo(Long value) {
            addCriterion("essentialelementid <>", value, "essentialElementId");
            return (Criteria) this;
        }

        public Criteria andEssentialElementIdGreaterThan(Long value) {
            addCriterion("essentialelementid >", value, "essentialElementId");
            return (Criteria) this;
        }

        public Criteria andEssentialElementIdGreaterThanOrEqualTo(Long value) {
            addCriterion("essentialelementid >=", value, "essentialElementId");
            return (Criteria) this;
        }

        public Criteria andEssentialElementIdLessThan(Long value) {
            addCriterion("essentialelementid <", value, "essentialElementId");
            return (Criteria) this;
        }

        public Criteria andEssentialElementIdLessThanOrEqualTo(Long value) {
            addCriterion("essentialelementid <=", value, "essentialElementId");
            return (Criteria) this;
        }

        public Criteria andEssentialElementIdIn(List<Long> values) {
            addCriterion("essentialelementid in", values, "essentialElementId");
            return (Criteria) this;
        }

        public Criteria andEssentialElementIdNotIn(List<Long> values) {
            addCriterion("essentialelementid not in", values, "essentialElementId");
            return (Criteria) this;
        }

        public Criteria andEssentialElementIdBetween(Long value1, Long value2) {
            addCriterion("essentialelementid between", value1, value2, "essentialElementId");
            return (Criteria) this;
        }

        public Criteria andEssentialElementIdNotBetween(Long value1, Long value2) {
            addCriterion("essentialelementid not between", value1, value2, "essentialElementId");
            return (Criteria) this;
        }

        public Criteria andConceptualAreaIsNull() {
            addCriterion("conceptualarea is null");
            return (Criteria) this;
        }

        public Criteria andConceptualAreaIsNotNull() {
            addCriterion("conceptualarea is not null");
            return (Criteria) this;
        }

        public Criteria andConceptualAreaEqualTo(String value) {
            addCriterion("conceptualarea =", value, "conceptualArea");
            return (Criteria) this;
        }

        public Criteria andConceptualAreaNotEqualTo(String value) {
            addCriterion("conceptualarea <>", value, "conceptualArea");
            return (Criteria) this;
        }

        public Criteria andConceptualAreaGreaterThan(String value) {
            addCriterion("conceptualarea >", value, "conceptualArea");
            return (Criteria) this;
        }

        public Criteria andConceptualAreaGreaterThanOrEqualTo(String value) {
            addCriterion("conceptualarea >=", value, "conceptualArea");
            return (Criteria) this;
        }

        public Criteria andConceptualAreaLessThan(String value) {
            addCriterion("conceptualarea <", value, "conceptualArea");
            return (Criteria) this;
        }

        public Criteria andConceptualAreaLessThanOrEqualTo(String value) {
            addCriterion("conceptualarea <=", value, "conceptualArea");
            return (Criteria) this;
        }

        public Criteria andConceptualAreaLike(String value) {
            addCriterion("conceptualarea like", value, "conceptualArea");
            return (Criteria) this;
        }

        public Criteria andConceptualAreaNotLike(String value) {
            addCriterion("conceptualarea not like", value, "conceptualArea");
            return (Criteria) this;
        }

        public Criteria andConceptualAreaIn(List<String> values) {
            addCriterion("conceptualarea in", values, "conceptualArea");
            return (Criteria) this;
        }

        public Criteria andConceptualAreaNotIn(List<String> values) {
            addCriterion("conceptualarea not in", values, "conceptualArea");
            return (Criteria) this;
        }

        public Criteria andConceptualAreaBetween(String value1, String value2) {
            addCriterion("conceptualarea between", value1, value2, "conceptualArea");
            return (Criteria) this;
        }

        public Criteria andConceptualAreaNotBetween(String value1, String value2) {
            addCriterion("conceptualarea not between", value1, value2, "conceptualArea");
            return (Criteria) this;
        }

        public Criteria andEssentialElementIsNull() {
            addCriterion("essentialelement is null");
            return (Criteria) this;
        }

        public Criteria andEssentialElementIsNotNull() {
            addCriterion("essentialelement is not null");
            return (Criteria) this;
        }

        public Criteria andEssentialElementEqualTo(String value) {
            addCriterion("essentialelement =", value, "essentialElement");
            return (Criteria) this;
        }

        public Criteria andEssentialElementNotEqualTo(String value) {
            addCriterion("essentialelement <>", value, "essentialElement");
            return (Criteria) this;
        }

        public Criteria andEssentialElementGreaterThan(String value) {
            addCriterion("essentialelement >", value, "essentialElement");
            return (Criteria) this;
        }

        public Criteria andEssentialElementGreaterThanOrEqualTo(String value) {
            addCriterion("essentialelement >=", value, "essentialElement");
            return (Criteria) this;
        }

        public Criteria andEssentialElementLessThan(String value) {
            addCriterion("essentialelement <", value, "essentialElement");
            return (Criteria) this;
        }

        public Criteria andEssentialElementLessThanOrEqualTo(String value) {
            addCriterion("essentialelement <=", value, "essentialElement");
            return (Criteria) this;
        }

        public Criteria andEssentialElementLike(String value) {
            addCriterion("essentialelement like", value, "essentialElement");
            return (Criteria) this;
        }

        public Criteria andEssentialElementNotLike(String value) {
            addCriterion("essentialelement not like", value, "essentialElement");
            return (Criteria) this;
        }

        public Criteria andEssentialElementIn(List<String> values) {
            addCriterion("essentialelement in", values, "essentialElement");
            return (Criteria) this;
        }

        public Criteria andEssentialElementNotIn(List<String> values) {
            addCriterion("essentialelement not in", values, "essentialElement");
            return (Criteria) this;
        }

        public Criteria andEssentialElementBetween(String value1, String value2) {
            addCriterion("essentialelement between", value1, value2, "essentialElement");
            return (Criteria) this;
        }

        public Criteria andEssentialElementNotBetween(String value1, String value2) {
            addCriterion("essentialelement not between", value1, value2, "essentialElement");
            return (Criteria) this;
        }

        public Criteria andEeDescriptionIsNull() {
            addCriterion("eedescription is null");
            return (Criteria) this;
        }

        public Criteria andEeDescriptionIsNotNull() {
            addCriterion("eedescription is not null");
            return (Criteria) this;
        }

        public Criteria andEeDescriptionEqualTo(String value) {
            addCriterion("eedescription =", value, "eeDescription");
            return (Criteria) this;
        }

        public Criteria andEeDescriptionNotEqualTo(String value) {
            addCriterion("eedescription <>", value, "eeDescription");
            return (Criteria) this;
        }

        public Criteria andEeDescriptionGreaterThan(String value) {
            addCriterion("eedescription >", value, "eeDescription");
            return (Criteria) this;
        }

        public Criteria andEeDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("eedescription >=", value, "eeDescription");
            return (Criteria) this;
        }

        public Criteria andEeDescriptionLessThan(String value) {
            addCriterion("eedescription <", value, "eeDescription");
            return (Criteria) this;
        }

        public Criteria andEeDescriptionLessThanOrEqualTo(String value) {
            addCriterion("eedescription <=", value, "eeDescription");
            return (Criteria) this;
        }

        public Criteria andEeDescriptionLike(String value) {
            addCriterion("eedescription like", value, "eeDescription");
            return (Criteria) this;
        }

        public Criteria andEeDescriptionNotLike(String value) {
            addCriterion("eedescription not like", value, "eeDescription");
            return (Criteria) this;
        }

        public Criteria andEeDescriptionIn(List<String> values) {
            addCriterion("eedescription in", values, "eeDescription");
            return (Criteria) this;
        }

        public Criteria andEeDescriptionNotIn(List<String> values) {
            addCriterion("eedescription not in", values, "eeDescription");
            return (Criteria) this;
        }

        public Criteria andEeDescriptionBetween(String value1, String value2) {
            addCriterion("eedescription between", value1, value2, "eeDescription");
            return (Criteria) this;
        }

        public Criteria andEeDescriptionNotBetween(String value1, String value2) {
            addCriterion("eedescription not between", value1, value2, "eeDescription");
            return (Criteria) this;
        }

        public Criteria andLinkageLevelAbbrIsNull() {
            addCriterion("linkagelevelabbr is null");
            return (Criteria) this;
        }

        public Criteria andLinkageLevelAbbrIsNotNull() {
            addCriterion("linkagelevelabbr is not null");
            return (Criteria) this;
        }

        public Criteria andLinkageLevelAbbrEqualTo(String value) {
            addCriterion("linkagelevelabbr =", value, "linkageLevelAbbr");
            return (Criteria) this;
        }

        public Criteria andLinkageLevelAbbrNotEqualTo(String value) {
            addCriterion("linkagelevelabbr <>", value, "linkageLevelAbbr");
            return (Criteria) this;
        }

        public Criteria andLinkageLevelAbbrGreaterThan(String value) {
            addCriterion("linkagelevelabbr >", value, "linkageLevelAbbr");
            return (Criteria) this;
        }

        public Criteria andLinkageLevelAbbrGreaterThanOrEqualTo(String value) {
            addCriterion("linkagelevelabbr >=", value, "linkageLevelAbbr");
            return (Criteria) this;
        }

        public Criteria andLinkageLevelAbbrLessThan(String value) {
            addCriterion("linkagelevelabbr <", value, "linkageLevelAbbr");
            return (Criteria) this;
        }

        public Criteria andLinkageLevelAbbrLessThanOrEqualTo(String value) {
            addCriterion("linkagelevelabbr <=", value, "linkageLevelAbbr");
            return (Criteria) this;
        }

        public Criteria andLinkageLevelAbbrLike(String value) {
            addCriterion("linkagelevelabbr like", value, "linkageLevelAbbr");
            return (Criteria) this;
        }

        public Criteria andLinkageLevelAbbrNotLike(String value) {
            addCriterion("linkagelevelabbr not like", value, "linkageLevelAbbr");
            return (Criteria) this;
        }

        public Criteria andLinkageLevelAbbrIn(List<String> values) {
            addCriterion("linkagelevelabbr in", values, "linkageLevelAbbr");
            return (Criteria) this;
        }

        public Criteria andLinkageLevelAbbrNotIn(List<String> values) {
            addCriterion("linkagelevelabbr not in", values, "linkageLevelAbbr");
            return (Criteria) this;
        }

        public Criteria andLinkageLevelAbbrBetween(String value1, String value2) {
            addCriterion("linkagelevelabbr between", value1, value2, "linkageLevelAbbr");
            return (Criteria) this;
        }

        public Criteria andLinkageLevelAbbrNotBetween(String value1, String value2) {
            addCriterion("linkagelevelabbr not between", value1, value2, "linkageLevelAbbr");
            return (Criteria) this;
        }

        public Criteria andProportionLowIsNull() {
            addCriterion("proportionlow is null");
            return (Criteria) this;
        }

        public Criteria andProportionLowIsNotNull() {
            addCriterion("proportionlow is not null");
            return (Criteria) this;
        }

        public Criteria andProportionLowEqualTo(BigDecimal value) {
            addCriterion("proportionlow =", value, "proportionLow");
            return (Criteria) this;
        }

        public Criteria andProportionLowNotEqualTo(BigDecimal value) {
            addCriterion("proportionlow <>", value, "proportionLow");
            return (Criteria) this;
        }

        public Criteria andProportionLowGreaterThan(BigDecimal value) {
            addCriterion("proportionlow >", value, "proportionLow");
            return (Criteria) this;
        }

        public Criteria andProportionLowGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("proportionlow >=", value, "proportionLow");
            return (Criteria) this;
        }

        public Criteria andProportionLowLessThan(BigDecimal value) {
            addCriterion("proportionlow <", value, "proportionLow");
            return (Criteria) this;
        }

        public Criteria andProportionLowLessThanOrEqualTo(BigDecimal value) {
            addCriterion("proportionlow <=", value, "proportionLow");
            return (Criteria) this;
        }

        public Criteria andProportionLowIn(List<BigDecimal> values) {
            addCriterion("proportionlow in", values, "proportionLow");
            return (Criteria) this;
        }

        public Criteria andProportionLowNotIn(List<BigDecimal> values) {
            addCriterion("proportionlow not in", values, "proportionLow");
            return (Criteria) this;
        }

        public Criteria andProportionLowBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("proportionlow between", value1, value2, "proportionLow");
            return (Criteria) this;
        }

        public Criteria andProportionLowNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("proportionlow not between", value1, value2, "proportionLow");
            return (Criteria) this;
        }

        public Criteria andProportionHighIsNull() {
            addCriterion("proportionhigh is null");
            return (Criteria) this;
        }

        public Criteria andProportionHighIsNotNull() {
            addCriterion("proportionhigh is not null");
            return (Criteria) this;
        }

        public Criteria andProportionHighEqualTo(BigDecimal value) {
            addCriterion("proportionhigh =", value, "proportionHigh");
            return (Criteria) this;
        }

        public Criteria andProportionHighNotEqualTo(BigDecimal value) {
            addCriterion("proportionhigh <>", value, "proportionHigh");
            return (Criteria) this;
        }

        public Criteria andProportionHighGreaterThan(BigDecimal value) {
            addCriterion("proportionhigh >", value, "proportionHigh");
            return (Criteria) this;
        }

        public Criteria andProportionHighGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("proportionhigh >=", value, "proportionHigh");
            return (Criteria) this;
        }

        public Criteria andProportionHighLessThan(BigDecimal value) {
            addCriterion("proportionhigh <", value, "proportionHigh");
            return (Criteria) this;
        }

        public Criteria andProportionHighLessThanOrEqualTo(BigDecimal value) {
            addCriterion("proportionhigh <=", value, "proportionHigh");
            return (Criteria) this;
        }

        public Criteria andProportionHighIn(List<BigDecimal> values) {
            addCriterion("proportionhigh in", values, "proportionHigh");
            return (Criteria) this;
        }

        public Criteria andProportionHighNotIn(List<BigDecimal> values) {
            addCriterion("proportionhigh not in", values, "proportionHigh");
            return (Criteria) this;
        }

        public Criteria andProportionHighBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("proportionhigh between", value1, value2, "proportionHigh");
            return (Criteria) this;
        }

        public Criteria andProportionHighNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("proportionhigh not between", value1, value2, "proportionHigh");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table proportionmetrics
     *
     * @mbggenerated do_not_delete_during_merge Thu Nov 20 01:30:46 CST 2014
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table proportionmetrics
     *
     * @mbggenerated Thu Nov 20 01:30:46 CST 2014
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}