package edu.ku.cete.model;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import edu.ku.cete.domain.api.APIDashboardError;
import edu.ku.cete.domain.apierrors.ApiAllErrorRecords;
import edu.ku.cete.domain.apierrors.ApiErrorsRecord;

public interface APIDashboardErrorMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table apidashboarderror
	 * @mbg.generated  Wed Aug 22 14:42:05 CDT 2018
	 */
	int insert(APIDashboardError record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table apidashboarderror
	 * @mbg.generated  Wed Aug 22 14:42:05 CDT 2018
	 */
	int insertSelective(APIDashboardError record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table apidashboarderror
	 * @mbg.generated  Wed Aug 22 14:42:05 CDT 2018
	 */
	APIDashboardError selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table apidashboarderror
	 * @mbg.generated  Wed Aug 22 14:42:05 CDT 2018
	 */
	int updateByPrimaryKeySelective(APIDashboardError record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table apidashboarderror
	 * @mbg.generated  Wed Aug 22 14:42:05 CDT 2018
	 */
	int updateByPrimaryKey(APIDashboardError record);
	
		
	List<ApiErrorsRecord> getApiErrorsToView(Map<String, Object> criteria);
		
	List<String> getErrorRecordTypes();

	List<String> getApiErrorsRequestTypes();
		
	Integer getCountOfApiErrorsToView(Map<String, Object> criteria);

	List<ApiAllErrorRecords> getAllApiErrorMessages(Map<String, Object> criteria);
		


}