package edu.ku.cete.model;

import java.util.Collection;
import java.util.List;
import org.apache.ibatis.annotations.Param;

import edu.ku.cete.domain.content.AutoRegistrationCriteria;

public interface AutoRegistrationCriteriaDao {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.testcollection
     *
     * @mbggenerated Wed Sep 12 16:14:17 CDT 2012
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.testcollection
     *
     * @mbggenerated Wed Sep 12 16:14:17 CDT 2012
     */
    int insert(AutoRegistrationCriteria record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.testcollection
     *
     * @mbggenerated Wed Sep 12 16:14:17 CDT 2012
     */
    int insertSelective(AutoRegistrationCriteria record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.testcollection
     *
     * @mbggenerated Wed Sep 12 16:14:17 CDT 2012
     */
    AutoRegistrationCriteria selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.testcollection
     *
     * @mbggenerated Wed Sep 12 16:14:17 CDT 2012
     */
    int updateByPrimaryKeySelective(AutoRegistrationCriteria record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.testcollection
     *
     * @mbggenerated Wed Sep 12 16:14:17 CDT 2012
     */
    int updateByPrimaryKey(AutoRegistrationCriteria record);

    /**
     * @param testTypeCode
     * @param subjectAreaCode
     * @return
     */
    AutoRegistrationCriteria selectByTestTypeAndSubjectAreaCode(@Param("testTypeCode") String testTypeCode, 
    		@Param("subjectAreaCode") String subjectAreaCode, @Param("gradeCourseId") String gradeCourseId,
    		@Param("assessmentId") Long assessmentId);      

}