package edu.ku.cete.model;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import edu.ku.cete.dlm.iti.BPCriteriaAndGroups;
import edu.ku.cete.domain.BluePrint;
import edu.ku.cete.domain.BluePrintCriteriaDescription;
import edu.ku.cete.domain.test.ContentFrameworkDetail;

public interface BluePrintMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table blueprint
	 * @mbggenerated  Wed Mar 25 10:28:09 CDT 2015
	 */
	int insert(BluePrint record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table blueprint
	 * @mbggenerated  Wed Mar 25 10:28:09 CDT 2015
	 */
	int insertSelective(BluePrint record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table blueprint
	 * @mbggenerated  Wed Mar 25 10:28:09 CDT 2015
	 */
	BluePrint selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table blueprint
	 * @mbggenerated  Wed Mar 25 10:28:09 CDT 2015
	 */
	int updateByPrimaryKeySelective(BluePrint record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table blueprint
	 * @mbggenerated  Wed Mar 25 10:28:09 CDT 2015
	 */
	int updateByPrimaryKey(BluePrint record);

	List<BluePrint> selectByContentAreaAndGrade(@Param("contentAreaId") Long contentAreaId, @Param("gradeCode") String gradeCode);
	
	List<ContentFrameworkDetail> selectWritingByLinkageLevel(@Param("contentAreaId") Long contentAreaId, @Param("gradeCode") String gradeCode,
			@Param("linkageLevelCodes") List<String> linkageLevelCodes, @Param("criteriaNum") Long criteriaNum);
	
	List<BPCriteriaAndGroups> getBluePrintCriteriasByGradeAndSub(@Param("contentAreaId") Long contentAreaId, @Param("gradeCode") String gradeCode);
	
	List<BluePrintCriteriaDescription> getBluePrintCriteriaDescByGradeAndSub(@Param("contentAreaId") Long contentAreaId, 
			@Param("gradeCourseAbbrName") String gradeCourseAbbrName);

	List<BPCriteriaAndGroups> getBluePrintCriteriasByGradeAndSubAndCriteria(@Param("contentAreaId") Long contentAreaId, @Param("gradeCourseAbbrName") String gradeCourseAbbrName, 
			@Param("criteria") Long criteria);
}