package edu.ku.cete.model;

import edu.ku.cete.domain.MicroMap;
import edu.ku.cete.domain.MicroMapExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MicroMapMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table micromap
     *
     * @mbggenerated Wed Dec 11 15:39:46 CST 2013
     */
    int countByExample(MicroMapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table micromap
     *
     * @mbggenerated Wed Dec 11 15:39:46 CST 2013
     */
    int deleteByExample(MicroMapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table micromap
     *
     * @mbggenerated Wed Dec 11 15:39:46 CST 2013
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table micromap
     *
     * @mbggenerated Wed Dec 11 15:39:46 CST 2013
     */
    int insert(MicroMap record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table micromap
     *
     * @mbggenerated Wed Dec 11 15:39:46 CST 2013
     */
    int insertSelective(MicroMap record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table micromap
     *
     * @mbggenerated Wed Dec 11 15:39:46 CST 2013
     */
    List<MicroMap> selectByExample(MicroMapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table micromap
     *
     * @mbggenerated Wed Dec 11 15:39:46 CST 2013
     */
    MicroMap selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table micromap
     *
     * @mbggenerated Wed Dec 11 15:39:46 CST 2013
     */
    int updateByExampleSelective(@Param("record") MicroMap record, @Param("example") MicroMapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table micromap
     *
     * @mbggenerated Wed Dec 11 15:39:46 CST 2013
     */
    int updateByExample(@Param("record") MicroMap record, @Param("example") MicroMapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table micromap
     *
     * @mbggenerated Wed Dec 11 15:39:46 CST 2013
     */
    int updateByPrimaryKeySelective(MicroMap record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table micromap
     *
     * @mbggenerated Wed Dec 11 15:39:46 CST 2013
     */
    int updateByPrimaryKey(MicroMap record);
    
    List<MicroMap> selectMicroMapByItiHistory(@Param("studentID") Long studentID);
}