package edu.ku.cete.model;

import edu.ku.cete.domain.OperationalTestWindowStudent;

public interface OperationalTestWindowStudentMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table operationaltestwindowstudent
	 * @mbggenerated  Tue Jan 05 16:24:16 CST 2016
	 */
	int insert(OperationalTestWindowStudent record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table operationaltestwindowstudent
	 * @mbggenerated  Tue Jan 05 16:24:16 CST 2016
	 */
	int insertSelective(OperationalTestWindowStudent record);

	int update(OperationalTestWindowStudent record);
	
	int updateSelective(OperationalTestWindowStudent record);

	OperationalTestWindowStudent findByOperationalTestWindowStudent(OperationalTestWindowStudent operationalTestWindowStudent);
}