package edu.ku.cete.model;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import edu.ku.cete.domain.report.ReportsMedianScore;
import edu.ku.cete.web.SchoolAndDistrictReportDTO;

public interface ReportsMedianScoreMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reportsmedianscore
	 * @mbggenerated  Wed Aug 19 16:04:01 CDT 2015
	 */
	int insert(ReportsMedianScore record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reportsmedianscore
	 * @mbggenerated  Wed Aug 19 16:04:01 CDT 2015
	 */
	int insertSelective(ReportsMedianScore record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reportsmedianscore
	 * @mbggenerated  Wed Aug 19 16:04:01 CDT 2015
	 */
	ReportsMedianScore selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reportsmedianscore
	 * @mbggenerated  Wed Aug 19 16:04:01 CDT 2015
	 */
	int updateByPrimaryKeySelective(ReportsMedianScore record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reportsmedianscore
	 * @mbggenerated  Wed Aug 19 16:04:01 CDT 2015
	 */
	int updateByPrimaryKey(ReportsMedianScore record);

	int deleteReportMedianScore(@Param("assessmentProgramId") Long assessmentProgramId, @Param("contentAreaId") Long contentAreaId, 
			@Param("gradeId") Long gradeId, @Param("schoolYear") Long schoolYear);
	
	List<ReportsMedianScore> getMedainScoreByOrgIdsAssessmentContentGradeSchoolYear(@Param("organizationIds") List<Long> organizationIds, @Param("assessmentProgramId") Long assessmentProgramId, @Param("contentAreaId") Long contentAreaId, 
			@Param("gradeIds") List<Long> gradeIds, @Param("schoolYear") Long schoolYear);
	
	List<Long> getDistinctOrganizationReportMedian(@Param("assessmentProgramId") Long assessmentProgramId, @Param("contentAreaId") Long contentAreaId, 
			@Param("gradeId") Long gradeId, @Param("schoolYear") Long scholYear, @Param("contractOrgId") Long contractOrgId,  @Param("offset") Integer offset, @Param("pageSize") Integer pageSize );
	
	List<Long> getDistinctGradeIdsInOrgFromMedains(@Param("assessmentProgramId") Long assessmentProgramId, @Param("contentAreaId") Long contentAreaId, 
			@Param("schoolYear") Long schoolYear, @Param("organizationId") Long organizationId);
	
	
}