package edu.ku.cete.model;

import edu.ku.cete.domain.RubricScore;
import edu.ku.cete.domain.RubricScoreExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RubricScoreMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rubricscore
	 * @mbggenerated  Sun Sep 22 02:53:50 CDT 2013
	 */
	int countByExample(RubricScoreExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rubricscore
	 * @mbggenerated  Sun Sep 22 02:53:50 CDT 2013
	 */
	int deleteByExample(RubricScoreExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rubricscore
	 * @mbggenerated  Sun Sep 22 02:53:50 CDT 2013
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rubricscore
	 * @mbggenerated  Sun Sep 22 02:53:50 CDT 2013
	 */
	int insert(RubricScore record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rubricscore
	 * @mbggenerated  Sun Sep 22 02:53:50 CDT 2013
	 */
	int insertSelective(RubricScore record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rubricscore
	 * @mbggenerated  Sun Sep 22 02:53:50 CDT 2013
	 */
	List<RubricScore> selectByExample(RubricScoreExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rubricscore
	 * @mbggenerated  Sun Sep 22 02:53:50 CDT 2013
	 */
	RubricScore selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rubricscore
	 * @mbggenerated  Sun Sep 22 02:53:50 CDT 2013
	 */
	int updateByExampleSelective(@Param("record") RubricScore record,
			@Param("example") RubricScoreExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rubricscore
	 * @mbggenerated  Sun Sep 22 02:53:50 CDT 2013
	 */
	int updateByExample(@Param("record") RubricScore record,
			@Param("example") RubricScoreExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rubricscore
	 * @mbggenerated  Sun Sep 22 02:53:50 CDT 2013
	 */
	int updateByPrimaryKeySelective(RubricScore record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rubricscore
	 * @mbggenerated  Sun Sep 22 02:53:50 CDT 2013
	 */
	int updateByPrimaryKey(RubricScore record);

	List<RubricScore>  selectByStudentTestId(@Param("studentTestId")Long studentTestId,@Param("taskVariantId")Long taskVariantId);
	
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rubricscore
	 * @mbggenerated  Tue Sep 17 00:33:04 CDT 2013
	 */
	int updateRubricScore(@Param("studentTestId")Long studentTestId,@Param("taskVariantId")Long taskVariantId,@Param("rubricScore")Float rubricScore);
}