package edu.ku.cete.model;

import edu.ku.cete.domain.StudentNodeProbability;
import edu.ku.cete.domain.StudentNodeProbabilityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StudentNodeProbabilityMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table studentnodeprobability
	 * @mbggenerated  Thu Aug 21 13:21:20 CDT 2014
	 */
	int countByExample(StudentNodeProbabilityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table studentnodeprobability
	 * @mbggenerated  Thu Aug 21 13:21:20 CDT 2014
	 */
	int deleteByExample(StudentNodeProbabilityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table studentnodeprobability
	 * @mbggenerated  Thu Aug 21 13:21:20 CDT 2014
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table studentnodeprobability
	 * @mbggenerated  Thu Aug 21 13:21:20 CDT 2014
	 */
	int insert(StudentNodeProbability record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table studentnodeprobability
	 * @mbggenerated  Thu Aug 21 13:21:20 CDT 2014
	 */
	int insertSelective(StudentNodeProbability record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table studentnodeprobability
	 * @mbggenerated  Thu Aug 21 13:21:20 CDT 2014
	 */
	List<StudentNodeProbability> selectByExample(
			StudentNodeProbabilityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table studentnodeprobability
	 * @mbggenerated  Thu Aug 21 13:21:20 CDT 2014
	 */
	StudentNodeProbability selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table studentnodeprobability
	 * @mbggenerated  Thu Aug 21 13:21:20 CDT 2014
	 */
	int updateByExampleSelective(
			@Param("record") StudentNodeProbability record,
			@Param("example") StudentNodeProbabilityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table studentnodeprobability
	 * @mbggenerated  Thu Aug 21 13:21:20 CDT 2014
	 */
	int updateByExample(@Param("record") StudentNodeProbability record,
			@Param("example") StudentNodeProbabilityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table studentnodeprobability
	 * @mbggenerated  Thu Aug 21 13:21:20 CDT 2014
	 */
	int updateByPrimaryKeySelective(StudentNodeProbability record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table studentnodeprobability
	 * @mbggenerated  Thu Aug 21 13:21:20 CDT 2014
	 */
	int updateByPrimaryKey(StudentNodeProbability record);
}