package edu.ku.cete.model;

import org.apache.ibatis.annotations.Param;

import edu.ku.cete.domain.StudentTrackerBluePrintStatus;
import edu.ku.cete.domain.StudentTrackerBluePrintStatusKey;

public interface StudentTrackerBluePrintStatusMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studenttrackerblueprintstatus
     *
     * @mbggenerated Wed Dec 23 10:20:03 CST 2015
     */
    int insert(StudentTrackerBluePrintStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studenttrackerblueprintstatus
     *
     * @mbggenerated Wed Dec 23 10:20:03 CST 2015
     */
    int insertSelective(StudentTrackerBluePrintStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studenttrackerblueprintstatus
     *
     * @mbggenerated Wed Dec 23 10:20:03 CST 2015
     */
    StudentTrackerBluePrintStatus selectByPrimaryKey(StudentTrackerBluePrintStatusKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studenttrackerblueprintstatus
     *
     * @mbggenerated Wed Dec 23 10:20:03 CST 2015
     */
    int updateByPrimaryKeySelective(StudentTrackerBluePrintStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studenttrackerblueprintstatus
     *
     * @mbggenerated Wed Dec 23 10:20:03 CST 2015
     */
    int updateByPrimaryKey(StudentTrackerBluePrintStatus record);
    
    int deleteCompletedStudentTrackerBlueprintStatus(@Param("studentTrackerId") Long studentTrackerId, @Param("operationalWindowId") Long operationalWindowId);
}