package edu.ku.cete.model;

import edu.ku.cete.domain.enrollment.SubjectArea;
import edu.ku.cete.domain.SubjectAreaExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SubjectAreaDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subjectarea
     *
     * @mbggenerated Fri Sep 27 18:11:53 CDT 2013
     */
    int countByExample(SubjectAreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subjectarea
     *
     * @mbggenerated Fri Sep 27 18:11:53 CDT 2013
     */
    int deleteByExample(SubjectAreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subjectarea
     *
     * @mbggenerated Fri Sep 27 18:11:53 CDT 2013
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subjectarea
     *
     * @mbggenerated Fri Sep 27 18:11:53 CDT 2013
     */
    int insert(SubjectArea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subjectarea
     *
     * @mbggenerated Fri Sep 27 18:11:53 CDT 2013
     */
    int insertSelective(SubjectArea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subjectarea
     *
     * @mbggenerated Fri Sep 27 18:11:53 CDT 2013
     */
    List<SubjectArea> selectByExample(SubjectAreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subjectarea
     *
     * @mbggenerated Fri Sep 27 18:11:53 CDT 2013
     */
    SubjectArea selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subjectarea
     *
     * @mbggenerated Fri Sep 27 18:11:53 CDT 2013
     */
    int updateByExampleSelective(@Param("record") SubjectArea record, @Param("example") SubjectAreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subjectarea
     *
     * @mbggenerated Fri Sep 27 18:11:53 CDT 2013
     */
    int updateByExample(@Param("record") SubjectArea record, @Param("example") SubjectAreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subjectarea
     *
     * @mbggenerated Fri Sep 27 18:11:53 CDT 2013
     */
    int updateByPrimaryKeySelective(SubjectArea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subjectarea
     *
     * @mbggenerated Fri Sep 27 18:11:53 CDT 2013
     */
    int updateByPrimaryKey(SubjectArea record);
    
    /**
     * 
     * @param testTypeId
     * @return
     */
    List<SubjectArea> selectByTestTypeId(Long testTypeId);
    
    List<SubjectArea> selectSubjectAreasForAutoRegistration(@Param("testTypeId") Long testTypeId, 
    		@Param("assessmentId") Long assessmentId);
}