package edu.ku.cete.model;

import edu.ku.cete.domain.content.TaskVariantsFoils;
import edu.ku.cete.domain.content.TaskVariantsFoilsExample;
import edu.ku.cete.domain.content.TaskVariantsFoilsKey;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TaskVariantsFoilsDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.taskvariantsfoils
     *
     * @mbggenerated Thu Oct 18 09:37:45 CDT 2012
     */
    int countByExample(TaskVariantsFoilsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.taskvariantsfoils
     *
     * @mbggenerated Thu Oct 18 09:37:45 CDT 2012
     */
    int deleteByExample(TaskVariantsFoilsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.taskvariantsfoils
     *
     * @mbggenerated Thu Oct 18 09:37:45 CDT 2012
     */
    int deleteByPrimaryKey(TaskVariantsFoilsKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.taskvariantsfoils
     *
     * @mbggenerated Thu Oct 18 09:37:45 CDT 2012
     */
    int insert(TaskVariantsFoils record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.taskvariantsfoils
     *
     * @mbggenerated Thu Oct 18 09:37:45 CDT 2012
     */
    int insertSelective(TaskVariantsFoils record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.taskvariantsfoils
     *
     * @mbggenerated Thu Oct 18 09:37:45 CDT 2012
     */
    List<TaskVariantsFoils> selectByExample(TaskVariantsFoilsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.taskvariantsfoils
     *
     * @mbggenerated Thu Oct 18 09:37:45 CDT 2012
     */
    List<TaskVariantsFoils> selectExtendedByExample(TaskVariantsFoilsExample example);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.taskvariantsfoils
     *
     * @mbggenerated Thu Oct 18 09:37:45 CDT 2012
     */
    TaskVariantsFoils selectByPrimaryKey(TaskVariantsFoilsKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.taskvariantsfoils
     *
     * @mbggenerated Thu Oct 18 09:37:45 CDT 2012
     */
    int updateByExampleSelective(@Param("record") TaskVariantsFoils record, @Param("example") TaskVariantsFoilsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.taskvariantsfoils
     *
     * @mbggenerated Thu Oct 18 09:37:45 CDT 2012
     */
    int updateByExample(@Param("record") TaskVariantsFoils record, @Param("example") TaskVariantsFoilsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.taskvariantsfoils
     *
     * @mbggenerated Thu Oct 18 09:37:45 CDT 2012
     */
    int updateByPrimaryKeySelective(TaskVariantsFoils record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.taskvariantsfoils
     *
     * @mbggenerated Thu Oct 18 09:37:45 CDT 2012
     */
    int updateByPrimaryKey(TaskVariantsFoils record);
}