package edu.ku.cete.model;

import edu.ku.cete.domain.content.TestSection;
import edu.ku.cete.domain.content.TestSectionExample;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TestSectionDao {
	/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.testsection
     *
     * @mbggenerated Wed Dec 12 21:51:26 CST 2012
     */
    int countByExample(TestSectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.testsection
     *
     * @mbggenerated Wed Dec 12 21:51:26 CST 2012
     */
    int deleteByExample(TestSectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.testsection
     *
     * @mbggenerated Wed Dec 12 21:51:26 CST 2012
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.testsection
     *
     * @mbggenerated Wed Dec 12 21:51:26 CST 2012
     */
    int insert(TestSection record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.testsection
     *
     * @mbggenerated Wed Dec 12 21:51:26 CST 2012
     */
    int insertSelective(TestSection record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.testsection
     *
     * @mbggenerated Wed Dec 12 21:51:26 CST 2012
     */
    List<TestSection> selectByExample(TestSectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.testsection
     *
     * @mbggenerated Wed Dec 12 21:51:26 CST 2012
     */
    TestSection selectByPrimaryKey(Long id);
    
    
    List<TestSection> selectByTestId(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.testsection
     *
     * @mbggenerated Wed Dec 12 21:51:26 CST 2012
     */
    int updateByExampleSelective(@Param("record") TestSection record, @Param("example") TestSectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.testsection
     *
     * @mbggenerated Wed Dec 12 21:51:26 CST 2012
     */
    int updateByExample(@Param("record") TestSection record, @Param("example") TestSectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.testsection
     *
     * @mbggenerated Wed Dec 12 21:51:26 CST 2012
     */
    int updateByPrimaryKeySelective(TestSection record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.testsection
     *
     * @mbggenerated Wed Dec 12 21:51:26 CST 2012
     */
    int updateByPrimaryKey(TestSection record);
    
    List<TestSection> getTestSectionsWithMaxNumberOfItemsByTestSessionId(@Param("testSessionId") Long testSessionId);
    List<Long> getContextStimulsIdByTestSectionId(@Param("testSessionId") Long testSessionId);

	int insertAuxillaryTestRoles(@Param("newId")Long newId,@Param("oldId") Long oldId);

	void deleteByPrimaryKeyInterim(Long id);

	List<TestSection> getTestSectionsByTestsInterim(@Param("testIds")List<Long> list);

	List<TestSection> getTestSectionsByTestInterim(@Param("testId")Long testId);
}