package edu.ku.cete.domain.enrollment;

import edu.ku.cete.domain.audit.AuditableDomain;

public class EnrollmentsRosters extends AuditableDomain {
	
	/**
	 * 
	 */
	private static final long serialVersionUID = -892726490654942575L;
	public EnrollmentsRosters(){
		
	}

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.enrollmentsrosters.enrollment_id
     *
     * @mbggenerated Wed May 16 23:31:04 CDT 2012
     */
    private Long enrollmentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.enrollmentsrosters.roster_id
     *
     * @mbggenerated Wed May 16 23:31:04 CDT 2012
     */
    private Long rosterId;
    
    private Long id;
    
    private Long courseEnrollmentStatusId;
	/**
	 * @param enrollId
	 * @param rostId
	 */
	public EnrollmentsRosters(long enrollId, long rostId){
		this.setEnrollmentId(enrollId);
		this.setRosterId(rostId);
	}
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.enrollmentsrosters.enrollment_id
     *
     * @return the value of public.enrollmentsrosters.enrollment_id
     *
     * @mbggenerated Wed May 16 23:31:04 CDT 2012
     */
    public Long getEnrollmentId() {
        return enrollmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.enrollmentsrosters.enrollment_id
     *
     * @param enrollmentId the value for public.enrollmentsrosters.enrollment_id
     *
     * @mbggenerated Wed May 16 23:31:04 CDT 2012
     */
    public void setEnrollmentId(Long enrollmentId) {
        this.enrollmentId = enrollmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.enrollmentsrosters.roster_id
     *
     * @return the value of public.enrollmentsrosters.roster_id
     *
     * @mbggenerated Wed May 16 23:31:04 CDT 2012
     */
    public Long getRosterId() {
        return rosterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.enrollmentsrosters.roster_id
     *
     * @param rosterId the value for public.enrollmentsrosters.roster_id
     *
     * @mbggenerated Wed May 16 23:31:04 CDT 2012
     */
    public void setRosterId(Long rosterId) {
        this.rosterId = rosterId;
    }
	/**
	 * @return the id
	 */
	public Long getId() {
		return id;
	}
	/**
	 * @param id the id to set
	 */
	public void setId(Long id) {
		this.id = id;
	}
	public Long getCourseEnrollmentStatusId() {
		return courseEnrollmentStatusId;
	}
	public void setCourseEnrollmentStatusId(Long courseEnrollmentStatusId) {
		this.courseEnrollmentStatusId = courseEnrollmentStatusId;
	}
	
	private String sourceType;
	public String getSourceType() {
		return sourceType;
	}
	public void setSourceType(String sourceType) {
		this.sourceType = sourceType;
	}
	
	private Long externalId;
	public Long getExternalId() {
		return externalId;
	}
	public void setExternalId(Long externalId) {
		this.externalId = externalId;
	}
}