package edu.ku.cete.report.model;

import edu.ku.cete.report.domain.BatchRegisteredTestSessions;
import edu.ku.cete.report.domain.BatchRegisteredTestSessionsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BatchRegisteredTestSessionsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table batchregisteredtestsessions
     *
     * @mbggenerated Mon Sep 14 16:42:42 CDT 2015
     */
    int countByExample(BatchRegisteredTestSessionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table batchregisteredtestsessions
     *
     * @mbggenerated Mon Sep 14 16:42:42 CDT 2015
     */
    int deleteByExample(BatchRegisteredTestSessionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table batchregisteredtestsessions
     *
     * @mbggenerated Mon Sep 14 16:42:42 CDT 2015
     */
    int insert(BatchRegisteredTestSessions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table batchregisteredtestsessions
     *
     * @mbggenerated Mon Sep 14 16:42:42 CDT 2015
     */
    int insertSelective(BatchRegisteredTestSessions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table batchregisteredtestsessions
     *
     * @mbggenerated Mon Sep 14 16:42:42 CDT 2015
     */
    List<BatchRegisteredTestSessions> selectByExample(BatchRegisteredTestSessionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table batchregisteredtestsessions
     *
     * @mbggenerated Mon Sep 14 16:42:42 CDT 2015
     */
    int updateByExampleSelective(@Param("record") BatchRegisteredTestSessions record, @Param("example") BatchRegisteredTestSessionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table batchregisteredtestsessions
     *
     * @mbggenerated Mon Sep 14 16:42:42 CDT 2015
     */
    int updateByExample(@Param("record") BatchRegisteredTestSessions record, @Param("example") BatchRegisteredTestSessionsExample example);
}