-- US15536: Student Tracker - Simple Version 1 (preliminary)
insert into proportionmetrics(gradeid, conceptualarea,essentialelement,eedescription,linkagelevelabbr,proportionlow,proportionhigh) values ((select id from gradecourse where name='3'),'C1.1','EE.RL.3.1','Answer who and what questions to demonstrate understanding of details in a text.','IP',NULL,0.8);
insert into proportionmetrics(gradeid, conceptualarea,essentialelement,eedescription,linkagelevelabbr,proportionlow,proportionhigh) values ((select id from gradecourse where name='3'),'C1.1','EE.RL.3.1','Answer who and what questions to demonstrate understanding of details in a text.','DP',0.3,0.8);
insert into proportionmetrics(gradeid, conceptualarea,essentialelement,eedescription,linkagelevelabbr,proportionlow,proportionhigh) values ((select id from gradecourse where name='3'),'C1.1','EE.RL.3.1','Answer who and what questions to demonstrate understanding of details in a text.','PP',0.35,0.75);
insert into proportionmetrics(gradeid, conceptualarea,essentialelement,eedescription,linkagelevelabbr,proportionlow,proportionhigh) values ((select id from gradecourse where name='3'),'C1.1','EE.RL.3.1','Answer who and what questions to demonstrate understanding of details in a text.','T',0.3,0.7);
insert into proportionmetrics(gradeid, conceptualarea,essentialelement,eedescription,linkagelevelabbr,proportionlow,proportionhigh) values ((select id from gradecourse where name='3'),'C1.1','EE.RL.3.1','Answer who and what questions to demonstrate understanding of details in a text.','S',0.4,NULL);
insert into proportionmetrics(gradeid, conceptualarea,essentialelement,eedescription,linkagelevelabbr,proportionlow,proportionhigh) values ((select id from gradecourse where name='3'),'C1.1','EE.RL.3.2','Associate details with events in stories from diverse cultures.','IP',NULL,0.8);
insert into proportionmetrics(gradeid, conceptualarea,essentialelement,eedescription,linkagelevelabbr,proportionlow,proportionhigh) values ((select id from gradecourse where name='3'),'C1.1','EE.RL.3.2','Associate details with events in stories from diverse cultures.','DP',0.3,0.7);
insert into proportionmetrics(gradeid, conceptualarea,essentialelement,eedescription,linkagelevelabbr,proportionlow,proportionhigh) values ((select id from gradecourse where name='3'),'C1.1','EE.RL.3.2','Associate details with events in stories from diverse cultures.','PP',0.35,0.75);
insert into proportionmetrics(gradeid, conceptualarea,essentialelement,eedescription,linkagelevelabbr,proportionlow,proportionhigh) values ((select id from gradecourse where name='3'),'C1.1','EE.RL.3.2','Associate details with events in stories from diverse cultures.','T',0.3,0.8);
insert into proportionmetrics(gradeid, conceptualarea,essentialelement,eedescription,linkagelevelabbr,proportionlow,proportionhigh) values ((select id from gradecourse where name='3'),'C1.1','EE.RL.3.2','Associate details with events in stories from diverse cultures.','S',0.4,NULL);
insert into proportionmetrics(gradeid, conceptualarea,essentialelement,eedescription,linkagelevelabbr,proportionlow,proportionhigh) values ((select id from gradecourse where name='3'),'C1.1','EE.RL.3.3','Identify the feelings of characters in a story.','IP',NULL,0.8);
insert into proportionmetrics(gradeid, conceptualarea,essentialelement,eedescription,linkagelevelabbr,proportionlow,proportionhigh) values ((select id from gradecourse where name='3'),'C1.1','EE.RL.3.3','Identify the feelings of characters in a story.','DP',0.2,0.67);
insert into proportionmetrics(gradeid, conceptualarea,essentialelement,eedescription,linkagelevelabbr,proportionlow,proportionhigh) values ((select id from gradecourse where name='3'),'C1.1','EE.RL.3.3','Identify the feelings of characters in a story.','PP',0.3,0.75);
insert into proportionmetrics(gradeid, conceptualarea,essentialelement,eedescription,linkagelevelabbr,proportionlow,proportionhigh) values ((select id from gradecourse where name='3'),'C1.1','EE.RL.3.3','Identify the feelings of characters in a story.','T',0.33,0.8);
insert into proportionmetrics(gradeid, conceptualarea,essentialelement,eedescription,linkagelevelabbr,proportionlow,proportionhigh) values ((select id from gradecourse where name='3'),'C1.1','EE.RL.3.3','Identify the feelings of characters in a story.','S',0.38,NULL);

