--US15813: Test Coordination - require confirm for some Special Circumstance codes

UPDATE specialcircumstance SET activeflag=FALSE;

INSERT INTO specialcircumstance(specialcircumstancetype, cedscode, ksdecode, assessmentprogramid, createduser, modifieduser) VALUES ('Long-term suspension - non-special education', 13807, '01', (select id from assessmentprogram where abbreviatedname='KAP'), (Select id from aartuser where username='cetesysadmin'), (Select id from aartuser where username='cetesysadmin'));
INSERT INTO specialcircumstance(specialcircumstancetype, cedscode, ksdecode, assessmentprogramid, createduser, modifieduser) VALUES ('Truancy - paperwork filed', 13810, '04', (select id from assessmentprogram where abbreviatedname='KAP'), (Select id from aartuser where username='cetesysadmin'), (Select id from aartuser where username='cetesysadmin'));
INSERT INTO specialcircumstance(specialcircumstancetype, cedscode, ksdecode, assessmentprogramid, createduser, modifieduser) VALUES ('Chronic absences', 13813, '08', (select id from assessmentprogram where abbreviatedname='KAP'), (Select id from aartuser where username='cetesysadmin'), (Select id from aartuser where username='cetesysadmin'));
INSERT INTO specialcircumstance(specialcircumstancetype, cedscode, ksdecode, assessmentprogramid, createduser, modifieduser) VALUES ('Student took this grade level assessment last year', 13816, '20', (select id from assessmentprogram where abbreviatedname='KAP'), (Select id from aartuser where username='cetesysadmin'), (Select id from aartuser where username='cetesysadmin'));
INSERT INTO specialcircumstance(specialcircumstancetype, cedscode, ksdecode, assessmentprogramid, createduser, modifieduser) VALUES ('Reading passage read to student (IEP)', 13827, '34', (select id from assessmentprogram where abbreviatedname='KAP'), (Select id from aartuser where username='cetesysadmin'), (Select id from aartuser where username='cetesysadmin'));
INSERT INTO specialcircumstance(specialcircumstancetype, cedscode, ksdecode, assessmentprogramid, createduser, modifieduser) VALUES ('Non-special education student used calculator on non-calculator items', 13828, '36', (select id from assessmentprogram where abbreviatedname='KAP'), (Select id from aartuser where username='cetesysadmin'), (Select id from aartuser where username='cetesysadmin'));
INSERT INTO specialcircumstance(specialcircumstancetype, cedscode, ksdecode, assessmentprogramid, createduser, modifieduser) VALUES ('Student used math journal (non-IEP)', 13829, '37', (select id from assessmentprogram where abbreviatedname='KAP'), (Select id from aartuser where username='cetesysadmin'), (Select id from aartuser where username='cetesysadmin'));
INSERT INTO specialcircumstance(specialcircumstancetype, cedscode, ksdecode, assessmentprogramid, createduser, modifieduser) VALUES ('Other - moved during testing', 9999, '41', (select id from assessmentprogram where abbreviatedname='KAP'), (Select id from aartuser where username='cetesysadmin'), (Select id from aartuser where username='cetesysadmin'));
INSERT INTO specialcircumstance(specialcircumstancetype, cedscode, ksdecode, assessmentprogramid, createduser, modifieduser) VALUES ('Incarcerated at adult facility', 13817, '24', (select id from assessmentprogram where abbreviatedname='KAP'), (Select id from aartuser where username='cetesysadmin'), (Select id from aartuser where username='cetesysadmin'));
INSERT INTO specialcircumstance(specialcircumstancetype, cedscode, ksdecode, assessmentprogramid, createduser, modifieduser) VALUES ('Special detention center', 13819, '26', (select id from assessmentprogram where abbreviatedname='KAP'), (Select id from aartuser where username='cetesysadmin'), (Select id from aartuser where username='cetesysadmin'));
INSERT INTO specialcircumstance(specialcircumstancetype, cedscode, ksdecode, assessmentprogramid, createduser, modifieduser) VALUES ('Other', 9999, '39', (select id from assessmentprogram where abbreviatedname='KAP'), (Select id from aartuser where username='cetesysadmin'), (Select id from aartuser where username='cetesysadmin'));
INSERT INTO specialcircumstance(specialcircumstancetype, cedscode, ksdecode, assessmentprogramid, createduser, modifieduser) VALUES ('Parent refusal', 13820, '27', (select id from assessmentprogram where abbreviatedname='KAP'), (Select id from aartuser where username='cetesysadmin'), (Select id from aartuser where username='cetesysadmin'));

INSERT INTO specialcircumstance(specialcircumstancetype, cedscode, assessmentprogramid, createduser, modifieduser) VALUES ('Absent', 3451, (select id from assessmentprogram where abbreviatedname='AMP'), (Select id from aartuser where username='cetesysadmin'), (Select id from aartuser where username='cetesysadmin'));
INSERT INTO specialcircumstance(specialcircumstancetype, cedscode, assessmentprogramid, createduser, modifieduser) VALUES ('Refusal by parent', 3452, (select id from assessmentprogram where abbreviatedname='AMP'), (Select id from aartuser where username='cetesysadmin'), (Select id from aartuser where username='cetesysadmin'));
INSERT INTO specialcircumstance(specialcircumstancetype, cedscode, assessmentprogramid, createduser, modifieduser) VALUES ('Refusal by student', 3453, (select id from assessmentprogram where abbreviatedname='AMP'), (Select id from aartuser where username='cetesysadmin'), (Select id from aartuser where username='cetesysadmin'));
INSERT INTO specialcircumstance(specialcircumstancetype, cedscode, assessmentprogramid, createduser, modifieduser) VALUES ('Medical Waiver', 3454, (select id from assessmentprogram where abbreviatedname='AMP'), (Select id from aartuser where username='cetesysadmin'), (Select id from aartuser where username='cetesysadmin'));

