--dml/472.sql US16990 - TASC
-- New category for TASC Record Type --
insert into category (categoryname, categorycode, categorydescription, createduser, activeflag, modifieduser, categorytypeid) 
values ('TASC Record Type', 'TASC_RECORD_TYPE', 'Record type for TASC records in KIDS web service upload', (Select id from aartuser where username='cetesysadmin'), TRUE, (Select id from aartuser where username='cetesysadmin'), (select id from categorytype where typecode ='WEB_SERVICE_RECORD_TYPE'));

insert into category (categoryname, categorycode, categorydescription, createduser, activeflag, modifieduser, categorytypeid) 
values ('08/16/2015 11:45:00 PM', 'TASC_SCHEDULED_WEB_SERVICE_START_TIME', 'This is the start time from which TASC records were pulled', (Select id from aartuser where username='cetesysadmin'), TRUE, (Select id from aartuser where username='cetesysadmin'), (select id from categorytype where typecode ='WEB_SERVICE_RECORD_TYPE'));

insert into category (categoryname, categorycode, categorydescription, createduser, activeflag, modifieduser, categorytypeid) 
values ('08/17/2015 12:00:00 AM', 'TASC_SCHEDULED_WEB_SERVICE_END_TIME', 'This is the end time untill which TASC records were pulled', (Select id from aartuser where username='cetesysadmin'), TRUE, (Select id from aartuser where username='cetesysadmin'), (select id from categorytype where typecode ='WEB_SERVICE_RECORD_TYPE'));


--FieldSpecifications for XML tags
INSERT INTO fieldspecification (fieldname, allowablevalues, minimum, maximum, fieldlength, rejectifempty, rejectifinvalid, formatregex, showerror,createddate,createduser,activeflag,modifieddate,modifieduser,iskeyvaluepairfield) VALUES ('tascRecordType', '{TASC}', NULL, NULL, 4, true, true, NULL, true,now(),(select id from aartuser where username='cetesysadmin'),true,now(),(select id from aartuser where username='cetesysadmin'),false);
INSERT INTO fieldspecification (fieldname, allowablevalues, minimum, maximum, fieldlength, rejectifempty, rejectifinvalid, formatregex, showerror,createddate,createduser,activeflag,modifieddate,modifieduser,iskeyvaluepairfield) VALUES ('tascAypSchoolIdentifier', NULL, NULL, NULL, 30, true, true, NULL, true,now(),(select id from aartuser where username='cetesysadmin'),true,now(),(select id from aartuser where username='cetesysadmin'),false);
INSERT INTO fieldspecification (fieldname, allowablevalues, minimum, maximum, fieldlength, rejectifempty, rejectifinvalid, formatregex, showerror,createddate,createduser,activeflag,modifieddate,modifieduser,iskeyvaluepairfield) VALUES ('studentLegalFirstName', NULL, NULL, NULL, 60, true, true, NULL, true,now(),(select id from aartuser where username='cetesysadmin'),true,now(),(select id from aartuser where username='cetesysadmin'),false);
INSERT INTO fieldspecification (fieldname, allowablevalues, minimum, maximum, fieldlength, rejectifempty, rejectifinvalid, formatregex, showerror,createddate,createduser,activeflag,modifieddate,modifieduser,iskeyvaluepairfield) VALUES ('studentLegalLastName', NULL, NULL, NULL, 60, true, true, NULL, true,now(),(select id from aartuser where username='cetesysadmin'),true,now(),(select id from aartuser where username='cetesysadmin'),false);
INSERT INTO fieldspecification (fieldname, allowablevalues, minimum, maximum, fieldlength, rejectifempty, rejectifinvalid, formatregex, showerror,createddate,createduser,activeflag,modifieddate,modifieduser,iskeyvaluepairfield) VALUES ('studentLegalMiddleName', NULL, NULL, NULL, 60, false, false, NULL, false,now(),(select id from aartuser where username='cetesysadmin'),true,now(),(select id from aartuser where username='cetesysadmin'),false);
INSERT INTO fieldspecification (fieldname, allowablevalues, minimum, maximum, fieldlength, rejectifempty, rejectifinvalid, formatregex, showerror,createddate,createduser,activeflag,modifieddate,modifieduser,iskeyvaluepairfield) VALUES ('tascStudentGenerationCode', NULL, NULL, NULL, 10, false, false, NULL, false,now(),(select id from aartuser where username='cetesysadmin'),true,now(),(select id from aartuser where username='cetesysadmin'),false);
INSERT INTO fieldspecification (fieldname, allowablevalues, minimum, maximum, fieldlength, rejectifempty, rejectifinvalid, formatregex, showerror,createddate,createduser,activeflag,modifieddate,modifieduser,iskeyvaluepairfield) VALUES ('tascStudentGender', '{0,1}', NULL, NULL, 1, true, true, NULL, true,now(),(select id from aartuser where username='cetesysadmin'),true,now(),(select id from aartuser where username='cetesysadmin'),false);
INSERT INTO fieldspecification (fieldname, allowablevalues, minimum, maximum, fieldlength, rejectifempty, rejectifinvalid, formatregex, showerror,createddate,createduser,activeflag,modifieddate,modifieduser,iskeyvaluepairfield) VALUES ('studentCurrentGradeLevel', '{00,01,02,03,04,05,06,07,08,09,10,11,12,13,14,15,16,17,18}', NULL, NULL, 2, true, true, NULL, true,now(),(select id from aartuser where username='cetesysadmin'),true,now(),(select id from aartuser where username='cetesysadmin'),false);
INSERT INTO fieldspecification (fieldname, allowablevalues, minimum, maximum, fieldlength, rejectifempty, rejectifinvalid, formatregex, showerror,createddate,createduser,activeflag,modifieddate,modifieduser,iskeyvaluepairfield) VALUES ('tascStateStudentIdentifier', NULL, 1, NULL, 10, true, true, '^[A-z0-9!@#$%^&*()-_''"~`:;\[\]{}<>+=\./\ ]++$', true,now(),(select id from aartuser where username='cetesysadmin'),true,now(),(select id from aartuser where username='cetesysadmin'),false);
INSERT INTO fieldspecification (fieldname, allowablevalues, minimum, maximum, fieldlength, rejectifempty, rejectifinvalid, formatregex, showerror,createddate,createduser,activeflag,modifieddate,modifieduser,iskeyvaluepairfield) VALUES ('tascCurrentSchoolYear', NULL, 1900, 2099, 4, true, true, NULL, true,now(),(select id from aartuser where username='cetesysadmin'),true,now(),(select id from aartuser where username='cetesysadmin'),false);
INSERT INTO fieldspecification (fieldname, allowablevalues, minimum, maximum, fieldlength, rejectifempty, rejectifinvalid, formatregex, showerror,createddate,createduser,activeflag,modifieddate,modifieduser,iskeyvaluepairfield) VALUES ('attendanceSchoolIdentifier', NULL, NULL, NULL, 30, true, true, '^[A-z0-9!@#$%^&*()-_''"~`:;\[\]{}<>+=\./\ ]++$', true,now(),(select id from aartuser where username='cetesysadmin'),true,now(),(select id from aartuser where username='cetesysadmin'),false);
INSERT INTO fieldspecification (fieldname, allowablevalues, minimum, maximum, fieldlength, rejectifempty, rejectifinvalid, formatregex, showerror,createddate,createduser,activeflag,modifieddate,modifieduser,iskeyvaluepairfield) VALUES ('educatorSchoolId', NULL, NULL, NULL, 30, true, true, '^[A-z0-9!@#$%^&*()-_''"~`:;\[\]{}<>+=\./\ ]++$', true,now(),(select id from aartuser where username='cetesysadmin'),true,now(),(select id from aartuser where username='cetesysadmin'),false);
INSERT INTO fieldspecification (fieldname, allowablevalues, minimum, maximum, fieldlength, rejectifempty, rejectifinvalid, formatregex, showerror,createddate,createduser,activeflag,modifieddate,modifieduser,iskeyvaluepairfield) VALUES ('tascStateSubjectAreaCode', '{01,02,03,04,05,06,07,08,09,10,11,12,13,14,15,16,17,18,19,20,21,22,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,80,81,82,83,84,85,86,87,88,89,90,92}', NULL, NULL, 17, true, true, NULL, true,now(),(select id from aartuser where username='cetesysadmin'),true,now(),(select id from aartuser where username='cetesysadmin'),false);
INSERT INTO fieldspecification (fieldname, allowablevalues, minimum, maximum, fieldlength, rejectifempty, rejectifinvalid, formatregex, showerror,createddate,createduser,activeflag,modifieddate,modifieduser,iskeyvaluepairfield) VALUES ('tascLocalCourseId', NULL, NULL, NULL, 50, false, false, NULL, false,now(),(select id from aartuser where username='cetesysadmin'),true,now(),(select id from aartuser where username='cetesysadmin'),false);
INSERT INTO fieldspecification (fieldname, allowablevalues, minimum, maximum, fieldlength, rejectifempty, rejectifinvalid, formatregex, showerror,createddate,createduser,activeflag,modifieddate,modifieduser,iskeyvaluepairfield) VALUES ('courseStatus', '{1,99}', NULL, NULL, 2, true, true, NULL, true,now(),(select id from aartuser where username='cetesysadmin'),true,now(),(select id from aartuser where username='cetesysadmin'),false);
INSERT INTO fieldspecification (fieldname, allowablevalues, minimum, maximum, fieldlength, rejectifempty, rejectifinvalid, formatregex, showerror,createddate,createduser,activeflag,modifieddate,modifieduser,iskeyvaluepairfield) VALUES ('tascEducatorIdentifier', NULL, NULL, NULL, 10, true, true, '^[\w~`!#$%^&*_+={};:/?|\-@\.]*$', true,now(),(select id from aartuser where username='cetesysadmin'),true,now(),(select id from aartuser where username='cetesysadmin'),false);
INSERT INTO fieldspecification (fieldname, allowablevalues, minimum, maximum, fieldlength, rejectifempty, rejectifinvalid, formatregex, showerror,createddate,createduser,activeflag,modifieddate,modifieduser,iskeyvaluepairfield) VALUES ('teacherLastName', NULL, NULL, NULL, 60, true, true, NULL, true,now(),(select id from aartuser where username='cetesysadmin'),true,now(),(select id from aartuser where username='cetesysadmin'),false);
INSERT INTO fieldspecification (fieldname, allowablevalues, minimum, maximum, fieldlength, rejectifempty, rejectifinvalid, formatregex, showerror,createddate,createduser,activeflag,modifieddate,modifieduser,iskeyvaluepairfield) VALUES ('teacherFirstName', NULL, NULL, NULL, 60, true, true, NULL, true,now(),(select id from aartuser where username='cetesysadmin'),true,now(),(select id from aartuser where username='cetesysadmin'),false);
INSERT INTO fieldspecification (fieldname, allowablevalues, minimum, maximum, fieldlength, rejectifempty, rejectifinvalid, formatregex, showerror,createddate,createduser,activeflag,modifieddate,modifieduser,iskeyvaluepairfield) VALUES ('teacherMiddleName', NULL, NULL, NULL, 60, false, false, NULL, false,now(),(select id from aartuser where username='cetesysadmin'),true,now(),(select id from aartuser where username='cetesysadmin'),false);
INSERT INTO fieldspecification (fieldname, allowablevalues, minimum, maximum, fieldlength, rejectifempty, rejectifinvalid, formatregex, showerror,createddate,createduser,activeflag,modifieddate,modifieduser,iskeyvaluepairfield) VALUES ('educatorEmailId', NULL, NULL, NULL, 254, false, true, '^[\w~`!#$%^&*_+={};:/?|-]+(\.{0,1}[\w~`!#$%^''&*_+={};:/?|-]+)*@{1}[A-Za-z0-9-]+(\.{0,1}[A-Za-z0-9]+-{0,1})*\.{1}[A-Za-z0-9]{2,}$', true,now(),(select id from aartuser where username='cetesysadmin'),true,now(),(select id from aartuser where username='cetesysadmin'),false);


--FieldSpecificationTypes for XML tags
INSERT INTO fieldspecificationsrecordtypes (fieldspecificationid, recordtypeid, mappedname, createddate,createduser,activeflag,modifieddate,modifieduser) VALUES ((select id from fieldspecification where fieldname = 'tascRecordType'), (select id from category where categorycode = 'TASC_RECORD_TYPE'),'Record_Type',now(),(select id from aartuser where username='cetesysadmin'),true,now(),(select id from aartuser where username='cetesysadmin'));
INSERT INTO fieldspecificationsrecordtypes (fieldspecificationid, recordtypeid, mappedname, createddate,createduser,activeflag,modifieddate,modifieduser) VALUES ((select id from fieldspecification where fieldname = 'tascAypSchoolIdentifier'), (select id from category where categorycode = 'TASC_RECORD_TYPE'),'AYP_QPA_Bldg_No',now(),(select id from aartuser where username='cetesysadmin'),true,now(),(select id from aartuser where username='cetesysadmin'));
INSERT INTO fieldspecificationsrecordtypes (fieldspecificationid, recordtypeid, mappedname, createddate,createduser,activeflag,modifieddate,modifieduser) VALUES ((select id from fieldspecification where fieldname = 'studentLegalFirstName'), (select id from category where categorycode = 'TASC_RECORD_TYPE'),'Student_Legal_First_Name',now(),(select id from aartuser where username='cetesysadmin'),true,now(),(select id from aartuser where username='cetesysadmin'));
INSERT INTO fieldspecificationsrecordtypes (fieldspecificationid, recordtypeid, mappedname, createddate,createduser,activeflag,modifieddate,modifieduser) VALUES ((select id from fieldspecification where fieldname = 'studentLegalLastName'), (select id from category where categorycode = 'TASC_RECORD_TYPE'),'Student_Legal_Last_Name',now(),(select id from aartuser where username='cetesysadmin'),true,now(),(select id from aartuser where username='cetesysadmin'));
INSERT INTO fieldspecificationsrecordtypes (fieldspecificationid, recordtypeid, mappedname, createddate,createduser,activeflag,modifieddate,modifieduser) VALUES ((select id from fieldspecification where fieldname = 'studentLegalMiddleName'), (select id from category where categorycode = 'TASC_RECORD_TYPE'), 'Student_Legal_Middle_Name',now(),(select id from aartuser where username='cetesysadmin'),true,now(),(select id from aartuser where username='cetesysadmin'));
INSERT INTO fieldspecificationsrecordtypes (fieldspecificationid, recordtypeid, mappedname, createddate,createduser,activeflag,modifieddate,modifieduser) VALUES ((select id from fieldspecification where fieldname = 'tascStudentGenerationCode'), (select id from category where categorycode = 'TASC_RECORD_TYPE'),'Student_Generation_Code',now(),(select id from aartuser where username='cetesysadmin'),true,now(),(select id from aartuser where username='cetesysadmin'));
INSERT INTO fieldspecificationsrecordtypes (fieldspecificationid, recordtypeid, mappedname, createddate,createduser,activeflag,modifieddate,modifieduser) VALUES ((select id from fieldspecification where fieldname = 'tascStudentGender'), (select id from category where categorycode = 'TASC_RECORD_TYPE'),'Student_Gender',now(),(select id from aartuser where username='cetesysadmin'),true,now(),(select id from aartuser where username='cetesysadmin'));
INSERT INTO fieldspecificationsrecordtypes (fieldspecificationid, recordtypeid, mappedname, createddate,createduser,activeflag,modifieddate,modifieduser) VALUES ((select id from fieldspecification where fieldname = 'studentCurrentGradeLevel'), (select id from category where categorycode = 'TASC_RECORD_TYPE'),'Current_Grade_Level',now(),(select id from aartuser where username='cetesysadmin'),true,now(),(select id from aartuser where username='cetesysadmin'));
INSERT INTO fieldspecificationsrecordtypes (fieldspecificationid, recordtypeid, mappedname, createddate,createduser,activeflag,modifieddate,modifieduser) VALUES ((select id from fieldspecification where fieldname = 'tascStateStudentIdentifier'), (select id from category where categorycode = 'TASC_RECORD_TYPE'),'State_Student_Identifier',now(),(select id from aartuser where username='cetesysadmin'),true,now(),(select id from aartuser where username='cetesysadmin'));
INSERT INTO fieldspecificationsrecordtypes (fieldspecificationid, recordtypeid, mappedname, createddate,createduser,activeflag,modifieddate,modifieduser) VALUES ((select id from fieldspecification where fieldname = 'tascCurrentSchoolYear'), (select id from category where categorycode = 'TASC_RECORD_TYPE'),'Current_School_Year',now(),(select id from aartuser where username='cetesysadmin'),true,now(),(select id from aartuser where username='cetesysadmin'));
INSERT INTO fieldspecificationsrecordtypes (fieldspecificationid, recordtypeid, mappedname, createddate,createduser,activeflag,modifieddate,modifieduser) VALUES ((select id from fieldspecification where fieldname = 'attendanceSchoolIdentifier'), (select id from category where categorycode = 'TASC_RECORD_TYPE'),'Attendance_Bldg_No',now(),(select id from aartuser where username='cetesysadmin'),true,now(),(select id from aartuser where username='cetesysadmin'));
INSERT INTO fieldspecificationsrecordtypes (fieldspecificationid, recordtypeid, mappedname, createddate,createduser,activeflag,modifieddate,modifieduser) VALUES ((select id from fieldspecification where fieldname = 'educatorSchoolId'), (select id from category where categorycode = 'TASC_RECORD_TYPE'),'Educator_Bldg_No',now(),(select id from aartuser where username='cetesysadmin'),true,now(),(select id from aartuser where username='cetesysadmin'));
INSERT INTO fieldspecificationsrecordtypes (fieldspecificationid, recordtypeid, mappedname, createddate,createduser,activeflag,modifieddate,modifieduser) VALUES ((select id from fieldspecification where fieldname = 'tascStateSubjectAreaCode'), (select id from category where categorycode = 'TASC_RECORD_TYPE'),'State_Subj_Area_Code',now(),(select id from aartuser where username='cetesysadmin'),true,now(),(select id from aartuser where username='cetesysadmin'));
INSERT INTO fieldspecificationsrecordtypes (fieldspecificationid, recordtypeid, mappedname, createddate,createduser,activeflag,modifieddate,modifieduser) VALUES ((select id from fieldspecification where fieldname = 'tascLocalCourseId'), (select id from category where categorycode = 'TASC_RECORD_TYPE'),'Local_Course_ID',now(),(select id from aartuser where username='cetesysadmin'),true,now(),(select id from aartuser where username='cetesysadmin'));
INSERT INTO fieldspecificationsrecordtypes (fieldspecificationid, recordtypeid, mappedname, createddate,createduser,activeflag,modifieddate,modifieduser) VALUES ((select id from fieldspecification where fieldname = 'courseStatus'), (select id from category where categorycode = 'TASC_RECORD_TYPE'),'Course_Status',now(),(select id from aartuser where username='cetesysadmin'),true,now(),(select id from aartuser where username='cetesysadmin'));
INSERT INTO fieldspecificationsrecordtypes (fieldspecificationid, recordtypeid, mappedname, createddate,createduser,activeflag,modifieddate,modifieduser) VALUES ((select id from fieldspecification where fieldname = 'tascEducatorIdentifier'), (select id from category where categorycode = 'TASC_RECORD_TYPE'),'Teacher_Identifier',now(),(select id from aartuser where username='cetesysadmin'),true,now(),(select id from aartuser where username='cetesysadmin'));
INSERT INTO fieldspecificationsrecordtypes (fieldspecificationid, recordtypeid, mappedname, createddate,createduser,activeflag,modifieddate,modifieduser) VALUES ((select id from fieldspecification where fieldname = 'teacherLastName'), (select id from category where categorycode = 'TASC_RECORD_TYPE'),'Teacher_Last_Name',now(),(select id from aartuser where username='cetesysadmin'),true,now(),(select id from aartuser where username='cetesysadmin'));
INSERT INTO fieldspecificationsrecordtypes (fieldspecificationid, recordtypeid, mappedname, createddate,createduser,activeflag,modifieddate,modifieduser) VALUES ((select id from fieldspecification where fieldname = 'teacherFirstName'), (select id from category where categorycode = 'TASC_RECORD_TYPE'),'Teacher_First_Name',now(),(select id from aartuser where username='cetesysadmin'),true,now(),(select id from aartuser where username='cetesysadmin'));
INSERT INTO fieldspecificationsrecordtypes (fieldspecificationid, recordtypeid, mappedname, createddate,createduser,activeflag,modifieddate,modifieduser) VALUES ((select id from fieldspecification where fieldname = 'teacherMiddleName'), (select id from category where categorycode = 'TASC_RECORD_TYPE'),'Teacher_Middle_Name',now(),(select id from aartuser where username='cetesysadmin'),true,now(),(select id from aartuser where username='cetesysadmin'));
INSERT INTO fieldspecificationsrecordtypes (fieldspecificationid, recordtypeid, mappedname, createddate,createduser,activeflag,modifieddate,modifieduser) VALUES ((select id from fieldspecification where fieldname = 'educatorEmailId'), (select id from category where categorycode = 'TASC_RECORD_TYPE'),'Teacher_District_Email',now(),(select id from aartuser where username='cetesysadmin'),true,now(),(select id from aartuser where username='cetesysadmin'));



