
--US12808 Name:  Auto registration - Auto register General population

INSERT INTO testtype(testtypecode,testtypename,assessmentid,createdate,createduser,modifieddate,modifieduser) VALUES ('1','General - Paper/English',(select id from assessment where assessmentcode = 'G'),now(), (select id from aartuser where username='cetesysadmin'), now(), (select id from aartuser where username='cetesysadmin'));
INSERT INTO testtype(testtypecode,testtypename,assessmentid,createdate,createduser,modifieddate,modifieduser) VALUES ('2','General - Computer/English',(select id from assessment where assessmentcode = 'G'),now(), (select id from aartuser where username='cetesysadmin'), now(), (select id from aartuser where username='cetesysadmin'));
INSERT INTO testtype(testtypecode,testtypename,assessmentid,createdate,createduser,modifieddate,modifieduser) VALUES ('6','General - Paper/Spanish',(select id from assessment where assessmentcode = 'G'),now(), (select id from aartuser where username='cetesysadmin'), now(), (select id from aartuser where username='cetesysadmin'));
INSERT INTO testtype(testtypecode,testtypename,assessmentid,createdate,createduser,modifieddate,modifieduser) VALUES ('7','General - Computer/Spanish',(select id from assessment where assessmentcode = 'G'),now(), (select id from aartuser where username='cetesysadmin'), now(), (select id from aartuser where username='cetesysadmin'));
INSERT INTO testtype(testtypecode,testtypename,assessmentid,createdate,createduser,modifieddate,modifieduser) VALUES ('8','General - Braille/English',(select id from assessment where assessmentcode = 'G'),now(), (select id from aartuser where username='cetesysadmin'), now(), (select id from aartuser where username='cetesysadmin'));
INSERT INTO testtype(testtypecode,testtypename,assessmentid,createdate,createduser,modifieddate,modifieduser) VALUES ('D','General - Computer/English/Deaf/Hard of Hearing',(select id from assessment where assessmentcode = 'G'),now(), (select id from aartuser where username='cetesysadmin'), now(), (select id from aartuser where username='cetesysadmin'));
INSERT INTO testtype(testtypecode,testtypename,assessmentid,createdate,createduser,modifieddate,modifieduser) VALUES ('A','General - Audio/Computer',(select id from assessment where assessmentcode = 'G'),now(), (select id from aartuser where username='cetesysadmin'), now(), (select id from aartuser where username='cetesysadmin'));
INSERT INTO testtype(testtypecode,testtypename,assessmentid,createdate,createduser,modifieddate,modifieduser) VALUES ('X','General - Spanish Side by Side English',(select id from assessment where assessmentcode = 'G'),now(), (select id from aartuser where username='cetesysadmin'), now(), (select id from aartuser where username='cetesysadmin'));
INSERT INTO testtype(testtypecode,testtypename,assessmentid,createdate,createduser,modifieddate,modifieduser) VALUES ('R','General - Read Aloud/Individual/Computer',(select id from assessment where assessmentcode = 'G'),now(), (select id from aartuser where username='cetesysadmin'), now(), (select id from aartuser where username='cetesysadmin'));
INSERT INTO testtype(testtypecode,testtypename,assessmentid,createdate,createduser,modifieddate,modifieduser) VALUES ('F','General - Read Aloud/Individual/Computer/Spanish',(select id from assessment where assessmentcode = 'G'),now(), (select id from aartuser where username='cetesysadmin'), now(), (select id from aartuser where username='cetesysadmin'));
INSERT INTO testtype(testtypecode,testtypename,assessmentid,createdate,createduser,modifieddate,modifieduser) VALUES ('S','General - Read Aloud/Individual/paper',(select id from assessment where assessmentcode = 'G'),now(), (select id from aartuser where username='cetesysadmin'), now(), (select id from aartuser where username='cetesysadmin'));
INSERT INTO testtype(testtypecode,testtypename,assessmentid,createdate,createduser,modifieddate,modifieduser) VALUES ('P','General - Read Aloud/Individual/paper/Spanish',(select id from assessment where assessmentcode = 'G'),now(), (select id from aartuser where username='cetesysadmin'), now(), (select id from aartuser where username='cetesysadmin'));
INSERT INTO testtype(testtypecode,testtypename,assessmentid,createdate,createduser,modifieddate,modifieduser) VALUES ('T','General - Read Aloud/Group/Computer',(select id from assessment where assessmentcode = 'G'),now(), (select id from aartuser where username='cetesysadmin'), now(), (select id from aartuser where username='cetesysadmin'));
INSERT INTO testtype(testtypecode,testtypename,assessmentid,createdate,createduser,modifieddate,modifieduser) VALUES ('G','General - Read Aloud/Group/Computer/Spanish',(select id from assessment where assessmentcode = 'G'),now(), (select id from aartuser where username='cetesysadmin'), now(), (select id from aartuser where username='cetesysadmin'));
INSERT INTO testtype(testtypecode,testtypename,assessmentid,createdate,createduser,modifieddate,modifieduser) VALUES ('U','General - Read Aloud/Group/Paper',(select id from assessment where assessmentcode = 'G'),now(), (select id from aartuser where username='cetesysadmin'), now(), (select id from aartuser where username='cetesysadmin'));
INSERT INTO testtype(testtypecode,testtypename,assessmentid,createdate,createduser,modifieddate,modifieduser) VALUES ('H','General - Read Aloud/Group/Paper/Spanish',(select id from assessment where assessmentcode = 'G'),now(), (select id from aartuser where username='cetesysadmin'), now(), (select id from aartuser where username='cetesysadmin'));
INSERT INTO testtype(testtypecode,testtypename,assessmentid,createdate,createduser,modifieddate,modifieduser) VALUES ('L','General - Large Print/English',(select id from assessment where assessmentcode = 'G'),now(), (select id from aartuser where username='cetesysadmin'), now(), (select id from aartuser where username='cetesysadmin'));

INSERT INTO subjectarea(subjectareacode,subjectareaname,createdate,createduser,modifieddate,modifieduser) VALUES ('D74','State Mathematics Assessment',now(), (select id from aartuser where username='cetesysadmin'), now(), (select id from aartuser where username='cetesysadmin'));	
INSERT INTO subjectarea(subjectareacode,subjectareaname,createdate,createduser,modifieddate,modifieduser) VALUES ('D75','State Reading Assessment',now(), (select id from aartuser where username='cetesysadmin'), now(), (select id from aartuser where username='cetesysadmin'));	
INSERT INTO subjectarea(subjectareacode,subjectareaname,createdate,createduser,modifieddate,modifieduser) VALUES ('D76','K-8 State Science Assessment',now(), (select id from aartuser where username='cetesysadmin'), now(), (select id from aartuser where username='cetesysadmin'));	
INSERT INTO subjectarea(subjectareacode,subjectareaname,createdate,createduser,modifieddate,modifieduser) VALUES ('D77','High School  State Life Science Assessment',now(), (select id from aartuser where username='cetesysadmin'), now(), (select id from aartuser where username='cetesysadmin'));	
INSERT INTO subjectarea(subjectareacode,subjectareaname,createdate,createduser,modifieddate,modifieduser) VALUES ('D78','High School State Physical Science Assessment',now(), (select id from aartuser where username='cetesysadmin'), now(), (select id from aartuser where username='cetesysadmin'));	
INSERT INTO subjectarea(subjectareacode,subjectareaname,createdate,createduser,modifieddate,modifieduser) VALUES ('D79','K-8 State History/Gov Assessment',now(), (select id from aartuser where username='cetesysadmin'), now(), (select id from aartuser where username='cetesysadmin'));	
INSERT INTO subjectarea(subjectareacode,subjectareaname,createdate,createduser,modifieddate,modifieduser) VALUES ('D80','High School State History/Gov. Assessment: World Focus',now(), (select id from aartuser where username='cetesysadmin'), now(), (select id from aartuser where username='cetesysadmin'));	
INSERT INTO subjectarea(subjectareacode,subjectareaname,createdate,createduser,modifieddate,modifieduser) VALUES ('D81','High School State History/Gov. Assessment: U.S.  Focus',now(), (select id from aartuser where username='cetesysadmin'), now(), (select id from aartuser where username='cetesysadmin'));	
INSERT INTO subjectarea(subjectareacode,subjectareaname,createdate,createduser,modifieddate,modifieduser) VALUES ('D82','State Writing Assessment',now(), (select id from aartuser where username='cetesysadmin'), now(), (select id from aartuser where username='cetesysadmin'));	
INSERT INTO subjectarea(subjectareacode,subjectareaname,createdate,createduser,modifieddate,modifieduser) VALUES ('D83','Kansas English Language Proficiency Assessment (KELPA)',now(), (select id from aartuser where username='cetesysadmin'), now(), (select id from aartuser where username='cetesysadmin'));


INSERT INTO testtypesubjectarea(testtypeid,subjectareaid,createdate,createduser,modifieddate,modifieduser) VALUES 
	((select id from testtype where testtypecode = '2'), (select id from subjectarea where subjectareacode = 'D74'),now(), (select id from aartuser where username='cetesysadmin'), now(), (select id from aartuser where username='cetesysadmin'));
INSERT INTO testtypesubjectarea(testtypeid,subjectareaid,createdate,createduser,modifieddate,modifieduser) VALUES 
	((select id from testtype where testtypecode = '2') , (select id from subjectarea where subjectareacode = 'D75'),now(), (select id from aartuser where username='cetesysadmin'), now(), (select id from aartuser where username='cetesysadmin'));


INSERT INTO contentareatesttypesubjectarea(contentareaid,testtypesubjectareaid,createdate,createduser,modifieddate,modifieduser) VALUES 
	( (select id from contentarea where abbreviatedname = 'M' order by modifieddate desc limit 1),(select id from testtypesubjectarea where testtypeid = (select id from testtype where testtypecode = '2') and subjectareaid = (select id from subjectarea where subjectareacode = 'D74')),
	now(), (select id from aartuser where username='cetesysadmin'), now(), (select id from aartuser where username='cetesysadmin'));


INSERT INTO contentareatesttypesubjectarea(contentareaid,testtypesubjectareaid,createdate,createduser,modifieddate,modifieduser) VALUES 
	( (select id from contentarea where abbreviatedname = 'ELA' order by modifieddate desc limit 1),(select id from testtypesubjectarea where testtypeid = (select id from testtype where testtypecode = '2') and subjectareaid = (select id from subjectarea where subjectareacode = 'D75')),
	now(), (select id from aartuser where username='cetesysadmin'), now(), (select id from aartuser where username='cetesysadmin'));
	
