--dml/675.sql 
-- Updating the reporlt label as is provided in excel sheet.
update surveylabel set reportlabel='Special Education_Special Education Services_Primary Disability' where labelnumber = 'Q16';
update surveylabel set reportlabel='Special Education_Special Education Services_Educational Placement' where labelnumber = 'Q17';
update surveylabel set reportlabel='Sensory Capabilities_Hearing' where labelnumber = 'Q19';
update surveylabel set reportlabel='Sensory Capabilities_Hearing_Classification of Hearing Impairment' where labelnumber = 'Q330';
update surveylabel set reportlabel='Sensory Capabilities_Hearing_Uses personal or classroom amplification' where labelnumber = 'Q20_1';
update surveylabel set reportlabel='Sensory Capabilities_Hearing_Uses unilateral hearing aid' where labelnumber = 'Q20_2';
update surveylabel set reportlabel='Sensory Capabilities_Hearing_Uses bilateral hearing aid' where labelnumber = 'Q20_3';
update surveylabel set reportlabel='Sensory Capabilities_Hearing_Has cochlear implant' where labelnumber = 'Q20_4';
update surveylabel set reportlabel='Sensory Capabilities_Hearing_Uses oral language' where labelnumber = 'Q20_5';
update surveylabel set reportlabel='Sensory Capabilities_Hearing_Uses sign language' where labelnumber = 'Q20_6';
update surveylabel set reportlabel='Sensory Capabilities_Vision' where labelnumber = 'Q22';
update surveylabel set reportlabel='Sensory Capabilities_Vision_Classification_Low Vision' where labelnumber = 'Q429_1';
update surveylabel set reportlabel='Sensory Capabilities_Vision_Classification_Legally Blind' where labelnumber = 'Q429_2';
update surveylabel set reportlabel='Sensory Capabilities_Vision_Classification_Light Perception Only' where labelnumber = 'Q429_3';
update surveylabel set reportlabel='Sensory Capabilities_Vision_Classification_Totally Blind' where labelnumber = 'Q429_4';
update surveylabel set reportlabel='Sensory Capabilities_Vision_Classification_Cortical Visual Impairment' where labelnumber = 'Q429_5';
update surveylabel set reportlabel='Sensory Capabilities_Vision_Requires enlarged print' where labelnumber = 'Q23_1';
update surveylabel set reportlabel='Sensory Capabilities_Vision_Requires tactical media' where labelnumber = 'Q23_2';
update surveylabel set reportlabel='Sensory Capabilities_Vision_Requires or uses Braille' where labelnumber = 'Q23_3';
update surveylabel set reportlabel='Sensory Capabilities_Vision_Requires or uses Braille_Uncontracted Braille' where labelnumber = 'Q24_1';
update surveylabel set reportlabel='Sensory Capabilities_Vision_Requires or uses Braille_Contracted Braille' where labelnumber = 'Q24_2';
update surveylabel set reportlabel='Sensory Capabilities_Vision_Requires or uses Braille_UEB' where labelnumber = 'Q24_3';
update surveylabel set reportlabel='Sensory Capabilities_Vision_Technological Visual Aids_Screen magnification device or software' where labelnumber = 'Q25_1';
update surveylabel set reportlabel='Sensory Capabilities_Vision_Technological Visual Aids_CCTV' where labelnumber = 'Q25_2';
update surveylabel set reportlabel='Sensory Capabilities_Vision_Technological Visual Aids_Screen reader and/or talking word processor' where labelnumber = 'Q25_3';
update surveylabel set reportlabel='Sensory Capabilities_Vision_Technological Visual Aids_Manual or Electronic Braille writing device' where labelnumber = 'Q25_4';
update surveylabel set reportlabel='Sensory Capabilities_Vision_Technological Visual Aids_Device with refreshable Braille display' where labelnumber = 'Q25_5';
update surveylabel set reportlabel='Motor Capabilities_Arm/Hand Control and Health_Uses two hands together to perform tasks' where labelnumber = 'Q29_1';
update surveylabel set reportlabel='Motor Capabilities_Arm/Hand Control and Health_Uses only one hand to perform tasks' where labelnumber = 'Q29_2';
update surveylabel set reportlabel='Motor Capabilities_Arm/Hand Control and Health_Requires physical assistance to perform tasks with hands' where labelnumber = 'Q29_3';
update surveylabel set reportlabel='Motor Capabilities_Arm/Hand Control and Health_Cannot use hands to complete tasks even with assistance' where labelnumber = 'Q29_4';
update surveylabel set reportlabel='Motor Capabilities_Arm/Hand Control and Health_Health issues that interfere with instruction or assessment?' where labelnumber = 'Q200';
update surveylabel set reportlabel='Computer Instruction_Computer Access and Attention During Instruction_Computer Use' where labelnumber = 'Q143';
update surveylabel set reportlabel='Computer Instruction_Computer Access and Attention During Instruction_Why has this student not had the opportunity to access a computer during instruction?' where labelnumber = 'Q147';
update surveylabel set reportlabel='Computer Instruction_Computer Access and Attention During Instruction_Computer access during instruction_Standard computer keyboard' where labelnumber = 'Q33_1';
update surveylabel set reportlabel='Computer Instruction_Computer Access and Attention During Instruction_Computer access during instruction_Keyboard with large keys or alternative keyboard ' where labelnumber = 'Q33_3';
update surveylabel set reportlabel='Computer Instruction_Computer Access and Attention During Instruction_Computer access during instruction_Touch screen' where labelnumber = 'Q33_5';
update surveylabel set reportlabel='Computer Instruction_Computer Access and Attention During Instruction_Computer access during instruction_Standard mouse or head mouse' where labelnumber = 'Q33_6';
update surveylabel set reportlabel='Computer Instruction_Computer Access and Attention During Instruction_Computer access during instruction_Eye gaze technology' where labelnumber = 'Q33_8';
update surveylabel set reportlabel='Computer Instruction_Computer Access and Attention During Instruction_Computer access during instruction_Scanning with switches' where labelnumber = 'Q33_11';
update surveylabel set reportlabel='Computer Instruction_Computer Access and Attention During Instruction_Level of attention to computer-directed instruction' where labelnumber = 'Q201';
update surveylabel set reportlabel='Computer Instruction_Computer Access and Attention During Instruction_Level of attention to teacher-directed instruction' where labelnumber = 'Q202';
update surveylabel set reportlabel='Communication_Expressive Communication_Does the student use speech to meet expressive communication needs?' where labelnumber = 'Q36';
update surveylabel set reportlabel='Communication_Expressive Communication_Highest statement that describes the student''s expressive communication with speech' where labelnumber = 'Q37';
update surveylabel set reportlabel='Communication_Expressive Communication_Does the student use sign language in addition to or in place of speech to meet expressive communication needs?' where labelnumber = 'Q39';
update surveylabel set reportlabel='Communication_Expressive Communication_Choose the highest statement that describes the student''s expressive communication with sign language' where labelnumber = 'Q40';
update surveylabel set reportlabel='Communication_Expressive Communication_Student''s primary sign system' where labelnumber = 'Q41';
update surveylabel set reportlabel='Communication_Expressive Communication_Does the student use augmentative or alternative communication in addition to or in place of speech or sign language to meet expressive communication needs?' where labelnumber = 'Q43';
update surveylabel set reportlabel='Communication_Expressive Communication_Highest statement that describes the student''s expressive communication with augmentative or alternative communication' where labelnumber = 'Q44';
update surveylabel set reportlabel='Communication_Expressive Communication_How many symbols does the student choose from when communicating?' where labelnumber = 'Q210';
update surveylabel set reportlabel='Communication_Expressive Communication_What types of symbols does the student use?_Real objects' where labelnumber = 'Q211_1';
update surveylabel set reportlabel='Communication_Expressive Communication_What types of symbols does the student use?_Tactual symbols' where labelnumber = 'Q211_2';
update surveylabel set reportlabel='Communication_Expressive Communication_What types of symbols does the student use?_Photos' where labelnumber = 'Q211_3';
update surveylabel set reportlabel='Communication_Expressive Communication_What types of symbols does the student use?_Line drawing symbol sets' where labelnumber = 'Q211_4';
update surveylabel set reportlabel='Communication_Expressive Communication_What types of symbols does the student use?_Text Only' where labelnumber = 'Q211_5';
update surveylabel set reportlabel='Communication_Expressive Communication_What voice output technology does the student use?_ Single message devices' where labelnumber = 'Q300_1';
update surveylabel set reportlabel='Communication_Expressive Communication_What voice output technology does the student use?_Simple devices ' where labelnumber = 'Q300_2';
update surveylabel set reportlabel='Communication_Expressive Communication_What voice output technology does the student use?_Speech generating device' where labelnumber = 'Q300_3';
update surveylabel set reportlabel='Communication_Expressive Communication_What voice output technology does the student use?_None' where labelnumber = 'Q300_4';
update surveylabel set reportlabel='Communication_Expressive Communication_If the student does not use speech, sign language, or augmentative or alternative communication, which of the following statements best describes the students expressive communication?' where labelnumber = 'Q47';
update surveylabel set reportlabel='Communication_Receptive Communication_Can point to, look at, or touch things in the immediate vicinity when asked' where labelnumber = 'Q491';
update surveylabel set reportlabel='Communication_Receptive Communication_Can perform simple actions, movements or activities when asked' where labelnumber = 'Q492';
update surveylabel set reportlabel='Communication_Receptive Communication_Responds appropriately in any modality when offered a favored item that is not present or visible ' where labelnumber = 'Q493';
update surveylabel set reportlabel='Communication_Receptive Communication_Responds appropriately in any modality to single words that are spoken or signed' where labelnumber = 'Q494';
update surveylabel set reportlabel='Communication_Receptive Communication_Responds appropriately in any modality to phrases and sentences that are spoken or signed' where labelnumber = 'Q495';
update surveylabel set reportlabel='Communication_Receptive Communication_Follows 2-step directions presented verbally or through sign' where labelnumber = 'Q496';
update surveylabel set reportlabel='Language_Primary Language_Is English the student''s primary language?' where labelnumber = 'Q501';
update surveylabel set reportlabel='Language_Primary Language_Is English the primary language spoken in the student''s home?' where labelnumber = 'Q502';
update surveylabel set reportlabel='Language_Primary Language_Is English the primary language used for the student''s instruction?' where labelnumber = 'Q503';
update surveylabel set reportlabel='Academic_Reading Skills_Recognizes single symbols presented visually or tactually' where labelnumber = 'Q511';
update surveylabel set reportlabel='Academic_Reading Skills_Understands purpose of print or Braille but not necessarily by manipulating a book' where labelnumber = 'Q512';
update surveylabel set reportlabel='Academic_Reading Skills_Matches sounds to symbols or signs to symbols' where labelnumber = 'Q513';
update surveylabel set reportlabel='Academic_Reading Skills_Reads words, phrases, or sentences in print or Braille when symbols are provided with the words' where labelnumber = 'Q514';
update surveylabel set reportlabel='Academic_Reading Skills_Identifies individual words without symbol support' where labelnumber = 'Q515';
update surveylabel set reportlabel='Academic_Reading Skills_Reads text presented in print or Braille without symbol support but WITHOUT comprehension' where labelnumber = 'Q516';
update surveylabel set reportlabel='Academic_Reading Skills_Reads text presented in print or Braille without symbol support and WITH comprehension' where labelnumber = 'Q517';
update surveylabel set reportlabel='Academic_Reading Skills_Explains or elaborates on text read in print or Braille' where labelnumber = 'Q518';
update surveylabel set reportlabel='Academic_Reading Skills_Student''s approximate instructional level of reading text with comprehension' where labelnumber = 'Q52';
update surveylabel set reportlabel='Academic_Math Skills_Creates or matches patterns of objects or images' where labelnumber = 'Q541';
update surveylabel set reportlabel='Academic_Math Skills_Identifies simple shapes in 2 or 3 dimensions' where labelnumber = 'Q542';
update surveylabel set reportlabel='Academic_Math Skills_Sorts objects by common properties' where labelnumber = 'Q543';
update surveylabel set reportlabel='Academic_Math Skills_Counts more than two objects' where labelnumber = 'Q544';
update surveylabel set reportlabel='Academic_Math Skills_Adds or subtracts by joining or separating groups of objects' where labelnumber = 'Q545';
update surveylabel set reportlabel='Academic_Math Skills_Adds and/or subtracts using numerals' where labelnumber = 'Q546';
update surveylabel set reportlabel='Academic_Math Skills_Forms groups of objects for multiplication or division' where labelnumber = 'Q547';
update surveylabel set reportlabel='Academic_Math Skills_Multiplies and/or divides using numerals' where labelnumber = 'Q548';
update surveylabel set reportlabel='Academic_Math Skills_Uses an abacus' where labelnumber = 'Q549';
update surveylabel set reportlabel='Academic_Math Skills_Uses a calculator' where labelnumber = 'Q5410';
update surveylabel set reportlabel='Academic_Math Skills_Tells time using an analog or digital clock' where labelnumber = 'Q5411';
update surveylabel set reportlabel='Academic_Math Skills_Uses common measuring tools ' where labelnumber = 'Q5412';
update surveylabel set reportlabel='Academic_Math Skills_Uses a schedule, agenda, or calendar to identify or anticipate sequence of activities' where labelnumber = 'Q5413';
update surveylabel set reportlabel='Academic_Writing Skills_Highest level that describes the student''s writing skills' where labelnumber = 'Q500';
update surveylabel set reportlabel='Academic_Science Skills_Sorts objects or materials by common properties' where labelnumber = 'Q212_1';
update surveylabel set reportlabel='Academic_Science Skills_Identifies similarities and differences' where labelnumber = 'Q212_2';
update surveylabel set reportlabel='Academic_Science Skills_Recognizes patterns' where labelnumber = 'Q212_3';
update surveylabel set reportlabel='Academic_Science Skills_Compares initial and final conditions to determine if something changed.' where labelnumber = 'Q212_4';
update surveylabel set reportlabel='Academic_Science Skills_Uses data to answer questions.' where labelnumber = 'Q212_5';
update surveylabel set reportlabel='Academic_Science Skills_Identifies evidence that supports a claim.' where labelnumber = 'Q212_6';
update surveylabel set reportlabel='Academic_Science Skills_Identifies cause and effect relationships.' where labelnumber = 'Q212_7';
update surveylabel set reportlabel='Academic_Science Skills_Uses diagrams to explain phenomena.' where labelnumber = 'Q212_8';

-- ITI science flag premissions options in reports set up tab
Select * from reportassessmentprogram_fn('DLM','ALT_CR','Sci','VIEW_ALTERNATE_ROSTER_REPORT');
Select * from reportassessmentprogram_fn('DLM','ALT_ST','Sci','VIEW_ALTERNATE_STUDENT_REPORT');

update reportassessmentprogram set readytoview = true, modifieddate = now() where reporttypeid in (select id from category where categorycode in ('ALT_CR', 'ALT_ST') and categorytypeid in (select id from categorytype
 where typecode = 'REPORT_TYPES_UI')) and subjectid = (select id from contentarea where abbreviatedname = 'Sci');