--dml/694.sql

INSERT INTO categorytype(
            typename, typecode, typedescription, externalid, originationcode, 
            createddate, createduser, activeflag, modifieddate, modifieduser)
select   'TIMEZONE' typename,
         'TIMEZONE' typecode,
         'TIMEZONE' typedescription, 
          null externalid,
          null originationcode, 
          now()  createddate,
          (select id from aartuser  where email='cete@ku.edu') createduser,
          true activeflag,
          now() modifieddate, 
          (Select id from aartuser  where email='cete@ku.edu') modifieduser ;

insert into category (categoryname, categorycode, categorydescription, categorytypeid, createduser,modifieduser,activeflag)
values
('Hawaii', 'US/Hawaii', 'HT', ( select id from categorytype where typecode='TIMEZONE'), (select id from aartuser  where email='cete@ku.edu'), (select id from aartuser  where email='cete@ku.edu'),true),
('Alaska', 'US/Alaska', 'AT', ( select id from categorytype where typecode='TIMEZONE'), (select id from aartuser  where email='cete@ku.edu'), ( select id from aartuser  where email='cete@ku.edu'), true),
('Pacific', 'US/Pacific', 'PT', ( select id from categorytype where typecode='TIMEZONE'), (select id from aartuser  where email='cete@ku.edu'), ( select id from aartuser  where email='cete@ku.edu'), true),
('Mountain', 'US/Mountain', 'MT', ( select id from categorytype where typecode='TIMEZONE'), (select id from aartuser  where email='cete@ku.edu'), ( select id from aartuser  where email='cete@ku.edu'),true),
('Central', 'US/Central', 'CT', ( select id from categorytype where typecode='TIMEZONE'), (select id from aartuser  where email='cete@ku.edu'), ( select id from aartuser  where email='cete@ku.edu'),true),
('Eastern', 'US/Eastern', 'ET', ( select id from categorytype where typecode='TIMEZONE'), (select id from aartuser  where email='cete@ku.edu'), ( select id from aartuser  where email='cete@ku.edu'),true);

update organization  
set timezoneid =(select id from category where categorytypeid=( select id from categorytype where typecode='TIMEZONE') and categorycode='US/Central');

update organization  
set timezoneid =(select id from category where categorytypeid=( select id from categorytype where typecode='TIMEZONE') and categorycode='US/Eastern')
where id in ( select schoolid from organizationtreedetail where statedisplayidentifier in ('NY','NJ'));


UPDATE organization o SET timezoneid = (SELECT c.id FROM categorytype ct JOIN category c ON ct.id = c.categorytypeid WHERE ct.typecode = 'TIMEZONE' AND c.categoryname = 'Mountain') WHERE o.displayidentifier = '0136' AND (SELECT displayidentifier FROM organization_parent(o.id) WHERE organizationtypeid = (SELECT id FROM organizationtype WHERE typecode = 'DT')) = 'D0200' AND (SELECT displayidentifier FROM organization_parent(o.id) WHERE organizationtypeid = (SELECT id FROM organizationtype WHERE typecode = 'ST')) = 'KS';
UPDATE organization o SET timezoneid = (SELECT c.id FROM categorytype ct JOIN category c ON ct.id = c.categorytypeid WHERE ct.typecode = 'TIMEZONE' AND c.categoryname = 'Mountain') WHERE o.displayidentifier = '0132' AND (SELECT displayidentifier FROM organization_parent(o.id) WHERE organizationtypeid = (SELECT id FROM organizationtype WHERE typecode = 'DT')) = 'D0200' AND (SELECT displayidentifier FROM organization_parent(o.id) WHERE organizationtypeid = (SELECT id FROM organizationtype WHERE typecode = 'ST')) = 'KS';
UPDATE organization o SET timezoneid = (SELECT c.id FROM categorytype ct JOIN category c ON ct.id = c.categorytypeid WHERE ct.typecode = 'TIMEZONE' AND c.categoryname = 'Mountain') WHERE o.displayidentifier = '0134' AND (SELECT displayidentifier FROM organization_parent(o.id) WHERE organizationtypeid = (SELECT id FROM organizationtype WHERE typecode = 'DT')) = 'D0200' AND (SELECT displayidentifier FROM organization_parent(o.id) WHERE organizationtypeid = (SELECT id FROM organizationtype WHERE typecode = 'ST')) = 'KS';
UPDATE organization o SET timezoneid = (SELECT c.id FROM categorytype ct JOIN category c ON ct.id = c.categorytypeid WHERE ct.typecode = 'TIMEZONE' AND c.categoryname = 'Mountain') WHERE o.displayidentifier = '0130' AND (SELECT displayidentifier FROM organization_parent(o.id) WHERE organizationtypeid = (SELECT id FROM organizationtype WHERE typecode = 'DT')) = 'D0200' AND (SELECT displayidentifier FROM organization_parent(o.id) WHERE organizationtypeid = (SELECT id FROM organizationtype WHERE typecode = 'ST')) = 'KS';
UPDATE organization o SET timezoneid = (SELECT c.id FROM categorytype ct JOIN category c ON ct.id = c.categorytypeid WHERE ct.typecode = 'TIMEZONE' AND c.categoryname = 'Mountain') WHERE o.displayidentifier = '0133' AND (SELECT displayidentifier FROM organization_parent(o.id) WHERE organizationtypeid = (SELECT id FROM organizationtype WHERE typecode = 'DT')) = 'D0200' AND (SELECT displayidentifier FROM organization_parent(o.id) WHERE organizationtypeid = (SELECT id FROM organizationtype WHERE typecode = 'ST')) = 'KS';
UPDATE organization o SET timezoneid = (SELECT c.id FROM categorytype ct JOIN category c ON ct.id = c.categorytypeid WHERE ct.typecode = 'TIMEZONE' AND c.categoryname = 'Mountain') WHERE o.displayidentifier = '0137' AND (SELECT displayidentifier FROM organization_parent(o.id) WHERE organizationtypeid = (SELECT id FROM organizationtype WHERE typecode = 'DT')) = 'D0200' AND (SELECT displayidentifier FROM organization_parent(o.id) WHERE organizationtypeid = (SELECT id FROM organizationtype WHERE typecode = 'ST')) = 'KS';
UPDATE organization o SET timezoneid = (SELECT c.id FROM categorytype ct JOIN category c ON ct.id = c.categorytypeid WHERE ct.typecode = 'TIMEZONE' AND c.categoryname = 'Mountain') WHERE o.displayidentifier = '0131' AND (SELECT displayidentifier FROM organization_parent(o.id) WHERE organizationtypeid = (SELECT id FROM organizationtype WHERE typecode = 'DT')) = 'D0200' AND (SELECT displayidentifier FROM organization_parent(o.id) WHERE organizationtypeid = (SELECT id FROM organizationtype WHERE typecode = 'ST')) = 'KS';
UPDATE organization o SET timezoneid = (SELECT c.id FROM categorytype ct JOIN category c ON ct.id = c.categorytypeid WHERE ct.typecode = 'TIMEZONE' AND c.categoryname = 'Mountain') WHERE o.displayidentifier = '8106' AND (SELECT displayidentifier FROM organization_parent(o.id) WHERE organizationtypeid = (SELECT id FROM organizationtype WHERE typecode = 'DT')) = 'D0494' AND (SELECT displayidentifier FROM organization_parent(o.id) WHERE organizationtypeid = (SELECT id FROM organizationtype WHERE typecode = 'ST')) = 'KS';
UPDATE organization o SET timezoneid = (SELECT c.id FROM categorytype ct JOIN category c ON ct.id = c.categorytypeid WHERE ct.typecode = 'TIMEZONE' AND c.categoryname = 'Mountain') WHERE o.displayidentifier = '8110' AND (SELECT displayidentifier FROM organization_parent(o.id) WHERE organizationtypeid = (SELECT id FROM organizationtype WHERE typecode = 'DT')) = 'D0494' AND (SELECT displayidentifier FROM organization_parent(o.id) WHERE organizationtypeid = (SELECT id FROM organizationtype WHERE typecode = 'ST')) = 'KS';
UPDATE organization o SET timezoneid = (SELECT c.id FROM categorytype ct JOIN category c ON ct.id = c.categorytypeid WHERE ct.typecode = 'TIMEZONE' AND c.categoryname = 'Mountain') WHERE o.displayidentifier = '8114' AND (SELECT displayidentifier FROM organization_parent(o.id) WHERE organizationtypeid = (SELECT id FROM organizationtype WHERE typecode = 'DT')) = 'D0494' AND (SELECT displayidentifier FROM organization_parent(o.id) WHERE organizationtypeid = (SELECT id FROM organizationtype WHERE typecode = 'ST')) = 'KS';
UPDATE organization o SET timezoneid = (SELECT c.id FROM categorytype ct JOIN category c ON ct.id = c.categorytypeid WHERE ct.typecode = 'TIMEZONE' AND c.categoryname = 'Mountain') WHERE o.displayidentifier = '8112' AND (SELECT displayidentifier FROM organization_parent(o.id) WHERE organizationtypeid = (SELECT id FROM organizationtype WHERE typecode = 'DT')) = 'D0494' AND (SELECT displayidentifier FROM organization_parent(o.id) WHERE organizationtypeid = (SELECT id FROM organizationtype WHERE typecode = 'ST')) = 'KS';
UPDATE organization o SET timezoneid = (SELECT c.id FROM categorytype ct JOIN category c ON ct.id = c.categorytypeid WHERE ct.typecode = 'TIMEZONE' AND c.categoryname = 'Mountain') WHERE o.displayidentifier = '8115' AND (SELECT displayidentifier FROM organization_parent(o.id) WHERE organizationtypeid = (SELECT id FROM organizationtype WHERE typecode = 'DT')) = 'D0494' AND (SELECT displayidentifier FROM organization_parent(o.id) WHERE organizationtypeid = (SELECT id FROM organizationtype WHERE typecode = 'ST')) = 'KS';
UPDATE organization o SET timezoneid = (SELECT c.id FROM categorytype ct JOIN category c ON ct.id = c.categorytypeid WHERE ct.typecode = 'TIMEZONE' AND c.categoryname = 'Mountain') WHERE o.displayidentifier = '8113' AND (SELECT displayidentifier FROM organization_parent(o.id) WHERE organizationtypeid = (SELECT id FROM organizationtype WHERE typecode = 'DT')) = 'D0494' AND (SELECT displayidentifier FROM organization_parent(o.id) WHERE organizationtypeid = (SELECT id FROM organizationtype WHERE typecode = 'ST')) = 'KS';
UPDATE organization o SET timezoneid = (SELECT c.id FROM categorytype ct JOIN category c ON ct.id = c.categorytypeid WHERE ct.typecode = 'TIMEZONE' AND c.categoryname = 'Mountain') WHERE o.displayidentifier = '8109' AND (SELECT displayidentifier FROM organization_parent(o.id) WHERE organizationtypeid = (SELECT id FROM organizationtype WHERE typecode = 'DT')) = 'D0494' AND (SELECT displayidentifier FROM organization_parent(o.id) WHERE organizationtypeid = (SELECT id FROM organizationtype WHERE typecode = 'ST')) = 'KS';
UPDATE organization o SET timezoneid = (SELECT c.id FROM categorytype ct JOIN category c ON ct.id = c.categorytypeid WHERE ct.typecode = 'TIMEZONE' AND c.categoryname = 'Mountain') WHERE o.displayidentifier = '8116' AND (SELECT displayidentifier FROM organization_parent(o.id) WHERE organizationtypeid = (SELECT id FROM organizationtype WHERE typecode = 'DT')) = 'D0494' AND (SELECT displayidentifier FROM organization_parent(o.id) WHERE organizationtypeid = (SELECT id FROM organizationtype WHERE typecode = 'ST')) = 'KS';
UPDATE organization o SET timezoneid = (SELECT c.id FROM categorytype ct JOIN category c ON ct.id = c.categorytypeid WHERE ct.typecode = 'TIMEZONE' AND c.categoryname = 'Mountain') WHERE o.displayidentifier = '8107' AND (SELECT displayidentifier FROM organization_parent(o.id) WHERE organizationtypeid = (SELECT id FROM organizationtype WHERE typecode = 'DT')) = 'D0494' AND (SELECT displayidentifier FROM organization_parent(o.id) WHERE organizationtypeid = (SELECT id FROM organizationtype WHERE typecode = 'ST')) = 'KS';
UPDATE organization o SET timezoneid = (SELECT c.id FROM categorytype ct JOIN category c ON ct.id = c.categorytypeid WHERE ct.typecode = 'TIMEZONE' AND c.categoryname = 'Mountain') WHERE o.displayidentifier = '8111' AND (SELECT displayidentifier FROM organization_parent(o.id) WHERE organizationtypeid = (SELECT id FROM organizationtype WHERE typecode = 'DT')) = 'D0494' AND (SELECT displayidentifier FROM organization_parent(o.id) WHERE organizationtypeid = (SELECT id FROM organizationtype WHERE typecode = 'ST')) = 'KS';
UPDATE organization o SET timezoneid = (SELECT c.id FROM categorytype ct JOIN category c ON ct.id = c.categorytypeid WHERE ct.typecode = 'TIMEZONE' AND c.categoryname = 'Mountain') WHERE o.displayidentifier = '8108' AND (SELECT displayidentifier FROM organization_parent(o.id) WHERE organizationtypeid = (SELECT id FROM organizationtype WHERE typecode = 'DT')) = 'D0494' AND (SELECT displayidentifier FROM organization_parent(o.id) WHERE organizationtypeid = (SELECT id FROM organizationtype WHERE typecode = 'ST')) = 'KS';
UPDATE organization o SET timezoneid = (SELECT c.id FROM categorytype ct JOIN category c ON ct.id = c.categorytypeid WHERE ct.typecode = 'TIMEZONE' AND c.categoryname = 'Mountain') WHERE o.displayidentifier = '4227' AND (SELECT displayidentifier FROM organization_parent(o.id) WHERE organizationtypeid = (SELECT id FROM organizationtype WHERE typecode = 'DT')) = 'D0352' AND (SELECT displayidentifier FROM organization_parent(o.id) WHERE organizationtypeid = (SELECT id FROM organizationtype WHERE typecode = 'ST')) = 'KS';
UPDATE organization o SET timezoneid = (SELECT c.id FROM categorytype ct JOIN category c ON ct.id = c.categorytypeid WHERE ct.typecode = 'TIMEZONE' AND c.categoryname = 'Mountain') WHERE o.displayidentifier = '4222' AND (SELECT displayidentifier FROM organization_parent(o.id) WHERE organizationtypeid = (SELECT id FROM organizationtype WHERE typecode = 'DT')) = 'D0352' AND (SELECT displayidentifier FROM organization_parent(o.id) WHERE organizationtypeid = (SELECT id FROM organizationtype WHERE typecode = 'ST')) = 'KS';
UPDATE organization o SET timezoneid = (SELECT c.id FROM categorytype ct JOIN category c ON ct.id = c.categorytypeid WHERE ct.typecode = 'TIMEZONE' AND c.categoryname = 'Mountain') WHERE o.displayidentifier = '4220' AND (SELECT displayidentifier FROM organization_parent(o.id) WHERE organizationtypeid = (SELECT id FROM organizationtype WHERE typecode = 'DT')) = 'D0352' AND (SELECT displayidentifier FROM organization_parent(o.id) WHERE organizationtypeid = (SELECT id FROM organizationtype WHERE typecode = 'ST')) = 'KS';
UPDATE organization o SET timezoneid = (SELECT c.id FROM categorytype ct JOIN category c ON ct.id = c.categorytypeid WHERE ct.typecode = 'TIMEZONE' AND c.categoryname = 'Mountain') WHERE o.displayidentifier = '4228' AND (SELECT displayidentifier FROM organization_parent(o.id) WHERE organizationtypeid = (SELECT id FROM organizationtype WHERE typecode = 'DT')) = 'D0352' AND (SELECT displayidentifier FROM organization_parent(o.id) WHERE organizationtypeid = (SELECT id FROM organizationtype WHERE typecode = 'ST')) = 'KS';
UPDATE organization o SET timezoneid = (SELECT c.id FROM categorytype ct JOIN category c ON ct.id = c.categorytypeid WHERE ct.typecode = 'TIMEZONE' AND c.categoryname = 'Mountain') WHERE o.displayidentifier = '4229' AND (SELECT displayidentifier FROM organization_parent(o.id) WHERE organizationtypeid = (SELECT id FROM organizationtype WHERE typecode = 'DT')) = 'D0352' AND (SELECT displayidentifier FROM organization_parent(o.id) WHERE organizationtypeid = (SELECT id FROM organizationtype WHERE typecode = 'ST')) = 'KS';
UPDATE organization o SET timezoneid = (SELECT c.id FROM categorytype ct JOIN category c ON ct.id = c.categorytypeid WHERE ct.typecode = 'TIMEZONE' AND c.categoryname = 'Mountain') WHERE o.displayidentifier = '4224' AND (SELECT displayidentifier FROM organization_parent(o.id) WHERE organizationtypeid = (SELECT id FROM organizationtype WHERE typecode = 'DT')) = 'D0352' AND (SELECT displayidentifier FROM organization_parent(o.id) WHERE organizationtypeid = (SELECT id FROM organizationtype WHERE typecode = 'ST')) = 'KS';
UPDATE organization o SET timezoneid = (SELECT c.id FROM categorytype ct JOIN category c ON ct.id = c.categorytypeid WHERE ct.typecode = 'TIMEZONE' AND c.categoryname = 'Mountain') WHERE o.displayidentifier = '4230' AND (SELECT displayidentifier FROM organization_parent(o.id) WHERE organizationtypeid = (SELECT id FROM organizationtype WHERE typecode = 'DT')) = 'D0352' AND (SELECT displayidentifier FROM organization_parent(o.id) WHERE organizationtypeid = (SELECT id FROM organizationtype WHERE typecode = 'ST')) = 'KS';
UPDATE organization o SET timezoneid = (SELECT c.id FROM categorytype ct JOIN category c ON ct.id = c.categorytypeid WHERE ct.typecode = 'TIMEZONE' AND c.categoryname = 'Mountain') WHERE o.displayidentifier = '4225' AND (SELECT displayidentifier FROM organization_parent(o.id) WHERE organizationtypeid = (SELECT id FROM organizationtype WHERE typecode = 'DT')) = 'D0352' AND (SELECT displayidentifier FROM organization_parent(o.id) WHERE organizationtypeid = (SELECT id FROM organizationtype WHERE typecode = 'ST')) = 'KS';
UPDATE organization o SET timezoneid = (SELECT c.id FROM categorytype ct JOIN category c ON ct.id = c.categorytypeid WHERE ct.typecode = 'TIMEZONE' AND c.categoryname = 'Mountain') WHERE o.displayidentifier = '4223' AND (SELECT displayidentifier FROM organization_parent(o.id) WHERE organizationtypeid = (SELECT id FROM organizationtype WHERE typecode = 'DT')) = 'D0352' AND (SELECT displayidentifier FROM organization_parent(o.id) WHERE organizationtypeid = (SELECT id FROM organizationtype WHERE typecode = 'ST')) = 'KS';
UPDATE organization o SET timezoneid = (SELECT c.id FROM categorytype ct JOIN category c ON ct.id = c.categorytypeid WHERE ct.typecode = 'TIMEZONE' AND c.categoryname = 'Mountain') WHERE o.displayidentifier = '4226' AND (SELECT displayidentifier FROM organization_parent(o.id) WHERE organizationtypeid = (SELECT id FROM organizationtype WHERE typecode = 'DT')) = 'D0352' AND (SELECT displayidentifier FROM organization_parent(o.id) WHERE organizationtypeid = (SELECT id FROM organizationtype WHERE typecode = 'ST')) = 'KS';
UPDATE organization o SET timezoneid = (SELECT c.id FROM categorytype ct JOIN category c ON ct.id = c.categorytypeid WHERE ct.typecode = 'TIMEZONE' AND c.categoryname = 'Mountain') WHERE o.displayidentifier = '4221' AND (SELECT displayidentifier FROM organization_parent(o.id) WHERE organizationtypeid = (SELECT id FROM organizationtype WHERE typecode = 'DT')) = 'D0352' AND (SELECT displayidentifier FROM organization_parent(o.id) WHERE organizationtypeid = (SELECT id FROM organizationtype WHERE typecode = 'ST')) = 'KS';
UPDATE organization o SET timezoneid = (SELECT c.id FROM categorytype ct JOIN category c ON ct.id = c.categorytypeid WHERE ct.typecode = 'TIMEZONE' AND c.categoryname = 'Mountain') WHERE o.displayidentifier = '4239' AND (SELECT displayidentifier FROM organization_parent(o.id) WHERE organizationtypeid = (SELECT id FROM organizationtype WHERE typecode = 'DT')) = 'D0352' AND (SELECT displayidentifier FROM organization_parent(o.id) WHERE organizationtypeid = (SELECT id FROM organizationtype WHERE typecode = 'ST')) = 'KS';
UPDATE organization o SET timezoneid = (SELECT c.id FROM categorytype ct JOIN category c ON ct.id = c.categorytypeid WHERE ct.typecode = 'TIMEZONE' AND c.categoryname = 'Mountain') WHERE o.displayidentifier = '1100' AND (SELECT displayidentifier FROM organization_parent(o.id) WHERE organizationtypeid = (SELECT id FROM organizationtype WHERE typecode = 'DT')) = 'D0241' AND (SELECT displayidentifier FROM organization_parent(o.id) WHERE organizationtypeid = (SELECT id FROM organizationtype WHERE typecode = 'ST')) = 'KS';
UPDATE organization o SET timezoneid = (SELECT c.id FROM categorytype ct JOIN category c ON ct.id = c.categorytypeid WHERE ct.typecode = 'TIMEZONE' AND c.categoryname = 'Mountain') WHERE o.displayidentifier = '1104' AND (SELECT displayidentifier FROM organization_parent(o.id) WHERE organizationtypeid = (SELECT id FROM organizationtype WHERE typecode = 'DT')) = 'D0241' AND (SELECT displayidentifier FROM organization_parent(o.id) WHERE organizationtypeid = (SELECT id FROM organizationtype WHERE typecode = 'ST')) = 'KS';
UPDATE organization o SET timezoneid = (SELECT c.id FROM categorytype ct JOIN category c ON ct.id = c.categorytypeid WHERE ct.typecode = 'TIMEZONE' AND c.categoryname = 'Mountain') WHERE o.displayidentifier = '1103' AND (SELECT displayidentifier FROM organization_parent(o.id) WHERE organizationtypeid = (SELECT id FROM organizationtype WHERE typecode = 'DT')) = 'D0241' AND (SELECT displayidentifier FROM organization_parent(o.id) WHERE organizationtypeid = (SELECT id FROM organizationtype WHERE typecode = 'ST')) = 'KS';
UPDATE organization o SET timezoneid = (SELECT c.id FROM categorytype ct JOIN category c ON ct.id = c.categorytypeid WHERE ct.typecode = 'TIMEZONE' AND c.categoryname = 'Mountain') WHERE o.displayidentifier = '1102' AND (SELECT displayidentifier FROM organization_parent(o.id) WHERE organizationtypeid = (SELECT id FROM organizationtype WHERE typecode = 'DT')) = 'D0241' AND (SELECT displayidentifier FROM organization_parent(o.id) WHERE organizationtypeid = (SELECT id FROM organizationtype WHERE typecode = 'ST')) = 'KS';
UPDATE organization o SET timezoneid = (SELECT c.id FROM categorytype ct JOIN category c ON ct.id = c.categorytypeid WHERE ct.typecode = 'TIMEZONE' AND c.categoryname = 'Mountain') WHERE o.displayidentifier = '1105' AND (SELECT displayidentifier FROM organization_parent(o.id) WHERE organizationtypeid = (SELECT id FROM organizationtype WHERE typecode = 'DT')) = 'D0241' AND (SELECT displayidentifier FROM organization_parent(o.id) WHERE organizationtypeid = (SELECT id FROM organizationtype WHERE typecode = 'ST')) = 'KS';
UPDATE organization o SET timezoneid = (SELECT c.id FROM categorytype ct JOIN category c ON ct.id = c.categorytypeid WHERE ct.typecode = 'TIMEZONE' AND c.categoryname = 'Mountain') WHERE o.displayidentifier = '1101' AND (SELECT displayidentifier FROM organization_parent(o.id) WHERE organizationtypeid = (SELECT id FROM organizationtype WHERE typecode = 'DT')) = 'D0241' AND (SELECT displayidentifier FROM organization_parent(o.id) WHERE organizationtypeid = (SELECT id FROM organizationtype WHERE typecode = 'ST')) = 'KS';
UPDATE organization o SET timezoneid = (SELECT c.id FROM categorytype ct JOIN category c ON ct.id = c.categorytypeid WHERE ct.typecode = 'TIMEZONE' AND c.categoryname = 'Mountain') WHERE o.displayidentifier = '1106' AND (SELECT displayidentifier FROM organization_parent(o.id) WHERE organizationtypeid = (SELECT id FROM organizationtype WHERE typecode = 'DT')) = 'D0241' AND (SELECT displayidentifier FROM organization_parent(o.id) WHERE organizationtypeid = (SELECT id FROM organizationtype WHERE typecode = 'ST')) = 'KS';
UPDATE organization o SET timezoneid = (SELECT c.id FROM categorytype ct JOIN category c ON ct.id = c.categorytypeid WHERE ct.typecode = 'TIMEZONE' AND c.categoryname = 'Mountain') WHERE o.displayidentifier = '1108' AND (SELECT displayidentifier FROM organization_parent(o.id) WHERE organizationtypeid = (SELECT id FROM organizationtype WHERE typecode = 'DT')) = 'D0241' AND (SELECT displayidentifier FROM organization_parent(o.id) WHERE organizationtypeid = (SELECT id FROM organizationtype WHERE typecode = 'ST')) = 'KS';
UPDATE organization o SET timezoneid = (SELECT c.id FROM categorytype ct JOIN category c ON ct.id = c.categorytypeid WHERE ct.typecode = 'TIMEZONE' AND c.categoryname = 'Mountain') WHERE o.displayidentifier = '1124' AND (SELECT displayidentifier FROM organization_parent(o.id) WHERE organizationtypeid = (SELECT id FROM organizationtype WHERE typecode = 'DT')) = 'D0242' AND (SELECT displayidentifier FROM organization_parent(o.id) WHERE organizationtypeid = (SELECT id FROM organizationtype WHERE typecode = 'ST')) = 'KS';
UPDATE organization o SET timezoneid = (SELECT c.id FROM categorytype ct JOIN category c ON ct.id = c.categorytypeid WHERE ct.typecode = 'TIMEZONE' AND c.categoryname = 'Mountain') WHERE o.displayidentifier = '1123' AND (SELECT displayidentifier FROM organization_parent(o.id) WHERE organizationtypeid = (SELECT id FROM organizationtype WHERE typecode = 'DT')) = 'D0242' AND (SELECT displayidentifier FROM organization_parent(o.id) WHERE organizationtypeid = (SELECT id FROM organizationtype WHERE typecode = 'ST')) = 'KS';
UPDATE organization o SET timezoneid = (SELECT c.id FROM categorytype ct JOIN category c ON ct.id = c.categorytypeid WHERE ct.typecode = 'TIMEZONE' AND c.categoryname = 'Mountain') WHERE o.displayidentifier = '1125' AND (SELECT displayidentifier FROM organization_parent(o.id) WHERE organizationtypeid = (SELECT id FROM organizationtype WHERE typecode = 'DT')) = 'D0242' AND (SELECT displayidentifier FROM organization_parent(o.id) WHERE organizationtypeid = (SELECT id FROM organizationtype WHERE typecode = 'ST')) = 'KS';
UPDATE organization o SET timezoneid = (SELECT c.id FROM categorytype ct JOIN category c ON ct.id = c.categorytypeid WHERE ct.typecode = 'TIMEZONE' AND c.categoryname = 'Mountain') WHERE o.displayidentifier = '1119' AND (SELECT displayidentifier FROM organization_parent(o.id) WHERE organizationtypeid = (SELECT id FROM organizationtype WHERE typecode = 'DT')) = 'D0242' AND (SELECT displayidentifier FROM organization_parent(o.id) WHERE organizationtypeid = (SELECT id FROM organizationtype WHERE typecode = 'ST')) = 'KS';
UPDATE organization o SET timezoneid = (SELECT c.id FROM categorytype ct JOIN category c ON ct.id = c.categorytypeid WHERE ct.typecode = 'TIMEZONE' AND c.categoryname = 'Mountain') WHERE o.displayidentifier = '1118' AND (SELECT displayidentifier FROM organization_parent(o.id) WHERE organizationtypeid = (SELECT id FROM organizationtype WHERE typecode = 'DT')) = 'D0242' AND (SELECT displayidentifier FROM organization_parent(o.id) WHERE organizationtypeid = (SELECT id FROM organizationtype WHERE typecode = 'ST')) = 'KS';
UPDATE organization o SET timezoneid = (SELECT c.id FROM categorytype ct JOIN category c ON ct.id = c.categorytypeid WHERE ct.typecode = 'TIMEZONE' AND c.categoryname = 'Mountain') WHERE o.displayidentifier = '1120' AND (SELECT displayidentifier FROM organization_parent(o.id) WHERE organizationtypeid = (SELECT id FROM organizationtype WHERE typecode = 'DT')) = 'D0242' AND (SELECT displayidentifier FROM organization_parent(o.id) WHERE organizationtypeid = (SELECT id FROM organizationtype WHERE typecode = 'ST')) = 'KS';
UPDATE organization o SET timezoneid = (SELECT c.id FROM categorytype ct JOIN category c ON ct.id = c.categorytypeid WHERE ct.typecode = 'TIMEZONE' AND c.categoryname = 'Mountain') WHERE o.displayidentifier = '1122' AND (SELECT displayidentifier FROM organization_parent(o.id) WHERE organizationtypeid = (SELECT id FROM organizationtype WHERE typecode = 'DT')) = 'D0242' AND (SELECT displayidentifier FROM organization_parent(o.id) WHERE organizationtypeid = (SELECT id FROM organizationtype WHERE typecode = 'ST')) = 'KS';
UPDATE organization o SET timezoneid = (SELECT c.id FROM categorytype ct JOIN category c ON ct.id = c.categorytypeid WHERE ct.typecode = 'TIMEZONE' AND c.categoryname = 'Mountain') WHERE o.displayidentifier = '1121' AND (SELECT displayidentifier FROM organization_parent(o.id) WHERE organizationtypeid = (SELECT id FROM organizationtype WHERE typecode = 'DT')) = 'D0242' AND (SELECT displayidentifier FROM organization_parent(o.id) WHERE organizationtypeid = (SELECT id FROM organizationtype WHERE typecode = 'ST')) = 'KS';

