--DE17632 
delete from appconfiguration where attrtype = 'student_generation';

INSERT INTO public.appconfiguration(
	id, 
	attrcode, 
	attrtype, 
	attrname, 
	attrvalue, 
	activeflag, 
	createduser, 
	createddate, 
	modifieduser, 
	modifieddate)
	VALUES ((select nextval('appconfiguration_id_seq'::regclass)), 
			'student_generation_Jr', 
			'student_generation', 
			'a.Jr', 
			'Jr', 
			true, 
			12, 
			now(), 
			12, 
			now());

INSERT INTO public.appconfiguration(
	id, 
	attrcode, 
	attrtype, 
	attrname, 
	attrvalue, 
	activeflag, 
	createduser, 
	createddate, 
	modifieduser, 
	modifieddate)
	VALUES ((select nextval('appconfiguration_id_seq'::regclass)), 
			'student_generation_Sr', 
			'student_generation', 
			'b.Sr', 
			'Sr', 
			true, 
			12, 
			now(), 
			12, 
			now());
			
INSERT INTO public.appconfiguration(
	id, 
	attrcode, 
	attrtype, 
	attrname, 
	attrvalue, 
	activeflag, 
	createduser, 
	createddate, 
	modifieduser, 
	modifieddate)
	VALUES ((select nextval('appconfiguration_id_seq'::regclass)), 
			'student_generation_II', 
			'student_generation', 
			'c.II', 
			'II', 
			true, 
			12, 
			now(), 
			12, 
			now());	
			
 INSERT INTO public.appconfiguration(
	id, 
	attrcode, 
	attrtype, 
	attrname, 
	attrvalue, 
	activeflag, 
	createduser, 
	createddate, 
	modifieduser, 
	modifieddate)
	VALUES ((select nextval('appconfiguration_id_seq'::regclass)), 
			'student_generation_III', 
			'student_generation', 
			'd.III', 
			'III', 
			true, 
			12, 
			now(), 
			12, 
			now());	
			
INSERT INTO public.appconfiguration(
	id, 
	attrcode, 
	attrtype, 
	attrname, 
	attrvalue, 
	activeflag, 
	createduser, 
	createddate, 
	modifieduser, 
	modifieddate)
	VALUES ((select nextval('appconfiguration_id_seq'::regclass)), 
			'student_generation_IV', 
			'student_generation', 
			'e.IV', 
			'IV', 
			true, 
			12, 
			now(), 
			12, 
			now());
INSERT INTO public.appconfiguration(
	id, 
	attrcode, 
	attrtype, 
	attrname, 
	attrvalue, 
	activeflag, 
	createduser, 
	createddate, 
	modifieduser, 
	modifieddate)
	VALUES ((select nextval('appconfiguration_id_seq'::regclass)), 
			'student_generation_V', 
			'student_generation', 
			'f.V', 
			'V', 
			true, 
			12, 
			now(), 
			12, 
			now());
INSERT INTO public.appconfiguration(
	id, 
	attrcode, 
	attrtype, 
	attrname, 
	attrvalue, 
	activeflag, 
	createduser, 
	createddate, 
	modifieduser, 
	modifieddate)
	VALUES ((select nextval('appconfiguration_id_seq'::regclass)), 
			'student_generation_VI', 
			'student_generation', 
			'g.VI', 
			'VI', 
			true, 
			12, 
			now(), 
			12, 
			now());	
	INSERT INTO public.appconfiguration(
	id, 
	attrcode, 
	attrtype, 
	attrname, 
	attrvalue, 
	activeflag, 
	createduser, 
	createddate, 
	modifieduser, 
	modifieddate)
	VALUES ((select nextval('appconfiguration_id_seq'::regclass)), 
			'student_generation_VII', 
			'student_generation', 
			'h.VII', 
			'VII', 
			true, 
			12, 
			now(), 
			12, 
			now());	
INSERT INTO public.appconfiguration(
	id, 
	attrcode, 
	attrtype, 
	attrname, 
	attrvalue, 
	activeflag, 
	createduser, 
	createddate, 
	modifieduser, 
	modifieddate)
	VALUES ((select nextval('appconfiguration_id_seq'::regclass)), 
			'student_generation_VIII', 
			'student_generation', 
			'i.VIII', 
			'VIII', 
			true, 
			12, 
			now(), 
			12, 
			now());	
INSERT INTO public.appconfiguration(
	id, 
	attrcode, 
	attrtype, 
	attrname, 
	attrvalue, 
	activeflag, 
	createduser, 
	createddate, 
	modifieduser, 
	modifieddate)
	VALUES ((select nextval('appconfiguration_id_seq'::regclass)), 
			'student_generation_IX', 
			'student_generation', 
			'j.IX', 
			'IX', 
			true, 
			12, 
			now(), 
			12, 
			now());	