package edu.ku.cete.model.lm;

import edu.ku.cete.domain.lm.TaskVariantLearningMapNode;
import edu.ku.cete.domain.lm.TaskVariantLearningMapNodeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TaskVariantLearningMapNodeDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.task_variant_learning_map_node
     *
     * @mbggenerated Fri Feb 15 18:37:38 CST 2013
     */
    int countByExample(TaskVariantLearningMapNodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.task_variant_learning_map_node
     *
     * @mbggenerated Fri Feb 15 18:37:38 CST 2013
     */
    int deleteByExample(TaskVariantLearningMapNodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.task_variant_learning_map_node
     *
     * @mbggenerated Fri Feb 15 18:37:38 CST 2013
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.task_variant_learning_map_node
     *
     * @mbggenerated Fri Feb 15 18:37:38 CST 2013
     */
    int insert(TaskVariantLearningMapNode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.task_variant_learning_map_node
     *
     * @mbggenerated Fri Feb 15 18:37:38 CST 2013
     */
    int insertSelective(TaskVariantLearningMapNode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.task_variant_learning_map_node
     *
     * @mbggenerated Fri Feb 15 18:37:38 CST 2013
     */
    List<TaskVariantLearningMapNode> selectByExample(TaskVariantLearningMapNodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.task_variant_learning_map_node
     *
     * @mbggenerated Fri Feb 15 18:37:38 CST 2013
     */
    TaskVariantLearningMapNode selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.task_variant_learning_map_node
     *
     * @mbggenerated Fri Feb 15 18:37:38 CST 2013
     */
    int updateByExampleSelective(@Param("record") TaskVariantLearningMapNode record, @Param("example") TaskVariantLearningMapNodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.task_variant_learning_map_node
     *
     * @mbggenerated Fri Feb 15 18:37:38 CST 2013
     */
    int updateByExample(@Param("record") TaskVariantLearningMapNode record, @Param("example") TaskVariantLearningMapNodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.task_variant_learning_map_node
     *
     * @mbggenerated Fri Feb 15 18:37:38 CST 2013
     */
    int updateByPrimaryKeySelective(TaskVariantLearningMapNode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.task_variant_learning_map_node
     *
     * @mbggenerated Fri Feb 15 18:37:38 CST 2013
     */
    int updateByPrimaryKey(TaskVariantLearningMapNode record);
}