package edu.ku.cete.model.professionaldevelopment;

import edu.ku.cete.domain.professionaldevelopment.BatchStudentTrackerReason;
import edu.ku.cete.domain.professionaldevelopment.BatchStudentTrackerReasonExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BatchStudentTrackerReasonMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table batchstudenttrackerreason
	 * @mbggenerated  Mon Nov 24 00:50:03 CST 2014
	 */
	int countByExample(BatchStudentTrackerReasonExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table batchstudenttrackerreason
	 * @mbggenerated  Mon Nov 24 00:50:03 CST 2014
	 */
	int deleteByExample(BatchStudentTrackerReasonExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table batchstudenttrackerreason
	 * @mbggenerated  Mon Nov 24 00:50:03 CST 2014
	 */
	int insert(BatchStudentTrackerReason record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table batchstudenttrackerreason
	 * @mbggenerated  Mon Nov 24 00:50:03 CST 2014
	 */
	int insertSelective(BatchStudentTrackerReason record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table batchstudenttrackerreason
	 * @mbggenerated  Mon Nov 24 00:50:03 CST 2014
	 */
	List<BatchStudentTrackerReason> selectByExample(
			BatchStudentTrackerReasonExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table batchstudenttrackerreason
	 * @mbggenerated  Mon Nov 24 00:50:03 CST 2014
	 */
	int updateByExampleSelective(
			@Param("record") BatchStudentTrackerReason record,
			@Param("example") BatchStudentTrackerReasonExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table batchstudenttrackerreason
	 * @mbggenerated  Mon Nov 24 00:50:03 CST 2014
	 */
	int updateByExample(@Param("record") BatchStudentTrackerReason record,
			@Param("example") BatchStudentTrackerReasonExample example);
}