package edu.ku.cete.model.professionaldevelopment;

import edu.ku.cete.domain.professionaldevelopment.BatchStudentTracker;
import edu.ku.cete.domain.professionaldevelopment.BatchStudentTrackerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BatchStudentTrackerMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table batchstudenttracker
	 * @mbggenerated  Mon Nov 24 00:50:03 CST 2014
	 */
	int countByExample(BatchStudentTrackerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table batchstudenttracker
	 * @mbggenerated  Mon Nov 24 00:50:03 CST 2014
	 */
	int deleteByExample(BatchStudentTrackerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table batchstudenttracker
	 * @mbggenerated  Mon Nov 24 00:50:03 CST 2014
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table batchstudenttracker
	 * @mbggenerated  Mon Nov 24 00:50:03 CST 2014
	 */
	int insert(BatchStudentTracker record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table batchstudenttracker
	 * @mbggenerated  Mon Nov 24 00:50:03 CST 2014
	 */
	int insertSelective(BatchStudentTracker record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table batchstudenttracker
	 * @mbggenerated  Mon Nov 24 00:50:03 CST 2014
	 */
	List<BatchStudentTracker> selectByExample(BatchStudentTrackerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table batchstudenttracker
	 * @mbggenerated  Mon Nov 24 00:50:03 CST 2014
	 */
	BatchStudentTracker selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table batchstudenttracker
	 * @mbggenerated  Mon Nov 24 00:50:03 CST 2014
	 */
	int updateByExampleSelective(@Param("record") BatchStudentTracker record,
			@Param("example") BatchStudentTrackerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table batchstudenttracker
	 * @mbggenerated  Mon Nov 24 00:50:03 CST 2014
	 */
	int updateByExample(@Param("record") BatchStudentTracker record,
			@Param("example") BatchStudentTrackerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table batchstudenttracker
	 * @mbggenerated  Mon Nov 24 00:50:03 CST 2014
	 */
	int updateByPrimaryKeySelective(BatchStudentTracker record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table batchstudenttracker
	 * @mbggenerated  Mon Nov 24 00:50:03 CST 2014
	 */
	int updateByPrimaryKey(BatchStudentTracker record);
}