package edu.ku.cete.model.professionaldevelopment;

import org.apache.ibatis.annotations.Param;

import edu.ku.cete.domain.professionaldevelopment.ModuleGroup;

public interface ModuleGroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table modulegroup
     *
     * @mbggenerated Tue May 06 15:22:20 CDT 2014
     */
    int insert(ModuleGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table modulegroup
     *
     * @mbggenerated Tue May 06 15:22:20 CDT 2014
     */
    int insertSelective(ModuleGroup record);
    
    void deleteByModule(@Param("moduleId") Long moduleId);
}