package edu.ku.cete.domain.report;

import java.util.Date;

public class DashboardTestingOutsideHours {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dashboardtestingoutsidehours.id
     *
     * @mbg.generated Mon Oct 16 16:56:05 CDT 2017
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dashboardtestingoutsidehours.assessmentprogram
     *
     * @mbg.generated Mon Oct 16 16:56:05 CDT 2017
     */
    private String assessmentProgram;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dashboardtestingoutsidehours.assessmentprogramid
     *
     * @mbg.generated Mon Oct 16 16:56:05 CDT 2017
     */
    private Long assessmentProgramId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dashboardtestingoutsidehours.contentarea
     *
     * @mbg.generated Mon Oct 16 16:56:05 CDT 2017
     */
    private String contentArea;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dashboardtestingoutsidehours.contentareaid
     *
     * @mbg.generated Mon Oct 16 16:56:05 CDT 2017
     */
    private Long contentAreaId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dashboardtestingoutsidehours.grade
     *
     * @mbg.generated Mon Oct 16 16:56:05 CDT 2017
     */
    private String grade;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dashboardtestingoutsidehours.gradecourseid
     *
     * @mbg.generated Mon Oct 16 16:56:05 CDT 2017
     */
    private Long gradeCourseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dashboardtestingoutsidehours.gradeband
     *
     * @mbg.generated Mon Oct 16 16:56:05 CDT 2017
     */
    private String gradeBand;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dashboardtestingoutsidehours.gradebandid
     *
     * @mbg.generated Mon Oct 16 16:56:05 CDT 2017
     */
    private Long gradeBandId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dashboardtestingoutsidehours.studentid
     *
     * @mbg.generated Mon Oct 16 16:56:05 CDT 2017
     */
    private Long studentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dashboardtestingoutsidehours.studentname
     *
     * @mbg.generated Mon Oct 16 16:56:05 CDT 2017
     */
    private String studentName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dashboardtestingoutsidehours.statestudentidentifier
     *
     * @mbg.generated Mon Oct 16 16:56:05 CDT 2017
     */
    private String stateStudentIdentifier;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dashboardtestingoutsidehours.schoolname
     *
     * @mbg.generated Mon Oct 16 16:56:05 CDT 2017
     */
    private String schoolName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dashboardtestingoutsidehours.schoolid
     *
     * @mbg.generated Mon Oct 16 16:56:05 CDT 2017
     */
    private Long schoolId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dashboardtestingoutsidehours.districtname
     *
     * @mbg.generated Mon Oct 16 16:56:05 CDT 2017
     */
    private String districtName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dashboardtestingoutsidehours.districtid
     *
     * @mbg.generated Mon Oct 16 16:56:05 CDT 2017
     */
    private Long districtId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dashboardtestingoutsidehours.statename
     *
     * @mbg.generated Mon Oct 16 16:56:05 CDT 2017
     */
    private String stateName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dashboardtestingoutsidehours.stateid
     *
     * @mbg.generated Mon Oct 16 16:56:05 CDT 2017
     */
    private Long stateId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dashboardtestingoutsidehours.startdatetime
     *
     * @mbg.generated Mon Oct 16 16:56:05 CDT 2017
     */
    private Date startDateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dashboardtestingoutsidehours.enddatetime
     *
     * @mbg.generated Mon Oct 16 16:56:05 CDT 2017
     */
    private Date endDateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dashboardtestingoutsidehours.studentstestsid
     *
     * @mbg.generated Mon Oct 16 16:56:05 CDT 2017
     */
    private Long studentsTestsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dashboardtestingoutsidehours.testname
     *
     * @mbg.generated Mon Oct 16 16:56:05 CDT 2017
     */
    private String testName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dashboardtestingoutsidehours.testsessionid
     *
     * @mbg.generated Mon Oct 16 16:56:05 CDT 2017
     */
    private Long testSessionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dashboardtestingoutsidehours.studentstestshistoryid
     *
     * @mbg.generated Mon Oct 16 16:56:05 CDT 2017
     */
    private Long studentsTestsHistoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dashboardtestingoutsidehours.stagename
     *
     * @mbg.generated Mon Oct 16 16:56:05 CDT 2017
     */
    private String stageName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dashboardtestingoutsidehours.createddate
     *
     * @mbg.generated Mon Oct 16 16:56:05 CDT 2017
     */
    private Date createdDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dashboardtestingoutsidehours.modifieddate
     *
     * @mbg.generated Mon Oct 16 16:56:05 CDT 2017
     */
    private Date modifiedDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dashboardtestingoutsidehours.id
     *
     * @return the value of dashboardtestingoutsidehours.id
     *
     * @mbg.generated Mon Oct 16 16:56:05 CDT 2017
     */
    
    private String legalLastName;
	private String legalFirstName;
	
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dashboardtestingoutsidehours.id
     *
     * @param id the value for dashboardtestingoutsidehours.id
     *
     * @mbg.generated Mon Oct 16 16:56:05 CDT 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dashboardtestingoutsidehours.assessmentprogram
     *
     * @return the value of dashboardtestingoutsidehours.assessmentprogram
     *
     * @mbg.generated Mon Oct 16 16:56:05 CDT 2017
     */
    public String getAssessmentProgram() {
        return assessmentProgram;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dashboardtestingoutsidehours.assessmentprogram
     *
     * @param assessmentProgram the value for dashboardtestingoutsidehours.assessmentprogram
     *
     * @mbg.generated Mon Oct 16 16:56:05 CDT 2017
     */
    public void setAssessmentProgram(String assessmentProgram) {
        this.assessmentProgram = assessmentProgram == null ? null : assessmentProgram.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dashboardtestingoutsidehours.assessmentprogramid
     *
     * @return the value of dashboardtestingoutsidehours.assessmentprogramid
     *
     * @mbg.generated Mon Oct 16 16:56:05 CDT 2017
     */
    public Long getAssessmentProgramId() {
        return assessmentProgramId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dashboardtestingoutsidehours.assessmentprogramid
     *
     * @param assessmentProgramId the value for dashboardtestingoutsidehours.assessmentprogramid
     *
     * @mbg.generated Mon Oct 16 16:56:05 CDT 2017
     */
    public void setAssessmentProgramId(Long assessmentProgramId) {
        this.assessmentProgramId = assessmentProgramId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dashboardtestingoutsidehours.contentarea
     *
     * @return the value of dashboardtestingoutsidehours.contentarea
     *
     * @mbg.generated Mon Oct 16 16:56:05 CDT 2017
     */
    public String getContentArea() {
        return contentArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dashboardtestingoutsidehours.contentarea
     *
     * @param contentArea the value for dashboardtestingoutsidehours.contentarea
     *
     * @mbg.generated Mon Oct 16 16:56:05 CDT 2017
     */
    public void setContentArea(String contentArea) {
        this.contentArea = contentArea == null ? null : contentArea.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dashboardtestingoutsidehours.contentareaid
     *
     * @return the value of dashboardtestingoutsidehours.contentareaid
     *
     * @mbg.generated Mon Oct 16 16:56:05 CDT 2017
     */
    public Long getContentAreaId() {
        return contentAreaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dashboardtestingoutsidehours.contentareaid
     *
     * @param contentAreaId the value for dashboardtestingoutsidehours.contentareaid
     *
     * @mbg.generated Mon Oct 16 16:56:05 CDT 2017
     */
    public void setContentAreaId(Long contentAreaId) {
        this.contentAreaId = contentAreaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dashboardtestingoutsidehours.grade
     *
     * @return the value of dashboardtestingoutsidehours.grade
     *
     * @mbg.generated Mon Oct 16 16:56:05 CDT 2017
     */
    public String getGrade() {
        return grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dashboardtestingoutsidehours.grade
     *
     * @param grade the value for dashboardtestingoutsidehours.grade
     *
     * @mbg.generated Mon Oct 16 16:56:05 CDT 2017
     */
    public void setGrade(String grade) {
        this.grade = grade == null ? null : grade.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dashboardtestingoutsidehours.gradecourseid
     *
     * @return the value of dashboardtestingoutsidehours.gradecourseid
     *
     * @mbg.generated Mon Oct 16 16:56:05 CDT 2017
     */
    public Long getGradeCourseId() {
        return gradeCourseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dashboardtestingoutsidehours.gradecourseid
     *
     * @param gradeCourseId the value for dashboardtestingoutsidehours.gradecourseid
     *
     * @mbg.generated Mon Oct 16 16:56:05 CDT 2017
     */
    public void setGradeCourseId(Long gradeCourseId) {
        this.gradeCourseId = gradeCourseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dashboardtestingoutsidehours.gradeband
     *
     * @return the value of dashboardtestingoutsidehours.gradeband
     *
     * @mbg.generated Mon Oct 16 16:56:05 CDT 2017
     */
    public String getGradeBand() {
        return gradeBand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dashboardtestingoutsidehours.gradeband
     *
     * @param gradeBand the value for dashboardtestingoutsidehours.gradeband
     *
     * @mbg.generated Mon Oct 16 16:56:05 CDT 2017
     */
    public void setGradeBand(String gradeBand) {
        this.gradeBand = gradeBand == null ? null : gradeBand.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dashboardtestingoutsidehours.gradebandid
     *
     * @return the value of dashboardtestingoutsidehours.gradebandid
     *
     * @mbg.generated Mon Oct 16 16:56:05 CDT 2017
     */
    public Long getGradeBandId() {
        return gradeBandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dashboardtestingoutsidehours.gradebandid
     *
     * @param gradeBandId the value for dashboardtestingoutsidehours.gradebandid
     *
     * @mbg.generated Mon Oct 16 16:56:05 CDT 2017
     */
    public void setGradeBandId(Long gradeBandId) {
        this.gradeBandId = gradeBandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dashboardtestingoutsidehours.studentid
     *
     * @return the value of dashboardtestingoutsidehours.studentid
     *
     * @mbg.generated Mon Oct 16 16:56:05 CDT 2017
     */
    public Long getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dashboardtestingoutsidehours.studentid
     *
     * @param studentId the value for dashboardtestingoutsidehours.studentid
     *
     * @mbg.generated Mon Oct 16 16:56:05 CDT 2017
     */
    public void setStudentId(Long studentId) {
        this.studentId = studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dashboardtestingoutsidehours.studentname
     *
     * @return the value of dashboardtestingoutsidehours.studentname
     *
     * @mbg.generated Mon Oct 16 16:56:05 CDT 2017
     */
    public String getStudentName() {
        return studentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dashboardtestingoutsidehours.studentname
     *
     * @param studentName the value for dashboardtestingoutsidehours.studentname
     *
     * @mbg.generated Mon Oct 16 16:56:05 CDT 2017
     */
    public void setStudentName(String studentName) {
        this.studentName = studentName == null ? null : studentName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dashboardtestingoutsidehours.statestudentidentifier
     *
     * @return the value of dashboardtestingoutsidehours.statestudentidentifier
     *
     * @mbg.generated Mon Oct 16 16:56:05 CDT 2017
     */
    public String getStateStudentIdentifier() {
        return stateStudentIdentifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dashboardtestingoutsidehours.statestudentidentifier
     *
     * @param stateStudentIdentifier the value for dashboardtestingoutsidehours.statestudentidentifier
     *
     * @mbg.generated Mon Oct 16 16:56:05 CDT 2017
     */
    public void setStateStudentIdentifier(String stateStudentIdentifier) {
        this.stateStudentIdentifier = stateStudentIdentifier == null ? null : stateStudentIdentifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dashboardtestingoutsidehours.schoolname
     *
     * @return the value of dashboardtestingoutsidehours.schoolname
     *
     * @mbg.generated Mon Oct 16 16:56:05 CDT 2017
     */
    public String getSchoolName() {
        return schoolName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dashboardtestingoutsidehours.schoolname
     *
     * @param schoolName the value for dashboardtestingoutsidehours.schoolname
     *
     * @mbg.generated Mon Oct 16 16:56:05 CDT 2017
     */
    public void setSchoolName(String schoolName) {
        this.schoolName = schoolName == null ? null : schoolName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dashboardtestingoutsidehours.schoolid
     *
     * @return the value of dashboardtestingoutsidehours.schoolid
     *
     * @mbg.generated Mon Oct 16 16:56:05 CDT 2017
     */
    public Long getSchoolId() {
        return schoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dashboardtestingoutsidehours.schoolid
     *
     * @param schoolId the value for dashboardtestingoutsidehours.schoolid
     *
     * @mbg.generated Mon Oct 16 16:56:05 CDT 2017
     */
    public void setSchoolId(Long schoolId) {
        this.schoolId = schoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dashboardtestingoutsidehours.districtname
     *
     * @return the value of dashboardtestingoutsidehours.districtname
     *
     * @mbg.generated Mon Oct 16 16:56:05 CDT 2017
     */
    public String getDistrictName() {
        return districtName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dashboardtestingoutsidehours.districtname
     *
     * @param districtName the value for dashboardtestingoutsidehours.districtname
     *
     * @mbg.generated Mon Oct 16 16:56:05 CDT 2017
     */
    public void setDistrictName(String districtName) {
        this.districtName = districtName == null ? null : districtName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dashboardtestingoutsidehours.districtid
     *
     * @return the value of dashboardtestingoutsidehours.districtid
     *
     * @mbg.generated Mon Oct 16 16:56:05 CDT 2017
     */
    public Long getDistrictId() {
        return districtId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dashboardtestingoutsidehours.districtid
     *
     * @param districtId the value for dashboardtestingoutsidehours.districtid
     *
     * @mbg.generated Mon Oct 16 16:56:05 CDT 2017
     */
    public void setDistrictId(Long districtId) {
        this.districtId = districtId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dashboardtestingoutsidehours.statename
     *
     * @return the value of dashboardtestingoutsidehours.statename
     *
     * @mbg.generated Mon Oct 16 16:56:05 CDT 2017
     */
    public String getStateName() {
        return stateName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dashboardtestingoutsidehours.statename
     *
     * @param stateName the value for dashboardtestingoutsidehours.statename
     *
     * @mbg.generated Mon Oct 16 16:56:05 CDT 2017
     */
    public void setStateName(String stateName) {
        this.stateName = stateName == null ? null : stateName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dashboardtestingoutsidehours.stateid
     *
     * @return the value of dashboardtestingoutsidehours.stateid
     *
     * @mbg.generated Mon Oct 16 16:56:05 CDT 2017
     */
    public Long getStateId() {
        return stateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dashboardtestingoutsidehours.stateid
     *
     * @param stateId the value for dashboardtestingoutsidehours.stateid
     *
     * @mbg.generated Mon Oct 16 16:56:05 CDT 2017
     */
    public void setStateId(Long stateId) {
        this.stateId = stateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dashboardtestingoutsidehours.startdatetime
     *
     * @return the value of dashboardtestingoutsidehours.startdatetime
     *
     * @mbg.generated Mon Oct 16 16:56:05 CDT 2017
     */
    public Date getStartDateTime() {
        return startDateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dashboardtestingoutsidehours.startdatetime
     *
     * @param startDateTime the value for dashboardtestingoutsidehours.startdatetime
     *
     * @mbg.generated Mon Oct 16 16:56:05 CDT 2017
     */
    public void setStartDateTime(Date startDateTime) {
        this.startDateTime = startDateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dashboardtestingoutsidehours.enddatetime
     *
     * @return the value of dashboardtestingoutsidehours.enddatetime
     *
     * @mbg.generated Mon Oct 16 16:56:05 CDT 2017
     */
    public Date getEndDateTime() {
        return endDateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dashboardtestingoutsidehours.enddatetime
     *
     * @param endDateTime the value for dashboardtestingoutsidehours.enddatetime
     *
     * @mbg.generated Mon Oct 16 16:56:05 CDT 2017
     */
    public void setEndDateTime(Date endDateTime) {
        this.endDateTime = endDateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dashboardtestingoutsidehours.studentstestsid
     *
     * @return the value of dashboardtestingoutsidehours.studentstestsid
     *
     * @mbg.generated Mon Oct 16 16:56:05 CDT 2017
     */
    public Long getStudentsTestsId() {
        return studentsTestsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dashboardtestingoutsidehours.studentstestsid
     *
     * @param studentsTestsId the value for dashboardtestingoutsidehours.studentstestsid
     *
     * @mbg.generated Mon Oct 16 16:56:05 CDT 2017
     */
    public void setStudentsTestsId(Long studentsTestsId) {
        this.studentsTestsId = studentsTestsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dashboardtestingoutsidehours.testname
     *
     * @return the value of dashboardtestingoutsidehours.testname
     *
     * @mbg.generated Mon Oct 16 16:56:05 CDT 2017
     */
    public String getTestName() {
        return testName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dashboardtestingoutsidehours.testname
     *
     * @param testName the value for dashboardtestingoutsidehours.testname
     *
     * @mbg.generated Mon Oct 16 16:56:05 CDT 2017
     */
    public void setTestName(String testName) {
        this.testName = testName == null ? null : testName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dashboardtestingoutsidehours.testsessionid
     *
     * @return the value of dashboardtestingoutsidehours.testsessionid
     *
     * @mbg.generated Mon Oct 16 16:56:05 CDT 2017
     */
    public Long getTestSessionId() {
        return testSessionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dashboardtestingoutsidehours.testsessionid
     *
     * @param testSessionId the value for dashboardtestingoutsidehours.testsessionid
     *
     * @mbg.generated Mon Oct 16 16:56:05 CDT 2017
     */
    public void setTestSessionId(Long testSessionId) {
        this.testSessionId = testSessionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dashboardtestingoutsidehours.studentstestshistoryid
     *
     * @return the value of dashboardtestingoutsidehours.studentstestshistoryid
     *
     * @mbg.generated Mon Oct 16 16:56:05 CDT 2017
     */
    public Long getStudentsTestsHistoryId() {
        return studentsTestsHistoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dashboardtestingoutsidehours.studentstestshistoryid
     *
     * @param studentsTestsHistoryId the value for dashboardtestingoutsidehours.studentstestshistoryid
     *
     * @mbg.generated Mon Oct 16 16:56:05 CDT 2017
     */
    public void setStudentsTestsHistoryId(Long studentsTestsHistoryId) {
        this.studentsTestsHistoryId = studentsTestsHistoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dashboardtestingoutsidehours.stagename
     *
     * @return the value of dashboardtestingoutsidehours.stagename
     *
     * @mbg.generated Mon Oct 16 16:56:05 CDT 2017
     */
    public String getStageName() {
        return stageName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dashboardtestingoutsidehours.stagename
     *
     * @param stageName the value for dashboardtestingoutsidehours.stagename
     *
     * @mbg.generated Mon Oct 16 16:56:05 CDT 2017
     */
    public void setStageName(String stageName) {
        this.stageName = stageName == null ? null : stageName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dashboardtestingoutsidehours.createddate
     *
     * @return the value of dashboardtestingoutsidehours.createddate
     *
     * @mbg.generated Mon Oct 16 16:56:05 CDT 2017
     */
    public Date getCreatedDate() {
        return createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dashboardtestingoutsidehours.createddate
     *
     * @param createdDate the value for dashboardtestingoutsidehours.createddate
     *
     * @mbg.generated Mon Oct 16 16:56:05 CDT 2017
     */
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dashboardtestingoutsidehours.modifieddate
     *
     * @return the value of dashboardtestingoutsidehours.modifieddate
     *
     * @mbg.generated Mon Oct 16 16:56:05 CDT 2017
     */
    public Date getModifiedDate() {
        return modifiedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dashboardtestingoutsidehours.modifieddate
     *
     * @param modifiedDate the value for dashboardtestingoutsidehours.modifieddate
     *
     * @mbg.generated Mon Oct 16 16:56:05 CDT 2017
     */
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }

	/**
	 * @return the legalLastName
	 */
	public String getLegalLastName() {
		return legalLastName;
	}

	/**
	 * @param legalLastName the legalLastName to set
	 */
	public void setLegalLastName(String legalLastName) {
		this.legalLastName = legalLastName;
	}

	/**
	 * @return the legalFirstName
	 */
	public String getLegalFirstName() {
		return legalFirstName;
	}

	/**
	 * @param legalFirstName the legalFirstName to set
	 */
	public void setLegalFirstName(String legalFirstName) {
		this.legalFirstName = legalFirstName;
	}
    
}