package edu.ku.cete.domain.report;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

public class ReportSubscores implements Serializable, Comparable<ReportSubscores> {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5417535797340350755L;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reportsubscores.id
	 * @mbggenerated  Wed Jul 15 13:44:25 CDT 2015
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reportsubscores.studentid
	 * @mbggenerated  Wed Jul 15 13:44:25 CDT 2015
	 */
	private Long studentId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reportsubscores.subscoredefinitionname
	 * @mbggenerated  Wed Jul 15 13:44:25 CDT 2015
	 */
	private String subscoreDefinitionName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reportsubscores.subscorerawscore
	 * @mbggenerated  Wed Jul 15 13:44:25 CDT 2015
	 */
	private BigDecimal subscoreRawScore;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reportsubscores.subscorescalescore
	 * @mbggenerated  Wed Jul 15 13:44:25 CDT 2015
	 */
	private Long subscoreScaleScore;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reportsubscores.subscorestandarderror
	 * @mbggenerated  Wed Jul 15 13:44:25 CDT 2015
	 */
	private BigDecimal subscoreStandardError;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reportsubscores.studentreportid
	 * @mbggenerated  Wed Jul 15 13:44:25 CDT 2015
	 */
	private Long studentReportId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reportsubscores.createddate
	 * @mbggenerated  Wed Jul 15 13:44:25 CDT 2015
	 */
	private Date createdDate;
	
	private Integer totalItems;
	
	private Integer itemsResponded;
	
	private Long testId;
	
	private Integer rating;
	
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reportsubscores.id
	 * @return  the value of reportsubscores.id
	 * @mbggenerated  Wed Jul 15 13:44:25 CDT 2015
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reportsubscores.id
	 * @param id  the value for reportsubscores.id
	 * @mbggenerated  Wed Jul 15 13:44:25 CDT 2015
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reportsubscores.studentid
	 * @return  the value of reportsubscores.studentid
	 * @mbggenerated  Wed Jul 15 13:44:25 CDT 2015
	 */
	public Long getStudentId() {
		return studentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reportsubscores.studentid
	 * @param studentId  the value for reportsubscores.studentid
	 * @mbggenerated  Wed Jul 15 13:44:25 CDT 2015
	 */
	public void setStudentId(Long studentId) {
		this.studentId = studentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reportsubscores.subscoredefinitionname
	 * @return  the value of reportsubscores.subscoredefinitionname
	 * @mbggenerated  Wed Jul 15 13:44:25 CDT 2015
	 */
	public String getSubscoreDefinitionName() {
		return subscoreDefinitionName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reportsubscores.subscoredefinitionname
	 * @param subscoreDefinitionName  the value for reportsubscores.subscoredefinitionname
	 * @mbggenerated  Wed Jul 15 13:44:25 CDT 2015
	 */
	public void setSubscoreDefinitionName(String subscoreDefinitionName) {
		this.subscoreDefinitionName = subscoreDefinitionName == null ? null
				: subscoreDefinitionName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reportsubscores.subscorerawscore
	 * @return  the value of reportsubscores.subscorerawscore
	 * @mbggenerated  Wed Jul 15 13:44:25 CDT 2015
	 */
	public BigDecimal getSubscoreRawScore() {
		return subscoreRawScore;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reportsubscores.subscorerawscore
	 * @param subscoreRawScore  the value for reportsubscores.subscorerawscore
	 * @mbggenerated  Wed Jul 15 13:44:25 CDT 2015
	 */
	public void setSubscoreRawScore(BigDecimal subscoreRawScore) {
		this.subscoreRawScore = subscoreRawScore;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reportsubscores.subscorescalescore
	 * @return  the value of reportsubscores.subscorescalescore
	 * @mbggenerated  Wed Jul 15 13:44:25 CDT 2015
	 */
	public Long getSubscoreScaleScore() {
		return subscoreScaleScore;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reportsubscores.subscorescalescore
	 * @param subscoreScaleScore  the value for reportsubscores.subscorescalescore
	 * @mbggenerated  Wed Jul 15 13:44:25 CDT 2015
	 */
	public void setSubscoreScaleScore(Long subscoreScaleScore) {
		this.subscoreScaleScore = subscoreScaleScore;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reportsubscores.subscorestandarderror
	 * @return  the value of reportsubscores.subscorestandarderror
	 * @mbggenerated  Wed Jul 15 13:44:25 CDT 2015
	 */
	public BigDecimal getSubscoreStandardError() {
		return subscoreStandardError;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reportsubscores.subscorestandarderror
	 * @param subscoreStandardError  the value for reportsubscores.subscorestandarderror
	 * @mbggenerated  Wed Jul 15 13:44:25 CDT 2015
	 */
	public void setSubscoreStandardError(BigDecimal subscoreStandardError) {
		this.subscoreStandardError = subscoreStandardError;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reportsubscores.studentreportid
	 * @return  the value of reportsubscores.studentreportid
	 * @mbggenerated  Wed Jul 15 13:44:25 CDT 2015
	 */
	public Long getStudentReportId() {
		return studentReportId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reportsubscores.studentreportid
	 * @param studentReportId  the value for reportsubscores.studentreportid
	 * @mbggenerated  Wed Jul 15 13:44:25 CDT 2015
	 */
	public void setStudentReportId(Long studentReportId) {
		this.studentReportId = studentReportId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reportsubscores.createddate
	 * @return  the value of reportsubscores.createddate
	 * @mbggenerated  Wed Jul 15 13:44:25 CDT 2015
	 */
	public Date getCreatedDate() {
		return createdDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reportsubscores.createddate
	 * @param createdDate  the value for reportsubscores.createddate
	 * @mbggenerated  Wed Jul 15 13:44:25 CDT 2015
	 */
	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	private Integer subScoreDisplaySequence;
	private String report;
	private String subScoreReportDisplayName;
	private String subScoreReportDescription;
	private Long organizationId;
	private boolean sectionLineBelow;
	
	private boolean childsubscore;
	
	private List<String> subsoreGradeRating;
	private String gradeName;
	private List<Rating> gradeRatings;
	

	

	public boolean isChildsubscore() {
		return childsubscore;
	}

	public void setChildsubscore(boolean childsubscore) {
		this.childsubscore = childsubscore;
	}



	public List<String> getSubsoreGradeRating() {
		return subsoreGradeRating;
	}

	public void setSubsoreGradeRating(List<String> subsoreGradeRating) {
		this.subsoreGradeRating = subsoreGradeRating;
	}

	public Integer getSubScoreDisplaySequence() {
		return subScoreDisplaySequence;
	}

	public void setSubScoreDisplaySequence(Integer subScoreDisplaySequence) {
		this.subScoreDisplaySequence = subScoreDisplaySequence;
	}

	public Long getOrganizationId() {
		return organizationId;
	}

	public void setOrganizationId(Long organizationId) {
		this.organizationId = organizationId;
	}

	public String getReport() {
		return report;
	}

	public void setReport(String report) {
		this.report = report;
	}

	public String getSubScoreReportDisplayName() {
		return subScoreReportDisplayName;
	}

	public void setSubScoreReportDisplayName(String subScoreReportDisplayName) {
		this.subScoreReportDisplayName = subScoreReportDisplayName;
	}

	public String getSubScoreReportDescription() {
		return subScoreReportDescription;
	}

	public void setSubScoreReportDescription(String subScoreReportDescription) {
		this.subScoreReportDescription = subScoreReportDescription;
	}

	public Integer getTotalItems() {
		return totalItems;
	}

	public void setTotalItems(Integer totalItems) {
		this.totalItems = totalItems;
	}

	public Integer getItemsResponded() {
		return itemsResponded;
	}

	public void setItemsResponded(Integer itemsResponded) {
		this.itemsResponded = itemsResponded;
	}

	public Long getTestId() {
		return testId;
	}

	public void setTestId(Long testId) {
		this.testId = testId;
	}

	public Integer getRating() {
		return rating;
	}

	public void setRating(Integer rating) {
		this.rating = rating;
	}

	public boolean isSectionLineBelow() {
		return sectionLineBelow;
	}

	public void setSectionLineBelow(boolean sectionLineBelow) {
		this.sectionLineBelow = sectionLineBelow;
	}

	public String getGradeName() {
		return gradeName;
	}

	public void setGradeName(String gradeName) {
		this.gradeName = gradeName;
	}

	public List<Rating> getGradeRatings() {
		return gradeRatings;
	}

	public void setGradeRatings(List<Rating> gradeRatings) {
		this.gradeRatings = gradeRatings;
	}

	
	@Override
	public int compareTo(ReportSubscores other) {
		// TODO Auto-generated method stub
		return subScoreDisplaySequence.compareTo(other.subScoreDisplaySequence);
	} 
	
}