package edu.ku.cete.domain.report;

import java.util.Date;

public class SubScoresMissingStages {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subscoresmissingstages.id
     *
     * @mbggenerated Fri Mar 31 11:53:56 CDT 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subscoresmissingstages.assessmentprogramid
     *
     * @mbggenerated Fri Mar 31 11:53:56 CDT 2017
     */
    private Long assessmentProgramId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subscoresmissingstages.subjectid
     *
     * @mbggenerated Fri Mar 31 11:53:56 CDT 2017
     */
    private Long subjectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subscoresmissingstages.subject
     *
     * @mbggenerated Fri Mar 31 11:53:56 CDT 2017
     */
    private String subject;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subscoresmissingstages.gradeid
     *
     * @mbggenerated Fri Mar 31 11:53:56 CDT 2017
     */
    private Long gradeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subscoresmissingstages.grade
     *
     * @mbggenerated Fri Mar 31 11:53:56 CDT 2017
     */
    private String grade;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subscoresmissingstages.default_stage2_testid
     *
     * @mbggenerated Fri Mar 31 11:53:56 CDT 2017
     */
    private Long defaultStage2EpTestId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subscoresmissingstages.default_stage2_externaltestid
     *
     * @mbggenerated Fri Mar 31 11:53:56 CDT 2017
     */
    private Long testId2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subscoresmissingstages.default_stage3_testid
     *
     * @mbggenerated Fri Mar 31 11:53:56 CDT 2017
     */
    private Long defaultStage3EpTestId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subscoresmissingstages.default_stage3_externaltestid
     *
     * @mbggenerated Fri Mar 31 11:53:56 CDT 2017
     */
    private Long testId3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subscoresmissingstages.default_performance_testid
     *
     * @mbggenerated Fri Mar 31 11:53:56 CDT 2017
     */
    private Long defaultPerformanceEpTestId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subscoresmissingstages.default_performance_externaltestid
     *
     * @mbggenerated Fri Mar 31 11:53:56 CDT 2017
     */
    private Long performanceTestId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subscoresmissingstages.createddate
     *
     * @mbggenerated Fri Mar 31 11:53:56 CDT 2017
     */
    private Date createdDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subscoresmissingstages.modifieddate
     *
     * @mbggenerated Fri Mar 31 11:53:56 CDT 2017
     */
    private Date modifiedDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subscoresmissingstages.schoolyear
     *
     * @mbggenerated Fri Mar 31 11:53:56 CDT 2017
     */
    private Long schoolYear;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subscoresmissingstages.createduser
     *
     * @mbggenerated Fri Mar 31 11:53:56 CDT 2017
     */
    private Long createdUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subscoresmissingstages.modifieduser
     *
     * @mbggenerated Fri Mar 31 11:53:56 CDT 2017
     */
    private Long modifiedUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subscoresmissingstages.comment
     *
     * @mbggenerated Fri Mar 31 11:53:56 CDT 2017
     */
    private String comment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subscoresmissingstages.batchuploadid
     *
     * @mbggenerated Fri Mar 31 11:53:56 CDT 2017
     */
    private Long batchUploadId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subscoresmissingstages.id
     *
     * @return the value of subscoresmissingstages.id
     *
     * @mbggenerated Fri Mar 31 11:53:56 CDT 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subscoresmissingstages.id
     *
     * @param id the value for subscoresmissingstages.id
     *
     * @mbggenerated Fri Mar 31 11:53:56 CDT 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subscoresmissingstages.assessmentprogramid
     *
     * @return the value of subscoresmissingstages.assessmentprogramid
     *
     * @mbggenerated Fri Mar 31 11:53:56 CDT 2017
     */
    public Long getAssessmentProgramId() {
        return assessmentProgramId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subscoresmissingstages.assessmentprogramid
     *
     * @param assessmentProgramId the value for subscoresmissingstages.assessmentprogramid
     *
     * @mbggenerated Fri Mar 31 11:53:56 CDT 2017
     */
    public void setAssessmentProgramId(Long assessmentProgramId) {
        this.assessmentProgramId = assessmentProgramId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subscoresmissingstages.subjectid
     *
     * @return the value of subscoresmissingstages.subjectid
     *
     * @mbggenerated Fri Mar 31 11:53:56 CDT 2017
     */
    public Long getSubjectId() {
        return subjectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subscoresmissingstages.subjectid
     *
     * @param subjectId the value for subscoresmissingstages.subjectid
     *
     * @mbggenerated Fri Mar 31 11:53:56 CDT 2017
     */
    public void setSubjectId(Long subjectId) {
        this.subjectId = subjectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subscoresmissingstages.subject
     *
     * @return the value of subscoresmissingstages.subject
     *
     * @mbggenerated Fri Mar 31 11:53:56 CDT 2017
     */
    public String getSubject() {
        return subject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subscoresmissingstages.subject
     *
     * @param subject the value for subscoresmissingstages.subject
     *
     * @mbggenerated Fri Mar 31 11:53:56 CDT 2017
     */
    public void setSubject(String subject) {
        this.subject = subject == null ? null : subject.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subscoresmissingstages.gradeid
     *
     * @return the value of subscoresmissingstages.gradeid
     *
     * @mbggenerated Fri Mar 31 11:53:56 CDT 2017
     */
    public Long getGradeId() {
        return gradeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subscoresmissingstages.gradeid
     *
     * @param gradeId the value for subscoresmissingstages.gradeid
     *
     * @mbggenerated Fri Mar 31 11:53:56 CDT 2017
     */
    public void setGradeId(Long gradeId) {
        this.gradeId = gradeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subscoresmissingstages.grade
     *
     * @return the value of subscoresmissingstages.grade
     *
     * @mbggenerated Fri Mar 31 11:53:56 CDT 2017
     */
    public String getGrade() {
        return grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subscoresmissingstages.grade
     *
     * @param grade the value for subscoresmissingstages.grade
     *
     * @mbggenerated Fri Mar 31 11:53:56 CDT 2017
     */
    public void setGrade(String grade) {
        this.grade = grade == null ? null : grade.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subscoresmissingstages.default_stage2_testid
     *
     * @return the value of subscoresmissingstages.default_stage2_testid
     *
     * @mbggenerated Fri Mar 31 11:53:56 CDT 2017
     */
    public Long getDefaultStage2EpTestId() {
        return defaultStage2EpTestId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subscoresmissingstages.default_stage2_testid
     *
     * @param defaultStage2EpTestId the value for subscoresmissingstages.default_stage2_testid
     *
     * @mbggenerated Fri Mar 31 11:53:56 CDT 2017
     */
    public void setDefaultStage2EpTestId(Long defaultStage2EpTestId) {
        this.defaultStage2EpTestId = defaultStage2EpTestId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subscoresmissingstages.default_stage2_externaltestid
     *
     * @return the value of subscoresmissingstages.default_stage2_externaltestid
     *
     * @mbggenerated Fri Mar 31 11:53:56 CDT 2017
     */
    public Long getTestId2() {
        return testId2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subscoresmissingstages.default_stage2_externaltestid
     *
     * @param testId2 the value for subscoresmissingstages.default_stage2_externaltestid
     *
     * @mbggenerated Fri Mar 31 11:53:56 CDT 2017
     */
    public void setTestId2(Long testId2) {
        this.testId2 = testId2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subscoresmissingstages.default_stage3_testid
     *
     * @return the value of subscoresmissingstages.default_stage3_testid
     *
     * @mbggenerated Fri Mar 31 11:53:56 CDT 2017
     */
    public Long getDefaultStage3EpTestId() {
        return defaultStage3EpTestId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subscoresmissingstages.default_stage3_testid
     *
     * @param defaultStage3EpTestId the value for subscoresmissingstages.default_stage3_testid
     *
     * @mbggenerated Fri Mar 31 11:53:56 CDT 2017
     */
    public void setDefaultStage3EpTestId(Long defaultStage3EpTestId) {
        this.defaultStage3EpTestId = defaultStage3EpTestId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subscoresmissingstages.default_stage3_externaltestid
     *
     * @return the value of subscoresmissingstages.default_stage3_externaltestid
     *
     * @mbggenerated Fri Mar 31 11:53:56 CDT 2017
     */
    public Long getTestId3() {
        return testId3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subscoresmissingstages.default_stage3_externaltestid
     *
     * @param testId3 the value for subscoresmissingstages.default_stage3_externaltestid
     *
     * @mbggenerated Fri Mar 31 11:53:56 CDT 2017
     */
    public void setTestId3(Long testId3) {
        this.testId3 = testId3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subscoresmissingstages.default_performance_testid
     *
     * @return the value of subscoresmissingstages.default_performance_testid
     *
     * @mbggenerated Fri Mar 31 11:53:56 CDT 2017
     */
    public Long getDefaultPerformanceEpTestId() {
        return defaultPerformanceEpTestId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subscoresmissingstages.default_performance_testid
     *
     * @param defaultPerformanceEpTestId the value for subscoresmissingstages.default_performance_testid
     *
     * @mbggenerated Fri Mar 31 11:53:56 CDT 2017
     */
    public void setDefaultPerformanceEpTestId(Long defaultPerformanceEpTestId) {
        this.defaultPerformanceEpTestId = defaultPerformanceEpTestId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subscoresmissingstages.default_performance_externaltestid
     *
     * @return the value of subscoresmissingstages.default_performance_externaltestid
     *
     * @mbggenerated Fri Mar 31 11:53:56 CDT 2017
     */
    public Long getPerformanceTestId() {
        return performanceTestId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subscoresmissingstages.default_performance_externaltestid
     *
     * @param performanceTestId the value for subscoresmissingstages.default_performance_externaltestid
     *
     * @mbggenerated Fri Mar 31 11:53:56 CDT 2017
     */
    public void setPerformanceTestId(Long performanceTestId) {
        this.performanceTestId = performanceTestId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subscoresmissingstages.createddate
     *
     * @return the value of subscoresmissingstages.createddate
     *
     * @mbggenerated Fri Mar 31 11:53:56 CDT 2017
     */
    public Date getCreatedDate() {
        return createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subscoresmissingstages.createddate
     *
     * @param createdDate the value for subscoresmissingstages.createddate
     *
     * @mbggenerated Fri Mar 31 11:53:56 CDT 2017
     */
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subscoresmissingstages.modifieddate
     *
     * @return the value of subscoresmissingstages.modifieddate
     *
     * @mbggenerated Fri Mar 31 11:53:56 CDT 2017
     */
    public Date getModifiedDate() {
        return modifiedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subscoresmissingstages.modifieddate
     *
     * @param modifiedDate the value for subscoresmissingstages.modifieddate
     *
     * @mbggenerated Fri Mar 31 11:53:56 CDT 2017
     */
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subscoresmissingstages.schoolyear
     *
     * @return the value of subscoresmissingstages.schoolyear
     *
     * @mbggenerated Fri Mar 31 11:53:56 CDT 2017
     */
    public Long getSchoolYear() {
        return schoolYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subscoresmissingstages.schoolyear
     *
     * @param schoolYear the value for subscoresmissingstages.schoolyear
     *
     * @mbggenerated Fri Mar 31 11:53:56 CDT 2017
     */
    public void setSchoolYear(Long schoolYear) {
        this.schoolYear = schoolYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subscoresmissingstages.createduser
     *
     * @return the value of subscoresmissingstages.createduser
     *
     * @mbggenerated Fri Mar 31 11:53:56 CDT 2017
     */
    public Long getCreatedUser() {
        return createdUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subscoresmissingstages.createduser
     *
     * @param createdUser the value for subscoresmissingstages.createduser
     *
     * @mbggenerated Fri Mar 31 11:53:56 CDT 2017
     */
    public void setCreatedUser(Long createdUser) {
        this.createdUser = createdUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subscoresmissingstages.modifieduser
     *
     * @return the value of subscoresmissingstages.modifieduser
     *
     * @mbggenerated Fri Mar 31 11:53:56 CDT 2017
     */
    public Long getModifiedUser() {
        return modifiedUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subscoresmissingstages.modifieduser
     *
     * @param modifiedUser the value for subscoresmissingstages.modifieduser
     *
     * @mbggenerated Fri Mar 31 11:53:56 CDT 2017
     */
    public void setModifiedUser(Long modifiedUser) {
        this.modifiedUser = modifiedUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subscoresmissingstages.comment
     *
     * @return the value of subscoresmissingstages.comment
     *
     * @mbggenerated Fri Mar 31 11:53:56 CDT 2017
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subscoresmissingstages.comment
     *
     * @param comment the value for subscoresmissingstages.comment
     *
     * @mbggenerated Fri Mar 31 11:53:56 CDT 2017
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subscoresmissingstages.batchuploadid
     *
     * @return the value of subscoresmissingstages.batchuploadid
     *
     * @mbggenerated Fri Mar 31 11:53:56 CDT 2017
     */
    public Long getBatchUploadId() {
        return batchUploadId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subscoresmissingstages.batchuploadid
     *
     * @param batchUploadId the value for subscoresmissingstages.batchuploadid
     *
     * @mbggenerated Fri Mar 31 11:53:56 CDT 2017
     */
    public void setBatchUploadId(Long batchUploadId) {
        this.batchUploadId = batchUploadId;
    }
    
    private String lineNumber;
    private String assessmentProgram;

	/**
	 * @return the lineNumber
	 */
	public String getLineNumber() {
		return lineNumber;
	}

	/**
	 * @param lineNumber the lineNumber to set
	 */
	public void setLineNumber(String lineNumber) {
		this.lineNumber = lineNumber;
	}

	/**
	 * @return the assessmentProgram
	 */
	public String getAssessmentProgram() {
		return assessmentProgram;
	}

	/**
	 * @param assessmentProgram the assessmentProgram to set
	 */
	public void setAssessmentProgram(String assessmentProgram) {
		this.assessmentProgram = assessmentProgram;
	}	
}