-- 347.sql
-- US15696 : Data extract - KSDE Test records for System Operations
-- US15698 : Data extract - KSDE STCO records for System Operations
-- permissions for the data extracts(in dml)
-- empty 