--610.sql
-- F118 changes from changepond
drop table If exists kelpastatestudentscore ;

CREATE TABLE kelpastatestudentscore
(
  administration character varying(15),
  districtnumber character varying(100),
  districtname character varying(100),
  schoolnumber character varying(100),
  schoolname character varying(100),
  studentlastname character varying(80),
  studentfirstname character varying(80),
  studentmiddleinitial character varying(80),
  studentdateofbirth character varying(8),
  statestudentid character varying(30),
  grade character varying(3),
  gender character varying(1),
  ethnicity character varying(1),
  homelanguage character varying(2),
  disability character varying(2),
  iep character varying(1),
  section504 character varying(1),
  ellstatus character varying(2),
  economicallydisadvantaged character varying(1),
  mobile character varying(1),
  studentstn character varying(10),
  studentresponseformlistening character varying(12),
  studentresponseformreading character varying(12),
  studentresponseformspeaking character varying(12),
  studentresponseformwriting character varying(12),
  studentresponseformwritingpp character varying(20),
  testedorattempted character varying(1),
  teacherid character varying(20),
  teacherlastname character varying(30),
  teacherfirstname character varying(30),
  teachermiddleinitial character varying(1),
  universalfeaturezoom character varying(1),
  designatedfeaturezoomsize character varying(5),
  designatedfeatureanswermasking character varying(1),
  designatedfeaturescreenreader character varying(1),
  designatedfeaturemagnifyingglass character varying(1),
  designatedfeaturebackgroundcolor character varying(2),
  designatedfeaturebackgroundcoloroptions character varying(2),
  designatedfeaturereversecontrast character varying(1),
  designatedfeaturebraille character varying(1),
  designatedfeaturelargeprint character varying(1),
  testmode character varying(1),
  studentnottestedcodelistening character varying(2),
  studentnottestedcodereading character varying(2),
  studentnottestedcodespeaking character varying(2),
  studentnottestedcodewriting character varying(2),
  testinvalidationforlistening character varying(2),
  testinvalidationforreading character varying(2),
  testinvalidationforspeaking character varying(2),
  testinvalidationforwriting character varying(2),
  domainstatuslistening character varying(1),
  domainstatusreading character varying(1),
  domainstatusspeaking character varying(1),
  domainstatuswriting character varying(1),
  overallrawscore character varying(3),
  overallscalescore character varying(20),
  proficiencydetermination character varying(1),
  overallmeasurementerror character varying(3),
  listeningrawscore character varying(3),
  listeningscalescore character varying(3),
  listeningmeasurementerror character varying(3),
  listeningperformancelevel character varying(3),
  readingrawscore character varying(3),
  readingscalescore character varying(3),
  readingmeasurementerror character varying(3),
  readingperformancelevel character varying(3),
  speakingrawscore character varying(3),
  speakingscalescore character varying(3),
  speakingmeasurementerror character varying(3),
  speakingperformancelevel character varying(3),
  writingrawscore character varying(3),
  writingscalescore character varying(3),
  writingmeasurementerror character varying(3),
  writingperformancelevel character varying(3),
  comprehensionscalescore character varying(20),
  comprehensionmeasurementerror character varying(3)  
);


drop table if exists kelpastudentpreid;

CREATE TABLE kelpastudentpreid
(
  districtnumber character varying(10),
  districtname character varying(80),
  schoolnumber character varying(10),
  schoolname character varying(80),
  localid character varying(10),
  teacherid integer,
  term character varying(20),
  credit character varying(5),
  subject character varying(60),
  classs character varying(60),
  grade integer,
  studentid character varying(10),
  studentlastname character varying(80),
  studentfirstname character varying(80),
  studentmiddlename character varying(80),
  dateofbirth character varying(12),
  gender character varying(1),
  ethnicity_hispanic boolean,
  ethnicity_american_indian boolean,
  ethnicity_asian boolean,
  ethnicity_black boolean,
  ethnicity_native_hawaiian boolean,
  ethnicity_white boolean,
  ethnicity_multiple boolean,
  homelanguage integer,
  disability_autism boolean,
  disability_deaf_blindness boolean,
  disability_development_delay boolean,
  disability_emotional_disturbance boolean,
  disability_hearing_impairment boolean,
  disability_intellectual_disability boolean,
  disability_multiple_disabilities boolean,
  disability_orthopedic_impairment boolean,
  disability_other_health_impairment boolean,
  disability_specific_learning_disability boolean,
  disability_speech_or_language_impairment boolean,
  disability_traumatic_brain_injury boolean,
  disability_visual_impairment boolean,
  iep boolean,
  section_504 boolean,
  lep boolean,
  highly_mobile boolean,
  economic_disadvantaged boolean,
  teacherlastname character varying(80),
  teachermiddleinitial character varying(80),
  teacherfirstname character varying(80),
  teacherrmailaddress character varying(80)
);

drop table If exists kelpastudentpseudoid;

CREATE TABLE kelpastudentpseudoid
(
  qai_sid character varying(20),
  kite_pseudoid character varying(20),
  kansasstateid character varying(20),
  remarks character varying(120),
  studentstateid character varying(40)
);