package edu.ku.cete.service;

import java.io.Serializable;
import java.util.List;

import edu.ku.cete.domain.common.Assessment;
import edu.ku.cete.domain.common.AssessmentExample;


/**
 * @author nicholas.studt
 */
public interface AssessmentService extends Serializable {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.assessment
     *
     * @mbggenerated Mon Jun 04 11:52:02 CDT 2012
     */
    int countByExample(AssessmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.assessment
     *
     * @mbggenerated Mon Jun 04 11:52:02 CDT 2012
     */
    int deleteByExample(AssessmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.assessment
     *
     * @mbggenerated Mon Jun 04 11:52:02 CDT 2012
     */
    int deleteByPrimaryKey(Assessment key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.assessment
     *
     * @mbggenerated Mon Jun 04 11:52:02 CDT 2012
     */
    Assessment insert(Assessment record);
    /**
     * @param assessmentName 
     * @return {@link Assessment}
     */
    Assessment insertIfNotPresent(String assessmentName);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.assessment
     *
     * @mbggenerated Mon Jun 04 11:52:02 CDT 2012
     */
    Assessment insertSelective(Assessment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.assessment
     *
     * @mbggenerated Mon Jun 04 11:52:02 CDT 2012
     */
    List<Assessment> selectByExample(AssessmentExample example);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.assessment
     *
     * @mbggenerated Mon Jun 04 11:52:02 CDT 2012
     */
    int updateByExampleSelective(Assessment record, AssessmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.assessment
     *
     * @mbggenerated Mon Jun 04 11:52:02 CDT 2012
     */
    int updateByExample(Assessment record,AssessmentExample example);

	/**
	 * @param assessment {@link Assessment}
	 * @return {@link Assessment}
	 */
	Assessment saveAssessment(Assessment assessment);
	
	/**
	 * @param assessmentProgramId {@link Long}
	 * @param testingProgramId {@link Long}
	 * @return List< {@link Assessment}>
	 */
	List<Assessment> getByAssessmentProgramIdAndTestingProgramId(Long assessmentProgramId, Long testingProgramId);
	
	/**
	 * @return
	 */
	List<Assessment> selectAllAssessments();
	
	
	/**
	 * 
	 * @param testingProgramId
	 * @param assessmentProgramId
	 * @return
	 */
	List<Assessment> getAssessmentsForAutoRegistration(Long testingProgramId, Long assessmentProgramId);
	
	Assessment getById(Long id);
}
