package edu.ku.cete.model.report;

import edu.ku.cete.domain.report.NodeReport;
import edu.ku.cete.domain.report.NodeReportExample;
import edu.ku.cete.domain.report.NodeReportKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface NodeReportDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.node_report
     *
     * @mbggenerated Fri Feb 01 18:40:42 CST 2013
     */
    int countByExample(NodeReportExample example);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.node_report
     *
     * @mbggenerated Fri Feb 01 18:40:42 CST 2013
     */
    List<NodeReport> selectByExample(NodeReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.node_report
     *
     * @mbggenerated Fri Feb 01 18:40:42 CST 2013
     */
    NodeReport selectByPrimaryKey(NodeReportKey key);
	/**
	 * @param studentKeyword
	 * @param testKeyword
	 * @param organizationId 
	 * @param limitCount no of records to retrieve.
	 * @param offset 
	 * @param sortType 
	 * @param sortColumn 
	 * @return
	 */
	List<NodeReport> selectByStudentAndTest(
			@Param("studentKeyword")String studentKeyword,
			@Param("testKeyword")String testKeyword,
			@Param("organizationId") Long organizationId,
			@Param("limitCount") int limitCount,
			@Param("offset") int offset,
			@Param("sortColumn") String sortColumn);
	/**
	 * @param studentKeyword
	 * @param testKeyword
	 * @param organizationId 
	 * @return
	 */
	int countByStudentAndTest(@Param("studentKeyword")String studentKeyword,
			@Param("testKeyword")String testKeyword,
			@Param("organizationId") Long organizationId);
}