package edu.ku.cete.model.common;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import edu.ku.cete.domain.common.Assessment;
import edu.ku.cete.domain.common.AssessmentExample;

public interface AssessmentDao {
	/**
	 * @return
	 */
	long lastid();	
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.assessment
     *
     * @mbggenerated Mon Jun 04 11:52:02 CDT 2012
     */
    int countByExample(AssessmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.assessment
     *
     * @mbggenerated Mon Jun 04 11:52:02 CDT 2012
     */
    int deleteByExample(AssessmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.assessment
     *
     * @mbggenerated Mon Jun 04 11:52:02 CDT 2012
     */
    int deleteByPrimaryKey(Assessment key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.assessment
     *
     * @mbggenerated Mon Jun 04 11:52:02 CDT 2012
     */
    int insert(Assessment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.assessment
     *
     * @mbggenerated Mon Jun 04 11:52:02 CDT 2012
     */
    int insertSelective(Assessment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.assessment
     *
     * @mbggenerated Mon Jun 04 11:52:02 CDT 2012
     */
    List<Assessment> selectByExample(AssessmentExample example);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.assessment
     *
     * @mbggenerated Mon Jun 04 11:52:02 CDT 2012
     */
    int updateByExampleSelective(@Param("record") Assessment record, @Param("example") AssessmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.assessment
     *
     * @mbggenerated Mon Jun 04 11:52:02 CDT 2012
     */
    int updateByExample(@Param("record") Assessment record, @Param("example") AssessmentExample example);
    
	/**
	 * @param assessmentProgramId {@link Long}
	 * @param testingProgramId {@link Long}
	 * @return List< {@link Assessment}>
	 */
    List<Assessment> getByAssessmentProgramIdAndTestingProgramId(@Param("assessmentProgramId") Long assessmentProgramId, @Param("testingProgramId") Long testingProgramId);
    
    /**
     * @return
     */
    List<Assessment> selectAllAssessments();
    
    /**
     * 
     * @param testingProgramId
     * @return
     */
	List<Assessment> getAssessmentsForAutoRegistration(@Param("testingProgramId") Long testingProgramId, @Param("assessmentProgramId") Long assessmentProgramId);
	
	Assessment selectByPrimaryKey(Long id);
}