package edu.ku.cete.domain.security;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TestingProgramExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.testingprogram
     *
     * @mbggenerated Wed Dec 12 11:18:45 CST 2012
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.testingprogram
     *
     * @mbggenerated Wed Dec 12 11:18:45 CST 2012
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.testingprogram
     *
     * @mbggenerated Wed Dec 12 11:18:45 CST 2012
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.testingprogram
     *
     * @mbggenerated Wed Dec 12 11:18:45 CST 2012
     */
    public TestingProgramExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.testingprogram
     *
     * @mbggenerated Wed Dec 12 11:18:45 CST 2012
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.testingprogram
     *
     * @mbggenerated Wed Dec 12 11:18:45 CST 2012
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.testingprogram
     *
     * @mbggenerated Wed Dec 12 11:18:45 CST 2012
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.testingprogram
     *
     * @mbggenerated Wed Dec 12 11:18:45 CST 2012
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.testingprogram
     *
     * @mbggenerated Wed Dec 12 11:18:45 CST 2012
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.testingprogram
     *
     * @mbggenerated Wed Dec 12 11:18:45 CST 2012
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.testingprogram
     *
     * @mbggenerated Wed Dec 12 11:18:45 CST 2012
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.testingprogram
     *
     * @mbggenerated Wed Dec 12 11:18:45 CST 2012
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.testingprogram
     *
     * @mbggenerated Wed Dec 12 11:18:45 CST 2012
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.testingprogram
     *
     * @mbggenerated Wed Dec 12 11:18:45 CST 2012
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.testingprogram
     *
     * @mbggenerated Wed Dec 12 11:18:45 CST 2012
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andExternalIdIsNull() {
            addCriterion("externalid is null");
            return (Criteria) this;
        }

        public Criteria andExternalIdIsNotNull() {
            addCriterion("externalid is not null");
            return (Criteria) this;
        }

        public Criteria andExternalIdEqualTo(Long value) {
            addCriterion("externalid =", value, "externalId");
            return (Criteria) this;
        }

        public Criteria andExternalIdNotEqualTo(Long value) {
            addCriterion("externalid <>", value, "externalId");
            return (Criteria) this;
        }

        public Criteria andExternalIdGreaterThan(Long value) {
            addCriterion("externalid >", value, "externalId");
            return (Criteria) this;
        }

        public Criteria andExternalIdGreaterThanOrEqualTo(Long value) {
            addCriterion("externalid >=", value, "externalId");
            return (Criteria) this;
        }

        public Criteria andExternalIdLessThan(Long value) {
            addCriterion("externalid <", value, "externalId");
            return (Criteria) this;
        }

        public Criteria andExternalIdLessThanOrEqualTo(Long value) {
            addCriterion("externalid <=", value, "externalId");
            return (Criteria) this;
        }

        public Criteria andExternalIdIn(List<Long> values) {
            addCriterion("externalid in", values, "externalId");
            return (Criteria) this;
        }

        public Criteria andExternalIdNotIn(List<Long> values) {
            addCriterion("externalid not in", values, "externalId");
            return (Criteria) this;
        }

        public Criteria andExternalIdBetween(Long value1, Long value2) {
            addCriterion("externalid between", value1, value2, "externalId");
            return (Criteria) this;
        }

        public Criteria andExternalIdNotBetween(Long value1, Long value2) {
            addCriterion("externalid not between", value1, value2, "externalId");
            return (Criteria) this;
        }

        public Criteria andProgramNameIsNull() {
            addCriterion("programname is null");
            return (Criteria) this;
        }

        public Criteria andProgramNameIsNotNull() {
            addCriterion("programname is not null");
            return (Criteria) this;
        }

        public Criteria andProgramNameEqualTo(String value) {
            addCriterion("programname =", value, "programName");
            return (Criteria) this;
        }

        public Criteria andProgramNameNotEqualTo(String value) {
            addCriterion("programname <>", value, "programName");
            return (Criteria) this;
        }

        public Criteria andProgramNameGreaterThan(String value) {
            addCriterion("programname >", value, "programName");
            return (Criteria) this;
        }

        public Criteria andProgramNameGreaterThanOrEqualTo(String value) {
            addCriterion("programname >=", value, "programName");
            return (Criteria) this;
        }

        public Criteria andProgramNameLessThan(String value) {
            addCriterion("programname <", value, "programName");
            return (Criteria) this;
        }

        public Criteria andProgramNameLessThanOrEqualTo(String value) {
            addCriterion("programname <=", value, "programName");
            return (Criteria) this;
        }

        public Criteria andProgramNameLike(String value) {
            addCriterion("programname like", value, "programName");
            return (Criteria) this;
        }

        public Criteria andProgramNameNotLike(String value) {
            addCriterion("programname not like", value, "programName");
            return (Criteria) this;
        }

        public Criteria andProgramNameIn(List<String> values) {
            addCriterion("programname in", values, "programName");
            return (Criteria) this;
        }

        public Criteria andProgramNameNotIn(List<String> values) {
            addCriterion("programname not in", values, "programName");
            return (Criteria) this;
        }

        public Criteria andProgramNameBetween(String value1, String value2) {
            addCriterion("programname between", value1, value2, "programName");
            return (Criteria) this;
        }

        public Criteria andProgramNameNotBetween(String value1, String value2) {
            addCriterion("programname not between", value1, value2, "programName");
            return (Criteria) this;
        }

        public Criteria andProgramDescriptionIsNull() {
            addCriterion("programdescription is null");
            return (Criteria) this;
        }

        public Criteria andProgramDescriptionIsNotNull() {
            addCriterion("programdescription is not null");
            return (Criteria) this;
        }

        public Criteria andProgramDescriptionEqualTo(String value) {
            addCriterion("programdescription =", value, "programDescription");
            return (Criteria) this;
        }

        public Criteria andProgramDescriptionNotEqualTo(String value) {
            addCriterion("programdescription <>", value, "programDescription");
            return (Criteria) this;
        }

        public Criteria andProgramDescriptionGreaterThan(String value) {
            addCriterion("programdescription >", value, "programDescription");
            return (Criteria) this;
        }

        public Criteria andProgramDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("programdescription >=", value, "programDescription");
            return (Criteria) this;
        }

        public Criteria andProgramDescriptionLessThan(String value) {
            addCriterion("programdescription <", value, "programDescription");
            return (Criteria) this;
        }

        public Criteria andProgramDescriptionLessThanOrEqualTo(String value) {
            addCriterion("programdescription <=", value, "programDescription");
            return (Criteria) this;
        }

        public Criteria andProgramDescriptionLike(String value) {
            addCriterion("programdescription like", value, "programDescription");
            return (Criteria) this;
        }

        public Criteria andProgramDescriptionNotLike(String value) {
            addCriterion("programdescription not like", value, "programDescription");
            return (Criteria) this;
        }

        public Criteria andProgramDescriptionIn(List<String> values) {
            addCriterion("programdescription in", values, "programDescription");
            return (Criteria) this;
        }

        public Criteria andProgramDescriptionNotIn(List<String> values) {
            addCriterion("programdescription not in", values, "programDescription");
            return (Criteria) this;
        }

        public Criteria andProgramDescriptionBetween(String value1, String value2) {
            addCriterion("programdescription between", value1, value2, "programDescription");
            return (Criteria) this;
        }

        public Criteria andProgramDescriptionNotBetween(String value1, String value2) {
            addCriterion("programdescription not between", value1, value2, "programDescription");
            return (Criteria) this;
        }

        public Criteria andAssessmentProgramIdIsNull() {
            addCriterion("assessmentprogramid is null");
            return (Criteria) this;
        }

        public Criteria andAssessmentProgramIdIsNotNull() {
            addCriterion("assessmentprogramid is not null");
            return (Criteria) this;
        }

        public Criteria andAssessmentProgramIdEqualTo(Long value) {
            addCriterion("assessmentprogramid =", value, "assessmentProgramId");
            return (Criteria) this;
        }

        public Criteria andAssessmentProgramIdNotEqualTo(Long value) {
            addCriterion("assessmentprogramid <>", value, "assessmentProgramId");
            return (Criteria) this;
        }

        public Criteria andAssessmentProgramIdGreaterThan(Long value) {
            addCriterion("assessmentprogramid >", value, "assessmentProgramId");
            return (Criteria) this;
        }

        public Criteria andAssessmentProgramIdGreaterThanOrEqualTo(Long value) {
            addCriterion("assessmentprogramid >=", value, "assessmentProgramId");
            return (Criteria) this;
        }

        public Criteria andAssessmentProgramIdLessThan(Long value) {
            addCriterion("assessmentprogramid <", value, "assessmentProgramId");
            return (Criteria) this;
        }

        public Criteria andAssessmentProgramIdLessThanOrEqualTo(Long value) {
            addCriterion("assessmentprogramid <=", value, "assessmentProgramId");
            return (Criteria) this;
        }

        public Criteria andAssessmentProgramIdIn(List<Long> values) {
            addCriterion("assessmentprogramid in", values, "assessmentProgramId");
            return (Criteria) this;
        }

        public Criteria andAssessmentProgramIdNotIn(List<Long> values) {
            addCriterion("assessmentprogramid not in", values, "assessmentProgramId");
            return (Criteria) this;
        }

        public Criteria andAssessmentProgramIdBetween(Long value1, Long value2) {
            addCriterion("assessmentprogramid between", value1, value2, "assessmentProgramId");
            return (Criteria) this;
        }

        public Criteria andAssessmentProgramIdNotBetween(Long value1, Long value2) {
            addCriterion("assessmentprogramid not between", value1, value2, "assessmentProgramId");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNull() {
            addCriterion("createdate is null");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNotNull() {
            addCriterion("createdate is not null");
            return (Criteria) this;
        }

        public Criteria andCreateDateEqualTo(Date value) {
            addCriterion("createdate =", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotEqualTo(Date value) {
            addCriterion("createdate <>", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThan(Date value) {
            addCriterion("createdate >", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("createdate >=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThan(Date value) {
            addCriterion("createdate <", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThanOrEqualTo(Date value) {
            addCriterion("createdate <=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateIn(List<Date> values) {
            addCriterion("createdate in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotIn(List<Date> values) {
            addCriterion("createdate not in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateBetween(Date value1, Date value2) {
            addCriterion("createdate between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotBetween(Date value1, Date value2) {
            addCriterion("createdate not between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andModifiedDateIsNull() {
            addCriterion("modifieddate is null");
            return (Criteria) this;
        }

        public Criteria andModifiedDateIsNotNull() {
            addCriterion("modifieddate is not null");
            return (Criteria) this;
        }

        public Criteria andModifiedDateEqualTo(Date value) {
            addCriterion("modifieddate =", value, "modifiedDate");
            return (Criteria) this;
        }

        public Criteria andModifiedDateNotEqualTo(Date value) {
            addCriterion("modifieddate <>", value, "modifiedDate");
            return (Criteria) this;
        }

        public Criteria andModifiedDateGreaterThan(Date value) {
            addCriterion("modifieddate >", value, "modifiedDate");
            return (Criteria) this;
        }

        public Criteria andModifiedDateGreaterThanOrEqualTo(Date value) {
            addCriterion("modifieddate >=", value, "modifiedDate");
            return (Criteria) this;
        }

        public Criteria andModifiedDateLessThan(Date value) {
            addCriterion("modifieddate <", value, "modifiedDate");
            return (Criteria) this;
        }

        public Criteria andModifiedDateLessThanOrEqualTo(Date value) {
            addCriterion("modifieddate <=", value, "modifiedDate");
            return (Criteria) this;
        }

        public Criteria andModifiedDateIn(List<Date> values) {
            addCriterion("modifieddate in", values, "modifiedDate");
            return (Criteria) this;
        }

        public Criteria andModifiedDateNotIn(List<Date> values) {
            addCriterion("modifieddate not in", values, "modifiedDate");
            return (Criteria) this;
        }

        public Criteria andModifiedDateBetween(Date value1, Date value2) {
            addCriterion("modifieddate between", value1, value2, "modifiedDate");
            return (Criteria) this;
        }

        public Criteria andModifiedDateNotBetween(Date value1, Date value2) {
            addCriterion("modifieddate not between", value1, value2, "modifiedDate");
            return (Criteria) this;
        }

        public Criteria andOriginationCodeIsNull() {
            addCriterion("originationcode is null");
            return (Criteria) this;
        }

        public Criteria andOriginationCodeIsNotNull() {
            addCriterion("originationcode is not null");
            return (Criteria) this;
        }

        public Criteria andOriginationCodeEqualTo(String value) {
            addCriterion("originationcode =", value, "originationCode");
            return (Criteria) this;
        }

        public Criteria andOriginationCodeNotEqualTo(String value) {
            addCriterion("originationcode <>", value, "originationCode");
            return (Criteria) this;
        }

        public Criteria andOriginationCodeGreaterThan(String value) {
            addCriterion("originationcode >", value, "originationCode");
            return (Criteria) this;
        }

        public Criteria andOriginationCodeGreaterThanOrEqualTo(String value) {
            addCriterion("originationcode >=", value, "originationCode");
            return (Criteria) this;
        }

        public Criteria andOriginationCodeLessThan(String value) {
            addCriterion("originationcode <", value, "originationCode");
            return (Criteria) this;
        }

        public Criteria andOriginationCodeLessThanOrEqualTo(String value) {
            addCriterion("originationcode <=", value, "originationCode");
            return (Criteria) this;
        }

        public Criteria andOriginationCodeLike(String value) {
            addCriterion("originationcode like", value, "originationCode");
            return (Criteria) this;
        }

        public Criteria andOriginationCodeNotLike(String value) {
            addCriterion("originationcode not like", value, "originationCode");
            return (Criteria) this;
        }

        public Criteria andOriginationCodeIn(List<String> values) {
            addCriterion("originationcode in", values, "originationCode");
            return (Criteria) this;
        }

        public Criteria andOriginationCodeNotIn(List<String> values) {
            addCriterion("originationcode not in", values, "originationCode");
            return (Criteria) this;
        }

        public Criteria andOriginationCodeBetween(String value1, String value2) {
            addCriterion("originationcode between", value1, value2, "originationCode");
            return (Criteria) this;
        }

        public Criteria andOriginationCodeNotBetween(String value1, String value2) {
            addCriterion("originationcode not between", value1, value2, "originationCode");
            return (Criteria) this;
        }

        public Criteria andProgramAbbrIsNull() {
            addCriterion("programabbr is null");
            return (Criteria) this;
        }

        public Criteria andProgramAbbrIsNotNull() {
            addCriterion("programabbr is not null");
            return (Criteria) this;
        }

        public Criteria andProgramAbbrEqualTo(String value) {
            addCriterion("programabbr =", value, "programAbbr");
            return (Criteria) this;
        }

        public Criteria andProgramAbbrNotEqualTo(String value) {
            addCriterion("programabbr <>", value, "programAbbr");
            return (Criteria) this;
        }

        public Criteria andProgramAbbrGreaterThan(String value) {
            addCriterion("programabbr >", value, "programAbbr");
            return (Criteria) this;
        }

        public Criteria andProgramAbbrGreaterThanOrEqualTo(String value) {
            addCriterion("programabbr >=", value, "programAbbr");
            return (Criteria) this;
        }

        public Criteria andProgramAbbrLessThan(String value) {
            addCriterion("programabbr <", value, "programAbbr");
            return (Criteria) this;
        }

        public Criteria andProgramAbbrLessThanOrEqualTo(String value) {
            addCriterion("programabbr <=", value, "programAbbr");
            return (Criteria) this;
        }

        public Criteria andProgramAbbrLike(String value) {
            addCriterion("programabbr like", value, "programAbbr");
            return (Criteria) this;
        }

        public Criteria andProgramAbbrNotLike(String value) {
            addCriterion("programabbr not like", value, "programAbbr");
            return (Criteria) this;
        }

        public Criteria andProgramAbbrIn(List<String> values) {
            addCriterion("programabbr in", values, "programAbbr");
            return (Criteria) this;
        }

        public Criteria andProgramAbbrNotIn(List<String> values) {
            addCriterion("programabbr not in", values, "programAbbr");
            return (Criteria) this;
        }

        public Criteria andProgramAbbrBetween(String value1, String value2) {
            addCriterion("programabbr between", value1, value2, "programAbbr");
            return (Criteria) this;
        }

        public Criteria andProgramAbbrNotBetween(String value1, String value2) {
            addCriterion("programabbr not between", value1, value2, "programAbbr");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.testingprogram
     *
     * @mbggenerated do_not_delete_during_merge Wed Dec 12 11:18:45 CST 2012
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }

        public Criteria andProgramNameLikeInsensitive(String value) {
            addCriterion("upper(programname) like", value.toUpperCase(), "programName");
            return this;
        }

        public Criteria andProgramDescriptionLikeInsensitive(String value) {
            addCriterion("upper(programdescription) like", value.toUpperCase(), "programDescription");
            return this;
        }

        public Criteria andOriginationCodeLikeInsensitive(String value) {
            addCriterion("upper(originationcode) like", value.toUpperCase(), "originationCode");
            return this;
        }

        public Criteria andProgramAbbrLikeInsensitive(String value) {
            addCriterion("upper(programabbr) like", value.toUpperCase(), "programAbbr");
            return this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.testingprogram
     *
     * @mbggenerated Wed Dec 12 11:18:45 CST 2012
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}