package edu.ku.cete.model.test;

import edu.ku.cete.domain.content.Foil;
import edu.ku.cete.domain.content.FoilExample;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FoilDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.foil
     *
     * @mbggenerated Wed Oct 24 22:34:11 CDT 2012
     */
    int countByExample(FoilExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.foil
     *
     * @mbggenerated Wed Oct 24 22:34:11 CDT 2012
     */
    int deleteByExample(FoilExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.foil
     *
     * @mbggenerated Wed Oct 24 22:34:11 CDT 2012
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.foil
     *
     * @mbggenerated Wed Oct 24 22:34:11 CDT 2012
     */
    int insert(Foil record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.foil
     *
     * @mbggenerated Wed Oct 24 22:34:11 CDT 2012
     */
    int insertSelective(Foil record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.foil
     *
     * @mbggenerated Wed Oct 24 22:34:11 CDT 2012
     */
    List<Foil> selectByExample(FoilExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.foil
     *
     * @mbggenerated Wed Oct 24 22:34:11 CDT 2012
     */
    Foil selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.foil
     *
     * @mbggenerated Wed Oct 24 22:34:11 CDT 2012
     */
    int updateByExampleSelective(@Param("record") Foil record, @Param("example") FoilExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.foil
     *
     * @mbggenerated Wed Oct 24 22:34:11 CDT 2012
     */
    int updateByExample(@Param("record") Foil record, @Param("example") FoilExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.foil
     *
     * @mbggenerated Wed Oct 24 22:34:11 CDT 2012
     */
    int updateByPrimaryKeySelective(Foil record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.foil
     *
     * @mbggenerated Wed Oct 24 22:34:11 CDT 2012
     */
    int updateByPrimaryKey(Foil record);
    
    List<Foil> selectByTaskVariantId(@Param("taskVariantId") Long taskVariantId);

	List<Foil> selectByMultipleFoils(@Param("response")String response);
}